In [1]:
# Cell 1: Build BeH2 fermionic Hamiltonian and Hermitian fermionic terms

import math
import pandas as pd

from openfermion.chem import MolecularData
from openfermion.ops import FermionOperator
from openfermion.transforms import get_fermion_operator, normal_ordered
from openfermion.utils import hermitian_conjugated
from openfermionpyscf import run_pyscf

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# Beryllium hydride / BeH2 configuration
# ------------------------------------------------------------

BEH2_BOND_LENGTH = 1.326  # Angstrom, approximate Be-H bond length
BASIS = "sto-3g"
MULTIPLICITY = 1
CHARGE = 0

# Full BeH2/STO-3G should give 14 qubits:
# Be has 5 STO-3G spatial orbitals and each H has 1.
# 7 spatial orbitals * 2 spin orbitals = 14 qubits.
USE_ACTIVE_SPACE = False

# Optional active-space example:
# Freeze the Be core-like spatial orbital and keep valence orbitals active.
# This usually reduces BeH2/STO-3G from 14 qubits to 12 qubits.
OCCUPIED_INDICES = [0]
ACTIVE_INDICES = [1, 2, 3, 4, 5, 6]

TERM_ABS_TOL = 1e-12
PRINT_FULL_HAMILTONIAN = True


def format_fermion_term(term):
    if term == ():
        return "I"

    pieces = []
    for orbital, action in term:
        if action == 1:
            pieces.append(f"a_{orbital}^dagger")
        else:
            pieces.append(f"a_{orbital}")
    return " ".join(pieces)


def sort_fermion_key(term):
    return (len(term), term)


def coeff_to_str(c, digits=8):
    c = complex(c)
    if abs(c.imag) < 1e-12:
        return f"{c.real:+.{digits}f}"
    return f"{c.real:+.{digits}f}{c.imag:+.{digits}f}j"


def operator_to_string(op, digits=8):
    pieces = []

    for term, coeff in sorted(op.terms.items(), key=lambda item: sort_fermion_key(item[0])):
        pieces.append(f"{coeff_to_str(coeff, digits)} {format_fermion_term(term)}")

    if len(pieces) == 0:
        return "0"

    return " + ".join(pieces)


def dagger_term_key(term):
    """
    Return the OpenFermion key for O^dagger, where O is one monomial.
    """
    O = FermionOperator(term, 1.0)
    O_dag = normal_ordered(hermitian_conjugated(O))
    O_dag.compress(abs_tol=TERM_ABS_TOL)

    if len(O_dag.terms) != 1:
        raise ValueError(f"Expected one dagger term, got: {O_dag}")

    return next(iter(O_dag.terms.keys()))


def make_hermitian_fermionic_terms(fermion_hamiltonian, tol=TERM_ABS_TOL):
    """
    Group raw monomials into Hermitian fermionic Hamiltonian terms.
    """
    used = set()
    hermitian_terms = []

    for term, coeff in fermion_hamiltonian.terms.items():
        if term in used:
            continue

        dag = dagger_term_key(term)

        if dag == term:
            T = FermionOperator(term, coeff)
            used.add(term)
        else:
            dag_coeff = fermion_hamiltonian.terms.get(dag, 0.0)

            T = FermionOperator(term, coeff)
            T += FermionOperator(dag, dag_coeff)

            used.add(term)
            used.add(dag)

        T = normal_ordered(T)
        T.compress(abs_tol=tol)
        hermitian_terms.append(T)

    return hermitian_terms


def infer_n_qubits_from_fermion_operator(op):
    """
    Infer the number of spin orbitals used by the FermionOperator.
    """
    max_orbital = -1

    for term in op.terms:
        for orbital, action in term:
            max_orbital = max(max_orbital, orbital)

    return max_orbital + 1


def build_beh2_geometry(beh2_bond_length=BEH2_BOND_LENGTH):
    """
    Build linear BeH2 geometry.

    Be is placed at the origin.
    The two H atoms are placed symmetrically on the z-axis.
    """
    geometry = [
        ("H",  (0.0, 0.0, -beh2_bond_length)),
        ("Be", (0.0, 0.0, 0.0)),
        ("H",  (0.0, 0.0, beh2_bond_length)),
    ]

    return geometry


def build_beh2_fermionic_hamiltonian(
    beh2_bond_length=BEH2_BOND_LENGTH,
    basis=BASIS,
    multiplicity=MULTIPLICITY,
    charge=CHARGE,
    use_active_space=USE_ACTIVE_SPACE,
    occupied_indices=OCCUPIED_INDICES,
    active_indices=ACTIVE_INDICES,
):
    """
    Build a BeH2 fermionic Hamiltonian using OpenFermion + PySCF.
    """
    geometry = build_beh2_geometry(beh2_bond_length=beh2_bond_length)

    molecule = MolecularData(
        geometry=geometry,
        basis=basis,
        multiplicity=multiplicity,
        charge=charge,
        description=f"BeH2_{beh2_bond_length}",
    )

    molecule = run_pyscf(
        molecule,
        run_scf=True,
        run_fci=False,
    )

    if use_active_space:
        molecular_hamiltonian = molecule.get_molecular_hamiltonian(
            occupied_indices=occupied_indices,
            active_indices=active_indices,
        )
    else:
        molecular_hamiltonian = molecule.get_molecular_hamiltonian()

    fermion_hamiltonian = get_fermion_operator(molecular_hamiltonian)
    fermion_hamiltonian = normal_ordered(fermion_hamiltonian)
    fermion_hamiltonian.compress(abs_tol=TERM_ABS_TOL)

    n_qubits = infer_n_qubits_from_fermion_operator(fermion_hamiltonian)

    return molecule, fermion_hamiltonian, n_qubits


# ------------------------------------------------------------
# Build BeH2 fermionic Hamiltonian
# ------------------------------------------------------------

molecule, Hf, n_qubits = build_beh2_fermionic_hamiltonian()
hermitian_terms = make_hermitian_fermionic_terms(Hf)

print("Molecule: BeH2 / Beryllium hydride")
print("Basis:", BASIS)
print("Be-H bond length [Angstrom]:", BEH2_BOND_LENGTH)
print("Use active space:", USE_ACTIVE_SPACE)
if USE_ACTIVE_SPACE:
    print("Frozen occupied spatial orbitals:", OCCUPIED_INDICES)
    print("Active spatial orbitals:", ACTIVE_INDICES)
print("Full molecule electrons:", molecule.n_electrons)
print("Full molecule spatial orbitals:", molecule.n_orbitals)
print("Full molecule spin orbitals / qubits:", molecule.n_qubits)
print("Hamiltonian spin orbitals / qubits used:", n_qubits)
print("Number of raw OpenFermion monomial terms:", len(Hf.terms))
print("Number of Hermitian fermionic terms:", len(hermitian_terms))

if PRINT_FULL_HAMILTONIAN:
    print("\n=== Full fermionic Hamiltonian H_f ===")
    print(Hf)


# ------------------------------------------------------------
# Tables
# ------------------------------------------------------------

raw_rows = []

for idx, (term, coeff) in enumerate(
    sorted(Hf.terms.items(), key=lambda item: sort_fermion_key(item[0]))
):
    raw_rows.append(
        {
            "raw_index": idx,
            "coefficient": coeff_to_str(coeff),
            "monomial": format_fermion_term(term),
            "OpenFermion_key": term,
        }
    )

raw_df = pd.DataFrame(raw_rows)

print("\n=== Raw fermionic monomials c_alpha O_alpha ===")
display(raw_df)


hermitian_rows = []

for i, T in enumerate(hermitian_terms):
    hermitian_rows.append(
        {
            "vertex": f"T_{i}",
            "number_of_monomials": len(T.terms),
            "fermionic_term": operator_to_string(T),
        }
    )

hermitian_df = pd.DataFrame(hermitian_rows)

print("\n=== Hermitian fermionic terms T_i ===")
display(hermitian_df)

Molecule: BeH2 / Beryllium hydride
Basis: sto-3g
Be-H bond length [Angstrom]: 1.326
Use active space: False
Full molecule electrons: 6
Full molecule spatial orbitals: 7
Full molecule spin orbitals / qubits: 14
Hamiltonian spin orbitals / qubits used: 14
Number of raw OpenFermion monomial terms: 666
Number of Hermitian fermionic terms: 386

=== Full fermionic Hamiltonian H_f ===
3.3921616084615387 [] +
-8.653614060526332 [0^ 0] +
0.2257881707079464 [0^ 2] +
0.1933759038468936 [0^ 10] +
-2.271489014068697 [1^ 0^ 1 0] +
-0.19912676459351364 [1^ 0^ 2 1] +
0.19912676459351364 [1^ 0^ 3 0] +
-0.026786606586168524 [1^ 0^ 3 2] +
-0.006047866793733274 [1^ 0^ 5 4] +
-0.01576724793895085 [1^ 0^ 7 6] +
-0.01576724793895087 [1^ 0^ 9 8] +
-0.1809163218063341 [1^ 0^ 10 1] +
0.02500722144397735 [1^ 0^ 10 3] +
0.1809163218063341 [1^ 0^ 11 0] +
-0.02500722144397735 [1^ 0^ 11 2] +
-0.02358722217677317 [1^ 0^ 11 10] +
0.011268108228017996 [1^ 0^ 12 5] +
-0.011268108228017996 [1^ 0^ 13 4] +
-0.021432334426820798 [1^ 0^ 13 12] +
-8.653614060526332 [1^ 1] +
0.2257881707079464 [1^ 3] +
0.1933759038468936 [1^ 11] +
0.22578817070794643 [2^ 0] +
-0.4618191684157131 [2^ 0^ 2 0] +
-0.0858256252228083 [2^ 0^ 10 0] +
-0.0001261560792097647 [2^ 0^ 10 2] +
0.017067464820020122 [2^ 0^ 12 4] +
-0.19912676459351364 [2^ 1^ 1 0] +
-0.4886057750018816 [2^ 1^ 2 1] +
0.026786606586168524 [2^ 1^ 3 0] +
-0.006749548667045035 [2^ 1^ 3 2] +
0.014250292634053127 [2^ 1^ 5 4] +
0.015300275764442548 [2^ 1^ 7 6] +
0.015300275764442563 [2^ 1^ 9 8] +
-0.11083284666678564 [2^ 1^ 10 1] +
0.006657818079604089 [2^ 1^ 10 3] +
0.02500722144397735 [2^ 1^ 11 0] +
-0.006783974158813854 [2^ 1^ 11 2] +
-0.00394620020149776 [2^ 1^ 11 10] +
-0.003483937499362717 [2^ 1^ 12 5] +
0.02055140231938284 [2^ 1^ 13 4] +
0.007308710844141353 [2^ 1^ 13 12] +
-2.4681092221118495 [2^ 2] +
-0.17086432180007993 [2^ 10] +
0.19912676459351364 [3^ 0^ 1 0] +
0.026786606586168524 [3^ 0^ 2 1] +
-0.4886057750018816 [3^ 0^ 3 0] +
0.006749548667045035 [3^ 0^ 3 2] +
-0.014250292634053127 [3^ 0^ 5 4] +
-0.015300275764442548 [3^ 0^ 7 6] +
-0.015300275764442563 [3^ 0^ 9 8] +
0.02500722144397735 [3^ 0^ 10 1] +
-0.006783974158813854 [3^ 0^ 10 3] +
-0.11083284666678564 [3^ 0^ 11 0] +
0.006657818079604089 [3^ 0^ 11 2] +
0.00394620020149776 [3^ 0^ 11 10] +
0.02055140231938284 [3^ 0^ 12 5] +
-0.003483937499362717 [3^ 0^ 13 4] +
-0.007308710844141353 [3^ 0^ 13 12] +
0.22578817070794643 [3^ 1] +
-0.4618191684157131 [3^ 1^ 3 1] +
-0.0858256252228083 [3^ 1^ 11 1] +
-0.0001261560792097647 [3^ 1^ 11 3] +
0.017067464820020122 [3^ 1^ 13 5] +
-0.026786606586168524 [3^ 2^ 1 0] +
-0.006749548667045035 [3^ 2^ 2 1] +
0.006749548667045035 [3^ 2^ 3 0] +
-0.3990317233887508 [3^ 2^ 3 2] +
-0.16451934594928347 [3^ 2^ 5 4] +
-0.04948617421381216 [3^ 2^ 7 6] +
-0.04948617421381222 [3^ 2^ 9 8] +
-0.006657818079604089 [3^ 2^ 10 1] +
-0.02489952720410239 [3^ 2^ 10 3] +
0.006657818079604089 [3^ 2^ 11 0] +
0.02489952720410239 [3^ 2^ 11 2] +
-0.07761488544042426 [3^ 2^ 11 10] +
-0.04441890031545352 [3^ 2^ 12 5] +
0.04441890031545352 [3^ 2^ 13 4] +
-0.056584600456812524 [3^ 2^ 13 12] +
-2.4681092221118495 [3^ 3] +
-0.17086432180007993 [3^ 11] +
-0.45310403754564726 [4^ 0^ 4 0] +
0.017081072714017223 [4^ 0^ 4 2] +
-0.0014324716267165591 [4^ 0^ 10 4] +
-0.1284726164071108 [4^ 0^ 12 0] +
0.025662934515149095 [4^ 0^ 12 2] +
0.001183314552094881 [4^ 0^ 12 10] +
-0.4591519043393806 [4^ 1^ 4 1] +
0.002830780079964094 [4^ 1^ 4 3] +
0.006047866793733274 [4^ 1^ 5 0] +
0.014250292634053127 [4^ 1^ 5 2] +
0.0026845426058224346 [4^ 1^ 10 5] +
-0.004117014232538994 [4^ 1^ 11 4] +
-0.1397407246351288 [4^ 1^ 12 1] +
0.005111532195766256 [4^ 1^ 12 3] +
0.0032961401527208498 [4^ 1^ 12 11] +
0.011268108228017996 [4^ 1^ 13 0] +
0.02055140231938284 [4^ 1^ 13 2] +
-0.0021128256006259687 [4^ 1^ 13 10] +
0.017081072714017223 [4^ 2^ 4 0] +
-0.24786683415166114 [4^ 2^ 4 2] +
0.046950461166914675 [4^ 2^ 10 4] +
0.008595469695128971 [4^ 2^ 12 0] +
-0.03842107742282559 [4^ 2^ 12 2] +
-0.011724330526497496 [4^ 2^ 12 10] +
0.002830780079964094 [4^ 3^ 4 1] +
-0.4123861801009446 [4^ 3^ 4 3] +
0.014250292634053127 [4^ 3^ 5 0] +
0.16451934594928347 [4^ 3^ 5 2] +
0.09479570696086506 [4^ 3^ 10 5] +
-0.0478452457939504 [4^ 3^ 11 4] +
0.005111532195766256 [4^ 3^ 12 1] +
0.005997822892627933 [4^ 3^ 12 3] +
-0.07292948563022617 [4^ 3^ 12 11] +
0.003483937499362717 [4^ 3^ 13 0] +
-0.04441890031545352 [4^ 3^ 13 2] +
0.061205155103728676 [4^ 3^ 13 10] +
-2.430490736730216 [4^ 4] +
-0.2794165481309364 [4^ 12] +
0.006047866793733274 [5^ 0^ 4 1] +
0.014250292634053127 [5^ 0^ 4 3] +
-0.4591519043393806 [5^ 0^ 5 0] +
0.002830780079964094 [5^ 0^ 5 2] +
-0.004117014232538994 [5^ 0^ 10 5] +
0.0026845426058224346 [5^ 0^ 11 4] +
0.011268108228017996 [5^ 0^ 12 1] +
0.02055140231938284 [5^ 0^ 12 3] +
-0.0021128256006259687 [5^ 0^ 12 11] +
-0.1397407246351288 [5^ 0^ 13 0] +
0.005111532195766256 [5^ 0^ 13 2] +
0.0032961401527208498 [5^ 0^ 13 10] +
-0.45310403754564726 [5^ 1^ 5 1] +
0.017081072714017223 [5^ 1^ 5 3] +
-0.0014324716267165591 [5^ 1^ 11 5] +
-0.1284726164071108 [5^ 1^ 13 1] +
0.025662934515149095 [5^ 1^ 13 3] +
0.001183314552094881 [5^ 1^ 13 11] +
0.014250292634053127 [5^ 2^ 4 1] +
0.16451934594928347 [5^ 2^ 4 3] +
0.002830780079964094 [5^ 2^ 5 0] +
-0.4123861801009446 [5^ 2^ 5 2] +
-0.0478452457939504 [5^ 2^ 10 5] +
0.09479570696086506 [5^ 2^ 11 4] +
0.003483937499362717 [5^ 2^ 12 1] +
-0.04441890031545352 [5^ 2^ 12 3] +
0.061205155103728676 [5^ 2^ 12 11] +
0.005111532195766256 [5^ 2^ 13 0] +
0.005997822892627933 [5^ 2^ 13 2] +
-0.07292948563022617 [5^ 2^ 13 10] +
0.017081072714017223 [5^ 3^ 5 1] +
-0.24786683415166114 [5^ 3^ 5 3] +
0.046950461166914675 [5^ 3^ 11 5] +
0.008595469695128971 [5^ 3^ 13 1] +
-0.03842107742282559 [5^ 3^ 13 3] +
-0.011724330526497496 [5^ 3^ 13 11] +
-0.006047866793733274 [5^ 4^ 1 0] +
0.014250292634053127 [5^ 4^ 2 1] +
-0.014250292634053127 [5^ 4^ 3 0] +
-0.16451934594928347 [5^ 4^ 3 2] +
-0.43554295772017254 [5^ 4^ 5 4] +
-0.014704686478210244 [5^ 4^ 7 6] +
-0.014704686478210261 [5^ 4^ 9 8] +
-0.0026845426058224346 [5^ 4^ 10 1] +
-0.09479570696086506 [5^ 4^ 10 3] +
0.0026845426058224346 [5^ 4^ 11 0] +
0.09479570696086506 [5^ 4^ 11 2] +
-0.08343013418341721 [5^ 4^ 11 10] +
-0.0212199008519232 [5^ 4^ 12 5] +
0.0212199008519232 [5^ 4^ 13 4] +
-0.08233580021950003 [5^ 4^ 13 12] +
-2.430490736730216 [5^ 5] +
-0.2794165481309364 [5^ 13] +
-0.5534062195467696 [6^ 0^ 6 0] +
0.023363329149235362 [6^ 0^ 6 2] +
-0.02105881567700263 [6^ 0^ 10 6] +
-0.5691734674857205 [6^ 1^ 6 1] +
0.008063053384792813 [6^ 1^ 6 3] +
0.01576724793895085 [6^ 1^ 7 0] +
0.015300275764442548 [6^ 1^ 7 2] +
-0.016351336722667406 [6^ 1^ 10 7] +
-0.0047074789543352265 [6^ 1^ 11 6] +
0.02336332914923536 [6^ 2^ 6 0] +
-0.3200629799403887 [6^ 2^ 6 2] +
0.004518232670743614 [6^ 2^ 10 6] +
0.008063053384792813 [6^ 3^ 6 1] +
-0.36954915415420087 [6^ 3^ 6 3] +
0.015300275764442548 [6^ 3^ 7 0] +
0.04948617421381216 [6^ 3^ 7 2] +
-0.04743776016622643 [6^ 3^ 10 7] +
0.05195599283697005 [6^ 3^ 11 6] +
-0.34228717536338804 [6^ 4^ 6 4] +
0.04522287671754937 [6^ 4^ 12 6] +
-0.35699186184159826 [6^ 5^ 6 5] +
0.014704686478210244 [6^ 5^ 7 4] +
-0.013776379310126395 [6^ 5^ 12 7] +
0.058999256027675764 [6^ 5^ 13 6] +
-2.2997426657607045 [6^ 6] +
0.01576724793895085 [7^ 0^ 6 1] +
0.015300275764442548 [7^ 0^ 6 3] +
-0.5691734674857205 [7^ 0^ 7 0] +
0.008063053384792813 [7^ 0^ 7 2] +
-0.0047074789543352265 [7^ 0^ 10 7] +
-0.016351336722667406 [7^ 0^ 11 6] +
-0.5534062195467696 [7^ 1^ 7 1] +
0.023363329149235362 [7^ 1^ 7 3] +
-0.02105881567700263 [7^ 1^ 11 7] +
0.015300275764442548 [7^ 2^ 6 1] +
0.04948617421381216 [7^ 2^ 6 3] +
0.008063053384792813 [7^ 2^ 7 0] +
-0.36954915415420087 [7^ 2^ 7 2] +
0.05195599283697005 [7^ 2^ 10 7] +
-0.04743776016622643 [7^ 2^ 11 6] +
0.02336332914923536 [7^ 3^ 7 1] +
-0.3200629799403887 [7^ 3^ 7 3] +
0.004518232670743614 [7^ 3^ 11 7] +
0.014704686478210244 [7^ 4^ 6 5] +
-0.35699186184159826 [7^ 4^ 7 4] +
0.058999256027675764 [7^ 4^ 12 7] +
-0.013776379310126395 [7^ 4^ 13 6] +
-0.34228717536338804 [7^ 5^ 7 5] +
0.04522287671754937 [7^ 5^ 13 7] +
-0.01576724793895085 [7^ 6^ 1 0] +
0.015300275764442548 [7^ 6^ 2 1] +
-0.015300275764442548 [7^ 6^ 3 0] +
-0.04948617421381216 [7^ 6^ 3 2] +
-0.014704686478210244 [7^ 6^ 5 4] +
-0.4498590410866703 [7^ 6^ 7 6] +
-0.024249379221171166 [7^ 6^ 9 8] +
0.016351336722667406 [7^ 6^ 10 1] +
0.04743776016622643 [7^ 6^ 10 3] +
-0.016351336722667406 [7^ 6^ 11 0] +
-0.04743776016622643 [7^ 6^ 11 2] +
-0.05092314430548645 [7^ 6^ 11 10] +
0.013776379310126395 [7^ 6^ 12 5] +
-0.013776379310126395 [7^ 6^ 13 4] +
-0.016531544619256183 [7^ 6^ 13 12] +
-2.2997426657607045 [7^ 7] +
-0.5534062195467703 [8^ 0^ 8 0] +
0.023363329149235387 [8^ 0^ 8 2] +
-0.02105881567700265 [8^ 0^ 10 8] +
-0.5691734674857212 [8^ 1^ 8 1] +
0.008063053384792823 [8^ 1^ 8 3] +
0.01576724793895087 [8^ 1^ 9 0] +
0.015300275764442563 [8^ 1^ 9 2] +
-0.016351336722667423 [8^ 1^ 10 9] +
-0.0047074789543352265 [8^ 1^ 11 8] +
0.023363329149235387 [8^ 2^ 8 0] +
-0.3200629799403891 [8^ 2^ 8 2] +
0.0045182326707436035 [8^ 2^ 10 8] +
0.008063053384792823 [8^ 3^ 8 1] +
-0.3695491541542013 [8^ 3^ 8 3] +
0.015300275764442563 [8^ 3^ 9 0] +
0.04948617421381222 [8^ 3^ 9 2] +
-0.04743776016622649 [8^ 3^ 10 9] +
0.0519559928369701 [8^ 3^ 11 8] +
-0.34228717536338843 [8^ 4^ 8 4] +
0.04522287671754943 [8^ 4^ 12 8] +
-0.3569918618415987 [8^ 5^ 8 5] +
0.014704686478210261 [8^ 5^ 9 4] +
-0.013776379310126409 [8^ 5^ 12 9] +
0.05899925602767584 [8^ 5^ 13 8] +
-0.37711090342315745 [8^ 6^ 8 6] +
-0.40136028264432866 [8^ 7^ 8 7] +
0.024249379221171166 [8^ 7^ 9 6] +
-2.2997426657607067 [8^ 8] +
0.01576724793895087 [9^ 0^ 8 1] +
0.015300275764442563 [9^ 0^ 8 3] +
-0.5691734674857212 [9^ 0^ 9 0] +
0.008063053384792823 [9^ 0^ 9 2] +
-0.0047074789543352265 [9^ 0^ 10 9] +
-0.016351336722667423 [9^ 0^ 11 8] +
-0.5534062195467703 [9^ 1^ 9 1] +
0.023363329149235387 [9^ 1^ 9 3] +
-0.02105881567700265 [9^ 1^ 11 9] +
0.015300275764442563 [9^ 2^ 8 1] +
0.04948617421381222 [9^ 2^ 8 3] +
0.008063053384792823 [9^ 2^ 9 0] +
-0.3695491541542013 [9^ 2^ 9 2] +
0.0519559928369701 [9^ 2^ 10 9] +
-0.04743776016622649 [9^ 2^ 11 8] +
0.023363329149235387 [9^ 3^ 9 1] +
-0.3200629799403891 [9^ 3^ 9 3] +
0.0045182326707436035 [9^ 3^ 11 9] +
0.014704686478210261 [9^ 4^ 8 5] +
-0.3569918618415987 [9^ 4^ 9 4] +
0.05899925602767584 [9^ 4^ 12 9] +
-0.013776379310126409 [9^ 4^ 13 8] +
-0.34228717536338843 [9^ 5^ 9 5] +
0.04522287671754943 [9^ 5^ 13 9] +
0.024249379221171166 [9^ 6^ 8 7] +
-0.40136028264432866 [9^ 6^ 9 6] +
-0.37711090342315745 [9^ 7^ 9 7] +
-0.01576724793895087 [9^ 8^ 1 0] +
0.015300275764442563 [9^ 8^ 2 1] +
-0.015300275764442563 [9^ 8^ 3 0] +
-0.04948617421381222 [9^ 8^ 3 2] +
-0.014704686478210261 [9^ 8^ 5 4] +
-0.024249379221171166 [9^ 8^ 7 6] +
-0.4498590410866713 [9^ 8^ 9 8] +
0.016351336722667423 [9^ 8^ 10 1] +
0.04743776016622649 [9^ 8^ 10 3] +
-0.016351336722667423 [9^ 8^ 11 0] +
-0.04743776016622649 [9^ 8^ 11 2] +
-0.050923144305486515 [9^ 8^ 11 10] +
0.013776379310126409 [9^ 8^ 12 5] +
-0.013776379310126409 [9^ 8^ 13 4] +
-0.0165315446192562 [9^ 8^ 13 12] +
-2.2997426657607067 [9^ 9] +
0.19337590384689385 [10^ 0] +
-0.08582562522280829 [10^ 0^ 2 0] +
-0.45270208645665444 [10^ 0^ 10 0] +
0.002645927190606969 [10^ 0^ 10 2] +
-0.013411171310694883 [10^ 0^ 12 4] +
-0.1809163218063341 [10^ 1^ 1 0] +
-0.11083284666678564 [10^ 1^ 2 1] +
0.02500722144397735 [10^ 1^ 3 0] +
-0.006657818079604089 [10^ 1^ 3 2] +
-0.0026845426058224346 [10^ 1^ 5 4] +
0.016351336722667406 [10^ 1^ 7 6] +
0.016351336722667423 [10^ 1^ 9 8] +
-0.4762893086334276 [10^ 1^ 10 1] +
0.00659212739210473 [10^ 1^ 10 3] +
0.02358722217677317 [10^ 1^ 11 0] +
-0.00394620020149776 [10^ 1^ 11 2] +
-0.006035157985678703 [10^ 1^ 11 10] +
-0.011298345710068915 [10^ 1^ 12 5] +
-0.0021128256006259687 [10^ 1^ 13 4] +
0.016448854971083865 [10^ 1^ 13 12] +
-0.1708643218000795 [10^ 2] +
-0.0001261560792097647 [10^ 2^ 2 0] +
0.0026459271906069696 [10^ 2^ 10 0] +
-0.31976220371757086 [10^ 2^ 10 2] +
-0.08167242390723375 [10^ 2^ 12 4] +
0.02500722144397735 [10^ 3^ 1 0] +
0.006657818079604089 [10^ 3^ 2 1] +
-0.006783974158813854 [10^ 3^ 3 0] +
-0.02489952720410239 [10^ 3^ 3 2] +
-0.09479570696086506 [10^ 3^ 5 4] +
0.04743776016622643 [10^ 3^ 7 6] +
0.04743776016622649 [10^ 3^ 9 8] +
0.00659212739210473 [10^ 3^ 10 1] +
-0.39737708915799513 [10^ 3^ 10 3] +
-0.00394620020149776 [10^ 3^ 11 0] +
0.07761488544042426 [10^ 3^ 11 2] +
-0.03509495685788454 [10^ 3^ 11 10] +
-0.14287757901096243 [10^ 3^ 12 5] +
0.061205155103728676 [10^ 3^ 13 4] +
-0.05591150842993149 [10^ 3^ 13 12] +
-0.0014324716267165591 [10^ 4^ 4 0] +
0.04695046116691467 [10^ 4^ 4 2] +
-0.32497862971461844 [10^ 4^ 10 4] +
-0.014594485862789764 [10^ 4^ 12 0] +
-0.06994809338073626 [10^ 4^ 12 2] +
0.06893541223429976 [10^ 4^ 12 10] +
0.0026845426058224346 [10^ 5^ 4 1] +
0.09479570696086506 [10^ 5^ 4 3] +
-0.004117014232538994 [10^ 5^ 5 0] +
-0.0478452457939504 [10^ 5^ 5 2] +
-0.4084087638980356 [10^ 5^ 10 5] +
0.08343013418341721 [10^ 5^ 11 4] +
-0.011298345710068915 [10^ 5^ 12 1] +
-0.14287757901096243 [10^ 5^ 12 3] +
0.09549910444811928 [10^ 5^ 12 11] +
-0.0032961401527208498 [10^ 5^ 13 0] +
0.07292948563022617 [10^ 5^ 13 2] +
-0.026563692213819524 [10^ 5^ 13 10] +
-0.021058815677002633 [10^ 6^ 6 0] +
0.004518232670743614 [10^ 6^ 6 2] +
-0.3167299451888317 [10^ 6^ 10 6] +
-0.016351336722667406 [10^ 7^ 6 1] +
-0.04743776016622643 [10^ 7^ 6 3] +
-0.0047074789543352265 [10^ 7^ 7 0] +
0.05195599283697005 [10^ 7^ 7 2] +
-0.3676530894943182 [10^ 7^ 10 7] +
0.05092314430548645 [10^ 7^ 11 6] +
-0.021058815677002646 [10^ 8^ 8 0] +
0.0045182326707436035 [10^ 8^ 8 2] +
-0.316729945188832 [10^ 8^ 10 8] +
-0.016351336722667423 [10^ 9^ 8 1] +
-0.04743776016622649 [10^ 9^ 8 3] +
-0.0047074789543352265 [10^ 9^ 9 0] +
0.0519559928369701 [10^ 9^ 9 2] +
-0.3676530894943185 [10^ 9^ 10 9] +
0.050923144305486515 [10^ 9^ 11 8] +
-1.9157654958013657 [10^ 10] +
0.1809163218063341 [11^ 0^ 1 0] +
0.02500722144397735 [11^ 0^ 2 1] +
-0.11083284666678564 [11^ 0^ 3 0] +
0.006657818079604089 [11^ 0^ 3 2] +
0.0026845426058224346 [11^ 0^ 5 4] +
-0.016351336722667406 [11^ 0^ 7 6] +
-0.016351336722667423 [11^ 0^ 9 8] +
0.02358722217677317 [11^ 0^ 10 1] +
-0.00394620020149776 [11^ 0^ 10 3] +
-0.4762893086334276 [11^ 0^ 11 0] +
0.00659212739210473 [11^ 0^ 11 2] +
0.006035157985678703 [11^ 0^ 11 10] +
-0.0021128256006259687 [11^ 0^ 12 5] +
-0.011298345710068915 [11^ 0^ 13 4] +
-0.016448854971083865 [11^ 0^ 13 12] +
0.19337590384689385 [11^ 1] +
-0.08582562522280829 [11^ 1^ 3 1] +
-0.45270208645665444 [11^ 1^ 11 1] +
0.002645927190606969 [11^ 1^ 11 3] +
-0.013411171310694883 [11^ 1^ 13 5] +
-0.02500722144397735 [11^ 2^ 1 0] +
-0.006783974158813854 [11^ 2^ 2 1] +
0.006657818079604089 [11^ 2^ 3 0] +
0.02489952720410239 [11^ 2^ 3 2] +
0.09479570696086506 [11^ 2^ 5 4] +
-0.04743776016622643 [11^ 2^ 7 6] +
-0.04743776016622649 [11^ 2^ 9 8] +
-0.00394620020149776 [11^ 2^ 10 1] +
0.07761488544042426 [11^ 2^ 10 3] +
0.00659212739210473 [11^ 2^ 11 0] +
-0.39737708915799513 [11^ 2^ 11 2] +
0.03509495685788454 [11^ 2^ 11 10] +
0.061205155103728676 [11^ 2^ 12 5] +
-0.14287757901096243 [11^ 2^ 13 4] +
0.05591150842993149 [11^ 2^ 13 12] +
-0.1708643218000795 [11^ 3] +
-0.0001261560792097647 [11^ 3^ 3 1] +
0.0026459271906069696 [11^ 3^ 11 1] +
-0.31976220371757086 [11^ 3^ 11 3] +
-0.08167242390723375 [11^ 3^ 13 5] +
-0.004117014232538994 [11^ 4^ 4 1] +
-0.0478452457939504 [11^ 4^ 4 3] +
0.0026845426058224346 [11^ 4^ 5 0] +
0.09479570696086506 [11^ 4^ 5 2] +
0.08343013418341721 [11^ 4^ 10 5] +
-0.4084087638980356 [11^ 4^ 11 4] +
-0.0032961401527208498 [11^ 4^ 12 1] +
0.07292948563022617 [11^ 4^ 12 3] +
-0.026563692213819524 [11^ 4^ 12 11] +
-0.011298345710068915 [11^ 4^ 13 0] +
-0.14287757901096243 [11^ 4^ 13 2] +
0.09549910444811928 [11^ 4^ 13 10] +
-0.0014324716267165591 [11^ 5^ 5 1] +
0.04695046116691467 [11^ 5^ 5 3] +
-0.32497862971461844 [11^ 5^ 11 5] +
-0.014594485862789764 [11^ 5^ 13 1] +
-0.06994809338073626 [11^ 5^ 13 3] +
0.06893541223429976 [11^ 5^ 13 11] +
-0.0047074789543352265 [11^ 6^ 6 1] +
0.05195599283697005 [11^ 6^ 6 3] +
-0.016351336722667406 [11^ 6^ 7 0] +
-0.04743776016622643 [11^ 6^ 7 2] +
0.05092314430548645 [11^ 6^ 10 7] +
-0.3676530894943182 [11^ 6^ 11 6] +
-0.021058815677002633 [11^ 7^ 7 1] +
0.004518232670743614 [11^ 7^ 7 3] +
-0.3167299451888317 [11^ 7^ 11 7] +
-0.0047074789543352265 [11^ 8^ 8 1] +
0.0519559928369701 [11^ 8^ 8 3] +
-0.016351336722667423 [11^ 8^ 9 0] +
-0.04743776016622649 [11^ 8^ 9 2] +
0.050923144305486515 [11^ 8^ 10 9] +
-0.3676530894943185 [11^ 8^ 11 8] +
-0.021058815677002646 [11^ 9^ 9 1] +
0.0045182326707436035 [11^ 9^ 9 3] +
-0.316729945188832 [11^ 9^ 11 9] +
-0.02358722217677317 [11^ 10^ 1 0] +
-0.00394620020149776 [11^ 10^ 2 1] +
0.00394620020149776 [11^ 10^ 3 0] +
-0.07761488544042426 [11^ 10^ 3 2] +
-0.08343013418341721 [11^ 10^ 5 4] +
-0.05092314430548645 [11^ 10^ 7 6] +
-0.050923144305486515 [11^ 10^ 9 8] +
-0.006035157985678703 [11^ 10^ 10 1] +
-0.03509495685788454 [11^ 10^ 10 3] +
0.006035157985678703 [11^ 10^ 11 0] +
0.03509495685788454 [11^ 10^ 11 2] +
-0.41211988446241576 [11^ 10^ 11 10] +
-0.09549910444811928 [11^ 10^ 12 5] +
0.09549910444811928 [11^ 10^ 13 4] +
-0.1408167744673943 [11^ 10^ 13 12] +
-1.9157654958013657 [11^ 11] +
-0.1284726164071108 [12^ 0^ 4 0] +
0.008595469695128971 [12^ 0^ 4 2] +
-0.014594485862789764 [12^ 0^ 10 4] +
-0.5567172143140702 [12^ 0^ 12 0] +
0.016402394414051977 [12^ 0^ 12 2] +
0.025280856018048945 [12^ 0^ 12 10] +
-0.1397407246351288 [12^ 1^ 4 1] +
0.005111532195766256 [12^ 1^ 4 3] +
0.011268108228017996 [12^ 1^ 5 0] +
0.003483937499362717 [12^ 1^ 5 2] +
-0.011298345710068915 [12^ 1^ 10 5] +
-0.0032961401527208498 [12^ 1^ 11 4] +
-0.578149548740891 [12^ 1^ 12 1] +
0.009093683569910624 [12^ 1^ 12 3] +
0.00883200104696508 [12^ 1^ 12 11] +
0.021432334426820798 [12^ 1^ 13 0] +
0.007308710844141353 [12^ 1^ 13 2] +
0.016448854971083865 [12^ 1^ 13 10] +
0.025662934515149095 [12^ 2^ 4 0] +
-0.03842107742282559 [12^ 2^ 4 2] +
-0.06994809338073626 [12^ 2^ 10 4] +
0.016402394414051977 [12^ 2^ 12 0] +
-0.37220749500429434 [12^ 2^ 12 2] +
-0.018857298197224235 [12^ 2^ 12 10] +
0.005111532195766256 [12^ 3^ 4 1] +
0.005997822892627933 [12^ 3^ 4 3] +
0.02055140231938284 [12^ 3^ 5 0] +
-0.04441890031545352 [12^ 3^ 5 2] +
-0.14287757901096243 [12^ 3^ 10 5] +
0.07292948563022617 [12^ 3^ 11 4] +
0.009093683569910624 [12^ 3^ 12 1] +
-0.42879209546110686 [12^ 3^ 12 3] +
0.03705421023270726 [12^ 3^ 12 11] +
0.007308710844141353 [12^ 3^ 13 0] +
0.056584600456812524 [12^ 3^ 13 2] +
-0.05591150842993149 [12^ 3^ 13 10] +
-0.2794165481309364 [12^ 4] +
0.017067464820020122 [12^ 4^ 2 0] +
-0.013411171310694883 [12^ 4^ 10 0] +
-0.08167242390723375 [12^ 4^ 10 2] +
-0.3652659935936407 [12^ 4^ 12 4] +
0.011268108228017996 [12^ 5^ 1 0] +
-0.003483937499362717 [12^ 5^ 2 1] +
0.02055140231938284 [12^ 5^ 3 0] +
-0.04441890031545352 [12^ 5^ 3 2] +
-0.0212199008519232 [12^ 5^ 5 4] +
0.013776379310126395 [12^ 5^ 7 6] +
0.013776379310126409 [12^ 5^ 9 8] +
-0.011298345710068915 [12^ 5^ 10 1] +
-0.14287757901096243 [12^ 5^ 10 3] +
-0.0021128256006259687 [12^ 5^ 11 0] +
0.061205155103728676 [12^ 5^ 11 2] +
-0.09549910444811928 [12^ 5^ 11 10] +
-0.44760179381314075 [12^ 5^ 12 5] +
0.08233580021950003 [12^ 5^ 13 4] +
-0.011427757634974039 [12^ 5^ 13 12] +
0.04522287671754937 [12^ 6^ 6 4] +
-0.37488256748636634 [12^ 6^ 12 6] +
-0.013776379310126395 [12^ 7^ 6 5] +
0.058999256027675764 [12^ 7^ 7 4] +
-0.39141411210562255 [12^ 7^ 12 7] +
0.016531544619256183 [12^ 7^ 13 6] +
0.04522287671754943 [12^ 8^ 8 4] +
-0.3748825674863666 [12^ 8^ 12 8] +
-0.013776379310126409 [12^ 9^ 8 5] +
0.05899925602767584 [12^ 9^ 9 4] +
-0.3914141121056228 [12^ 9^ 12 9] +
0.0165315446192562 [12^ 9^ 13 8] +
0.0011833145520948813 [12^ 10^ 4 0] +
-0.011724330526497496 [12^ 10^ 4 2] +
0.06893541223429975 [12^ 10^ 10 4] +
0.02528085601804894 [12^ 10^ 12 0] +

,raw_index,coefficient,monomial,OpenFermion_key
0,0,+3.39216161,I,()
1,1,-8.65361406,a_0^dagger a_0,"((0, 1), (0, 0))"
2,2,+0.22578817,a_0^dagger a_2,"((0, 1), (2, 0))"
3,3,+0.19337590,a_0^dagger a_10,"((0, 1), (10, 0))"
4,4,-8.65361406,a_1^dagger a_1,"((1, 1), (1, 0))"
...,...,...,...,...
661,661,+0.05591151,a_13^dagger a_12^dagger a_11 a_2,"((13, 1), (12, 1), (11, 0), (2, 0))"
662,662,-0.14081677,a_13^dagger a_12^dagger a_11 a_10,"((13, 1), (12, 1), (11, 0), (10, 0))"
663,663,-0.01142776,a_13^dagger a_12^dagger a_12 a_5,"((13, 1), (12, 1), (12, 0), (5, 0))"
664,664,+0.01142776,a_13^dagger a_12^dagger a_13 a_4,"((13, 1), (12, 1), (13, 0), (4, 0))"
665,665,-0.48965248,a_13^dagger a_12^dagger a_13 a_12,"((13, 1), (12, 1), (13, 0), (12, 0))"

=== Hermitian fermionic terms T_i ===

,vertex,number_of_monomials,fermionic_term
0,T_0,1,+3.39216161 I
1,T_1,1,-8.65361406 a_0^dagger a_0
2,T_2,2,+0.22578817 a_0^dagger a_2 + +0.22578817 a_2^dagger a_0
3,T_3,2,+0.19337590 a_0^dagger a_10 + +0.19337590 a_10^dagger a_0
4,T_4,1,-8.65361406 a_1^dagger a_1
...,...,...,...
381,T_381,2,+0.14081677 a_12^dagger a_11^dagger a_13 a_10 + +0.14081677 a_13^dagger a_10^dagger a_12 a_11
382,T_382,1,-0.43649838 a_13^dagger a_10^dagger a_13 a_10
383,T_383,1,-0.43649838 a_12^dagger a_11^dagger a_12 a_11
384,T_384,1,-0.29568160 a_13^dagger a_11^dagger a_13 a_11
385,T_385,1,-0.48965248 a_13^dagger a_12^dagger a_13 a_12

In [2]:
# Cell 2: Build the H2 fermionic noncommutation graph

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from openfermion.transforms import normal_ordered

pd.set_option("display.max_colwidth", None)


def fermionic_commutator(A, B, tol=1e-12):
    """
    Compute [A, B] = AB - BA directly in the fermionic algebra.
    """
    C = normal_ordered(A * B - B * A)
    C.compress(abs_tol=tol)
    return C


def commute(A, B, tol=1e-12):
    """
    Return True if [A, B] = 0.
    """
    C = fermionic_commutator(A, B, tol=tol)
    return len(C.terms) == 0


# ------------------------------------------------------------
# Build noncommutation graph
# ------------------------------------------------------------
# Vertex i = Hermitian fermionic term T_i
# Edge (i, j) exists if [T_i, T_j] != 0

G = nx.Graph()

for i, T in enumerate(hermitian_terms):
    G.add_node(
        i,
        label=f"T_{i}",
        operator=T,
        operator_string=operator_to_string(T),
        number_of_monomials=len(T.terms),
    )

for i in range(len(hermitian_terms)):
    for j in range(i + 1, len(hermitian_terms)):
        Cij = fermionic_commutator(hermitian_terms[i], hermitian_terms[j])

        if len(Cij.terms) != 0:
            G.add_edge(
                i,
                j,
                commutator=Cij,
                commutator_string=operator_to_string(Cij),
            )


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

n_vertices = G.number_of_nodes()
n_total_pairs = n_vertices * (n_vertices - 1) // 2
n_noncommuting_pairs = G.number_of_edges()
n_commuting_pairs = n_total_pairs - n_noncommuting_pairs

print("=== Fermionic noncommutation graph summary ===")
print("Number of vertices / fermionic terms:", n_vertices)
print("Number of total unordered pairs:", n_total_pairs)
print("Number of noncommuting pairs / edges:", n_noncommuting_pairs)
print("Number of commuting pairs:", n_commuting_pairs)
print("Is graph bipartite?", nx.is_bipartite(G))


# ------------------------------------------------------------
# Vertex table
# ------------------------------------------------------------

vertex_rows = []

for i, data in G.nodes(data=True):
    vertex_rows.append(
        {
            "vertex": f"T_{i}",
            "degree": G.degree[i],
            "commutes_with_all": G.degree[i] == 0,
            "fermionic_term": data["operator_string"],
        }
    )

vertex_df = pd.DataFrame(vertex_rows)

print("\n=== Vertices: fermionic terms ===")
display(vertex_df)


# ------------------------------------------------------------
# Edge table
# ------------------------------------------------------------

edge_rows = []

for i, j, data in G.edges(data=True):
    edge_rows.append(
        {
            "source": f"T_{i}",
            "target": f"T_{j}",
            "meaning": f"[T_{i}, T_{j}] != 0",
            "commutator": data["commutator_string"],
        }
    )

edge_df = pd.DataFrame(edge_rows)

print("\n=== Edges: noncommuting pairs ===")
display(edge_df)


# # ------------------------------------------------------------
# # Draw graph
# # ------------------------------------------------------------

# plt.figure(figsize=(12, 8))

# pos = nx.kamada_kawai_layout(G)

# node_labels = {
#     i: f"T_{i}"
#     for i in G.nodes()
# }

# node_sizes = [
#     1000 + 250 * G.degree[i]
#     for i in G.nodes()
# ]

# nx.draw_networkx_nodes(G, pos, node_size=node_sizes)
# nx.draw_networkx_edges(G, pos, width=1.5)
# nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=11, font_weight="bold")

# plt.title("H2 Fermionic Noncommutation Graph")
# plt.axis("off")
# plt.show()

=== Fermionic noncommutation graph summary ===
Number of vertices / fermionic terms: 386
Number of total unordered pairs: 74305
Number of noncommuting pairs / edges: 35170
Number of commuting pairs: 39135
Is graph bipartite? False

=== Vertices: fermionic terms ===

,vertex,degree,commutes_with_all,fermionic_term
0,T_0,0,True,+3.39216161 I
1,T_1,84,False,-8.65361406 a_0^dagger a_0
2,T_2,166,False,+0.22578817 a_0^dagger a_2 + +0.22578817 a_2^dagger a_0
3,T_3,166,False,+0.19337590 a_0^dagger a_10 + +0.19337590 a_10^dagger a_0
4,T_4,84,False,-8.65361406 a_1^dagger a_1
...,...,...,...,...
381,T_381,242,False,+0.14081677 a_12^dagger a_11^dagger a_13 a_10 + +0.14081677 a_13^dagger a_10^dagger a_12 a_11
382,T_382,134,False,-0.43649838 a_13^dagger a_10^dagger a_13 a_10
383,T_383,134,False,-0.43649838 a_12^dagger a_11^dagger a_12 a_11
384,T_384,124,False,-0.29568160 a_13^dagger a_11^dagger a_13 a_11
385,T_385,112,False,-0.48965248 a_13^dagger a_12^dagger a_13 a_12

=== Edges: noncommuting pairs ===

,source,target,meaning,commutator
0,T_1,T_2,"[T_1, T_2] != 0",-1.95388369 a_0^dagger a_2 + +1.95388369 a_2^dagger a_0
1,T_1,T_3,"[T_1, T_3] != 0",-1.67340044 a_0^dagger a_10 + +1.67340044 a_10^dagger a_0
2,T_1,T_24,"[T_1, T_24] != 0",+1.72316617 a_1^dagger a_0^dagger a_2 a_1 + -1.72316617 a_2^dagger a_1^dagger a_1 a_0
3,T_1,T_25,"[T_1, T_25] != 0",+1.56558003 a_1^dagger a_0^dagger a_10 a_1 + -1.56558003 a_10^dagger a_1^dagger a_1 a_0
4,T_1,T_27,"[T_1, T_27] != 0",+0.23180096 a_1^dagger a_0^dagger a_3 a_2 + -0.23180096 a_3^dagger a_2^dagger a_1 a_0
...,...,...,...,...
35165,T_377,T_381,"[T_377, T_381] != 0",-0.05278975 a_12^dagger a_11^dagger a_9^dagger a_13 a_10 a_9 + +0.05278975 a_13^dagger a_10^dagger a_9^dagger a_12 a_11 a_9
35166,T_378,T_379,"[T_378, T_379] != 0",-0.05803339 a_11^dagger a_10^dagger a_13 a_12 + +0.05803339 a_13^dagger a_12^dagger a_11 a_10
35167,T_379,T_385,"[T_379, T_385] != 0",-0.06895128 a_11^dagger a_10^dagger a_13 a_12 + +0.06895128 a_13^dagger a_12^dagger a_11 a_10
35168,T_381,T_382,"[T_381, T_382] != 0",+0.06146629 a_12^dagger a_11^dagger a_13 a_10 + -0.06146629 a_13^dagger a_10^dagger a_12 a_11
35169,T_381,T_383,"[T_381, T_383] != 0",-0.06146629 a_12^dagger a_11^dagger a_13 a_10 + +0.06146629 a_13^dagger a_10^dagger a_12 a_11

In [3]:
# Cell 2 alpha: Faster H2 / molecular fermionic noncommutation graph
#
# Main idea:
#   1. Use cheap fermionic index rules first.
#   2. Only if rules cannot decide, use exact OpenFermion symbolic commutator.
#   3. Never build sparse/dense matrices.
#
# This cell assumes Cell 1 already defined:
#   hermitian_terms
#   operator_to_string

import time
from collections import Counter

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from openfermion.utils import commutator
from openfermion.transforms import normal_ordered

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# Fermionic key utilities
# ------------------------------------------------------------

def key_modes(key):
    """
    Modes appearing in one OpenFermion monomial key.

    Example:
        ((3, 1), (0, 1), (3, 0), (0, 0)) -> {0, 3}
    """
    return frozenset(mode for mode, action in key)


def key_creations(key):
    """
    Creation modes in one monomial.
    """
    return frozenset(mode for mode, action in key if action == 1)


def key_annihilations(key):
    """
    Annihilation modes in one monomial.
    """
    return frozenset(mode for mode, action in key if action == 0)


def key_net_delta(key):
    """
    Net occupation change caused by a monomial.

    creation contributes +1
    annihilation contributes -1

    For example:
        a_2^dagger a_1^dagger a_3 a_0
    has delta:
        +1 on modes 2 and 1
        -1 on modes 3 and 0
    """
    delta = Counter()

    for mode, action in key:
        if action == 1:
            delta[mode] += 1
        else:
            delta[mode] -= 1

    return delta


def is_diagonal_key(key):
    """
    True if a monomial preserves occupation mode-by-mode.

    Examples:
        a_p^dagger a_p is diagonal.
        a_p^dagger a_q^dagger a_q a_p is diagonal.
        a_p^dagger a_q is not diagonal when p != q.
    """
    delta = key_net_delta(key)
    return all(value == 0 for value in delta.values())


def is_even_key(key):
    """
    Electronic Hamiltonian terms normally have even fermionic parity:
    length 0, 2, or 4.
    """
    return len(key) % 2 == 0


# ------------------------------------------------------------
# Safe monomial-level commutation rules
# ------------------------------------------------------------

def diagonal_key_commutes_with_key(diagonal_key, other_key):
    """
    Safe rule:

    A diagonal occupation operator depending on modes S commutes with another
    monomial if the other monomial has zero net occupation change on every
    mode in S.
    """
    support = key_modes(diagonal_key)
    delta = key_net_delta(other_key)

    return all(delta.get(mode, 0) == 0 for mode in support)


def no_cross_contractions_even_commute(key_a, key_b):
    """
    Safe rule for normal-ordered even fermionic monomials.

    If there are no possible cross contractions:
        annihilations(A) intersect creations(B) = empty
        annihilations(B) intersect creations(A) = empty

    then even monomials commute.

    This catches many cases beyond completely disjoint support.
    """
    if not is_even_key(key_a) or not is_even_key(key_b):
        return False

    a_ann = key_annihilations(key_a)
    a_cre = key_creations(key_a)

    b_ann = key_annihilations(key_b)
    b_cre = key_creations(key_b)

    return a_ann.isdisjoint(b_cre) and b_ann.isdisjoint(a_cre)


def monomial_pair_definitely_commutes(key_a, key_b):
    """
    Return (True, reason) only when we are sure two monomials commute.
    Return (False, None) if the rule cannot decide.

    Important:
        False here does NOT mean noncommuting.
        It only means "unknown; use exact symbolic fallback."
    """
    # Identity commutes with everything.
    if key_a == () or key_b == ():
        return True, "identity"

    # Any monomial commutes with itself.
    if key_a == key_b:
        return True, "same_monomial"

    # Diagonal occupation-like monomials commute with each other.
    if is_diagonal_key(key_a) and is_diagonal_key(key_b):
        return True, "diagonal_diagonal"

    # Diagonal with excitation-like term, if excitation preserves diagonal support.
    if is_diagonal_key(key_a) and diagonal_key_commutes_with_key(key_a, key_b):
        return True, "diagonal_support_preserved"

    if is_diagonal_key(key_b) and diagonal_key_commutes_with_key(key_b, key_a):
        return True, "diagonal_support_preserved"

    # Even monomials with no cross contractions commute.
    if no_cross_contractions_even_commute(key_a, key_b):
        return True, "no_cross_contractions_even"

    return False, None


# ------------------------------------------------------------
# Operator-level metadata and precheck
# ------------------------------------------------------------

def operator_metadata(op):
    """
    Precompute simple structural data for one FermionOperator.
    """
    keys = list(op.terms.keys())

    modes = set()
    for key in keys:
        modes.update(key_modes(key))

    return {
        "is_zero": len(keys) == 0,
        "only_identity": len(keys) == 1 and keys[0] == (),
        "modes": frozenset(modes),
        "is_even": all(is_even_key(key) for key in keys),
        "is_diagonal": all(is_diagonal_key(key) for key in keys),
        "number_of_monomials": len(keys),
    }


def operator_pair_definitely_commutes(A, B, meta_A, meta_B):
    """
    Return (True, reason) only for guaranteed-commuting pairs.
    Return (False, None) when unresolved.
    """
    if meta_A["is_zero"] or meta_B["is_zero"]:
        return True, "zero"

    if meta_A["only_identity"] or meta_B["only_identity"]:
        return True, "identity"

    # Very cheap global rule:
    # disjoint even fermionic operators commute.
    if (
        meta_A["is_even"]
        and meta_B["is_even"]
        and meta_A["modes"].isdisjoint(meta_B["modes"])
    ):
        return True, "disjoint_even_support"

    # Diagonal occupation-like operators commute with each other.
    if meta_A["is_diagonal"] and meta_B["is_diagonal"]:
        return True, "diagonal_diagonal"

    # More detailed but still cheap:
    # if every monomial pair has a safe commuting reason, the sums commute.
    reasons = Counter()

    for key_a in A.terms:
        for key_b in B.terms:
            ok, reason = monomial_pair_definitely_commutes(key_a, key_b)

            if not ok:
                return False, None

            reasons[reason] += 1

    if len(reasons) > 0:
        main_reason = reasons.most_common(1)[0][0]
        return True, f"all_monomial_pairs_{main_reason}"

    return False, None


# ------------------------------------------------------------
# Exact symbolic fallback
# ------------------------------------------------------------

def exact_symbolic_fermionic_commutator(A, B, tol=1e-12):
    """
    Exact symbolic commutator in fermionic algebra.

    This does not build a 2^n matrix.
    """
    C = normal_ordered(commutator(A, B))
    C.compress(abs_tol=tol)
    return C


# ------------------------------------------------------------
# Alpha graph builder
# ------------------------------------------------------------

def build_fermionic_noncommutation_graph_alpha(
    hermitian_terms,
    tol=1e-12,
    store_commutators=False,
):
    """
    Build noncommutation graph using:
        fast safe index rules first,
        exact symbolic OpenFermion fallback only when needed.

    Parameters
    ----------
    hermitian_terms:
        list of FermionOperator terms T_i from Cell 1.

    tol:
        numerical compression tolerance.

    store_commutators:
        False is recommended for large molecules.
        True is useful for H2 debugging, but can be memory-heavy.

    Returns
    -------
    G:
        networkx.Graph

    stats_df:
        pandas.DataFrame with timing and skip counts
    """
    t_start = time.perf_counter()

    G = nx.Graph()
    stats = Counter()

    metadata = [operator_metadata(T) for T in hermitian_terms]

    # Add vertices.
    for i, T in enumerate(hermitian_terms):
        G.add_node(
            i,
            label=f"T_{i}",
            operator=T,
            operator_string=operator_to_string(T),
            number_of_monomials=len(T.terms),
            modes=sorted(metadata[i]["modes"]),
            is_diagonal=metadata[i]["is_diagonal"],
            is_even=metadata[i]["is_even"],
        )

    n = len(hermitian_terms)

    # Pairwise graph construction.
    for i in range(n):
        A = hermitian_terms[i]
        meta_A = metadata[i]

        for j in range(i + 1, n):
            B = hermitian_terms[j]
            meta_B = metadata[j]

            stats["total_pairs"] += 1

            # 1. Fast guaranteed-commuting rules.
            definitely_commutes, reason = operator_pair_definitely_commutes(
                A, B, meta_A, meta_B
            )

            if definitely_commutes:
                stats["pairs_skipped_by_index_rules"] += 1
                stats[f"skip_{reason}"] += 1
                continue

            # 2. Exact symbolic fallback.
            stats["pairs_sent_to_exact_symbolic"] += 1

            Cij = exact_symbolic_fermionic_commutator(A, B, tol=tol)

            if len(Cij.terms) != 0:
                stats["noncommuting_edges"] += 1

                edge_data = {
                    "method": "exact_symbolic_fallback",
                    "meaning": f"[T_{i}, T_{j}] != 0",
                }

                if store_commutators:
                    edge_data["commutator"] = Cij
                    edge_data["commutator_string"] = operator_to_string(Cij)
                else:
                    edge_data["commutator_string"] = (
                        "(not stored; rerun with store_commutators=True)"
                    )

                G.add_edge(i, j, **edge_data)

            else:
                stats["exact_symbolic_found_commuting"] += 1

    elapsed = time.perf_counter() - t_start

    stats["vertices"] = n
    stats["edges"] = G.number_of_edges()
    stats["commuting_pairs"] = stats["total_pairs"] - G.number_of_edges()
    stats["elapsed_seconds"] = elapsed

    stats_df = pd.DataFrame([dict(stats)])

    return G, stats_df


# ------------------------------------------------------------
# Run alpha graph builder
# ------------------------------------------------------------

# For H2 debugging, you can set store_commutators=True.
# For larger molecules, keep this False.
G_alpha, stats_df = build_fermionic_noncommutation_graph_alpha(
    hermitian_terms,
    tol=1e-12,
    store_commutators=False,
)

print("=== Fermionic noncommutation graph alpha summary ===")
display(stats_df)

print("Number of vertices / fermionic terms:", G_alpha.number_of_nodes())
print("Number of noncommuting pairs / edges:", G_alpha.number_of_edges())
print("Is graph bipartite?", nx.is_bipartite(G_alpha))


# ------------------------------------------------------------
# Vertex table
# ------------------------------------------------------------

vertex_rows = []

for i, data in G_alpha.nodes(data=True):
    vertex_rows.append(
        {
            "vertex": f"T_{i}",
            "degree": G_alpha.degree[i],
            "commutes_with_all": G_alpha.degree[i] == 0,
            "number_of_monomials": data["number_of_monomials"],
            "modes": data["modes"],
            "is_diagonal": data["is_diagonal"],
            "fermionic_term": data["operator_string"],
        }
    )

vertex_df_alpha = pd.DataFrame(vertex_rows)

print("\n=== Alpha vertices: fermionic terms ===")
display(vertex_df_alpha)


# ------------------------------------------------------------
# Edge table
# ------------------------------------------------------------

edge_rows = []

for i, j, data in G_alpha.edges(data=True):
    edge_rows.append(
        {
            "source": f"T_{i}",
            "target": f"T_{j}",
            "meaning": data["meaning"],
            "method": data["method"],
            "commutator": data["commutator_string"],
        }
    )

edge_df_alpha = pd.DataFrame(edge_rows)

print("\n=== Alpha edges: noncommuting pairs ===")
display(edge_df_alpha)

# The commutation graph is too large for this.

# # ------------------------------------------------------------
# # Draw graph
# # ------------------------------------------------------------

# plt.figure(figsize=(12, 8))

# pos = nx.kamada_kawai_layout(G_alpha)

# node_labels = {
#     i: f"T_{i}"
#     for i in G_alpha.nodes()
# }

# node_sizes = [
#     1000 + 250 * G_alpha.degree[i]
#     for i in G_alpha.nodes()
# ]

# nx.draw_networkx_nodes(G_alpha, pos, node_size=node_sizes)
# nx.draw_networkx_edges(G_alpha, pos, width=1.5)
# nx.draw_networkx_labels(
#     G_alpha,
#     pos,
#     labels=node_labels,
#     font_size=11,
#     font_weight="bold",
# )

# plt.title("Fermionic Noncommutation Graph Alpha")
# plt.axis("off")
# plt.show()

=== Fermionic noncommutation graph alpha summary ===

,total_pairs,pairs_skipped_by_index_rules,skip_identity,pairs_sent_to_exact_symbolic,noncommuting_edges,skip_disjoint_even_support,skip_diagonal_diagonal,skip_all_monomial_pairs_diagonal_support_preserved,exact_symbolic_found_commuting,vertices,edges,commuting_pairs,elapsed_seconds
0,74305,34700,385,39605,35170,31889,1274,1152,4435,386,35170,39135,2.227835

Number of vertices / fermionic terms: 386
Number of noncommuting pairs / edges: 35170
Is graph bipartite? False

=== Alpha vertices: fermionic terms ===

,vertex,degree,commutes_with_all,number_of_monomials,modes,is_diagonal,fermionic_term
0,T_0,0,True,1,[],True,+3.39216161 I
1,T_1,84,False,1,[0],True,-8.65361406 a_0^dagger a_0
2,T_2,166,False,2,"[0, 2]",False,+0.22578817 a_0^dagger a_2 + +0.22578817 a_2^dagger a_0
3,T_3,166,False,2,"[0, 10]",False,+0.19337590 a_0^dagger a_10 + +0.19337590 a_10^dagger a_0
4,T_4,84,False,1,[1],True,-8.65361406 a_1^dagger a_1
...,...,...,...,...,...,...,...
381,T_381,242,False,2,"[10, 11, 12, 13]",False,+0.14081677 a_12^dagger a_11^dagger a_13 a_10 + +0.14081677 a_13^dagger a_10^dagger a_12 a_11
382,T_382,134,False,1,"[10, 13]",True,-0.43649838 a_13^dagger a_10^dagger a_13 a_10
383,T_383,134,False,1,"[11, 12]",True,-0.43649838 a_12^dagger a_11^dagger a_12 a_11
384,T_384,124,False,1,"[11, 13]",True,-0.29568160 a_13^dagger a_11^dagger a_13 a_11
385,T_385,112,False,1,"[12, 13]",True,-0.48965248 a_13^dagger a_12^dagger a_13 a_12

=== Alpha edges: noncommuting pairs ===

,source,target,meaning,method,commutator
0,T_1,T_2,"[T_1, T_2] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
1,T_1,T_3,"[T_1, T_3] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
2,T_1,T_24,"[T_1, T_24] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
3,T_1,T_25,"[T_1, T_25] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
4,T_1,T_27,"[T_1, T_27] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
...,...,...,...,...,...
35165,T_377,T_381,"[T_377, T_381] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
35166,T_378,T_379,"[T_378, T_379] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
35167,T_379,T_385,"[T_379, T_385] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
35168,T_381,T_382,"[T_381, T_382] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
35169,T_381,T_383,"[T_381, T_383] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)

In [4]:
print("Same edge set?")
print(set(G.edges()) == set(G_alpha.edges()))

Same edge set?
True

In [5]:
# Cell 3: Color graph, build commuting blocks, map JW/BK, verify commutation

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from itertools import combinations
from openfermion.ops import FermionOperator
from openfermion.transforms import normal_ordered, jordan_wigner, bravyi_kitaev

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# 1. Color the noncommutation graph
# ------------------------------------------------------------
# Since edges mean noncommutation, each color class is a commuting group.

coloring = nx.coloring.greedy_color(G, strategy="largest_first")

color_groups = {}

for node, color in coloring.items():
    color_groups.setdefault(color, []).append(node)

for color in color_groups:
    color_groups[color] = sorted(color_groups[color])

color_names = [
    "red",
    "blue",
    "green",
    "orange",
    "purple",
    "brown",
    "pink",
    "gray",
]

color_name = {
    color: color_names[color] if color < len(color_names) else f"color_{color}"
    for color in color_groups
}

num_grouped_terms = sum(len(nodes) for nodes in color_groups.values())

print("Number of fermionic terms / vertices:", G.number_of_nodes())
print("Number of colors / commuting groups:", len(color_groups))
print("Number of grouped terms:", num_grouped_terms)

assert num_grouped_terms == G.number_of_nodes()


# ------------------------------------------------------------
# 2. Verify each color group is mutually commuting
# ------------------------------------------------------------

def verify_commuting_group(nodes, tol=1e-12):
    for i, j in combinations(nodes, 2):
        A = G.nodes[i]["operator"]
        B = G.nodes[j]["operator"]

        if not commute(A, B, tol=tol):
            return False

    return True


group_summary_rows = []

for color, nodes in sorted(color_groups.items()):
    group_summary_rows.append(
        {
            "color_id": color,
            "color_name": color_name[color],
            "number_of_terms": len(nodes),
            "vertices": [f"T_{i}" for i in nodes],
            "verified_mutually_commuting": verify_commuting_group(nodes),
        }
    )

group_summary_df = pd.DataFrame(group_summary_rows)

print("\n=== Commuting groups from graph coloring ===")
display(group_summary_df)


# ------------------------------------------------------------
# 3. Build Hamiltonian pieces by color
# ------------------------------------------------------------

H_by_color = {}

for color, nodes in sorted(color_groups.items()):
    H_color = FermionOperator.zero()

    for node in nodes:
        H_color += G.nodes[node]["operator"]

    H_color = normal_ordered(H_color)
    H_color.compress(abs_tol=1e-12)

    H_by_color[color] = H_color


color_block_rows = []

for color, nodes in sorted(color_groups.items()):
    for local_index, node in enumerate(nodes, start=1):
        color_block_rows.append(
            {
                "color_block": f"H_{color_name[color]}",
                "local_term_name": f"{color_name[color][0].upper()}_{local_index}",
                "vertex": f"T_{node}",
                "fermionic_term": G.nodes[node]["operator_string"],
            }
        )

color_block_df = pd.DataFrame(color_block_rows)

print("\n=== Which T_i belongs to which color block ===")
display(color_block_df)


print("\n=== Hamiltonian split by commuting color groups ===")

for color, H_color in H_by_color.items():
    nodes = color_groups[color]

    print("\n" + "=" * 80)
    print(f"H_{color_name[color]} consists of:")
    print(" + ".join([f"T_{node}" for node in nodes]))

    print(f"\nSummed operator H_{color_name[color]} =")
    print(H_color)


# ------------------------------------------------------------
# 4. Trotter ordering induced by color groups
# ------------------------------------------------------------

trotter_order = []

for color, nodes in sorted(color_groups.items()):
    for node in nodes:
        trotter_order.append(node)

print("\n=== Trotter order by commuting color groups ===")
print([f"T_{i}" for i in trotter_order])


# ------------------------------------------------------------
# 5. Helper functions for JW/BK output
# ------------------------------------------------------------

def sort_qubit_key(term):
    return (len(term), term)


def format_qubit_term(term):
    if term == ():
        return "I"

    return " ".join([f"{pauli}{qubit}" for qubit, pauli in term])


def qubit_coeff_to_str(c, digits=8):
    c = complex(c)
    if abs(c.imag) < 1e-12:
        return f"{c.real:+.{digits}f}"
    return f"{c.real:+.{digits}f}{c.imag:+.{digits}f}j"


def qubit_operator_to_string(op, digits=8):
    pieces = []

    for term, coeff in sorted(op.terms.items(), key=lambda item: sort_qubit_key(item[0])):
        pieces.append(f"{qubit_coeff_to_str(coeff, digits)} {format_qubit_term(term)}")

    if len(pieces) == 0:
        return "0"

    return " + ".join(pieces)


def apply_bk(op, n_qubits):
    try:
        return bravyi_kitaev(op, n_qubits=n_qubits)
    except TypeError:
        return bravyi_kitaev(op, n_qubits)


def qubit_commutator(A, B, tol=1e-12):
    C = A * B - B * A
    C.compress(abs_tol=tol)
    return C


def qubit_commute(A, B, tol=1e-12):
    C = qubit_commutator(A, B, tol=tol)
    return len(C.terms) == 0


n_qubits = molecule.n_qubits

print("\nNumber of qubits / spin orbitals:", n_qubits)


# ------------------------------------------------------------
# 6. Map each fermionic vertex T_i to JW(T_i) and BK(T_i)
# ------------------------------------------------------------

mapped_rows = []

for node in sorted(G.nodes()):
    T_i = G.nodes[node]["operator"]

    JW_T_i = jordan_wigner(T_i)
    JW_T_i.compress(abs_tol=1e-12)

    BK_T_i = apply_bk(T_i, n_qubits=n_qubits)
    BK_T_i.compress(abs_tol=1e-12)

    G.nodes[node]["JW_operator"] = JW_T_i
    G.nodes[node]["BK_operator"] = BK_T_i
    G.nodes[node]["JW_operator_string"] = qubit_operator_to_string(JW_T_i)
    G.nodes[node]["BK_operator_string"] = qubit_operator_to_string(BK_T_i)

    node_color = coloring[node]
    node_color_name = color_name[node_color]

    mapped_rows.append(
        {
            "color": node_color_name,
            "vertex": f"T_{node}",
            "fermionic_term": G.nodes[node]["operator_string"],
            "number_of_JW_Pauli_strings": len(JW_T_i.terms),
            "JW_transform": qubit_operator_to_string(JW_T_i),
            "number_of_BK_Pauli_strings": len(BK_T_i.terms),
            "BK_transform": qubit_operator_to_string(BK_T_i),
        }
    )

mapped_terms_df = pd.DataFrame(mapped_rows)

print("\n=== Fermionic terms mapped to JW and BK ===")
display(mapped_terms_df)


# ------------------------------------------------------------
# 7. Map each color block H_color to JW and BK
# ------------------------------------------------------------

JW_by_color = {}
BK_by_color = {}

block_rows = []

for color, H_color in sorted(H_by_color.items()):
    JW_color = jordan_wigner(H_color)
    JW_color.compress(abs_tol=1e-12)

    BK_color = apply_bk(H_color, n_qubits=n_qubits)
    BK_color.compress(abs_tol=1e-12)

    JW_by_color[color] = JW_color
    BK_by_color[color] = BK_color

    block_rows.append(
        {
            "color_block": f"H_{color_name[color]}",
            "fermionic_vertices": " + ".join([f"T_{node}" for node in color_groups[color]]),
            "number_of_fermionic_terms": len(color_groups[color]),
            "number_of_JW_Pauli_strings": len(JW_color.terms),
            "JW_block": qubit_operator_to_string(JW_color),
            "number_of_BK_Pauli_strings": len(BK_color.terms),
            "BK_block": qubit_operator_to_string(BK_color),
        }
    )

block_map_df = pd.DataFrame(block_rows)

print("\n=== Color blocks mapped to JW and BK ===")
display(block_map_df)


# ------------------------------------------------------------
# 8. Verify same-color terms commute after JW and BK
# ------------------------------------------------------------

verification_rows = []

for color, nodes in sorted(color_groups.items()):
    for i, j in combinations(nodes, 2):
        Ti = G.nodes[i]["operator"]
        Tj = G.nodes[j]["operator"]

        JW_Ti = G.nodes[i]["JW_operator"]
        JW_Tj = G.nodes[j]["JW_operator"]

        BK_Ti = G.nodes[i]["BK_operator"]
        BK_Tj = G.nodes[j]["BK_operator"]

        verification_rows.append(
            {
                "color_group": color_name[color],
                "pair": f"T_{i}, T_{j}",
                "fermionic_commute": commute(Ti, Tj),
                "JW_commute": qubit_commute(JW_Ti, JW_Tj),
                "BK_commute": qubit_commute(BK_Ti, BK_Tj),
            }
        )

verification_df = pd.DataFrame(verification_rows)

print("\n=== Verify commuting groups after JW/BK mapping ===")
display(verification_df)

Number of fermionic terms / vertices: 386
Number of colors / commuting groups: 45
Number of grouped terms: 386

=== Commuting groups from graph coloring ===

,color_id,color_name,number_of_terms,vertices,verified_mutually_commuting
0,0,red,14,"[T_0, T_17, T_18, T_29, T_59, T_62, T_153, T_209, T_249, T_348, T_353, T_354, T_362, T_365]",True
1,1,blue,14,"[T_15, T_16, T_30, T_63, T_109, T_150, T_208, T_248, T_290, T_346, T_366, T_368, T_369, T_375]",True
2,2,green,14,"[T_19, T_20, T_36, T_56, T_113, T_196, T_203, T_215, T_245, T_347, T_350, T_351, T_360, T_378]",True
3,3,orange,14,"[T_37, T_108, T_114, T_195, T_202, T_210, T_214, T_261, T_352, T_355, T_359, T_361, T_370, T_374]",True
4,4,purple,4,"[T_47, T_64, T_135, T_187]",True
5,5,brown,4,"[T_48, T_65, T_128, T_141]",True
6,6,pink,4,"[T_54, T_115, T_134, T_186]",True
7,7,gray,4,"[T_55, T_116, T_127, T_140]",True
8,8,color_8,10,"[T_61, T_69, T_99, T_182, T_191, T_198, T_204, T_222, T_224, T_268]",True
9,9,color_9,10,"[T_70, T_100, T_111, T_146, T_175, T_205, T_228, T_230, T_273, T_338]",True
10,10,color_10,13,"[T_7, T_9, T_106, T_119, T_155, T_181, T_190, T_200, T_225, T_231, T_265, T_270, T_380]",True
11,11,color_11,6,"[T_107, T_120, T_145, T_174, T_312, T_384]",True
12,12,color_12,10,"[T_31, T_74, T_77, T_161, T_213, T_218, T_237, T_282, T_287, T_291]",True
13,13,color_13,9,"[T_32, T_83, T_86, T_169, T_219, T_238, T_246, T_258, T_276]",True
14,14,color_14,12,"[T_1, T_4, T_23, T_79, T_88, T_157, T_165, T_243, T_251, T_264, T_281, T_286]",True
15,15,color_15,4,"[T_244, T_252, T_257, T_275]",True
16,16,color_16,10,"[T_27, T_38, T_42, T_136, T_297, T_314, T_349, T_356, T_357, T_364]",True
17,17,color_17,23,"[T_2, T_13, T_21, T_24, T_45, T_67, T_75, T_80, T_84, T_89, T_110, T_192, T_288, T_317, T_322, T_325, T_328, T_330, T_333, T_343, T_363, T_371, T_376]",True
18,18,color_18,23,"[T_5, T_11, T_22, T_26, T_121, T_125, T_143, T_158, T_162, T_166, T_170, T_197, T_253, T_300, T_303, T_306, T_309, T_323, T_337, T_342, T_358, T_373, T_377]",True
19,19,color_19,5,"[T_58, T_152, T_293, T_379, T_381]",True
20,20,color_20,8,"[T_28, T_43, T_94, T_139, T_227, T_239, T_299, T_319]",True
21,21,color_21,12,"[T_12, T_14, T_34, T_41, T_95, T_185, T_267, T_277, T_307, T_310, T_331, T_334]",True
22,22,color_22,14,"[T_35, T_92, T_96, T_183, T_211, T_220, T_259, T_262, T_301, T_304, T_318, T_326, T_329, T_345]",True
23,23,color_23,7,"[T_52, T_97, T_160, T_176, T_284, T_298, T_344]",True
24,24,color_24,8,"[T_53, T_98, T_129, T_156, T_283, T_296, T_308, T_385]",True
25,25,color_25,7,"[T_82, T_101, T_132, T_172, T_235, T_294, T_324]",True
26,26,color_26,7,"[T_49, T_78, T_133, T_173, T_234, T_311, T_321]",True
27,27,color_27,6,"[T_57, T_71, T_147, T_151, T_207, T_236]",True
28,28,color_28,4,"[T_72, T_117, T_148, T_188]",True
29,29,color_29,4,"[T_73, T_118, T_149, T_189]",True
30,30,color_30,4,"[T_221, T_250, T_260, T_285]",True
31,31,color_31,20,"[T_3, T_25, T_40, T_46, T_60, T_68, T_76, T_81, T_85, T_90, T_105, T_112, T_123, T_124, T_142, T_216, T_241, T_255, T_315, T_383]",True
32,32,color_32,18,"[T_6, T_33, T_44, T_66, T_126, T_138, T_144, T_154, T_159, T_163, T_167, T_171, T_180, T_194, T_199, T_279, T_335, T_382]",True
33,33,color_33,22,"[T_8, T_10, T_39, T_51, T_131, T_137, T_212, T_217, T_223, T_226, T_229, T_232, T_247, T_254, T_256, T_263, T_266, T_269, T_271, T_274, T_289, T_292]",True
34,34,color_34,8,"[T_93, T_104, T_122, T_179, T_184, T_193, T_295, T_302]",True
35,35,color_35,5,"[T_103, T_201, T_242, T_316, T_339]",True
36,36,color_36,5,"[T_178, T_206, T_280, T_313, T_336]",True
37,37,color_37,4,"[T_50, T_87, T_305, T_320]",True
38,38,color_38,4,"[T_91, T_102, T_327, T_340]",True
39,39,color_39,2,"[T_130, T_164]",True
40,40,color_40,2,"[T_168, T_177]",True
41,41,color_41,2,"[T_233, T_240]",True
42,42,color_42,2,"[T_272, T_278]",True
43,43,color_43,2,"[T_332, T_341]",True
44,44,color_44,2,"[T_367, T_372]",True

=== Which T_i belongs to which color block ===

,color_block,local_term_name,vertex,fermionic_term
0,H_red,R_1,T_0,+3.39216161 I
1,H_red,R_2,T_17,-2.29974267 a_8^dagger a_8
2,H_red,R_3,T_18,-2.29974267 a_9^dagger a_9
3,H_red,R_4,T_29,-0.00604787 a_1^dagger a_0^dagger a_5 a_4 + -0.00604787 a_5^dagger a_4^dagger a_1 a_0
4,H_red,R_5,T_59,+0.02566293 a_4^dagger a_0^dagger a_12 a_2 + +0.02566293 a_12^dagger a_2^dagger a_4 a_0
...,...,...,...,...
381,H_color_42,C_2,T_278,+0.04743776 a_9^dagger a_8^dagger a_10 a_3 + +0.04743776 a_10^dagger a_3^dagger a_9 a_8
382,H_color_43,C_1,T_332,-0.01377638 a_8^dagger a_5^dagger a_12 a_9 + -0.01377638 a_12^dagger a_9^dagger a_8 a_5
383,H_color_43,C_2,T_341,+0.01377638 a_9^dagger a_8^dagger a_12 a_5 + +0.01377638 a_12^dagger a_5^dagger a_9 a_8
384,H_color_44,C_1,T_367,-0.01653154 a_9^dagger a_8^dagger a_13 a_12 + -0.01653154 a_13^dagger a_12^dagger a_9 a_8
385,H_color_44,C_2,T_372,+0.01653154 a_12^dagger a_9^dagger a_13 a_8 + +0.01653154 a_13^dagger a_8^dagger a_12 a_9

=== Hamiltonian split by commuting color groups ===

================================================================================
H_red consists of:
T_0 + T_17 + T_18 + T_29 + T_59 + T_62 + T_153 + T_209 + T_249 + T_348 + T_353 + T_354 + T_362 + T_365

Summed operator H_red =
3.3921616084615387 [] +
-0.006047866793733274 [1^ 0^ 5 4] +
-0.056584600456812524 [3^ 2^ 13 12] +
0.025662934515149095 [4^ 0^ 12 2] +
0.006047866793733274 [4^ 1^ 5 0] +
0.006047866793733274 [5^ 0^ 4 1] +
0.025662934515149095 [5^ 1^ 13 3] +
-0.006047866793733274 [5^ 4^ 1 0] +
-0.05092314430548645 [7^ 6^ 11 10] +
-2.2997426657607067 [8^ 8] +
-0.4498590410866713 [9^ 8^ 9 8] +
-2.2997426657607067 [9^ 9] +
-0.3167299451888317 [10^ 6^ 10 6] +
0.05092314430548645 [10^ 7^ 11 6] +
0.05092314430548645 [11^ 6^ 10 7] +
-0.3167299451888317 [11^ 7^ 11 7] +
-0.05092314430548645 [11^ 10^ 7 6] +
0.025662934515149095 [12^ 2^ 4 0] +
0.056584600456812524 [12^ 3^ 13 2] +
0.056584600456812524 [13^ 2^ 12 3] +
0.025662934515149095 [13^ 3^ 5 1] +
-0.056584600456812524 [13^ 12^ 3 2]

================================================================================
H_blue consists of:
T_15 + T_16 + T_30 + T_63 + T_109 + T_150 + T_208 + T_248 + T_290 + T_346 + T_366 + T_368 + T_369 + T_375

Summed operator H_blue =
0.011268108228017996 [1^ 0^ 12 5] +
0.04441890031545352 [3^ 2^ 13 4] +
0.008595469695128971 [4^ 2^ 12 0] +
-0.04441890031545352 [4^ 3^ 13 2] +
0.011268108228017996 [5^ 0^ 12 1] +
-0.45310403754564726 [5^ 1^ 5 1] +
-2.2997426657607045 [6^ 6] +
-0.4498590410866703 [7^ 6^ 7 6] +
-2.2997426657607045 [7^ 7] +
-0.050923144305486515 [9^ 8^ 11 10] +
-0.316729945188832 [10^ 8^ 10 8] +
0.050923144305486515 [10^ 9^ 11 8] +
0.050923144305486515 [11^ 8^ 10 9] +
-0.316729945188832 [11^ 9^ 11 9] +
-0.050923144305486515 [11^ 10^ 9 8] +
0.008595469695128971 [12^ 0^ 4 2] +
0.011268108228017996 [12^ 1^ 5 0] +
0.011268108228017996 [12^ 5^ 1 0] +
-0.04441890031545352 [13^ 2^ 4 3] +
-0.37220749500429434 [13^ 3^ 13 3] +
0.04441890031545352 [13^ 4^ 3 2]

================================================================================
H_green consists of:
T_19 + T_20 + T_36 + T_56 + T_113 + T_196 + T_203 + T_215 + T_245 + T_347 + T_350 + T_351 + T_360 + T_378

Summed operator H_green =
-0.011268108228017996 [1^ 0^ 13 4] +
-0.04441890031545352 [3^ 2^ 12 5] +
-0.45310403754564726 [4^ 0^ 4 0] +
0.011268108228017996 [4^ 1^ 13 0] +
-0.04441890031545352 [5^ 2^ 12 3] +
0.008595469695128971 [5^ 3^ 13 1] +
-0.024249379221171166 [7^ 6^ 9 8] +
-0.37711090342315745 [8^ 6^ 8 6] +
0.024249379221171166 [8^ 7^ 9 6] +
0.024249379221171166 [9^ 6^ 8 7] +
-0.37711090342315745 [9^ 7^ 9 7] +
-0.024249379221171166 [9^ 8^ 7 6] +
-1.9157654958013657 [10^ 10] +
-0.41211988446241576 [11^ 10^ 11 10] +
-1.9157654958013657 [11^ 11] +
-0.37220749500429434 [12^ 2^ 12 2] +
-0.04441890031545352 [12^ 3^ 5 2] +
-0.04441890031545352 [12^ 5^ 3 2] +
0.011268108228017996 [13^ 0^ 4 1] +
0.008595469695128971 [13^ 1^ 5 3] +
-0.011268108228017996 [13^ 4^ 1 0]

================================================================================
H_orange consists of:
T_37 + T_108 + T_114 + T_195 + T_202 + T_210 + T_214 + T_261 + T_352 + T_355 + T_359 + T_361 + T_370 + T_374

Summed operator H_orange =
-0.021432334426820798 [1^ 0^ 13 12] +
-0.16451934594928347 [3^ 2^ 5 4] +
-0.24786683415166114 [4^ 2^ 4 2] +
0.16451934594928347 [4^ 3^ 5 2] +
0.16451934594928347 [5^ 2^ 4 3] +
-0.24786683415166114 [5^ 3^ 5 3] +
-0.16451934594928347 [5^ 4^ 3 2] +
-0.40136028264432866 [8^ 7^ 8 7] +
-0.40136028264432866 [9^ 6^ 9 6] +
-0.3676530894943182 [10^ 7^ 10 7] +
-0.3676530894943185 [10^ 9^ 10 9] +
-0.3676530894943182 [11^ 6^ 11 6] +
-0.3676530894943185 [11^ 8^ 11 8] +
-0.5567172143140702 [12^ 0^ 12 0] +
0.021432334426820798 [12^ 1^ 13 0] +
0.021432334426820798 [13^ 0^ 12 1] +
-0.5567172143140702 [13^ 1^ 13 1] +
-0.021432334426820798 [13^ 12^ 1 0]

================================================================================
H_purple consists of:
T_47 + T_64 + T_135 + T_187

Summed operator H_purple =
0.007308710844141353 [2^ 1^ 13 12] +
-0.014250292634053127 [3^ 0^ 5 4] +
0.014250292634053127 [4^ 3^ 5 0] +
0.014250292634053127 [5^ 0^ 4 3] +
-0.014250292634053127 [5^ 4^ 3 0] +
0.007308710844141353 [12^ 1^ 13 2] +
0.007308710844141353 [13^ 2^ 12 1] +
0.007308710844141353 [13^ 12^ 2 1]

================================================================================
H_brown consists of:
T_48 + T_65 + T_128 + T_141

Summed operator H_brown =
0.02055140231938284 [2^ 1^ 13 4] +
0.02055140231938284 [3^ 0^ 12 5] +
0.02055140231938284 [4^ 1^ 13 2] +
0.02055140231938284 [5^ 0^ 12 3] +
0.02055140231938284 [12^ 3^ 5 0] +
0.02055140231938284 [12^ 5^ 3 0] +
0.02055140231938284 [13^ 2^ 4 1] +
0.02055140231938284 [13^ 4^ 2 1]

================================================================================
H_pink consists of:
T_54 + T_115 + T_134 + T_186

Summed operator H_pink =
-0.003483937499362717 [2^ 1^ 12 5] +
-0.003483937499362717 [3^ 0^ 13 4] +
0.003483937499362717 [4^ 3^ 13 0] +
0.003483937499362717 [5^ 2^ 12 1] +
0.003483937499362717 [12^ 1^ 5 2] +
-0.003483937499362717 [12^ 5^ 2 1] +
0.003483937499362717 [13^ 0^ 4 3] +
-0.003483937499362717 [13^ 4^ 3 0]

================================================================================
H_gray consists of:
T_55 + T_116 + T_127 + T_140

Summed operator H_gray =
0.014250292634053127 [2^ 1^ 5 4] +
-0.007308710844141353 [3^ 0^ 13 12] +
0.014250292634053127 [4^ 1^ 5 2] +
0.014250292634053127 [5^ 2^ 4 1] +
0.014250292634053127 [5^ 4^ 2 1] +
0.007308710844141353 [12^ 3^ 13 0] +
0.007308710844141353 [13^ 0^ 12 3] +
-0.007308710844141353 [13^ 12^ 3 0]

================================================================================
H_color_8 consists of:
T_61 + T_69 + T_99 + T_182 + T_191 + T_198 + T_204 + T_222 + T_224 + T_268

Summed operator H_color_8 =
-0.04948617421381216 [3^ 2^ 7 6] +
0.001183314552094881 [4^ 0^ 12 10] +
0.0026845426058224346 [5^ 0^ 11 4] +
0.0026845426058224346 [5^ 4^ 11 0] +
-0.3200629799403887 [6^ 2^ 6 2] +
0.04948617421381216 [6^ 3^ 7 2] +
0.04948617421381216 [7^ 2^ 6 3] +
-0.3200629799403887 [7^ 3^ 7 3] +
-0.04948617421381216 [7^ 6^ 3 2] +
0.016448854971083865 [10^ 1^ 13 12] +
0.0026845426058224346 [11^ 0^ 5 4] +
0.0026845426058224346 [11^ 4^ 5 0] +
-0.014594485862789764 [11^ 5^ 13 1] +
0.016448854971083865 [12^ 1^ 13 10] +
0.0011833145520948813 [12^ 10^ 4 0] +
-0.014594485862789764 [13^ 1^ 11 5] +
0.016448854971083865 [13^ 10^ 12 1] +
0.016448854971083865 [13^ 12^ 10 1]

================================================================================
H_color_9 consists of:
T_70 + T_100 + T_111 + T_146 + T_175 + T_205 + T_228 + T_230 + T_273 + T_338

Summed operator H_color_9 =
-0.04948617421381222 [3^ 2^ 9 8] +
-0.0021128256006259687 [4^ 1^ 13 10] +
-0.0021128256006259687 [5^ 0^ 12 11] +
-0.3200629799403891 [8^ 2^ 8 2] +
0.04948617421381222 [8^ 3^ 9 2] +
0.04948617421381222 [9^ 2^ 8 3] +
-0.3200629799403891 [9^ 3^ 9 3] +
-0.04948617421381222 [9^ 8^ 3 2] +
-0.0021128256006259687 [10^ 1^ 13 4] +
-0.014594485862789764 [10^ 4^ 12 0] +
-0.0021128256006259687 [11^ 0^ 12 5] +
-0.32497862971461844 [11^ 5^ 11 5] +
-0.014594485862789764 [12^ 0^ 10 4] +
-0.0021128256006259687 [12^ 5^ 11 0] +
-0.0021128256006259687 [12^ 11^ 5 0] +
-0.0021128256006259687 [13^ 4^ 10 1] +
-0.0021128256006259687 [13^ 10^ 4 1]

================================================================================
H_color_10 consists of:
T_7 + T_9 + T_106 + T_119 + T_155 + T_181 + T_190 + T_200 + T_225 + T_231 + T_265 + T_270 + T_380

Summed operator H_color_10 =
-2.4681092221118495 [2^ 2] +
-0.3990317233887508 [3^ 2^ 3 2] +
-2.4681092221118495 [3^ 3] +
0.001183314552094881 [5^ 1^ 13 11] +
-0.36954915415420087 [6^ 3^ 6 3] +
-0.36954915415420087 [7^ 2^ 7 2] +
-0.3695491541542013 [8^ 3^ 8 3] +
-0.3695491541542013 [9^ 2^ 9 2] +
-0.011298345710068915 [10^ 1^ 12 5] +
-0.011298345710068915 [10^ 5^ 12 1] +
-0.011298345710068915 [11^ 0^ 13 4] +
-0.011298345710068915 [11^ 4^ 13 0] +
-0.011298345710068915 [12^ 1^ 10 5] +
-0.011298345710068915 [12^ 5^ 10 1] +
-0.29568160320256215 [12^ 10^ 12 10] +
-0.011298345710068915 [13^ 0^ 11 4] +
-0.011298345710068915 [13^ 4^ 11 0] +
0.0011833145520948813 [13^ 11^ 5 1]

================================================================================
H_color_11 consists of:
T_107 + T_120 + T_145 + T_174 + T_312 + T_384

Summed operator H_color_11 =
0.0026845426058224346 [4^ 1^ 10 5] +
-0.0026845426058224346 [5^ 4^ 10 1] +
-0.0026845426058224346 [10^ 1^ 5 4] +
-0.32497862971461844 [10^ 4^ 10 4] +
0.0026845426058224346 [10^ 5^ 4 1] +
-0.016448854971083865 [11^ 0^ 13 12] +
0.016448854971083865 [12^ 11^ 13 0] +
0.016448854971083865 [13^ 0^ 12 11] +
-0.29568160320256215 [13^ 11^ 13 11] +
-0.016448854971083865 [13^ 12^ 11 0]

================================================================================
H_color_12 consists of:
T_31 + T_74 + T_77 + T_161 + T_213 + T_218 + T_237 + T_282 + T_287 + T_291

Summed operator H_color_12 =
-0.01576724793895085 [1^ 0^ 7 6] +
-0.011724330526497496 [4^ 2^ 12 10] +
0.09479570696086506 [5^ 2^ 11 4] +
0.09479570696086506 [5^ 4^ 11 2] +
-0.5534062195467696 [6^ 0^ 6 0] +
0.01576724793895085 [6^ 1^ 7 0] +
0.01576724793895085 [7^ 0^ 6 1] +
-0.5534062195467696 [7^ 1^ 7 1] +
-0.01576724793895085 [7^ 6^ 1 0] +
-0.05591150842993149 [10^ 3^ 13 12] +
0.09479570696086506 [11^ 2^ 5 4] +
0.09479570696086506 [11^ 4^ 5 2] +
-0.06994809338073626 [11^ 5^ 13 3] +
-0.05591150842993149 [12^ 3^ 13 10] +
-0.011724330526497496 [12^ 10^ 4 2] +
-0.06994809338073626 [13^ 3^ 11 5] +
-0.05591150842993149 [13^ 10^ 12 3] +
-0.05591150842993149 [13^ 12^ 10 3]

================================================================================
H_color_13 consists of:
T_32 + T_83 + T_86 + T_169 + T_219 + T_238 + T_246 + T_258 + T_276

Summed operator H_color_13 =
-0.01576724793895087 [1^ 0^ 9 8] +
0.061205155103728676 [4^ 3^ 13 10] +
0.061205155103728676 [5^ 2^ 12 11] +
-0.5534062195467703 [8^ 0^ 8 0] +
0.01576724793895087 [8^ 1^ 9 0] +
0.01576724793895087 [9^ 0^ 8 1] +
-0.5534062195467703 [9^ 1^ 9 1] +
-0.01576724793895087 [9^ 8^ 1 0] +
0.061205155103728676 [10^ 3^ 13 4] +
-0.06994809338073626 [10^ 4^ 12 2] +
0.061205155103728676 [11^ 2^ 12 5] +
-0.06994809338073626 [12^ 2^ 10 4] +
0.061205155103728676 [12^ 5^ 11 2] +
0.061205155103728676 [12^ 11^ 5 2] +
0.061205155103728676 [13^ 4^ 10 3] +
0.061205155103728676 [13^ 10^ 4 3]

================================================================================
H_color_14 consists of:
T_1 + T_4 + T_23 + T_79 + T_88 + T_157 + T_165 + T_243 + T_251 + T_264 + T_281 + T_286

Summed operator H_color_14 =
-8.653614060526332 [0^ 0] +
-2.271489014068697 [1^ 0^ 1 0] +
-8.653614060526332 [1^ 1] +
-0.011724330526497496 [5^ 3^ 13 11] +
-0.5691734674857205 [6^ 1^ 6 1] +
-0.5691734674857205 [7^ 0^ 7 0] +
-0.5691734674857212 [8^ 1^ 8 1] +
-0.5691734674857212 [9^ 0^ 9 0] +
-0.14287757901096243 [10^ 3^ 12 5] +
-0.14287757901096243 [10^ 5^ 12 3] +
-0.14287757901096243 [11^ 2^ 13 4] +
-0.14287757901096243 [11^ 4^ 13 2] +
-0.14287757901096243 [12^ 3^ 10 5] +
-0.14287757901096243 [12^ 5^ 10 3] +
-0.14287757901096243 [13^ 2^ 11 4] +
-0.14287757901096243 [13^ 4^ 11 2] +
-0.011724330526497496 [13^ 11^ 5 3]

================================================================================
H_color_15 consists of:
T_244 + T_252 + T_257 + T_275

Summed operator H_color_15 =
0.09479570696086506 [4^ 3^ 10 5] +
-0.09479570696086506 [5^ 4^ 10 3] +
-0.09479570696086506 [10^ 3^ 5 4] +
0.09479570696086506 [10^ 5^ 4 3] +
0.05591150842993149 [11^ 2^ 13 12] +
-0.05591150842993149 [12^ 11^ 13 2] +
-0.05591150842993149 [13^ 2^ 12 11] +
0.05591150842993149 [13^ 12^ 11 2]

================================================================================
H_color_16 consists of:
T_27 + T_38 + T_42 + T_136 + T_297 + T_314 + T_349 + T_356 + T_357 + T_364

Summed operator H_color_16 =
-0.026786606586168524 [1^ 0^ 3 2] +
-0.4618191684157131 [2^ 0^ 2 0] +
0.026786606586168524 [2^ 1^ 3 0] +
0.026786606586168524 [3^ 0^ 2 1] +
-0.4618191684157131 [3^ 1^ 3 1] +
-0.026786606586168524 [3^ 2^ 1 0] +
-0.08343013418341721 [5^ 4^ 11 10] +
-0.016531544619256183 [7^ 6^ 13 12] +
0.08343013418341721 [10^ 5^ 11 4] +
0.08343013418341721 [11^ 4^ 10 5] +
-0.08343013418341721 [11^ 10^ 5 4] +
-0.37488256748636634 [12^ 6^ 12 6] +
0.016531544619256183 [12^ 7^ 13 6] +
0.016531544619256183 [13^ 6^ 12 7] +
-0.37488256748636634 [13^ 7^ 13 7] +
-0.016531544619256183 [13^ 12^ 7 6]

================================================================================
H_color_17 consists of:
T_2 + T_13 + T_21 + T_24 + T_45 + T_67 + T_75 + T_80 + T_84 + T_89 + T_110 + T_192 + T_288 + T_317 + T_322 + T_325 + T_328 + T_330 + T_333 + T_343 + T_363 + T_371 + T_376

Summed operator H_color_17 =
0.2257881707079464 [0^ 2] +
-0.19912676459351364 [1^ 0^ 2 1] +
0.22578817070794643 [2^ 0] +
-0.19912676459351364 [2^ 1^ 1 0] +
0.006749548667045035 [3^ 0^ 3 2] +
0.006749548667045035 [3^ 2^ 3 0] +
0.002830780079964094 [5^ 0^ 5 2] +
0.002830780079964094 [5^ 2^ 5 0] +
-2.430490736730216 [5^ 5] +
0.023363329149235362 [6^ 0^ 6 2] +
0.02336332914923536 [6^ 2^ 6 0] +
-0.35699186184159826 [6^ 5^ 6 5] +
0.008063053384792813 [7^ 0^ 7 2] +
0.008063053384792813 [7^ 2^ 7 0] +
-0.34228717536338804 [7^ 5^ 7 5] +
0.023363329149235387 [8^ 0^ 8 2] +
0.023363329149235387 [8^ 2^ 8 0] +
-0.3569918618415987 [8^ 5^ 8 5] +
0.008063053384792823 [9^ 0^ 9 2] +
0.008063053384792823 [9^ 2^ 9 0] +
-0.34228717536338843 [9^ 5^ 9 5] +
0.09549910444811928 [11^ 4^ 13 10] +
0.09549910444811928 [11^ 10^ 13 4] +
0.016402394414051977 [12^ 0^ 12 2] +
-0.578149548740891 [12^ 1^ 12 1] +
0.016402394414051977 [12^ 2^ 12 0] +
-0.42879209546110686 [12^ 3^ 12 3] +
-0.44760179381314075 [12^ 5^ 12 5] +
-0.39141411210562255 [12^ 7^ 12 7] +
-0.3748825674863666 [12^ 8^ 12 8] +
-0.3914141121056228 [12^ 9^ 12 9] +
-1.7978181638816753 [12^ 12] +
0.09549910444811928 [13^ 4^ 11 10] +
0.09549910444811928 [13^ 10^ 11 4]

================================================================================
H_color_18 consists of:
T_5 + T_11 + T_22 + T_26 + T_121 + T_125 + T_143 + T_158 + T_162 + T_166 + T_170 + T_197 + T_253 + T_300 + T_303 + T_306 + T_309 + T_323 + T_337 + T_342 + T_358 + T_373 + T_377

Summed operator H_color_18 =
0.19912676459351364 [1^ 0^ 3 0] +
0.2257881707079464 [1^ 3] +
-0.006749548667045035 [2^ 1^ 3 2] +
0.19912676459351364 [3^ 0^ 1 0] +
0.22578817070794643 [3^ 1] +
-0.006749548667045035 [3^ 2^ 2 1] +
0.002830780079964094 [4^ 1^ 4 3] +
0.002830780079964094 [4^ 3^ 4 1] +
-2.430490736730216 [4^ 4] +
0.008063053384792813 [6^ 1^ 6 3] +
0.008063053384792813 [6^ 3^ 6 1] +
-0.34228717536338804 [6^ 4^ 6 4] +
0.023363329149235362 [7^ 1^ 7 3] +
0.02336332914923536 [7^ 3^ 7 1] +
-0.35699186184159826 [7^ 4^ 7 4] +
0.008063053384792823 [8^ 1^ 8 3] +
0.008063053384792823 [8^ 3^ 8 1] +
-0.34228717536338843 [8^ 4^ 8 4] +
0.023363329149235387 [9^ 1^ 9 3] +
0.023363329149235387 [9^ 3^ 9 1] +
-0.3569918618415987 [9^ 4^ 9 4] +
0.09549910444811928 [10^ 5^ 12 11] +
-0.09549910444811928 [11^ 10^ 12 5] +
-0.09549910444811928 [12^ 5^ 11 10] +
0.09549910444811928 [12^ 11^ 10 5] +
-0.578149548740891 [13^ 0^ 13 0] +
0.016402394414051977 [13^ 1^ 13 3] +
-0.42879209546110686 [13^ 2^ 13 2] +
0.016402394414051977 [13^ 3^ 13 1] +
-0.44760179381314075 [13^ 4^ 13 4] +
-0.39141411210562255 [13^ 6^ 13 6] +
-0.3914141121056228 [13^ 8^ 13 8] +
-0.3748825674863666 [13^ 9^ 13 9] +
-1.7978181638816753 [13^ 13]

================================================================================
H_color_19 consists of:
T_58 + T_152 + T_293 + T_379 + T_381

Summed operator H_color_19 =
0.017081072714017223 [4^ 0^ 4 2] +
0.017081072714017223 [4^ 2^ 4 0] +
0.017081072714017223 [5^ 1^ 5 3] +
0.017081072714017223 [5^ 3^ 5 1] +
-0.43554295772017254 [5^ 4^ 5 4] +
-0.1408167744673943 [11^ 10^ 13 12] +
0.1408167744673943 [12^ 11^ 13 10] +
0.1408167744673943 [13^ 10^ 12 11] +
-0.1408167744673943 [13^ 12^ 11 10]

================================================================================
H_color_20 consists of:
T_28 + T_43 + T_94 + T_139 + T_227 + T_239 + T_299 + T_319

Summed operator H_color_20 =
0.02500722144397735 [1^ 0^ 10 3] +
0.02500722144397735 [3^ 0^ 10 1] +
0.017067464820020122 [3^ 1^ 13 5] +
-0.08233580021950003 [5^ 4^ 13 12] +
-0.04743776016622643 [7^ 2^ 11 6] +
-0.04743776016622643 [7^ 6^ 11 2] +
-0.013411171310694883 [10^ 0^ 12 4] +
0.02500722144397735 [10^ 1^ 3 0] +
0.02500722144397735 [10^ 3^ 1 0] +
-0.04743776016622643 [11^ 2^ 7 6] +
-0.04743776016622643 [11^ 6^ 7 2] +
-0.013411171310694883 [12^ 4^ 10 0] +
0.08233580021950003 [12^ 5^ 13 4] +
0.08233580021950003 [13^ 4^ 12 5] +
0.017067464820020122 [13^ 5^ 3 1] +
-0.08233580021950003 [13^ 12^ 5 4]

================================================================================
H_color_21 consists of:
T_12 + T_14 + T_34 + T_41 + T_95 + T_185 + T_267 + T_277 + T_307 + T_310 + T_331 + T_334

Summed operator H_color_21 =
-0.02500722144397735 [1^ 0^ 11 2] +
0.017067464820020122 [2^ 0^ 12 4] +
0.02500722144397735 [2^ 1^ 11 0] +
-0.2794165481309364 [4^ 12] +
-0.2794165481309364 [5^ 13] +
-0.04743776016622643 [6^ 3^ 10 7] +
0.04743776016622643 [7^ 6^ 10 3] +
0.04522287671754943 [8^ 4^ 12 8] +
0.05899925602767584 [8^ 5^ 13 8] +
0.05899925602767584 [9^ 4^ 12 9] +
0.04522287671754943 [9^ 5^ 13 9] +
0.04743776016622643 [10^ 3^ 7 6] +
-0.04743776016622643 [10^ 7^ 6 3] +
0.02500722144397735 [11^ 0^ 2 1] +
-0.013411171310694883 [11^ 1^ 13 5] +
-0.02500722144397735 [11^ 2^ 1 0] +
-0.2794165481309364 [12^ 4] +
0.017067464820020122 [12^ 4^ 2 0] +
0.04522287671754943 [12^ 8^ 8 4] +
0.05899925602767584 [12^ 9^ 9 4] +
-0.2794165481309364 [13^ 5] +
-0.013411171310694883 [13^ 5^ 11 1] +
0.05899925602767584 [13^ 8^ 8 5] +
0.04522287671754943 [13^ 9^ 9 5]

================================================================================
H_color_22 consists of:
T_35 + T_92 + T_96 + T_183 + T_211 + T_220 + T_259 + T_262 + T_301 + T_304 + T_318 + T_326 + T_329 + T_345

Summed operator H_color_22 =
-0.02358722217677317 [1^ 0^ 11 10] +
-0.03842107742282559 [4^ 2^ 12 2] +
0.005997822892627933 [4^ 3^ 12 3] +
0.005997822892627933 [5^ 2^ 13 2] +
-0.03842107742282559 [5^ 3^ 13 3] +
0.04522287671754937 [6^ 4^ 12 6] +
0.058999256027675764 [6^ 5^ 13 6] +
0.058999256027675764 [7^ 4^ 12 7] +
0.04522287671754937 [7^ 5^ 13 7] +
-0.45270208645665444 [10^ 0^ 10 0] +
0.02358722217677317 [10^ 1^ 11 0] +
0.02358722217677317 [11^ 0^ 10 1] +
-0.45270208645665444 [11^ 1^ 11 1] +
-0.02358722217677317 [11^ 10^ 1 0] +
-0.03842107742282559 [12^ 2^ 4 2] +
0.005997822892627933 [12^ 3^ 4 3] +
-0.3652659935936407 [12^ 4^ 12 4] +
0.04522287671754937 [12^ 6^ 6 4] +
0.058999256027675764 [12^ 7^ 7 4] +
0.005997822892627933 [13^ 2^ 5 2] +
-0.03842107742282559 [13^ 3^ 5 3] +
-0.3652659935936407 [13^ 5^ 13 5] +
0.058999256027675764 [13^ 6^ 6 5] +
0.04522287671754937 [13^ 7^ 7 5]

================================================================================
H_color_23 consists of:
T_52 + T_97 + T_160 + T_176 + T_284 + T_298 + T_344

Summed operator H_color_23 =
0.006657818079604089 [3^ 0^ 11 2] +
0.006657818079604089 [3^ 2^ 11 0] +
0.0212199008519232 [5^ 4^ 13 4] +
-0.016351336722667406 [6^ 1^ 10 7] +
0.016351336722667406 [7^ 6^ 10 1] +
0.016351336722667406 [10^ 1^ 7 6] +
-0.016351336722667406 [10^ 7^ 6 1] +
0.006657818079604089 [11^ 0^ 3 2] +
0.006657818079604089 [11^ 2^ 3 0] +
-0.08167242390723375 [11^ 3^ 13 5] +
-0.011427757634974039 [12^ 5^ 13 12] +
0.0212199008519232 [13^ 4^ 5 4] +
-0.08167242390723375 [13^ 5^ 11 3] +
-0.011427757634974039 [13^ 12^ 12 5]

================================================================================
H_color_24 consists of:
T_53 + T_98 + T_129 + T_156 + T_283 + T_296 + T_308 + T_385

Summed operator H_color_24 =
0.015300275764442548 [2^ 1^ 7 6] +
0.00394620020149776 [3^ 0^ 11 10] +
-0.014704686478210261 [5^ 4^ 9 8] +
0.015300275764442548 [6^ 1^ 7 2] +
0.015300275764442548 [7^ 2^ 6 1] +

,color,vertex,fermionic_term,number_of_JW_Pauli_strings,JW_transform,number_of_BK_Pauli_strings,BK_transform
0,red,T_0,+3.39216161 I,1,+3.39216161 I,1,+3.39216161 I
1,color_14,T_1,-8.65361406 a_0^dagger a_0,2,-4.32680703 I + +4.32680703 Z0,2,-4.32680703 I + +4.32680703 Z0
2,color_17,T_2,+0.22578817 a_0^dagger a_2 + +0.22578817 a_2^dagger a_0,2,+0.11289409 X0 Z1 X2 + +0.11289409 Y0 Z1 Y2,2,+0.11289409 X0 Y1 Y2 + -0.11289409 Y0 Y1 X2
3,color_31,T_3,+0.19337590 a_0^dagger a_10 + +0.19337590 a_10^dagger a_0,2,+0.09668795 X0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 X10 + +0.09668795 Y0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Y10,2,+0.09668795 X0 X1 X3 Y7 Z9 Y10 X11 + -0.09668795 Y0 X1 X3 Y7 Z9 X10 X11
4,color_14,T_4,-8.65361406 a_1^dagger a_1,2,-4.32680703 I + +4.32680703 Z1,2,-4.32680703 I + +4.32680703 Z0 Z1
...,...,...,...,...,...,...,...
381,color_19,T_381,+0.14081677 a_12^dagger a_11^dagger a_13 a_10 + +0.14081677 a_13^dagger a_10^dagger a_12 a_11,8,-0.01760210 X10 X11 X12 X13 + -0.01760210 X10 X11 Y12 Y13 + -0.01760210 X10 Y11 X12 Y13 + +0.01760210 X10 Y11 Y12 X13 + +0.01760210 Y10 X11 X12 Y13 + -0.01760210 Y10 X11 Y12 X13 + -0.01760210 Y10 Y11 X12 X13 + -0.01760210 Y10 Y11 Y12 Y13,8,-0.01760210 X10 X12 + -0.01760210 Y10 Y12 + +0.01760210 X10 X12 Z13 + +0.01760210 Y10 Y12 Z13 + +0.01760210 Z9 X10 Z11 X12 + +0.01760210 Z9 Y10 Z11 Y12 + -0.01760210 Z9 X10 Z11 X12 Z13 + -0.01760210 Z9 Y10 Z11 Y12 Z13
382,color_32,T_382,-0.43649838 a_13^dagger a_10^dagger a_13 a_10,4,+0.10912459 I + -0.10912459 Z10 + -0.10912459 Z13 + +0.10912459 Z10 Z13,4,+0.10912459 I + -0.10912459 Z10 + -0.10912459 Z12 Z13 + +0.10912459 Z10 Z12 Z13
383,color_31,T_383,-0.43649838 a_12^dagger a_11^dagger a_12 a_11,4,+0.10912459 I + -0.10912459 Z11 + -0.10912459 Z12 + +0.10912459 Z11 Z12,4,+0.10912459 I + -0.10912459 Z12 + -0.10912459 Z9 Z10 Z11 + +0.10912459 Z9 Z10 Z11 Z12
384,color_11,T_384,-0.29568160 a_13^dagger a_11^dagger a_13 a_11,4,+0.07392040 I + -0.07392040 Z11 + -0.07392040 Z13 + +0.07392040 Z11 Z13,4,+0.07392040 I + -0.07392040 Z12 Z13 + -0.07392040 Z9 Z10 Z11 + +0.07392040 Z9 Z10 Z11 Z12 Z13
385,color_24,T_385,-0.48965248 a_13^dagger a_12^dagger a_13 a_12,4,+0.12241312 I + -0.12241312 Z12 + -0.12241312 Z13 + +0.12241312 Z12 Z13,4,+0.12241312 I + -0.12241312 Z12 + +0.12241312 Z13 + -0.12241312 Z12 Z13

=== Color blocks mapped to JW and BK ===

,color_block,fermionic_vertices,number_of_fermionic_terms,number_of_JW_Pauli_strings,JW_block,number_of_BK_Pauli_strings,BK_block
0,H_red,T_0 + T_17 + T_18 + T_29 + T_59 + T_62 + T_153 + T_209 + T_249 + T_348 + T_353 + T_354 + T_362 + T_365,14,38,+1.36324868 I + -0.07918249 Z6 + -0.07918249 Z7 + +1.03740657 Z8 + +1.03740657 Z9 + -0.07918249 Z10 + -0.07918249 Z11 + +0.07918249 Z6 Z10 + +0.07918249 Z7 Z11 + +0.11246476 Z8 Z9 + -0.00151197 X0 X1 Y4 Y5 + +0.00151197 X0 Y1 Y4 X5 + +0.00151197 Y0 X1 X4 Y5 + -0.00151197 Y0 Y1 X4 X5 + -0.01414615 X2 X3 Y12 Y13 + +0.01414615 X2 Y3 Y12 X13 + +0.01414615 Y2 X3 X12 Y13 + -0.01414615 Y2 Y3 X12 X13 + -0.01273079 X6 X7 Y10 Y11 + +0.01273079 X6 Y7 Y10 X11 + +0.01273079 Y6 X7 X10 Y11 + -0.01273079 Y6 Y7 X10 X11 + -0.00320787 X0 Z1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00320787 X0 Z1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + +0.00320787 X0 Z1 Y2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00320787 X0 Z1 Y2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00320787 Y0 Z1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + +0.00320787 Y0 Z1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00320787 Y0 Z1 Y2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00320787 Y0 Z1 Y2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00320787 X1 Z2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00320787 X1 Z2 X3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + +0.00320787 X1 Z2 Y3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.00320787 X1 Z2 Y3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00320787 Y1 Z2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + +0.00320787 Y1 Z2 X3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00320787 Y1 Z2 Y3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00320787 Y1 Z2 Y3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13,38,+1.36324868 I + -0.07918249 Z6 + +1.03740657 Z8 + +0.11246476 Z9 + -0.07918249 Z10 + +0.07918249 Z6 Z10 + +1.03740657 Z8 Z9 + +0.00151197 X0 Z1 X4 + +0.00151197 X0 X4 Z5 + +0.00151197 Y0 Z1 Y4 + +0.00151197 Y0 Y4 Z5 + +0.01414615 X2 X12 Z13 + +0.01414615 Y2 Y12 Z13 + -0.07918249 Z9 Z10 Z11 + +0.01414615 Z1 X2 Z3 X12 + +0.01414615 Z1 Y2 Z3 Y12 + -0.07918249 Z3 Z5 Z6 Z7 + +0.01273079 X6 Z9 X10 Z11 + +0.01273079 Y6 Z9 Y10 Z11 + -0.00320787 Y1 Y5 Y7 Z11 Y13 + +0.01273079 Z3 Z5 X6 Z7 X10 + +0.01273079 Z3 Z5 Y6 Z7 Y10 + +0.00320787 Z0 X1 Z4 X5 Y7 Z11 Y13 + -0.00320787 Z0 X1 Y5 Y7 Z11 Z12 X13 + -0.00320787 Y1 Z4 X5 Y7 Z11 Z12 X13 + +0.07918249 Z3 Z5 Z6 Z7 Z9 Z10 Z11 + +0.00320787 Z0 Y1 Z2 Z3 Y5 Y7 Z11 Y13 + -0.00320787 X1 Z2 Z3 Z4 X5 Y7 Z11 Y13 + +0.00320787 X1 Z2 Z3 Y5 Y7 Z11 Z12 X13 + +0.00320787 X0 Y1 X2 Z3 X4 X5 Y7 Z11 X12 X13 + +0.00320787 X0 Y1 X2 Z3 Y4 X5 Y7 Z11 Y12 X13 + -0.00320787 X0 Y1 Y2 Z3 X4 X5 Y7 Z11 Y12 X13 + +0.00320787 X0 Y1 Y2 Z3 Y4 X5 Y7 Z11 X12 X13 + +0.00320787 Y0 Y1 X2 Z3 X4 X5 Y7 Z11 Y12 X13 + -0.00320787 Y0 Y1 X2 Z3 Y4 X5 Y7 Z11 X12 X13 + +0.00320787 Y0 Y1 Y2 Z3 X4 X5 Y7 Z11 X12 X13 + +0.00320787 Y0 Y1 Y2 Z3 Y4 X5 Y7 Z11 Y12 X13 + +0.00320787 Z0 Y1 Z2 Z3 Z4 X5 Y7 Z11 Z12 X13
1,H_blue,T_15 + T_16 + T_30 + T_63 + T_109 + T_150 + T_208 + T_248 + T_290 + T_346 + T_366 + T_368 + T_369 + T_375,14,36,-1.82258505 I + -0.11327601 Z1 + -0.09305187 Z3 + -0.11327601 Z5 + +1.03740657 Z6 + +1.03740657 Z7 + -0.07918249 Z8 + -0.07918249 Z9 + -0.07918249 Z10 + -0.07918249 Z11 + -0.09305187 Z13 + +0.11327601 Z1 Z5 + +0.09305187 Z3 Z13 + +0.11246476 Z6 Z7 + +0.07918249 Z8 Z10 + +0.07918249 Z9 Z11 + -0.01273079 X8 X9 Y10 Y11 + +0.01273079 X8 Y9 Y10 X11 + +0.01273079 Y8 X9 X10 Y11 + -0.01273079 Y8 Y9 X10 X11 + -0.00281703 X0 X1 X5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00281703 X0 Y1 Y5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00281703 Y0 X1 X5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00281703 Y0 Y1 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00107443 X0 Z1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00107443 X0 Z1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00107443 X0 Z1 Y2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + +0.00107443 X0 Z1 Y2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + +0.00107443 Y0 Z1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00107443 Y0 Z1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00107443 Y0 Z1 Y2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00107443 Y0 Z1 Y2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + +0.01110473 X2 X3 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.01110473 X2 Y3 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.01110473 Y2 X3 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + +0.01110473 Y2 Y3 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13,36,-1.82258505 I + +1.03740657 Z6 + -0.07918249 Z8 + -0.07918249 Z10 + -0.11327601 Z0 Z1 + -0.11327601 Z4 Z5 + -0.07918249 Z8 Z9 + +0.07918249 Z8 Z10 + -0.09305187 Z12 Z13 + -0.09305187 Z1 Z2 Z3 + +0.11246476 Z3 Z5 Z7 + +0.01273079 X8 Z9 X10 + +0.01273079 Y8 Z9 Y10 + +0.07918249 Z8 Z10 Z11 + -0.07918249 Z9 Z10 Z11 + +0.11327601 Z0 Z1 Z4 Z5 + +1.03740657 Z3 Z5 Z6 Z7 + +0.01273079 X8 Z9 X10 Z11 + +0.01273079 Y8 Z9 Y10 Z11 + +0.09305187 Z1 Z2 Z3 Z12 Z13 + +0.00281703 X0 Z3 Y5 Y7 Z11 X12 X13 + +0.00281703 Y0 Z3 Y5 Y7 Z11 Y12 X13 + +0.01110473 X2 Z3 X4 X5 Y7 Z11 Y13 + +0.01110473 Y2 Z3 Y4 X5 Y7 Z11 Y13 + +0.01110473 Z1 X2 Y4 X5 Y7 Z11 Z12 X13 + -0.01110473 Z1 Y2 X4 X5 Y7 Z11 Z12 X13 + +0.00281703 X0 Z1 Z3 Z4 X5 Y7 Z11 Y12 X13 + -0.00281703 Y0 Z1 Z3 Z4 X5 Y7 Z11 X12 X13 + -0.00107443 X0 Y1 X2 Z3 X4 X5 Y7 Z11 X12 X13 + -0.00107443 X0 Y1 X2 Z3 Y4 X5 Y7 Z11 Y12 X13 + -0.00107443 X0 Y1 Y2 Z3 X4 X5 Y7 Z11 Y12 X13 + +0.00107443 X0 Y1 Y2 Z3 Y4 X5 Y7 Z11 X12 X13 + +0.00107443 Y0 Y1 X2 Z3 X4 X5 Y7 Z11 Y12 X13 + -0.00107443 Y0 Y1 X2 Z3 Y4 X5 Y7 Z11 X12 X13 + -0.00107443 Y0 Y1 Y2 Z3 X4 X5 Y7 Z11 X12 X13 + -0.00107443 Y0 Y1 Y2 Z3 Y4 X5 Y7 Z11 Y12 X13
2,H_green,T_19 + T_20 + T_36 + T_56 + T_113 + T_196 + T_203 + T_215 + T_245 + T_347 + T_350 + T_351 + T_360 + T_378,14,36,-1.41785219 I + -0.11327601 Z0 + -0.09305187 Z2 + -0.11327601 Z4 + -0.09427773 Z6 + -0.09427773 Z7 + -0.09427773 Z8 + -0.09427773 Z9 + +0.85485278 Z10 + +0.85485278 Z11 + -0.09305187 Z12 + +0.11327601 Z0 Z4 + +0.09305187 Z2 Z12 + +0.09427773 Z6 Z8 + +0.09427773 Z7 Z9 + +0.10302997 Z10 Z11 + -0.00606234 X6 X7 Y8 Y9 + +0.00606234 X6 Y7 Y8 X9 + +0.00606234 Y6 X7 X8 Y9 + -0.00606234 Y6 Y7 X8 X9 + +0.01110473 X2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + +0.01110473 X2 Y3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + +0.01110473 Y2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + +0.01110473 Y2 Y3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00281703 X0 X1 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + +0.00281703 X0 Y1 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + +0.00281703 Y0 X1 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.00281703 Y0 Y1 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00107443 X1 Z2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00107443 X1 Z2 X3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.00107443 X1 Z2 Y3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + +0.00107443 X1 Z2 Y3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + +0.00107443 Y1 Z2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.00107443 Y1 Z2 X3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00107443 Y1 Z2 Y3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00107443 Y1 Z2 Y3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13,36,-1.41785219 I + -0.11327601 Z0 + -0.09305187 Z2 + -0.11327601 Z4 + -0.09427773 Z6 + -0.09427773 Z8 + +0.85485278 Z10 + -0.09305187 Z12 + +0.11327601 Z0 Z4 + +0.09305187 Z2 Z12 + +0.09427773 Z6 Z8 + -0.09427773 Z8 Z9 + +0.10302997 Z9 Z11 + +0.00606234 X6 X8 Z9 + +0.00606234 Y6 Y8 Z9 + +0.85485278 Z9 Z10 Z11 + -0.09427773 Z3 Z5 Z6 Z7 + +0.00107443 Y1 Y5 Y7 Z11 Y13 + +0.00606234 Z3 Z5 X6 Z7 X8 + +0.00606234 Z3 Z5 Y6 Z7 Y8 + +0.09427773 Z3 Z5 Z6 Z7 Z8 Z9 + -0.00281703 X0 Z3 X4 X5 Y7 Z11 Y13 + -0.00281703 Y0 Z3 Y4 X5 Y7 Z11 Y13 + +0.00107443 Z0 X1 Z4 X5 Y7 Z11 Y13 + -0.00107443 Z0 X1 Y5 Y7 Z11 Z12 X13 + +0.00107443 Y1 Z4 X5 Y7 Z11 Z12 X13 + -0.01110473 X2 Z3 Y5 Y7 Z11 X12 X13 + -0.01110473 Y2 Z3 Y5 Y7 Z11 Y12 X13 + -0.00107443 Z0 Y1 Z2 Z3 Y5 Y7 Z11 Y13 + -0.00107443 X1 Z2 Z3 Z4 X5 Y7 Z11 Y13 + +0.00107443 X1 Z2 Z3 Y5 Y7 Z11 Z12 X13 + -0.01110473 Z1 X2 Z4 X5 Y7 Z11 Y12 X13 + +0.01110473 Z1 Y2 Z4 X5 Y7 Z11 X12 X13 + -0.00281703 X0 Z1 Z3 Y4 X5 Y7 Z11 Z12 X13 + +0.00281703 Y0 Z1 Z3 X4 X5 Y7 Z11 Z12 X13 + -0.00107443 Z0 Y1 Z2 Z3 Z4 X5 Y7 Z11 Z12 X13
3,H_orange,T_37 + T_108 + T_114 + T_195 + T_202 + T_210 + T_214 + T_261 + T_352 + T_355 + T_359 + T_361 + T_370 + T_374,14,33,+0.97062526 I + -0.13917930 Z0 + -0.13917930 Z1 + -0.06196671 Z2 + -0.06196671 Z3 + -0.06196671 Z4 + -0.06196671 Z5 + -0.19225334 Z6 + -0.19225334 Z7 + -0.19225334 Z8 + -0.19225334 Z9 + -0.18382654 Z10 + -0.18382654 Z11 + -0.13917930 Z12 + -0.13917930 Z13 + +0.13917930 Z0 Z12 + +0.13917930 Z1 Z13 + +0.06196671 Z2 Z4 + +0.06196671 Z3 Z5 + +0.10034007 Z6 Z9 + +0.09191327 Z6 Z11 + +0.10034007 Z7 Z8 + +0.09191327 Z7 Z10 + +0.09191327 Z8 Z11 + +0.09191327 Z9 Z10 + -0.00535808 X0 X1 Y12 Y13 + +0.00535808 X0 Y1 Y12 X13 + +0.00535808 Y0 X1 X12 Y13 + -0.00535808 Y0 Y1 X12 X13 + -0.04112984 X2 X3 Y4 Y5 + +0.04112984 X2 Y3 Y4 X5 + +0.04112984 Y2 X3 X4 Y5 + -0.04112984 Y2 Y3 X4 X5,33,+0.97062526 I + -0.13917930 Z0 + -0.06196671 Z2 + -0.06196671 Z4 + -0.19225334 Z6 + -0.19225334 Z8 + -0.18382654 Z10 + -0.13917930 Z12 + -0.13917930 Z0 Z1 + +0.13917930 Z0 Z12 + +0.06196671 Z2 Z4 + -0.06196671 Z4 Z5 + -0.19225334 Z8 Z9 + -0.13917930 Z12 Z13 + +0.00535808 X0 Z1 X12 + +0.00535808 X0 X12 Z13 + +0.00535808 Y0 Z1 Y12 + +0.00535808 Y0 Y12 Z13 + -0.06196671 Z1 Z2 Z3 + +0.04112984 X2 X4 Z5 + +0.04112984 Y2 Y4 Z5 + +0.10034007 Z6 Z8 Z9 + +0.09191327 Z8 Z9 Z10 + -0.18382654 Z9 Z10 Z11 + +0.13917930 Z0 Z1 Z12 Z13 + +0.04112984 Z1 X2 Z3 X4 + +0.04112984 Z1 Y2 Z3 Y4 + -0.19225334 Z3 Z5 Z6 Z7 + +0.09191327 Z6 Z9 Z10 Z11 + +0.09191327 Z8 Z9 Z10 Z11 + +0.06196671 Z1 Z2 Z3 Z4 Z5 + +0.10034007 Z3 Z5 Z6 Z7 Z8 + +0.09191327 Z3 Z5 Z6 Z7 Z10
4,H_purple,T_47 + T_64 + T_135 + T_187,4,8,-0.00182718 X1 X2 X12 X13 + -0.00182718 X1 Y2 Y12 X13 + -0.00182718 Y1 X2 X12 Y13 + -0.00182718 Y1 Y2 Y12 Y13 + -0.00356257 X0 Z1 Z2 X3 Y4 Y5 + +0.00356257 X0 Z1 Z2 Y3 Y4 X5 + +0.00356257 Y0 Z1 Z2 X3 X4 Y5 + -0.00356257 Y0 Z1 Z2 Y3 X4 X5,8,-0.00182718 X1 X2 X12 + -0.00182718 X1 Y2 Y12 + +0.00356257 X0 X1 Z3 X4 + +0.00356257 Y0 X1 Z3 Y4 + +0.00356257 X0 Y1 Z2 Y4 Z5 + -0.00356257 Y0 Y1 Z2 X4 Z5 + -0.00182718 Z0 Y1 X2 Y12 Z13 + +0.00182718 Z0 Y1 Y2 X12 Z13
5,H_brown,T_48 + T_65 + T_128 + T_141,4,8,-0.00513785 X0 Z1 Z2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00513785 X0 Z1 Z2 Y3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00513785 Y0 Z1 Z2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00513785 Y0 Z1 Z2 Y3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00513785 X1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00513785 X1 Y2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + -0.00513785 Y1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.00513785 Y1 Y2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13,8,+0.00513785 X0 X1 Z4 X5 Y7 Z11 Y12 X13 + -0.00513785 Y0 X1 Z4 X5 Y7 Z11 X12 X13 + +0.00513785 X0 Y1 Z2 Z3 Y5 Y7 Z11 Y12 X13 + -0.00513785 Y0 Y1 Z2 Z3 Y5 Y7 Z11 X12 X13 + +0.00513785 Z0 Y1 X2 Z3 Y4 X5 Y7 Z11 Y13 + -0.00513785 Z0 Y1 Y2 Z3 X4 X5 Y7 Z11 Y13 + +0.00513785 X1 X2 Z3 Y4 X5 Y7 Z11 Z12 X13 + -0.00513785 X1 Y2 Z3 X4 X5 Y7 Z11 Z12 X13
6,H_pink,T_54 + T_115 + T_134 + T_186,4,8,-0.00087098 X1 X2 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + +0.00087098 X1 Y2 Y5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + +0.00087098 Y1 X2 X5 Z6 Z7 Z8 Z9 Z10 Z11 Y12 + -0.00087098 Y1 Y2 X5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + -0.00087098 X0 Z1 Z2 X3 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + +0.00087098 X0 Z1 Z2 Y3 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13 + +0.00087098 Y0 Z1 Z2 X3 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.00087098 Y0 Z1 Z2 Y3 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13,8,-0.00087098 X0 X1 Y4 X5 Y7 Z11 Z12 X13 + +0.00087098 Y0 X1 X4 X5 Y7 Z11 Z12 X13 + -0.00087098 X0 Y1 Z2 Z3 Y4 X5 Y7 Z11 Y13 + +0.00087098 Y0 Y1 Z2 Z3 X4 X5 Y7 Z11 Y13 + -0.00087098 Z0 Y1 X2 Z3 Y5 Y7 Z11 Y12 X13 + +0.00087098 Z0 Y1 Y2 Z3 Y5 Y7 Z11 X12 X13 + -0.00087098 X1 X2 Z3 Z4 X5 Y7 Z11 Y12 X13 + +0.00087098 X1 Y2 Z3 Z4 X5 Y7 Z11 X12 X13
7,H_gray,T_55 + T_116 + T_127 + T_140,4,8,-0.00356257 X1 X2 X4 X5 + -0.00356257 X1 Y2 Y4 X5 + -0.00356257 Y1 X2 X4 Y5 + -0.00356257 Y1 Y2 Y4 Y5 + -0.00182718 X0 Z1 Z2 X3 Y12 Y13 + +0.00182718 X0 Z1 Z2 Y3 Y12 X13 + +0.00182718 Y0 Z1 Z2 X3 X12 Y13 + -0.00182718 Y0 Z1 Z2 Y3 X12 X13,8,-0.00356257 X1 X2 X4 + -0.00356257 X1 Y2 Y4 + +0.00182718 X0 X1 Z3 X12 + +0.00182718 Y0 X1 Z3 Y12 + +0.00182718 X0 Y1 Z2 Y12 Z13 + -0.00182718 Y0 Y1 Z2 X12 Z13 + -0.00356257 Z0 Y1 X2 Y4 Z5 + +0.00356257 Z0 Y1 Y2 X4 Z5
8,H_color_8,T_61 + T_69 + T_99 + T_182 + T_191 + T_198 + T_204 + T_222 + T_224 + T_268,10,35,+0.16003149 I + -0.08001574 Z2 + -0.08001574 Z3 + -0.08001574 Z6 + -0.08001574 Z7 + +0.08001574 Z2 Z6 + +0.08001574 Z3 Z7 + -0.01237154 X2 X3 Y6 Y7 + +0.01237154 X2 Y3 Y6 X7 + +0.01237154 Y2 X3 X6 Y7 + -0.01237154 Y2 Y3 X6 X7 + -0.00014791 X0 Z1 Z2 Z3 X4 X10 Z11 X12 + +0.00014791 X0 Z1 Z2 Z3 X4 Y10 Z11 Y12 + -0.00014791 X0 Z1 Z2 Z3 Y4 X10 Z11 Y12 + -0.00014791 X0 Z1 Z2 Z3 Y4 Y10 Z11 X12 + -0.00014791 Y0 Z1 Z2 Z3 X4 X10 Z11 Y12 + -0.00014791 Y0 Z1 Z2 Z3 X4 Y10 Z11 X12 + +0.00014791 Y0 Z1 Z2 Z3 Y4 X10 Z11 X12 + -0.00014791 Y0 Z1 Z2 Z3 Y4 Y10 Z11 Y12 + +0.00182431 X1 Z2 Z3 Z4 X5 X11 Z12 X13 + +0.00182431 X1 Z2 Z3 Z4 X5 Y11 Z12 Y13 + +0.00182431 X1 Z2 Z3 Z4 Y5 X11 Z12 Y13 + -0.00182431 X1 Z2 Z3 Z4 Y5 Y11 Z12 X13 + -0.00182431 Y1 Z2 Z3 Z4 X5 X11 Z12 Y13 + +0.00182431 Y1 Z2 Z3 Z4 X5 Y11 Z12 X13 + +0.00182431 Y1 Z2 Z3 Z4 Y5 X11 Z12 X13 + +0.00182431 Y1 Z2 Z3 Z4 Y5 Y11 Z12 Y13 + -0.00067114 X0 Z1 Z2 Z3 X4 X5 Z6 Z7 Z8 Z9 Z10 X11 + -0.00067114 X0 Z1 Z2 Z3 X4 Y5 Z6 Z7 Z8 Z9 Z10 Y11 + -0.00067114 Y0 Z1 Z2 Z3 Y4 X5 Z6 Z7 Z8 Z9 Z10 X11 + -0.00067114 Y0 Z1 Z2 Z3 Y4 Y5 Z6 Z7 Z8 Z9 Z10 Y11 + -0.00411221 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 X10 X12 X13 + -0.00411221 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Y10 Y12 X13 + -0.00411221 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 X10 X12 Y13 + -0.00411221 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Y10 Y12 Y13,35,+0.16003149 I + -0.08001574 Z2 + -0.08001574 Z6 + +0.08001574 Z2 Z6 + -0.08001574 Z1 Z2 Z3 + +0.01237154 Z1 X2 Z3 X6 + +0.01237154 Z1 Y2 Z3 Y6 + -0.08001574 Z3 Z5 Z6 Z7 + -0.00182431 Y1 Y3 Y5 X11 Y13 + +0.08001574 Z1 Z2 Z5 Z6 Z7 + +0.01237154 X2 Z3 Z5 X6 Z7 + +0.01237154 Y2 Z3 Z5 Y6 Z7 + +0.00067114 X0 X1 X3 X4 Y7 Y11 + +0.00067114 Y0 X1 X3 Y4 Y7 Y11 + -0.00182431 Z0 X1 Y3 Z4 X5 X11 Y13 + +0.00182431 Z0 X1 Y3 Y5 X11 Z12 X13 + +0.00411221 Y1 X3 Y7 Z9 X10 X11 X12 + +0.00411221 Y1 X3 Y7 Z9 Y10 X11 Y12 + -0.00182431 Y1 Y3 Z4 X5 X11 Z12 X13 + +0.00182431 Z0 X1 Y3 Y5 Z9 Z10 Y11 Y13 + -0.00182431 Y1 Y3 Z4 X5 Z9 Z10 Y11 Y13 + +0.00182431 Y1 Y3 Y5 Z9 Z10 Y11 Z12 X13 + -0.00067114 X0 X1 X3 Y4 Z5 Y7 Z9 Z10 X11 + +0.00067114 Y0 X1 X3 X4 Z5 Y7 Z9 Z10 X11 + -0.00411221 Z0 X1 X3 Y7 Z9 X10 X11 Y12 Z13 + +0.00411221 Z0 X1 X3 Y7 Z9 Y10 X11 X12 Z13 + -0.00014791 X0 X1 Y3 X4 X5 Z9 X10 Y11 X12 X13 + +0.00014791 X0 X1 Y3 X4 X5 Z9 Y10 Y11 Y12 X13 + -0.00014791 X0 X1 Y3 Y4 X5 Z9 X10 Y11 Y12 X13 + -0.00014791 X0 X1 Y3 Y4 X5 Z9 Y10 Y11 X12 X13 + -0.00014791 Y0 X1 Y3 X4 X5 Z9 X10 Y11 Y12 X13 + -0.00014791 Y0 X1 Y3 X4 X5 Z9 Y10 Y11 X12 X13 + +0.00014791 Y0 X1 Y3 Y4 X5 Z9 X10 Y11 X12 X13 + -0.00014791 Y0 X1 Y3 Y4 X5 Z9 Y10 Y11 Y12 X13 + +0.00182431 Z0 X1 Y3 Z4 X5 Z9 Z10 Y11 Z12 X13
9,H_color_9,T_70 + T_100 + T_111 + T_146 + T_175 + T_205 + T_228 + T_230 + T_273 + T_338,10,30,+0.24127615 I + -0.08001574 Z2 + -0.08001574 Z3 + -0.08124466 Z5 + -0.08001574 Z8 + -0.08001574 Z9 + -0.08124466 Z11 + +0.08001574 Z2 Z8 + +0.08001574 Z3 Z9 + +0.08124466 Z5 Z11 + -0.01237154 X2 X3 Y8 Y9 + +0.01237154 X2 Y3 Y8 X9 + +0.01237154 Y2 X3 X8 Y9 + -0.01237154 Y2 Y3 X8 X9 + +0.00182431 X0 Z1 Z2 Z3 X4 X10 Z11 X12 + +0.00182431 X0 Z1 Z2 Z3 X4 Y10 Z11 Y12 + +0.00182431 X0 Z1 Z2 Z3 Y4 X10 Z11 Y12 + -0.00182431 X0 Z1 Z2 Z3 Y4 Y10 Z11 X12 + +0.00052821 X0 Z1 Z2 Z3 Z4 X5 X11 X12 + +0.00052821 X0 Z1 Z2 Z3 Z4 Y5 Y11 X12 + -0.00182431 Y0 Z1 Z2 Z3 X4 X10 Z11 Y12 + +0.00182431 Y0 Z1 Z2 Z3 X4 Y10 Z11 X12 + +0.00182431 Y0 Z1 Z2 Z3 Y4 X10 Z11 X12 + +0.00182431 Y0 Z1 Z2 Z3 Y4 Y10 Z11 Y12 + +0.00052821 Y0 Z1 Z2 Z3 Z4 X5 X11 Y12 + +0.00052821 Y0 Z1 Z2 Z3 Z4 Y5 Y11 Y12 + +0.00052821 X1 Z2 Z3 X4 X10 Z11 Z12 X13 + +0.00052821 X1 Z2 Z3 Y4 Y10 Z11 Z12 X13 + +0.00052821 Y1 Z2 Z3 X4 X10 Z11 Z12 Y13 + +0.00052821 Y1 Z2 Z3 Y4 Y10 Z11 Z12 Y13,30,+0.24127615 I + -0.08001574 Z2 + -0.08001574 Z8 + +0.08001574 Z2 Z8 + -0.08124466 Z4 Z5 + -0.08001574 Z8 Z9 + -0.08001574 Z1 Z2 Z3 + +0.01237154 X2 X8 Z9 + +0.01237154 Y2 Y8 Z9 + -0.08124466 Z9 Z10 Z11 + +0.01237154 Z1 X2 Z3 X8 + +0.01237154 Z1 Y2 Z3 Y8 + +0.08001574 Z1 Z2 Z3 Z8 Z9 + +0.08124466 Z4 Z5 Z9 Z10 Z11 + +0.00052821 X0 X1 Y3 Z4 X5 X11 Y12 X13 + -0.00052821 Y0 X1 Y3 Z4 X5 X11 X12 X13 + +0.00052821 X0 X1 Y3 Y5 Z9 Z10 Y11 Y12 X13 + -0.00052821 Y0 X1 Y3 Y5 Z9 Z10 Y11 X12 X13 + -0.00052821 Z0 X1 Y3 X4 X5 Z9 Y10 Y11 Y13 + +0.00052821 Z0 X1 Y3 Y4 X5 Z9 X10 Y11 Y13 + +0.00052821 Y1 Y3 X4 X5 Z9 Y10 Y11 Z12 X13 + -0.00052821 Y1 Y3 Y4 X5 Z9 X10 Y11 Z12 X13 + +0.00182431 X0 X1 Y3 X4 X5 Z9 X10 Y11 X12 X13 + +0.00182431 X0 X1 Y3 X4 X5 Z9 Y10 Y11 Y12 X13 + +0.00182431 X0 X1 Y3 Y4 X5 Z9 X10 Y11 Y12 X13 + -0.00182431 X0 X1 Y3 Y4 X5 Z9 Y10 Y11 X12 X13 + -0.00182431 Y0 X1 Y3 X4 X5 Z9 X10 Y11 Y12 X13 + +0.00182431 Y0 X1 Y3 X4 X5 Z9 Y10 Y11 X12 X13 + +0.00182431 Y0 X1 Y3 Y4 X5 Z9 X10 Y11 X12 X13 + +0.00182431 Y0 X1 Y3 Y4 X5 Z9 Y10 Y11 Y12 X13
10,H_color_10,T_7 + T_9 + T_106 + T_119 + T_155 + T_181 + T_190 + T_200 + T_225 + T_231 + T_265 + T_270 + T_380,13,31,-1.92488174 I + +0.94952210 Z2 + +0.94952210 Z3 + -0.09238729 Z6 + -0.09238729 Z7 + -0.09238729 Z8 + -0.09238729 Z9 + -0.07392040 Z10 + -0.07392040 Z12 + +0.09975793 Z2 Z3 + +0.09238729 Z2 Z7 + +0.09238729 Z2 Z9 + +0.09238729 Z3 Z6 + +0.09238729 Z3 Z8 + +0.07392040 Z10 Z12 + +0.00282459 X0 Z1 Z2 Z3 X4 X11 Z12 X13 + +0.00282459 X0 Z1 Z2 Z3 X4 Y11 Z12 Y13 + +0.00282459 Y0 Z1 Z2 Z3 Y4 X11 Z12 X13 + +0.00282459 Y0 Z1 Z2 Z3 Y4 Y11 Z12 Y13 + +0.00282459 X1 Z2 Z3 Z4 X5 X10 Z11 X12 + +0.00282459 X1 Z2 Z3 Z4 X5 Y10 Z11 Y12 + -0.00014791 X1 Z2 Z3 Z4 X5 X11 Z12 X13 + +0.00014791 X1 Z2 Z3 Z4 X5 Y11 Z12 Y13 + -0.00014791 X1 Z2 Z3 Z4 Y5 X11 Z12 Y13 + -0.00014791 X1 Z2 Z3 Z4 Y5 Y11 Z12 X13 + -0.00014791 Y1 Z2 Z3 Z4 X5 X11 Z12 Y13 + -0.00014791 Y1 Z2 Z3 Z4 X5 Y11 Z12 X13 + +0.00282459 Y1 Z2 Z3 Z4 Y5 X10 Z11 X12 + +0.00282459 Y1 Z2 Z3 Z4 Y5 Y10 Z11 Y12 + +0.00014791 Y1 Z2 Z3 Z4 Y5 X11 Z12 X13 + -0.00014791 Y1 Z2 Z3 Z4 Y5 Y11 Z12 Y13,31,-1.92488174 I + +0.94952210 Z2 + -0.09238729 Z6 + -0.09238729 Z8 + -0.07392040 Z10 + -0.07392040 Z12 + +0.09975793 Z1 Z3 + -0.09238729 Z8 Z9 + +0.07392040 Z10 Z12 + +0.94952210 Z1 Z2 Z3 + +0.09238729 Z2 Z8 Z9 + +0.09238729 Z1 Z2 Z3 Z6 + +0.09238729 Z1 Z2 Z3 Z8 + -0.09238729 Z3 Z5 Z6 Z7 + +0.00014791 Y1 Y3 Y5 X11 Y13 + +0.09238729 Z2 Z3 Z5 Z6 Z7 + -0.00014791 Z0 X1 Y3 Z4 X5 X11 Y13 + +0.00014791 Z0 X1 Y3 Y5 X11 Z12 X13 + +0.00014791 Y1 Y3 Z4 X5 X11 Z12 X13 + +0.00282459 X0 X1 Y3 Y4 X5 X11 Z12 X13 + -0.00282459 Y0 X1 Y3 X4 X5 X11 Z12 X13 + -0.00014791 Z0 X1 Y3 Y5 Z9 Z10 Y11 Y13 + -0.00014791 Y1 Y3 Z4 X5 Z9 Z10 Y11 Y13 + +0.00014791 Y1 Y3 Y5 Z9 Z10 Y11 Z12 X13 + +0.00282459 X0 X1 Y3 Y4 X5 Z9 Z10 Y11 Y13 + -0.00282459 Y0 X1 Y3 X4 X5 Z9 Z10 Y11 Y13 + +0.00282459 Z0 X1 Y3 Y5 Z9 X10 Y11 Y12 X13 + -0.00282459 Z0 X1 Y3 Y5 Z9 Y10 Y11 X12 X13 + -0.00282459 Y1 Y3 Z4 X5 Z9 X10 Y11 Y12 X13 + +0.00282459 Y1 Y3 Z4 X5 Z9 Y10 Y11 X12 X13 + -0.00014791 Z0 X1 Y3 Z4 X5 Z9 Z10 Y11 Z12 X13
11,H_color_11,T_107 + T_120 + T_145 + T_174 + T_312 + T_384,6,15,+0.15516506 I + -0.08124466 Z4 + -0.08124466 Z10 + -0.07392040 Z11 + -0.07392040 Z13 + +0.08124466 Z4 Z10 + +0.07392040 Z11 Z13 + +0.00067114 X1 Z2 Z3 X4 Y5 Z6 Z7 Z8 Z9 Y10 + -0.00067114 X1 Z2 Z3 Y4 Y5 Z6 Z7 Z8 Z9 X10 + -0.00067114 Y1 Z2 Z3 X4 X5 Z6 Z7 Z8 Z9 Y10 + +0.00067114 Y1 Z2 Z3 Y4 X5 Z6 Z7 Z8 Z9 X10 + -0.00411221 X0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 X11 Y12 Y13 + +0.00411221 X0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Y11 Y12 X13 + +0.00411221 Y0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 X11 X12 Y13 + -0.00411221 Y0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Y11 X12 X13,15,+0.15516506 I + -0.08124466 Z4 + -0.08124466 Z10 + +0.08124466 Z4 Z10 + -0.07392040 Z12 Z13 + -0.07392040 Z9 Z10 Z11 + +0.07392040 Z9 Z10 Z11 Z12 Z13 + -0.00411221 X0 X1 X3 Y7 Y11 X12 + -0.00411221 Y0 X1 X3 Y7 Y11 Y12 + -0.00067114 Y1 X3 X4 Y7 Z9 X10 X11 + -0.00067114 Y1 X3 Y4 Y7 Z9 Y10 X11 + +0.00411221 X0 X1 X3 Y7 Z9 Z10 X11 Y12 Z13 + -0.00411221 Y0 X1 X3 Y7 Z9 Z10 X11 X12 Z13 + -0.00067114 Z0 X1 X3 X4 Z5 Y7 Z9 Y10 X11 + +0.00067114 Z0 X1 X3 Y4 Z5 Y7 Z9 X10 X11

=== Verify commuting groups after JW/BK mapping ===

     color_group          pair  fermionic_commute  JW_commute  BK_commute
0            red     T_0, T_17               True        True        True
1            red     T_0, T_18               True        True        True
2            red     T_0, T_29               True        True        True
3            red     T_0, T_59               True        True        True
4            red     T_0, T_62               True        True        True
...          ...           ...                ...         ...         ...
2229    color_40  T_168, T_177               True        True        True
2230    color_41  T_233, T_240               True        True        True
2231    color_42  T_272, T_278               True        True        True
2232    color_43  T_332, T_341               True        True        True
2233    color_44  T_367, T_372               True        True        True

[2234 rows x 5 columns]

In [6]:
# Find duplicated JW Pauli strings across fermionic terms T_i

from collections import defaultdict
import pandas as pd

pauli_usage = defaultdict(list)

for node in sorted(G.nodes()):
    JW_T = G.nodes[node]["JW_operator"]

    for pauli_key, coeff in JW_T.terms.items():
        pauli_string = format_qubit_term(pauli_key)

        pauli_usage[pauli_string].append(
            {
                "vertex": f"T_{node}",
                "coefficient": coeff,
                "fermionic_term": G.nodes[node]["operator_string"],
            }
        )

duplicate_rows = []

for pauli_string, appearances in pauli_usage.items():
    if len(appearances) > 1:
        duplicate_rows.append(
            {
                "JW_Pauli_string": pauli_string,
                "number_of_appearances": len(appearances),
                "appears_in_vertices": [x["vertex"] for x in appearances],
                "coefficients": [x["coefficient"] for x in appearances],
            }
        )

duplicate_jw_df = pd.DataFrame(duplicate_rows)
duplicate_jw_df = duplicate_jw_df.sort_values(
    "number_of_appearances",
    ascending=False
).reset_index(drop=True)

print("Total JW Pauli-string appearances:", sum(len(G.nodes[node]["JW_operator"].terms) for node in G.nodes()))
print("Number of unique JW Pauli strings:", len(pauli_usage))
print("Number of duplicated JW Pauli strings:", len(duplicate_jw_df))

display(duplicate_jw_df)

Total JW Pauli-string appearances: 2201
Number of unique JW Pauli strings: 994
Number of duplicated JW Pauli strings: 711

,JW_Pauli_string,number_of_appearances,appears_in_vertices,coefficients
0,I,106,"[T_0, T_1, T_4, T_7, T_9, T_11, T_13, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_22, T_23, T_38, T_44, T_56, T_66, T_74, T_79, T_83, T_88, T_92, T_103, T_108, T_121, T_124, T_136, T_142, T_150, T_157, T_161, T_165, T_169, T_178, T_183, T_192, T_195, T_200, T_210, T_216, T_222, T_225, T_228, T_231, T_234, T_241, T_245, T_253, T_255, T_261, T_265, T_268, T_270, T_273, T_279, T_283, T_288, T_290, T_293, T_300, T_303, T_306, T_309, T_312, T_315, T_318, T_323, T_325, T_328, T_330, T_333, T_335, T_338, T_343, T_345, T_346, T_350, T_352, T_353, T_355, T_356, T_358, T_359, T_360, T_361, T_362, T_363, T_364, T_365, T_368, T_370, T_371, T_373, T_374, T_375, T_376, T_377, ...]","[3.3921616084615387, -4.326807030263166, -4.326807030263166, -1.2340546110559247, -1.2340546110559247, -1.215245368365108, -1.215245368365108, -1.1498713328803523, -1.1498713328803523, -1.1498713328803534, -1.1498713328803534, -0.9578827479006828, -0.9578827479006828, -0.8989090819408376, -0.8989090819408376, 0.5678722535171743, 0.11545479210392827, 0.1221514437504704, 0.11327600938641182, 0.11478797608484514, 0.1383515548866924, 0.14229336687143013, 0.13835155488669257, 0.1422933668714303, 0.11317552161416361, 0.1190723271583569, 0.13917930357851754, 0.14453738718522274, 0.1221514437504704, 0.11545479210392827, 0.11478797608484514, 0.11327600938641182, 0.14229336687143013, 0.1383515548866924, 0.1422933668714303, 0.13835155488669257, 0.1190723271583569, 0.11317552161416361, 0.14453738718522274, 0.13917930357851754, 0.0997579308471877, 0.061966708537915284, 0.10309654502523614, 0.08001574498509717, 0.09238728853855022, 0.08001574498509728, 0.09238728853855033, 0.07994055092939271, 0.09934427228949878, 0.09305187375107359, 0.10719802386527671, 0.10309654502523614, 0.061966708537915284, 0.09238728853855022, 0.08001574498509717, 0.09238728853855033, 0.08001574498509728, 0.09934427228949878, 0.07994055092939271, 0.10719802386527671, 0.09305187375107359, 0.10888573943004314, 0.08557179384084701, 0.08924796546039956, 0.08557179384084711, 0.08924796546039968, 0.08124465742865461, 0.1021021909745089, 0.09131649839841018, 0.11190044845328519, 0.08924796546039956, 0.08557179384084701, 0.08924796546039968, 0.08557179384084711, 0.1021021909745089, 0.08124465742865461, 0.11190044845328519, 0.09131649839841018, 0.11246476027166757, 0.09427772585578936, 0.10034007066108216, 0.07918248629720792, 0.09191327237357955, 0.09372064187159158, 0.09785352802640564, 0.10034007066108216, 0.09427772585578936, 0.09191327237357955, 0.07918248629720792, 0.09785352802640564, 0.09372064187159158, 0.11246476027166782, 0.079182486297208, 0.09191327237357963, 0.09372064187159165, 0.0978535280264057, 0.09191327237357963, 0.079182486297208, 0.0978535280264057, 0.09372064187159165, ...]"
1,Z9,14,"[T_18, T_88, T_169, T_231, T_273, T_309, T_333, T_352, T_360, T_365, T_374, T_375, T_376, T_377]","[1.1498713328803534, -0.1422933668714303, -0.13835155488669257, -0.09238728853855033, -0.08001574498509728, -0.08924796546039968, -0.08557179384084711, -0.10034007066108216, -0.09427772585578936, -0.11246476027166782, -0.09191327237357963, -0.079182486297208, -0.0978535280264057, -0.09372064187159165]"
2,Z5,14,"[T_13, T_66, T_150, T_216, T_261, T_293, T_325, T_328, T_330, T_333, T_335, T_338, T_343, T_345]","[1.215245368365108, -0.11478797608484514, -0.11327600938641182, -0.10309654502523614, -0.061966708537915284, -0.10888573943004314, -0.08924796546039956, -0.08557179384084701, -0.08924796546039968, -0.08557179384084711, -0.1021021909745089, -0.08124465742865461, -0.11190044845328519, -0.09131649839841018]"
3,Z3,14,"[T_9, T_44, T_136, T_200, T_255, T_261, T_265, T_268, T_270, T_273, T_279, T_283, T_288, T_290]","[1.2340546110559247, -0.1221514437504704, -0.11545479210392827, -0.0997579308471877, -0.10309654502523614, -0.061966708537915284, -0.09238728853855022, -0.08001574498509717, -0.09238728853855033, -0.08001574498509728, -0.09934427228949878, -0.07994055092939271, -0.10719802386527671, -0.09305187375107359]"
4,Z6,14,"[T_15, T_74, T_157, T_222, T_265, T_300, T_325, T_346, T_350, T_352, T_353, T_355, T_356, T_358]","[1.1498713328803523, -0.1383515548866924, -0.14229336687143013, -0.08001574498509717, -0.09238728853855022, -0.08557179384084701, -0.08924796546039956, -0.11246476027166757, -0.09427772585578936, -0.10034007066108216, -0.07918248629720792, -0.09191327237357955, -0.09372064187159158, -0.09785352802640564]"
...,...,...,...,...
706,Y1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13,2,"[T_128, T_141]","[-0.002568925289922855, 0.002568925289922855]"
707,Y1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13,2,"[T_128, T_141]","[-0.002568925289922855, -0.002568925289922855]"
708,X1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13,2,"[T_128, T_141]","[-0.002568925289922855, -0.002568925289922855]"
709,X1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13,2,"[T_128, T_141]","[0.002568925289922855, -0.002568925289922855]"
710,X10 Y11 X12 Y13,2,"[T_379, T_381]","[0.017602096808424287, -0.017602096808424287]"

In [7]:
# Compute Pauli-duplication ratio for JW and BK

from collections import defaultdict
import pandas as pd

from openfermion.ops import FermionOperator
from openfermion.transforms import jordan_wigner, bravyi_kitaev, normal_ordered


def pauli_support(qubit_op, tol=1e-12, include_identity=True):
    """
    Return the set of Pauli strings with nonzero coefficients.
    """
    qubit_op.compress(abs_tol=tol)

    support = set()

    for pauli_key, coeff in qubit_op.terms.items():
        if abs(coeff) <= tol:
            continue

        if not include_identity and pauli_key == ():
            continue

        support.add(pauli_key)

    return support


def map_fermion_to_qubit(op, mapping="JW", n_qubits=None):
    """
    Map a FermionOperator to a QubitOperator using JW or BK.
    """
    mapping = mapping.upper()

    if mapping == "JW":
        qop = jordan_wigner(op)

    elif mapping == "BK":
        if n_qubits is None:
            raise ValueError("n_qubits is required for BK.")

        try:
            qop = bravyi_kitaev(op, n_qubits=n_qubits)
        except TypeError:
            qop = bravyi_kitaev(op, n_qubits)

    else:
        raise ValueError("mapping must be 'JW' or 'BK'.")

    qop.compress(abs_tol=1e-12)
    return qop


def pauli_duplication_ratio(
    fermionic_terms,
    mapping="JW",
    n_qubits=None,
    include_identity=True,
    tol=1e-12,
):
    """
    Compute

        sum_alpha #mapping(H_alpha) / #mapping(H)

    where H = sum_alpha H_alpha.

    Also returns a duplicate-use table.
    """

    H_full = FermionOperator.zero()

    numerator = 0
    union_support = set()
    pauli_usage = defaultdict(list)

    for alpha, H_alpha in enumerate(fermionic_terms):
        H_full += H_alpha

        Q_alpha = map_fermion_to_qubit(
            H_alpha,
            mapping=mapping,
            n_qubits=n_qubits,
        )

        support_alpha = pauli_support(
            Q_alpha,
            tol=tol,
            include_identity=include_identity,
        )

        numerator += len(support_alpha)
        union_support |= support_alpha

        for pauli_key, coeff in Q_alpha.terms.items():
            if abs(coeff) <= tol:
                continue

            if not include_identity and pauli_key == ():
                continue

            pauli_usage[pauli_key].append(
                {
                    "vertex": f"T_{alpha}",
                    "coefficient": coeff,
                }
            )

    H_full = normal_ordered(H_full)
    H_full.compress(abs_tol=tol)

    Q_full = map_fermion_to_qubit(
        H_full,
        mapping=mapping,
        n_qubits=n_qubits,
    )

    full_support = pauli_support(
        Q_full,
        tol=tol,
        include_identity=include_identity,
    )

    denominator = len(full_support)

    duplication_ratio = numerator / denominator
    union_ratio = numerator / len(union_support)

    summary_df = pd.DataFrame(
        [
            {
                "mapping": mapping.upper(),
                "include_identity": include_identity,
                "sum_alpha_number_of_Pauli_strings": numerator,
                "number_of_unique_Pauli_strings_before_cancellation": len(union_support),
                "number_of_Pauli_strings_in_full_H": denominator,
                "duplication_ratio": duplication_ratio,
                "raw_reuse_ratio_before_cancellation": union_ratio,
            }
        ]
    )

    duplicate_rows = []

    for pauli_key, appearances in pauli_usage.items():
        if len(appearances) <= 1:
            continue

        combined_coeff = Q_full.terms.get(pauli_key, 0.0)

        duplicate_rows.append(
            {
                "Pauli_string": format_qubit_term(pauli_key),
                "number_of_appearances": len(appearances),
                "appears_in_vertices": [x["vertex"] for x in appearances],
                "individual_coefficients": [complex(x["coefficient"]) for x in appearances],
                "combined_coefficient_in_full_H": complex(combined_coeff),
                "survives_in_full_H": abs(combined_coeff) > tol,
            }
        )

    duplicate_df = pd.DataFrame(duplicate_rows)

    if len(duplicate_df) > 0:
        duplicate_df = duplicate_df.sort_values(
            "number_of_appearances",
            ascending=False,
        ).reset_index(drop=True)

    return summary_df, duplicate_df


# ------------------------------------------------------------
# Run for JW
# ------------------------------------------------------------

n_qubits = molecule.n_qubits

jw_summary_df, jw_duplicate_df = pauli_duplication_ratio(
    hermitian_terms,
    mapping="JW",
    n_qubits=n_qubits,
    include_identity=True,
)

print("=== JW Pauli-duplication ratio ===")
display(jw_summary_df)

print("\n=== Duplicated JW Pauli strings ===")
display(jw_duplicate_df)


# ------------------------------------------------------------
# Optional: run for BK too
# ------------------------------------------------------------

bk_summary_df, bk_duplicate_df = pauli_duplication_ratio(
    hermitian_terms,
    mapping="BK",
    n_qubits=n_qubits,
    include_identity=True,
)

print("=== BK Pauli-duplication ratio ===")
display(bk_summary_df)

print("\n=== Duplicated BK Pauli strings ===")
display(bk_duplicate_df)

=== JW Pauli-duplication ratio ===

,mapping,include_identity,sum_alpha_number_of_Pauli_strings,number_of_unique_Pauli_strings_before_cancellation,number_of_Pauli_strings_in_full_H,duplication_ratio,raw_reuse_ratio_before_cancellation
0,JW,True,2201,994,666,3.304805,2.214286

=== Duplicated JW Pauli strings ===

,Pauli_string,number_of_appearances,appears_in_vertices,individual_coefficients,combined_coefficient_in_full_H,survives_in_full_H
0,I,106,"[T_0, T_1, T_4, T_7, T_9, T_11, T_13, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_22, T_23, T_38, T_44, T_56, T_66, T_74, T_79, T_83, T_88, T_92, T_103, T_108, T_121, T_124, T_136, T_142, T_150, T_157, T_161, T_165, T_169, T_178, T_183, T_192, T_195, T_200, T_210, T_216, T_222, T_225, T_228, T_231, T_234, T_241, T_245, T_253, T_255, T_261, T_265, T_268, T_270, T_273, T_279, T_283, T_288, T_290, T_293, T_300, T_303, T_306, T_309, T_312, T_315, T_318, T_323, T_325, T_328, T_330, T_333, T_335, T_338, T_343, T_345, T_346, T_350, T_352, T_353, T_355, T_356, T_358, T_359, T_360, T_361, T_362, T_363, T_364, T_365, T_368, T_370, T_371, T_373, T_374, T_375, T_376, T_377, ...]","[(3.3921616084615387+0j), (-4.326807030263166+0j), (-4.326807030263166+0j), (-1.2340546110559247+0j), (-1.2340546110559247+0j), (-1.215245368365108+0j), (-1.215245368365108+0j), (-1.1498713328803523+0j), (-1.1498713328803523+0j), (-1.1498713328803534+0j), (-1.1498713328803534+0j), (-0.9578827479006828+0j), (-0.9578827479006828+0j), (-0.8989090819408376+0j), (-0.8989090819408376+0j), (0.5678722535171743+0j), (0.11545479210392827+0j), (0.1221514437504704+0j), (0.11327600938641182+0j), (0.11478797608484514+0j), (0.1383515548866924+0j), (0.14229336687143013+0j), (0.13835155488669257+0j), (0.1422933668714303+0j), (0.11317552161416361+0j), (0.1190723271583569+0j), (0.13917930357851754+0j), (0.14453738718522274+0j), (0.1221514437504704+0j), (0.11545479210392827+0j), (0.11478797608484514+0j), (0.11327600938641182+0j), (0.14229336687143013+0j), (0.1383515548866924+0j), (0.1422933668714303+0j), (0.13835155488669257+0j), (0.1190723271583569+0j), (0.11317552161416361+0j), (0.14453738718522274+0j), (0.13917930357851754+0j), (0.0997579308471877+0j), (0.061966708537915284+0j), (0.10309654502523614+0j), (0.08001574498509717+0j), (0.09238728853855022+0j), (0.08001574498509728+0j), (0.09238728853855033+0j), (0.07994055092939271+0j), (0.09934427228949878+0j), (0.09305187375107359+0j), (0.10719802386527671+0j), (0.10309654502523614+0j), (0.061966708537915284+0j), (0.09238728853855022+0j), (0.08001574498509717+0j), (0.09238728853855033+0j), (0.08001574498509728+0j), (0.09934427228949878+0j), (0.07994055092939271+0j), (0.10719802386527671+0j), (0.09305187375107359+0j), (0.10888573943004314+0j), (0.08557179384084701+0j), (0.08924796546039956+0j), (0.08557179384084711+0j), (0.08924796546039968+0j), (0.08124465742865461+0j), (0.1021021909745089+0j), (0.09131649839841018+0j), (0.11190044845328519+0j), (0.08924796546039956+0j), (0.08557179384084701+0j), (0.08924796546039968+0j), (0.08557179384084711+0j), (0.1021021909745089+0j), (0.08124465742865461+0j), (0.11190044845328519+0j), (0.09131649839841018+0j), (0.11246476027166757+0j), (0.09427772585578936+0j), (0.10034007066108216+0j), (0.07918248629720792+0j), (0.09191327237357955+0j), (0.09372064187159158+0j), (0.09785352802640564+0j), (0.10034007066108216+0j), (0.09427772585578936+0j), (0.09191327237357955+0j), (0.07918248629720792+0j), (0.09785352802640564+0j), (0.09372064187159158+0j), (0.11246476027166782+0j), (0.079182486297208+0j), (0.09191327237357963+0j), (0.09372064187159165+0j), (0.0978535280264057+0j), (0.09191327237357963+0j), (0.079182486297208+0j), (0.0978535280264057+0j), (0.09372064187159165+0j), ...]",-8.703164+0.000000j,True
1,Z9,14,"[T_18, T_88, T_169, T_231, T_273, T_309, T_333, T_352, T_360, T_365, T_374, T_375, T_376, T_377]","[(1.1498713328803534+0j), (-0.1422933668714303+0j), (-0.13835155488669257+0j), (-0.09238728853855033+0j), (-0.08001574498509728+0j), (-0.08924796546039968+0j), (-0.08557179384084711+0j), (-0.10034007066108216+0j), (-0.09427772585578936+0j), (-0.11246476027166782+0j), (-0.09191327237357963+0j), (-0.079182486297208+0j), (-0.0978535280264057+0j), (-0.09372064187159165+0j)]",-0.147749+0.000000j,True
2,Z5,14,"[T_13, T_66, T_150, T_216, T_261, T_293, T_325, T_328, T_330, T_333, T_335, T_338, T_343, T_345]","[(1.215245368365108+0j), (-0.11478797608484514+0j), (-0.11327600938641182+0j), (-0.10309654502523614+0j), (-0.061966708537915284+0j), (-0.10888573943004314+0j), (-0.08924796546039956+0j), (-0.08557179384084701+0j), (-0.08924796546039968+0j), (-0.08557179384084711+0j), (-0.1021021909745089+0j), (-0.08124465742865461+0j), (-0.11190044845328519+0j), (-0.09131649839841018+0j)]",-0.022971+0.000000j,True
3,Z3,14,"[T_9, T_44, T_136, T_200, T_255, T_261, T_265, T_268, T_270, T_273, T_279, T_283, T_288, T_290]","[(1.2340546110559247+0j), (-0.1221514437504704+0j), (-0.11545479210392827+0j), (-0.0997579308471877+0j), (-0.10309654502523614+0j), (-0.061966708537915284+0j), (-0.09238728853855022+0j), (-0.08001574498509717+0j), (-0.09238728853855033+0j), (-0.08001574498509728+0j), (-0.09934427228949878+0j), (-0.07994055092939271+0j), (-0.10719802386527671+0j), (-0.09305187375107359+0j)]",0.007286+0.000000j,True
4,Z6,14,"[T_15, T_74, T_157, T_222, T_265, T_300, T_325, T_346, T_350, T_352, T_353, T_355, T_356, T_358]","[(1.1498713328803523+0j), (-0.1383515548866924+0j), (-0.14229336687143013+0j), (-0.08001574498509717+0j), (-0.09238728853855022+0j), (-0.08557179384084701+0j), (-0.08924796546039956+0j), (-0.11246476027166757+0j), (-0.09427772585578936+0j), (-0.10034007066108216+0j), (-0.07918248629720792+0j), (-0.09191327237357955+0j), (-0.09372064187159158+0j), (-0.09785352802640564+0j)]",-0.147749+0.000000j,True
...,...,...,...,...,...,...
706,Y1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13,2,"[T_128, T_141]","[(-0.002568925289922855+0j), (0.002568925289922855+0j)]",0.000000+0.000000j,False
707,Y1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13,2,"[T_128, T_141]","[(-0.002568925289922855+0j), (-0.002568925289922855+0j)]",-0.005138+0.000000j,True
708,X1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 X13,2,"[T_128, T_141]","[(-0.002568925289922855+0j), (-0.002568925289922855+0j)]",-0.005138+0.000000j,True
709,X1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Y13,2,"[T_128, T_141]","[(0.002568925289922855+0j), (-0.002568925289922855+0j)]",0.000000+0.000000j,False
710,X10 Y11 X12 Y13,2,"[T_379, T_381]","[(0.017602096808424287+0j), (-0.017602096808424287+0j)]",0.000000+0.000000j,False

=== BK Pauli-duplication ratio ===

,mapping,include_identity,sum_alpha_number_of_Pauli_strings,number_of_unique_Pauli_strings_before_cancellation,number_of_Pauli_strings_in_full_H,duplication_ratio,raw_reuse_ratio_before_cancellation
0,BK,True,2201,994,666,3.304805,2.214286

=== Duplicated BK Pauli strings ===

,Pauli_string,number_of_appearances,appears_in_vertices,individual_coefficients,combined_coefficient_in_full_H,survives_in_full_H
0,I,106,"[T_0, T_1, T_4, T_7, T_9, T_11, T_13, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_22, T_23, T_38, T_44, T_56, T_66, T_74, T_79, T_83, T_88, T_92, T_103, T_108, T_121, T_124, T_136, T_142, T_150, T_157, T_161, T_165, T_169, T_178, T_183, T_192, T_195, T_200, T_210, T_216, T_222, T_225, T_228, T_231, T_234, T_241, T_245, T_253, T_255, T_261, T_265, T_268, T_270, T_273, T_279, T_283, T_288, T_290, T_293, T_300, T_303, T_306, T_309, T_312, T_315, T_318, T_323, T_325, T_328, T_330, T_333, T_335, T_338, T_343, T_345, T_346, T_350, T_352, T_353, T_355, T_356, T_358, T_359, T_360, T_361, T_362, T_363, T_364, T_365, T_368, T_370, T_371, T_373, T_374, T_375, T_376, T_377, ...]","[(3.3921616084615387+0j), (-4.326807030263166+0j), (-4.326807030263166+0j), (-1.2340546110559247+0j), (-1.2340546110559247+0j), (-1.215245368365108+0j), (-1.215245368365108+0j), (-1.1498713328803523+0j), (-1.1498713328803523+0j), (-1.1498713328803534+0j), (-1.1498713328803534+0j), (-0.9578827479006828+0j), (-0.9578827479006828+0j), (-0.8989090819408376+0j), (-0.8989090819408376+0j), (0.5678722535171743+0j), (0.11545479210392827+0j), (0.1221514437504704+0j), (0.11327600938641182+0j), (0.11478797608484514+0j), (0.1383515548866924+0j), (0.14229336687143013+0j), (0.13835155488669257+0j), (0.1422933668714303+0j), (0.11317552161416361+0j), (0.1190723271583569+0j), (0.13917930357851754+0j), (0.14453738718522274+0j), (0.1221514437504704+0j), (0.11545479210392827+0j), (0.11478797608484514+0j), (0.11327600938641182+0j), (0.14229336687143013+0j), (0.1383515548866924+0j), (0.1422933668714303+0j), (0.13835155488669257+0j), (0.1190723271583569+0j), (0.11317552161416361+0j), (0.14453738718522274+0j), (0.13917930357851754+0j), (0.0997579308471877+0j), (0.061966708537915284+0j), (0.10309654502523614+0j), (0.08001574498509717+0j), (0.09238728853855022+0j), (0.08001574498509728+0j), (0.09238728853855033+0j), (0.07994055092939271+0j), (0.09934427228949878+0j), (0.09305187375107359+0j), (0.10719802386527671+0j), (0.10309654502523614+0j), (0.061966708537915284+0j), (0.09238728853855022+0j), (0.08001574498509717+0j), (0.09238728853855033+0j), (0.08001574498509728+0j), (0.09934427228949878+0j), (0.07994055092939271+0j), (0.10719802386527671+0j), (0.09305187375107359+0j), (0.10888573943004314+0j), (0.08557179384084701+0j), (0.08924796546039956+0j), (0.08557179384084711+0j), (0.08924796546039968+0j), (0.08124465742865461+0j), (0.1021021909745089+0j), (0.09131649839841018+0j), (0.11190044845328519+0j), (0.08924796546039956+0j), (0.08557179384084701+0j), (0.08924796546039968+0j), (0.08557179384084711+0j), (0.1021021909745089+0j), (0.08124465742865461+0j), (0.11190044845328519+0j), (0.09131649839841018+0j), (0.11246476027166757+0j), (0.09427772585578936+0j), (0.10034007066108216+0j), (0.07918248629720792+0j), (0.09191327237357955+0j), (0.09372064187159158+0j), (0.09785352802640564+0j), (0.10034007066108216+0j), (0.09427772585578936+0j), (0.09191327237357955+0j), (0.07918248629720792+0j), (0.09785352802640564+0j), (0.09372064187159158+0j), (0.11246476027166782+0j), (0.079182486297208+0j), (0.09191327237357963+0j), (0.09372064187159165+0j), (0.0978535280264057+0j), (0.09191327237357963+0j), (0.079182486297208+0j), (0.0978535280264057+0j), (0.09372064187159165+0j), ...]",-8.703164+0.000000j,True
1,Z8 Z9,14,"[T_18, T_88, T_169, T_231, T_273, T_309, T_333, T_352, T_360, T_365, T_374, T_375, T_376, T_377]","[(1.1498713328803534+0j), (-0.1422933668714303+0j), (-0.13835155488669257+0j), (-0.09238728853855033+0j), (-0.08001574498509728+0j), (-0.08924796546039968+0j), (-0.08557179384084711+0j), (-0.10034007066108216+0j), (-0.09427772585578936+0j), (-0.11246476027166782+0j), (-0.09191327237357963+0j), (-0.079182486297208+0j), (-0.0978535280264057+0j), (-0.09372064187159165+0j)]",-0.147749+0.000000j,True
2,Z4 Z5,14,"[T_13, T_66, T_150, T_216, T_261, T_293, T_325, T_328, T_330, T_333, T_335, T_338, T_343, T_345]","[(1.215245368365108+0j), (-0.11478797608484514+0j), (-0.11327600938641182+0j), (-0.10309654502523614+0j), (-0.061966708537915284+0j), (-0.10888573943004314+0j), (-0.08924796546039956+0j), (-0.08557179384084701+0j), (-0.08924796546039968+0j), (-0.08557179384084711+0j), (-0.1021021909745089+0j), (-0.08124465742865461+0j), (-0.11190044845328519+0j), (-0.09131649839841018+0j)]",-0.022971+0.000000j,True
3,Z1 Z2 Z3,14,"[T_9, T_44, T_136, T_200, T_255, T_261, T_265, T_268, T_270, T_273, T_279, T_283, T_288, T_290]","[(1.2340546110559247+0j), (-0.1221514437504704+0j), (-0.11545479210392827+0j), (-0.0997579308471877+0j), (-0.10309654502523614+0j), (-0.061966708537915284+0j), (-0.09238728853855022+0j), (-0.08001574498509717+0j), (-0.09238728853855033+0j), (-0.08001574498509728+0j), (-0.09934427228949878+0j), (-0.07994055092939271+0j), (-0.10719802386527671+0j), (-0.09305187375107359+0j)]",0.007286+0.000000j,True
4,Z6,14,"[T_15, T_74, T_157, T_222, T_265, T_300, T_325, T_346, T_350, T_352, T_353, T_355, T_356, T_358]","[(1.1498713328803523+0j), (-0.1383515548866924+0j), (-0.14229336687143013+0j), (-0.08001574498509717+0j), (-0.09238728853855022+0j), (-0.08557179384084701+0j), (-0.08924796546039956+0j), (-0.11246476027166757+0j), (-0.09427772585578936+0j), (-0.10034007066108216+0j), (-0.07918248629720792+0j), (-0.09191327237357955+0j), (-0.09372064187159158+0j), (-0.09785352802640564+0j)]",-0.147749+0.000000j,True
...,...,...,...,...,...,...
706,Z0 Y1 X2 Z3 X4 X5 Y7 Z11 Z12 X13,2,"[T_128, T_141]","[(-0.002568925289922855+0j), (0.002568925289922855+0j)]",0.000000+0.000000j,False
707,Z0 Y1 X2 Z3 Y4 X5 Y7 Z11 Y13,2,"[T_128, T_141]","[(0.002568925289922855+0j), (0.002568925289922855+0j)]",0.005138+0.000000j,True
708,X1 X2 Z3 Y4 X5 Y7 Z11 Z12 X13,2,"[T_128, T_141]","[(0.002568925289922855+0j), (0.002568925289922855+0j)]",0.005138+0.000000j,True
709,X1 X2 Z3 X4 X5 Y7 Z11 Y13,2,"[T_128, T_141]","[(0.002568925289922855+0j), (-0.002568925289922855+0j)]",0.000000+0.000000j,False
710,Z9 Y10 Z11 Y12 Z13,2,"[T_379, T_381]","[(0.017602096808424287+0j), (-0.017602096808424287+0j)]",0.000000+0.000000j,False