In [11]:
# Cell 1: Build CH4 fermionic Hamiltonian and Hermitian fermionic terms

import pandas as pd
import numpy as np

from openfermion.chem import MolecularData
from openfermion.ops import FermionOperator
from openfermion.transforms import get_fermion_operator, normal_ordered
from openfermion.utils import hermitian_conjugated
from openfermionpyscf import run_pyscf

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# Methane / CH4 configuration
# ------------------------------------------------------------

CH_BOND_LENGTH = 1.087  # Angstrom, approximate equilibrium C-H bond length
BASIS = "sto-3g"
MULTIPLICITY = 1
CHARGE = 0

# Full CH4/STO-3G should give 18 qubits:
# C has 5 STO-3G spatial orbitals, each H has 1, so 5 + 4 = 9 spatial orbitals.
# 9 spatial orbitals * 2 spin orbitals = 18 qubits.
USE_ACTIVE_SPACE = True

# Optional active-space example:
# Freeze carbon 1s-like core spatial orbital 0 and keep valence active orbitals.
# This would usually reduce CH4/STO-3G from 18 qubits to 16 qubits.
OCCUPIED_INDICES = [0]
ACTIVE_INDICES = [1, 2, 3, 4, 5, 6, 7, 8]

# Set this smaller, e.g. 1e-10, if tiny numerical terms clutter the graph.
TERM_ABS_TOL = 1e-12


def format_fermion_term(term):
    if term == ():
        return "I"

    pieces = []
    for orbital, action in term:
        if action == 1:
            pieces.append(f"a_{orbital}^dagger")
        else:
            pieces.append(f"a_{orbital}")
    return " ".join(pieces)


def sort_fermion_key(term):
    return (len(term), term)


def coeff_to_str(c, digits=8):
    c = complex(c)
    if abs(c.imag) < 1e-12:
        return f"{c.real:+.{digits}f}"
    return f"{c.real:+.{digits}f}{c.imag:+.{digits}f}j"


def operator_to_string(op, digits=8):
    pieces = []

    for term, coeff in sorted(op.terms.items(), key=lambda item: sort_fermion_key(item[0])):
        pieces.append(f"{coeff_to_str(coeff, digits)} {format_fermion_term(term)}")

    if len(pieces) == 0:
        return "0"

    return " + ".join(pieces)


def dagger_term_key(term):
    """
    Return the OpenFermion key for O^dagger, where O is one monomial.
    """
    O = FermionOperator(term, 1.0)
    O_dag = normal_ordered(hermitian_conjugated(O))
    O_dag.compress(abs_tol=TERM_ABS_TOL)

    if len(O_dag.terms) != 1:
        raise ValueError(f"Expected one dagger term, got: {O_dag}")

    return next(iter(O_dag.terms.keys()))


def make_hermitian_fermionic_terms(fermion_hamiltonian, tol=TERM_ABS_TOL):
    """
    Group raw monomials into Hermitian fermionic Hamiltonian terms.

    If O is self-adjoint, keep c O.
    If O is not self-adjoint, group c O + c* O^dagger using the
    coefficients already present in the Hamiltonian.
    """
    used = set()
    hermitian_terms = []

    for term, coeff in fermion_hamiltonian.terms.items():
        if term in used:
            continue

        dag = dagger_term_key(term)

        if dag == term:
            T = FermionOperator(term, coeff)
            used.add(term)
        else:
            dag_coeff = fermion_hamiltonian.terms.get(dag, 0.0)

            T = FermionOperator(term, coeff)
            T += FermionOperator(dag, dag_coeff)

            used.add(term)
            used.add(dag)

        T = normal_ordered(T)
        T.compress(abs_tol=tol)
        hermitian_terms.append(T)

    return hermitian_terms


def infer_n_qubits_from_fermion_operator(op):
    """
    Infer the number of spin orbitals used by the FermionOperator.

    This is important for active-space Hamiltonians, where the active
    modes may be reindexed and smaller than molecule.n_qubits.
    """
    max_orbital = -1

    for term in op.terms:
        for orbital, action in term:
            max_orbital = max(max_orbital, orbital)

    return max_orbital + 1


def build_ch4_geometry(ch_bond_length=CH_BOND_LENGTH):
    """
    Build tetrahedral methane geometry.

    Carbon is placed at the origin.
    The four hydrogens are placed at tetrahedral directions:
        ( 1,  1,  1)
        ( 1, -1, -1)
        (-1,  1, -1)
        (-1, -1,  1)

    Each direction is normalized so the C-H distance equals ch_bond_length.
    """
    scale = ch_bond_length / np.sqrt(3.0)

    geometry = [
        ("C", (0.0, 0.0, 0.0)),
        ("H", ( scale,  scale,  scale)),
        ("H", ( scale, -scale, -scale)),
        ("H", (-scale,  scale, -scale)),
        ("H", (-scale, -scale,  scale)),
    ]

    return geometry


def build_ch4_fermionic_hamiltonian(
    ch_bond_length=CH_BOND_LENGTH,
    basis=BASIS,
    multiplicity=MULTIPLICITY,
    charge=CHARGE,
    use_active_space=USE_ACTIVE_SPACE,
    occupied_indices=OCCUPIED_INDICES,
    active_indices=ACTIVE_INDICES,
):
    """
    Build a CH4 fermionic Hamiltonian using OpenFermion + PySCF.

    If use_active_space=True, molecule.get_molecular_hamiltonian is called
    with occupied_indices and active_indices.
    """
    geometry = build_ch4_geometry(ch_bond_length=ch_bond_length)

    molecule = MolecularData(
        geometry=geometry,
        basis=basis,
        multiplicity=multiplicity,
        charge=charge,
        description=f"CH4_{ch_bond_length}",
    )

    # FCI is not required for constructing the fermionic Hamiltonian.
    # For CH4, keep run_fci=False.
    molecule = run_pyscf(
        molecule,
        run_scf=True,
        run_fci=False,
    )

    if use_active_space:
        molecular_hamiltonian = molecule.get_molecular_hamiltonian(
            occupied_indices=occupied_indices,
            active_indices=active_indices,
        )
    else:
        molecular_hamiltonian = molecule.get_molecular_hamiltonian()

    fermion_hamiltonian = get_fermion_operator(molecular_hamiltonian)
    fermion_hamiltonian = normal_ordered(fermion_hamiltonian)
    fermion_hamiltonian.compress(abs_tol=TERM_ABS_TOL)

    n_qubits = infer_n_qubits_from_fermion_operator(fermion_hamiltonian)

    return molecule, fermion_hamiltonian, n_qubits


# ------------------------------------------------------------
# Build CH4 fermionic Hamiltonian
# ------------------------------------------------------------

molecule, Hf, n_qubits = build_ch4_fermionic_hamiltonian()
hermitian_terms = make_hermitian_fermionic_terms(Hf)

print("Molecule: CH4 / Methane")
print("Basis:", BASIS)
print("C-H bond length [Angstrom]:", CH_BOND_LENGTH)
print("Use active space:", USE_ACTIVE_SPACE)
if USE_ACTIVE_SPACE:
    print("Frozen occupied spatial orbitals:", OCCUPIED_INDICES)
    print("Active spatial orbitals:", ACTIVE_INDICES)
print("Full molecule electrons:", molecule.n_electrons)
print("Full molecule spatial orbitals:", molecule.n_orbitals)
print("Full molecule spin orbitals / qubits:", molecule.n_qubits)
print("Hamiltonian spin orbitals / qubits used:", n_qubits)
print("Number of raw OpenFermion monomial terms:", len(Hf.terms))
print("Number of Hermitian fermionic terms:", len(hermitian_terms))

print("\n=== Full fermionic Hamiltonian H_f ===")
print(Hf)


# ------------------------------------------------------------
# Tables
# ------------------------------------------------------------

raw_rows = []

for idx, (term, coeff) in enumerate(
    sorted(Hf.terms.items(), key=lambda item: sort_fermion_key(item[0]))
):
    raw_rows.append(
        {
            "raw_index": idx,
            "coefficient": coeff_to_str(coeff),
            "monomial": format_fermion_term(term),
            "OpenFermion_key": term,
        }
    )

raw_df = pd.DataFrame(raw_rows)

print("\n=== Raw fermionic monomials c_alpha O_alpha ===")
display(raw_df)


hermitian_rows = []

for i, T in enumerate(hermitian_terms):
    hermitian_rows.append(
        {
            "vertex": f"T_{i}",
            "number_of_monomials": len(T.terms),
            "fermionic_term": operator_to_string(T),
        }
    )

hermitian_df = pd.DataFrame(hermitian_rows)

print("\n=== Hermitian fermionic terms T_i ===")
display(hermitian_df)

Molecule: CH4 / Methane
Basis: sto-3g
C-H bond length [Angstrom]: 1.087
Use active space: True
Frozen occupied spatial orbitals: [0]
Active spatial orbitals: [1, 2, 3, 4, 5, 6, 7, 8]
Full molecule electrons: 10
Full molecule spatial orbitals: 9
Full molecule spin orbitals / qubits: 18
Hamiltonian spin orbitals / qubits used: 16
Number of raw OpenFermion monomial terms: 4689
Number of Hermitian fermionic terms: 2413

=== Full fermionic Hamiltonian H_f ===
-22.408915115183795 [] +
-4.005144750335747 [0^ 0] +
-0.5329579619356528 [0^ 14] +
-0.5040433677317613 [1^ 0^ 1 0] +
-0.10834818702074449 [1^ 0^ 3 2] +
-0.10834818702074467 [1^ 0^ 5 4] +
-0.10834818702074432 [1^ 0^ 7 6] +
0.0038543796497326277 [1^ 0^ 8 3] +
-0.010819833086620264 [1^ 0^ 8 5] +
-0.014460132543415518 [1^ 0^ 8 7] +
-0.0038543796497326277 [1^ 0^ 9 2] +
0.010819833086620264 [1^ 0^ 9 4] +
0.014460132543415518 [1^ 0^ 9 6] +
-0.04762387544706916 [1^ 0^ 9 8] +
0.001996315980880118 [1^ 0^ 10 3] +
-0.014439923307331728 [1^ 0^ 10 5] +
0.011336833820013386 [1^ 0^ 10 7] +
-0.001996315980880118 [1^ 0^ 11 2] +
0.014439923307331728 [1^ 0^ 11 4] +
-0.011336833820013386 [1^ 0^ 11 6] +
-0.04762387544706939 [1^ 0^ 11 10] +
0.017949343823659647 [1^ 0^ 12 3] +
0.003929413510410046 [1^ 0^ 12 5] +
0.0018442422411378881 [1^ 0^ 12 7] +
-0.017949343823659647 [1^ 0^ 13 2] +
-0.003929413510410046 [1^ 0^ 13 4] +
-0.0018442422411378881 [1^ 0^ 13 6] +
-0.047623875447069544 [1^ 0^ 13 12] +
0.08766213261681724 [1^ 0^ 14 1] +
-0.08766213261681724 [1^ 0^ 15 0] +
-0.07342356567648453 [1^ 0^ 15 14] +
-4.005144750335747 [1^ 1] +
-0.5329579619356528 [1^ 15] +
-0.3776711205809687 [2^ 0^ 2 0] +
-0.012986987599956049 [2^ 0^ 8 0] +
0.03209297878811664 [2^ 0^ 8 2] +
-0.001108395917824013 [2^ 0^ 8 4] +
-0.0044218073517137794 [2^ 0^ 8 6] +
-0.006726408201922363 [2^ 0^ 10 0] +
0.007355361293071041 [2^ 0^ 10 2] +
0.0022155188798518876 [2^ 0^ 10 4] +
-0.001767948728330991 [2^ 0^ 10 6] +
-0.0604787091176619 [2^ 0^ 12 0] +
-0.0013673584725370543 [2^ 0^ 12 2] +
-0.02557058047082176 [2^ 0^ 12 4] +
-0.020203036588340655 [2^ 0^ 12 6] +
0.07938195991180055 [2^ 0^ 14 2] +
0.00630025415112089 [2^ 0^ 14 8] +
0.00326311863087012 [2^ 0^ 14 10] +
0.029339462692200658 [2^ 0^ 14 12] +
-0.48601930760171314 [2^ 1^ 2 1] +
0.10834818702074449 [2^ 1^ 3 0] +
0.010980648396222824 [2^ 1^ 3 2] +
0.04425716634648821 [2^ 1^ 4 3] +
-0.0442571663464882 [2^ 1^ 5 2] +
-0.011620904547637114 [2^ 1^ 5 4] +
0.03696298568492691 [2^ 1^ 6 3] +
0.0005800797793652627 [2^ 1^ 6 5] +
-0.03696298568492695 [2^ 1^ 7 2] +
-0.0005800797793652575 [2^ 1^ 7 4] +
0.0006402561514142887 [2^ 1^ 7 6] +
-0.016841367249688675 [2^ 1^ 8 1] +
0.052296061328588925 [2^ 1^ 8 3] +
-0.0018061502261156807 [2^ 1^ 8 5] +
-0.007205411189006135 [2^ 1^ 8 7] +
0.0038543796497326277 [2^ 1^ 9 0] +
-0.020203082540472282 [2^ 1^ 9 2] +
0.0006977543082916678 [2^ 1^ 9 4] +
0.002783603837292355 [2^ 1^ 9 6] +
0.002050668163078792 [2^ 1^ 9 8] +
-0.00872272418280248 [2^ 1^ 10 1] +
0.011985687829598064 [2^ 1^ 10 3] +
0.0036102261488511 [2^ 1^ 10 5] +
-0.0028809028832448317 [2^ 1^ 10 7] +
-0.00030758910792551866 [2^ 1^ 10 9] +
0.001996315980880118 [2^ 1^ 11 0] +
-0.004630326536527023 [2^ 1^ 11 2] +
-0.0013947072689992125 [2^ 1^ 11 4] +
0.001112954154913841 [2^ 1^ 11 6] +
0.000307589107925692 [2^ 1^ 11 8] +
-0.00038368267257364607 [2^ 1^ 11 10] +
-0.07842805294132155 [2^ 1^ 12 1] +
-0.0022281341663556954 [2^ 1^ 12 3] +
-0.04166770100520821 [2^ 1^ 12 5] +
-0.03292119586103423 [2^ 1^ 12 7] +
-0.005788821281584894 [2^ 1^ 12 9] +
-0.0014121218896704767 [2^ 1^ 12 11] +
0.017949343823659647 [2^ 1^ 13 0] +
0.0008607756938186409 [2^ 1^ 13 2] +
0.01609712053438645 [2^ 1^ 13 4] +
0.01271815927269358 [2^ 1^ 13 6] +
0.005788821281584655 [2^ 1^ 13 8] +
0.0014121218896696922 [2^ 1^ 13 10] +
-0.0016669854905057326 [2^ 1^ 13 12] +
0.01033197753770618 [2^ 1^ 14 3] +
-0.008635690101432192 [2^ 1^ 14 9] +
-0.0044727213513111016 [2^ 1^ 14 11] +
-0.040215283617931544 [2^ 1^ 14 13] +
0.06904998237409438 [2^ 1^ 15 2] +
0.014935944252553082 [2^ 1^ 15 8] +
0.007735839982181221 [2^ 1^ 15 10] +
0.0695547463101322 [2^ 1^ 15 12] +
-3.6153217088487963 [2^ 2] +
-0.10521789024123275 [2^ 8] +
-0.0544959694817893 [2^ 10] +
-0.48998600552256255 [2^ 12] +
0.10834818702074449 [3^ 0^ 2 1] +
-0.48601930760171314 [3^ 0^ 3 0] +
-0.010980648396222824 [3^ 0^ 3 2] +
-0.0442571663464882 [3^ 0^ 4 3] +
0.04425716634648821 [3^ 0^ 5 2] +
0.011620904547637114 [3^ 0^ 5 4] +
-0.03696298568492695 [3^ 0^ 6 3] +
-0.0005800797793652575 [3^ 0^ 6 5] +
0.03696298568492691 [3^ 0^ 7 2] +
0.0005800797793652627 [3^ 0^ 7 4] +
-0.0006402561514142887 [3^ 0^ 7 6] +
0.0038543796497326277 [3^ 0^ 8 1] +
-0.020203082540472282 [3^ 0^ 8 3] +
0.0006977543082916678 [3^ 0^ 8 5] +
0.002783603837292355 [3^ 0^ 8 7] +
-0.016841367249688675 [3^ 0^ 9 0] +
0.052296061328588925 [3^ 0^ 9 2] +
-0.0018061502261156807 [3^ 0^ 9 4] +
-0.007205411189006135 [3^ 0^ 9 6] +
-0.002050668163078792 [3^ 0^ 9 8] +
0.001996315980880118 [3^ 0^ 10 1] +
-0.004630326536527023 [3^ 0^ 10 3] +
-0.0013947072689992125 [3^ 0^ 10 5] +
0.001112954154913841 [3^ 0^ 10 7] +
0.000307589107925692 [3^ 0^ 10 9] +
-0.00872272418280248 [3^ 0^ 11 0] +
0.011985687829598064 [3^ 0^ 11 2] +
0.0036102261488511 [3^ 0^ 11 4] +
-0.0028809028832448317 [3^ 0^ 11 6] +
-0.00030758910792551866 [3^ 0^ 11 8] +
0.00038368267257364607 [3^ 0^ 11 10] +
0.017949343823659647 [3^ 0^ 12 1] +
0.0008607756938186409 [3^ 0^ 12 3] +
0.01609712053438645 [3^ 0^ 12 5] +
0.01271815927269358 [3^ 0^ 12 7] +
0.005788821281584655 [3^ 0^ 12 9] +
0.0014121218896696922 [3^ 0^ 12 11] +
-0.07842805294132155 [3^ 0^ 13 0] +
-0.0022281341663556954 [3^ 0^ 13 2] +
-0.04166770100520821 [3^ 0^ 13 4] +
-0.03292119586103423 [3^ 0^ 13 6] +
-0.005788821281584894 [3^ 0^ 13 8] +
-0.0014121218896704767 [3^ 0^ 13 10] +
0.0016669854905057326 [3^ 0^ 13 12] +
0.06904998237409438 [3^ 0^ 14 3] +
0.014935944252553082 [3^ 0^ 14 9] +
0.007735839982181221 [3^ 0^ 14 11] +
0.0695547463101322 [3^ 0^ 14 13] +
0.01033197753770618 [3^ 0^ 15 2] +
-0.008635690101432192 [3^ 0^ 15 8] +
-0.0044727213513111016 [3^ 0^ 15 10] +
-0.040215283617931544 [3^ 0^ 15 12] +
-0.3776711205809687 [3^ 1^ 3 1] +
-0.012986987599956049 [3^ 1^ 9 1] +
0.03209297878811664 [3^ 1^ 9 3] +
-0.001108395917824013 [3^ 1^ 9 5] +
-0.0044218073517137794 [3^ 1^ 9 7] +
-0.006726408201922363 [3^ 1^ 11 1] +
0.007355361293071041 [3^ 1^ 11 3] +
0.0022155188798518876 [3^ 1^ 11 5] +
-0.001767948728330991 [3^ 1^ 11 7] +
-0.0604787091176619 [3^ 1^ 13 1] +
-0.0013673584725370543 [3^ 1^ 13 3] +
-0.02557058047082176 [3^ 1^ 13 5] +
-0.020203036588340655 [3^ 1^ 13 7] +
0.07938195991180055 [3^ 1^ 15 3] +
0.00630025415112089 [3^ 1^ 15 9] +
0.00326311863087012 [3^ 1^ 15 11] +
0.029339462692200658 [3^ 1^ 15 13] +
-0.10834818702074449 [3^ 2^ 1 0] +
0.010980648396222824 [3^ 2^ 2 1] +
-0.010980648396222824 [3^ 2^ 3 0] +
-0.5380174445437979 [3^ 2^ 3 2] +
-0.04425716634648821 [3^ 2^ 4 1] +
0.000669198143306506 [3^ 2^ 4 3] +
0.04425716634648821 [3^ 2^ 5 0] +
-0.000669198143306506 [3^ 2^ 5 2] +
-0.04144414256907128 [3^ 2^ 5 4] +
-0.03696298568492691 [3^ 2^ 6 1] +
-0.005429561683922021 [3^ 2^ 6 3] +
0.02207805822580939 [3^ 2^ 6 5] +
0.03696298568492691 [3^ 2^ 7 0] +
0.005429561683922021 [3^ 2^ 7 2] +
-0.02207805822580939 [3^ 2^ 7 4] +
-0.03166954947669902 [3^ 2^ 7 6] +
-0.052296061328588925 [3^ 2^ 8 1] +
0.0036833993296648882 [3^ 2^ 8 3] +
0.024528720620048287 [3^ 2^ 8 5] +
0.017496548723666835 [3^ 2^ 8 7] +
0.052296061328588925 [3^ 2^ 9 0] +
-0.0036833993296648882 [3^ 2^ 9 2] +
-0.024528720620048287 [3^ 2^ 9 4] +
-0.017496548723666835 [3^ 2^ 9 6] +
-0.04928720881846882 [3^ 2^ 9 8] +
-0.011985687829598064 [3^ 2^ 10 1] +
0.007331112532530156 [3^ 2^ 10 3] +
-0.00108196567873443 [3^ 2^ 10 5] +
0.01303222697091956 [3^ 2^ 10 7] +
0.009373130291297924 [3^ 2^ 10 9] +
0.011985687829598064 [3^ 2^ 11 0] +
-0.007331112532530156 [3^ 2^ 11 2] +
0.00108196567873443 [3^ 2^ 11 4] +
-0.01303222697091956 [3^ 2^ 11 6] +
-0.009373130291297924 [3^ 2^ 11 8] +
-0.015350077975725383 [3^ 2^ 11 10] +
0.0022281341663556954 [3^ 2^ 12 1] +
0.03417011581271358 [3^ 2^ 12 3] +
-0.005784557428698973 [3^ 2^ 12 5] +
-3.273943432801195e-05 [3^ 2^ 12 7] +
0.017261838206900654 [3^ 2^ 12 9] +
0.006728523264618891 [3^ 2^ 12 11] +
-0.0022281341663556954 [3^ 2^ 13 0] +
-0.03417011581271358 [3^ 2^ 13 2] +
0.005784557428698973 [3^ 2^ 13 4] +
3.273943432801195e-05 [3^ 2^ 13 6] +
-0.017261838206900654 [3^ 2^ 13 8] +
-0.006728523264618891 [3^ 2^ 13 10] +
-0.11591038858364026 [3^ 2^ 13 12] +
-0.01033197753770618 [3^ 2^ 14 1] +
-0.005783678432482152 [3^ 2^ 14 3] +
0.02331093841134289 [3^ 2^ 14 5] +
0.01946897991739681 [3^ 2^ 14 7] +
0.024997761090024218 [3^ 2^ 14 9] +
0.005729214653114784 [3^ 2^ 14 11] +
-0.0010650585178316055 [3^ 2^ 14 13] +
0.01033197753770618 [3^ 2^ 15 0] +
0.005783678432482152 [3^ 2^ 15 2] +
-0.02331093841134289 [3^ 2^ 15 4] +
-0.01946897991739681 [3^ 2^ 15 6] +
-0.024997761090024218 [3^ 2^ 15 8] +
-0.005729214653114784 [3^ 2^ 15 10] +
0.0010650585178316055 [3^ 2^ 15 12] +
-0.04692575339470699 [3^ 2^ 15 14] +
-3.6153217088487963 [3^ 3] +
-0.10521789024123275 [3^ 9] +
-0.0544959694817893 [3^ 11] +
-0.48998600552256255 [3^ 13] +
-0.3776711205809689 [4^ 0^ 4 0] +
0.03645646015676742 [4^ 0^ 8 0] +
-0.0011083959178240033 [4^ 0^ 8 2] +
-0.005564630128946046 [4^ 0^ 8 4] +
0.013611082538520114 [4^ 0^ 8 6] +
0.048654030474046144 [4^ 0^ 10 0] +
0.0022155188798518815 [4^ 0^ 10 2] +
-0.03427906824156827 [4^ 0^ 10 4] +
0.010164951290729184 [4^ 0^ 10 6] +
-0.01323980748454163 [4^ 0^ 12 0] +
-0.02557058047082173 [4^ 0^ 12 2] +
-0.001704608240296085 [4^ 0^ 12 4] +
-0.004388380902060248 [4^ 0^ 12 6] +
0.07938195991180189 [4^ 0^ 14 4] +
-0.01768577683393059 [4^ 0^ 14 8] +
-0.023603068463999215 [4^ 0^ 14 10] +
0.006422902264479505 [4^ 0^ 14 12] +
-0.04425716634648821 [4^ 1^ 3 2] +
-0.4860193076017136 [4^ 1^ 4 1] +
0.011620904547637069 [4^ 1^ 4 3] +
0.10834818702074467 [4^ 1^ 5 0] +
-0.011620904547637114 [4^ 1^ 5 2] +
0.05290681415513654 [4^ 1^ 5 4] +
0.0005800797793652683 [4^ 1^ 6 3] +
0.030026764293582545 [4^ 1^ 6 5] +
-0.0005800797793652575 [4^ 1^ 7 2] +
-0.03002676429358254 [4^ 1^ 7 4] +
-0.00864964780864852 [4^ 1^ 7 6] +
0.04727629324338768 [4^ 1^ 8 1] +
-0.0018061502261156707 [4^ 1^ 8 3] +
-0.009067660575093213 [4^ 1^ 8 5] +
0.02217949327428937 [4^ 1^ 8 7] +
-0.010819833086620264 [4^ 1^ 9 0] +
0.0006977543082916678 [4^ 1^ 9 2] +
0.0035030304461471664 [4^ 1^ 9 4] +
-0.00856841073576926 [4^ 1^ 9 6] +
-0.0014471790937275288 [4^ 1^ 9 8] +
0.06309395378137787 [4^ 1^ 10 1] +
0.003610226148851094 [4^ 1^ 10 3] +
-0.05585833172057725 [4^ 1^ 10 5] +
0.01656396309023634 [4^ 1^ 10 7] +
-0.002387759464230788 [4^ 1^ 10 9] +
-0.014439923307331728 [4^ 1^ 11 0] +
-0.0013947072689992125 [4^ 1^ 11 2] +
0.02157926347900898 [4^ 1^ 11 4] +
-0.006399011799507156 [4^ 1^ 11 6] +
0.0023877594642304663 [4^ 1^ 11 8] +
0.006313844848035263 [4^ 1^ 11 10] +
-0.017169220994951676 [4^ 1^ 12 1] +
-0.04166770100520818 [4^ 1^ 12 3] +
-0.002777688467756616 [4^ 1^ 12 5] +
-0.007150942213950287 [4^ 1^ 12 7] +
0.00017112171757883488 [4^ 1^ 12 9] +
0.0007825725890259108 [4^ 1^ 12 11] +
0.003929413510410046 [4^ 1^ 13 0] +
0.01609712053438645 [4^ 1^ 13 2] +
0.001073080227460531 [4^ 1^ 13 4] +
0.0027625613118900374 [4^ 1^ 13 6] +
-0.0001711217175787277 [4^ 1^ 13 8] +
-0.0007825725890258373 [4^ 1^ 13 10] +
-0.004866665754310771 [4^ 1^ 13 12] +
0.010331977537708346 [4^ 1^ 14 5] +
0.024241702680159544 [4^ 1^ 14 9] +
0.03235247020340003 [4^ 1^ 14 11] +
-0.00880380254151561 [4^ 1^ 14 13] +
0.06904998237409354 [4^ 1^ 15 4] +
-0.041927479514090135 [4^ 1^ 15 8] +
-0.055955538667399246 [4^ 1^ 15 10] +
0.015226704805995113 [4^ 1^ 15 12] +
-0.40539545062948423 [4^ 2^ 4 2] +
0.05081074009520105 [4^ 2^ 8 2] +
0.01810045321798676 [4^ 2^ 8 4] +
0.06781095274665197 [4^ 2^ 10 2] +
0.00937484817375138 [4^ 2^ 10 4] +
0.0020192893932280765 [4^ 2^ 10 8] +
-0.018452817802791125 [4^ 2^ 12 2] +
0.08429145224348839 [4^ 2^ 12 4] +
-0.012412874933076594 [4^ 2^ 12 8] +
-0.015832623078611538 [4^ 2^ 12 10] +
0.04425716634648821 [4^ 3^ 2 1] +
-0.0442571663464882 [4^ 3^ 3 0] +
0.000669198143306506 [4^ 3^ 3 2] +
0.011620904547637069 [4^ 3^ 4 1] +
-0.4468395931985555 [4^ 3^ 4 3] +
-0.011620904547637114 [4^ 3^ 5 0] +
0.04144414256907128 [4^ 3^ 5 2] +
-0.0011171649625065804 [4^ 3^ 5 4] +
0.0005800797793652683 [4^ 3^ 6 1] +
-0.022078058225809494 [4^ 3^ 6 3] +
-0.005103652632325066 [4^ 3^ 6 5] +
-0.0005800797793652627 [4^ 3^ 7 0] +
0.02207805822580939 [4^ 3^ 7 2] +
0.005103652632324943 [4^ 3^ 7 4] +
0.0004479668192009238 [4^ 3^ 7 6] +
-0.0018061502261156707 [4^ 3^ 8 1] +
0.026282019475152768 [4^ 3^ 8 3] +
-1.5218826622233668e-05 [4^ 3^ 8 5] +
0.0011735782867816165 [4^ 3^ 8 7] +
0.0018061502261156807 [4^ 3^ 9 0] +
0.024528720620048287 [4^ 3^ 9 2] +
0.018115672044608993 [4^ 3^ 9 4] +
-0.0011735782867816201 [4^ 3^ 9 6] +
-0.011846997541019214 [4^ 3^ 9 8] +
0.003610226148851094 [4^ 3^ 10 1] +
0.06889291842538639 [4^ 3^ 10 3] +
0.005306261453884526 [4^ 3^ 10 5] +
-0.0012309638542146195 [4^ 3^ 10 7] +
0.009017630597833583 [4^ 3^ 10 9] +
-0.0036102261488511 [4^ 3^ 11 0] +
-0.00108196567873443 [4^ 3^ 11 2] +
0.004068586719866855 [4^ 3^ 11 4] +
0.0012309638542146101 [4^ 3^ 11 6] +
-0.006998341204605508 [4^ 3^ 11 8] +
-0.008690527846455545 [4^ 3^ 11 10] +
-0.04166770100520818 [4^ 3^ 12 1] +
-0.01266826037409215 [4^ 3^ 12 3] +
0.014594893651679533 [4^ 3^ 12 5] +
0.020923144699833404 [4^ 3^ 12 7] +
0.02794985619196557 [4^ 3^ 12 9] +
0.011420730698552095 [4^ 3^ 12 11] +
0.04166770100520821 [4^ 3^ 13 0] +
-0.005784557428698973 [4^ 3^ 13 2] +
0.06969655859180884 [4^ 3^ 13 4] +
-0.020923144699833383 [4^ 3^ 13 6] +
-0.04036273112504216 [4^ 3^ 13 8] +
-0.027253353777163633 [4^ 3^ 13 10] +
0.02053752538747554 [4^ 3^ 13 12] +
-0.023310938411345097 [4^ 3^ 14 3] +
-0.006120911313508922 [4^ 3^ 14 5] +
-0.00030553704917694587 [4^ 3^ 14 7] +
0.0008633482273443622 [4^ 3^ 14 9] +
-0.001725704928004022 [4^ 3^ 14 11] +
0.01991735531198186 [4^ 3^ 14 13] +
0.02331093841134289 [4^ 3^ 15 2] +
0.006120911313509319 [4^ 3^ 15 4] +
0.00030553704917693795 [4^ 3^ 15 6] +
-0.0008633482273445426 [4^ 3^ 15 8] +
0.0017257049280038907 [4^ 3^ 15 10] +
-0.019917355311982368 [4^ 3^ 15 12] +
-3.615321708848799 [4^ 4] +
0.29536270777463053 [4^ 8] +
0.3941849022962832 [4^ 10] +
-0.10726618471001392 [4^ 12] +
0.04425716634648821 [5^ 0^ 3 2] +
0.10834818702074467 [5^ 0^ 4 1] +
-0.011620904547637114 [5^ 0^ 4 3] +
-0.4860193076017136 [5^ 0^ 5 0] +
0.011620904547637069 [5^ 0^ 5 2] +
-0.05290681415513654 [5^ 0^ 5 4] +
-0.0005800797793652575 [5^ 0^ 6 3] +
-0.03002676429358254 [5^ 0^ 6 5] +
0.0005800797793652683 [5^ 0^ 7 2] +
0.030026764293582545 [5^ 0^ 7 4] +
0.00864964780864852 [5^ 0^ 7 6] +
-0.010819833086620264 [5^ 0^ 8 1] +
0.0006977543082916678 [5^ 0^ 8 3] +
0.0035030304461471664 [5^ 0^ 8 5] +
-0.00856841073576926 [5^ 0^ 8 7] +
0.04727629324338768 [5^ 0^ 9 0] +
-0.0018061502261156707 [5^ 0^ 9 2] +
-0.009067660575093213 [5^ 0^ 9 4] +
0.02217949327428937 [5^ 0^ 9 6] +
0.0014471790937275288 [5^ 0^ 9 8] +
-0.014439923307331728 [5^ 0^ 10 1] +
-0.0013947072689992125 [5^ 0^ 10 3] +
0.02157926347900898 [5^ 0^ 10 5] +
-0.006399011799507156 [5^ 0^ 10 7] +
0.0023877594642304663 [5^ 0^ 10 9] +
0.06309395378137787 [5^ 0^ 11 0] +
0.003610226148851094 [5^ 0^ 11 2] +
-0.05585833172057725 [5^ 0^ 11 4] +
0.01656396309023634 [5^ 0^ 11 6] +
-0.002387759464230788 [5^ 0^ 11 8] +
-0.006313844848035263 [5^ 0^ 11 10] +
0.003929413510410046 [5^ 0^ 12 1] +
0.01609712053438645 [5^ 0^ 12 3] +
0.001073080227460531 [5^ 0^ 12 5] +
0.0027625613118900374 [5^ 0^ 12 7] +
-0.0001711217175787277 [5^ 0^ 12 9] +
-0.0007825725890258373 [5^ 0^ 12 11] +
-0.017169220994951676 [5^ 0^ 13 0] +
-0.04166770100520818 [5^ 0^ 13 2] +
-0.002777688467756616 [5^ 0^ 13 4] +
-0.007150942213950287 [5^ 0^ 13 6] +
0.00017112171757883488 [5^ 0^ 13 8] +
0.0007825725890259108 [5^ 0^ 13 10] +
0.004866665754310771 [5^ 0^ 13 12] +
0.06904998237409354 [5^ 0^ 14 5] +
-0.041927479514090135 [5^ 0^ 14 9] +
-0.055955538667399246 [5^ 0^ 14 11] +
0.015226704805995113 [5^ 0^ 14 13] +
0.010331977537708346 [5^ 0^ 15 4] +
0.024241702680159544 [5^ 0^ 15 8] +
0.03235247020340003 [5^ 0^ 15 10] +
-0.00880380254151561 [5^ 0^ 15 12] +
-0.3776711205809689 [5^ 1^ 5 1] +
0.03645646015676742 [5^ 1^ 9 1] +
-0.0011083959178240033 [5^ 1^ 9 3] +
-0.005564630128946046 [5^ 1^ 9 5] +
0.013611082538520114 [5^ 1^ 9 7] +
0.048654030474046144 [5^ 1^ 11 1] +
0.0022155188798518815 [5^ 1^ 11 3] +
-0.03427906824156827 [5^ 1^ 11 5] +
0.010164951290729184 [5^ 1^ 11 7] +
-0.01323980748454163 [5^ 1^ 13 1] +
-0.02557058047082173 [5^ 1^ 13 3] +
-0.001704608240296085 [5^ 1^ 13 5] +
-0.004388380902060248 [5^ 1^ 13 7] +
0.07938195991180189 [5^ 1^ 15 5] +
-0.01768577683393059 [5^ 1^ 15 9] +
-0.023603068463999215 [5^ 1^ 15 11] +
0.006422902264479505 [5^ 1^ 15 13] +
-0.0442571663464882 [5^ 2^ 2 1] +
0.04425716634648821 [5^ 2^ 3 0] +
-0.000669198143306506 [5^ 2^ 3 2] +
-0.011620904547637114 [5^ 2^ 4 1] +
0.04144414256907128 [5^ 2^ 4 3] +
0.011620904547637069 [5^ 2^ 5 0] +
-0.4468395931985555 [5^ 2^ 5 2] +
0.0011171649625065804 [5^ 2^ 5 4] +
-0.0005800797793652627 [5^ 2^ 6 1] +
0.02207805822580939 [5^ 2^ 6 3] +
0.005103652632324943 [5^ 2^ 6 5] +
0.0005800797793652683 [5^ 2^ 7 0] +
-0.022078058225809494 [5^ 2^ 7 2] +
-0.005103652632325066 [5^ 2^ 7 4] +
-0.0004479668192009238 [5^ 2^ 7 6] +
0.0018061502261156807 [5^ 2^ 8 1] +
0.024528720620048287 [5^ 2^ 8 3] +
0.018115672044608993 [5^ 2^ 8 5] +
-0.0011735782867816201 [5^ 2^ 8 7] +
-0.0018061502261156707 [5^ 2^ 9 0] +
0.026282019475152768 [5^ 2^ 9 2] +
-1.5218826622233668e-05 [5^ 2^ 9 4] +
0.0011735782867816165 [5^ 2^ 9 6] +
0.011846997541019214 [5^ 2^ 9 8] +
-0.0036102261488511 [5^ 2^ 10 1] +
-0.00108196567873443 [5^ 2^ 10 3] +
0.004068586719866855 [5^ 2^ 10 5] +
0.0012309638542146101 [5^ 2^ 10 7] +
-0.006998341204605508 [5^ 2^ 10 9] +
0.003610226148851094 [5^ 2^ 11 0] +
0.06889291842538639 [5^ 2^ 11 2] +
0.005306261453884526 [5^ 2^ 11 4] +
-0.0012309638542146195 [5^ 2^ 11 6] +
0.009017630597833583 [5^ 2^ 11 8] +
0.008690527846455545 [5^ 2^ 11 10] +
0.04166770100520821 [5^ 2^ 12 1] +
-0.005784557428698973 [5^ 2^ 12 3] +
0.06969655859180884 [5^ 2^ 12 5] +
-0.020923144699833383 [5^ 2^ 12 7] +
-0.04036273112504216 [5^ 2^ 12 9] +
-0.027253353777163633 [5^ 2^ 12 11] +
-0.04166770100520818 [5^ 2^ 13 0] +
-0.01266826037409215 [5^ 2^ 13 2] +
0.014594893651679533 [5^ 2^ 13 4] +
0.020923144699833404 [5^ 2^ 13 6] +
0.02794985619196557 [5^ 2^ 13 8] +
0.011420730698552095 [5^ 2^ 13 10] +
-0.02053752538747554 [5^ 2^ 13 12] +
0.02331093841134289 [5^ 2^ 14 3] +
0.006120911313509319 [5^ 2^ 14 5] +
0.00030553704917693795 [5^ 2^ 14 7] +
-0.0008633482273445426 [5^ 2^ 14 9] +
0.0017257049280038907 [5^ 2^ 14 11] +
-0.019917355311982368 [5^ 2^ 14 13] +
-0.023310938411345097 [5^ 2^ 15 2] +
-0.006120911313508922 [5^ 2^ 15 4] +
-0.00030553704917694587 [5^ 2^ 15 6] +
0.0008633482273443622 [5^ 2^ 15 8] +
-0.001725704928004022 [5^ 2^ 15 10] +
0.01991735531198186 [5^ 2^ 15 12] +
-0.40539545062948423 [5^ 3^ 5 3] +
0.05081074009520105 [5^ 3^ 9 3] +
0.01810045321798676 [5^ 3^ 9 5] +
0.06781095274665197 [5^ 3^ 11 3] +
0.00937484817375138 [5^ 3^ 11 5] +
0.0020192893932280765 [5^ 3^ 11 9] +
-0.018452817802791125 [5^ 3^ 13 3] +
0.08429145224348839 [5^ 3^ 13 5] +
-0.012412874933076594 [5^ 3^ 13 9] +
-0.015832623078611538 [5^ 3^ 13 11] +
-0.10834818702074467 [5^ 4^ 1 0] +
-0.011620904547637114 [5^ 4^ 2 1] +
0.011620904547637114 [5^ 4^ 3 0] +
-0.04144414256907128 [5^ 4^ 3 2] +
0.05290681415513654 [5^ 4^ 4 1] +
-0.0011171649625065804 [5^ 4^ 4 3] +
-0.05290681415513654 [5^ 4^ 5 0] +
0.0011171649625065804 [5^ 4^ 5 2] +
-0.5432638828830986 [5^ 4^ 5 4] +
-0.030026764293582545 [5^ 4^ 6 1] +
0.005103652632325066 [5^ 4^ 6 3] +
-0.01777485197275203 [5^ 4^ 6 5] +
0.030026764293582545 [5^ 4^ 7 0] +
-0.005103652632325066 [5^ 4^ 7 2] +
0.01777485197275203 [5^ 4^ 7 4] +
-0.02642311113739874 [5^ 4^ 7 6] +
0.009067660575093213 [5^ 4^ 8 1] +
1.5218826622233668e-05 [5^ 4^ 8 3] +
-0.030202634847637994 [5^ 4^ 8 5] +

,raw_index,coefficient,monomial,OpenFermion_key
0,0,-22.40891512,I,()
1,1,-4.00514475,a_0^dagger a_0,"((0, 1), (0, 0))"
2,2,-0.53295796,a_0^dagger a_14,"((0, 1), (14, 0))"
3,3,-4.00514475,a_1^dagger a_1,"((1, 1), (1, 0))"
4,4,-0.53295796,a_1^dagger a_15,"((1, 1), (15, 0))"
...,...,...,...,...
4684,4684,+0.00185219,a_15^dagger a_14^dagger a_13 a_6,"((15, 1), (14, 1), (13, 0), (6, 0))"
4685,4685,-0.10185535,a_15^dagger a_14^dagger a_13 a_12,"((15, 1), (14, 1), (13, 0), (12, 0))"
4686,4686,+0.06588115,a_15^dagger a_14^dagger a_14 a_1,"((15, 1), (14, 1), (14, 0), (1, 0))"
4687,4687,-0.06588115,a_15^dagger a_14^dagger a_15 a_0,"((15, 1), (14, 1), (15, 0), (0, 0))"
4688,4688,-0.46242426,a_15^dagger a_14^dagger a_15 a_14,"((15, 1), (14, 1), (15, 0), (14, 0))"

=== Hermitian fermionic terms T_i ===

,vertex,number_of_monomials,fermionic_term
0,T_0,1,-22.40891512 I
1,T_1,1,-4.00514475 a_0^dagger a_0
2,T_2,2,-0.53295796 a_0^dagger a_14 + -0.53295796 a_14^dagger a_0
3,T_3,1,-4.00514475 a_1^dagger a_1
4,T_4,2,-0.53295796 a_1^dagger a_15 + -0.53295796 a_15^dagger a_1
...,...,...,...
2408,T_2408,2,+0.10185535 a_14^dagger a_13^dagger a_15 a_12 + +0.10185535 a_15^dagger a_12^dagger a_14 a_13
2409,T_2409,1,-0.47820478 a_15^dagger a_12^dagger a_15 a_12
2410,T_2410,1,-0.47820478 a_14^dagger a_13^dagger a_14 a_13
2411,T_2411,1,-0.37634943 a_15^dagger a_13^dagger a_15 a_13
2412,T_2412,1,-0.46242426 a_15^dagger a_14^dagger a_15 a_14

In [12]:
# Cell 2: Build the H2 fermionic noncommutation graph

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from openfermion.transforms import normal_ordered

pd.set_option("display.max_colwidth", None)


def fermionic_commutator(A, B, tol=1e-12):
    """
    Compute [A, B] = AB - BA directly in the fermionic algebra.
    """
    C = normal_ordered(A * B - B * A)
    C.compress(abs_tol=tol)
    return C


def commute(A, B, tol=1e-12):
    """
    Return True if [A, B] = 0.
    """
    C = fermionic_commutator(A, B, tol=tol)
    return len(C.terms) == 0


# ------------------------------------------------------------
# Build noncommutation graph
# ------------------------------------------------------------
# Vertex i = Hermitian fermionic term T_i
# Edge (i, j) exists if [T_i, T_j] != 0

G = nx.Graph()

for i, T in enumerate(hermitian_terms):
    G.add_node(
        i,
        label=f"T_{i}",
        operator=T,
        operator_string=operator_to_string(T),
        number_of_monomials=len(T.terms),
    )

for i in range(len(hermitian_terms)):
    for j in range(i + 1, len(hermitian_terms)):
        Cij = fermionic_commutator(hermitian_terms[i], hermitian_terms[j])

        if len(Cij.terms) != 0:
            G.add_edge(
                i,
                j,
                commutator=Cij,
                commutator_string=operator_to_string(Cij),
            )


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

n_vertices = G.number_of_nodes()
n_total_pairs = n_vertices * (n_vertices - 1) // 2
n_noncommuting_pairs = G.number_of_edges()
n_commuting_pairs = n_total_pairs - n_noncommuting_pairs

print("=== Fermionic noncommutation graph summary ===")
print("Number of vertices / fermionic terms:", n_vertices)
print("Number of total unordered pairs:", n_total_pairs)
print("Number of noncommuting pairs / edges:", n_noncommuting_pairs)
print("Number of commuting pairs:", n_commuting_pairs)
print("Is graph bipartite?", nx.is_bipartite(G))


# ------------------------------------------------------------
# Vertex table
# ------------------------------------------------------------

vertex_rows = []

for i, data in G.nodes(data=True):
    vertex_rows.append(
        {
            "vertex": f"T_{i}",
            "degree": G.degree[i],
            "commutes_with_all": G.degree[i] == 0,
            "fermionic_term": data["operator_string"],
        }
    )

vertex_df = pd.DataFrame(vertex_rows)

print("\n=== Vertices: fermionic terms ===")
display(vertex_df)


# ------------------------------------------------------------
# Edge table
# ------------------------------------------------------------

edge_rows = []

for i, j, data in G.edges(data=True):
    edge_rows.append(
        {
            "source": f"T_{i}",
            "target": f"T_{j}",
            "meaning": f"[T_{i}, T_{j}] != 0",
            "commutator": data["commutator_string"],
        }
    )

edge_df = pd.DataFrame(edge_rows)

print("\n=== Edges: noncommuting pairs ===")
display(edge_df)


# # ------------------------------------------------------------
# # Draw graph
# # ------------------------------------------------------------

# plt.figure(figsize=(12, 8))

# pos = nx.kamada_kawai_layout(G)

# node_labels = {
#     i: f"T_{i}"
#     for i in G.nodes()
# }

# node_sizes = [
#     1000 + 250 * G.degree[i]
#     for i in G.nodes()
# ]

# nx.draw_networkx_nodes(G, pos, node_size=node_sizes)
# nx.draw_networkx_edges(G, pos, width=1.5)
# nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=11, font_weight="bold")

# plt.title("H2 Fermionic Noncommutation Graph")
# plt.axis("off")
# plt.show()

=== Fermionic noncommutation graph summary ===
Number of vertices / fermionic terms: 2413
Number of total unordered pairs: 2910078
Number of noncommuting pairs / edges: 1663978
Number of commuting pairs: 1246100
Is graph bipartite? False

=== Vertices: fermionic terms ===

,vertex,degree,commutes_with_all,fermionic_term
0,T_0,0,True,-22.40891512 I
1,T_1,428,False,-4.00514475 a_0^dagger a_0
2,T_2,838,False,-0.53295796 a_0^dagger a_14 + -0.53295796 a_14^dagger a_0
3,T_3,428,False,-4.00514475 a_1^dagger a_1
4,T_4,838,False,-0.53295796 a_1^dagger a_15 + -0.53295796 a_15^dagger a_1
...,...,...,...,...
2408,T_2408,1424,False,+0.10185535 a_14^dagger a_13^dagger a_15 a_12 + +0.10185535 a_15^dagger a_12^dagger a_14 a_13
2409,T_2409,817,False,-0.47820478 a_15^dagger a_12^dagger a_15 a_12
2410,T_2410,817,False,-0.47820478 a_14^dagger a_13^dagger a_14 a_13
2411,T_2411,785,False,-0.37634943 a_15^dagger a_13^dagger a_15 a_13
2412,T_2412,781,False,-0.46242426 a_15^dagger a_14^dagger a_15 a_14

=== Edges: noncommuting pairs ===

,source,target,meaning,commutator
0,T_1,T_2,"[T_1, T_2] != 0",+2.13457378 a_0^dagger a_14 + -2.13457378 a_14^dagger a_0
1,T_1,T_38,"[T_1, T_38] != 0",-0.35109953 a_1^dagger a_0^dagger a_14 a_1 + +0.35109953 a_14^dagger a_1^dagger a_1 a_0
2,T_1,T_39,"[T_1, T_39] != 0",+0.43395017 a_1^dagger a_0^dagger a_3 a_2 + -0.43395017 a_3^dagger a_2^dagger a_1 a_0
3,T_1,T_40,"[T_1, T_40] != 0",-0.01543735 a_1^dagger a_0^dagger a_8 a_3 + +0.01543735 a_8^dagger a_3^dagger a_1 a_0
4,T_1,T_41,"[T_1, T_41] != 0",-0.00799553 a_1^dagger a_0^dagger a_10 a_3 + +0.00799553 a_10^dagger a_3^dagger a_1 a_0
...,...,...,...,...
1663973,T_2405,T_2410,"[T_2405, T_2410] != 0",+0.00914893 a_14^dagger a_13^dagger a_12^dagger a_15 a_14 a_12 + -0.00914893 a_15^dagger a_14^dagger a_12^dagger a_14 a_13 a_12
1663974,T_2405,T_2412,"[T_2405, T_2412] != 0",-0.00884702 a_14^dagger a_13^dagger a_12^dagger a_15 a_14 a_12 + +0.00884702 a_15^dagger a_14^dagger a_12^dagger a_14 a_13 a_12
1663975,T_2406,T_2412,"[T_2406, T_2412] != 0",-0.04710039 a_13^dagger a_12^dagger a_15 a_14 + +0.04710039 a_15^dagger a_14^dagger a_13 a_12
1663976,T_2408,T_2409,"[T_2408, T_2409] != 0",+0.04870772 a_14^dagger a_13^dagger a_15 a_12 + -0.04870772 a_15^dagger a_12^dagger a_14 a_13
1663977,T_2408,T_2410,"[T_2408, T_2410] != 0",-0.04870772 a_14^dagger a_13^dagger a_15 a_12 + +0.04870772 a_15^dagger a_12^dagger a_14 a_13

In [13]:
# Cell 2 alpha: Faster H2 / molecular fermionic noncommutation graph
#
# Main idea:
#   1. Use cheap fermionic index rules first.
#   2. Only if rules cannot decide, use exact OpenFermion symbolic commutator.
#   3. Never build sparse/dense matrices.
#
# This cell assumes Cell 1 already defined:
#   hermitian_terms
#   operator_to_string

import time
from collections import Counter

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from openfermion.utils import commutator
from openfermion.transforms import normal_ordered

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# Fermionic key utilities
# ------------------------------------------------------------

def key_modes(key):
    """
    Modes appearing in one OpenFermion monomial key.

    Example:
        ((3, 1), (0, 1), (3, 0), (0, 0)) -> {0, 3}
    """
    return frozenset(mode for mode, action in key)


def key_creations(key):
    """
    Creation modes in one monomial.
    """
    return frozenset(mode for mode, action in key if action == 1)


def key_annihilations(key):
    """
    Annihilation modes in one monomial.
    """
    return frozenset(mode for mode, action in key if action == 0)


def key_net_delta(key):
    """
    Net occupation change caused by a monomial.

    creation contributes +1
    annihilation contributes -1

    For example:
        a_2^dagger a_1^dagger a_3 a_0
    has delta:
        +1 on modes 2 and 1
        -1 on modes 3 and 0
    """
    delta = Counter()

    for mode, action in key:
        if action == 1:
            delta[mode] += 1
        else:
            delta[mode] -= 1

    return delta


def is_diagonal_key(key):
    """
    True if a monomial preserves occupation mode-by-mode.

    Examples:
        a_p^dagger a_p is diagonal.
        a_p^dagger a_q^dagger a_q a_p is diagonal.
        a_p^dagger a_q is not diagonal when p != q.
    """
    delta = key_net_delta(key)
    return all(value == 0 for value in delta.values())


def is_even_key(key):
    """
    Electronic Hamiltonian terms normally have even fermionic parity:
    length 0, 2, or 4.
    """
    return len(key) % 2 == 0


# ------------------------------------------------------------
# Safe monomial-level commutation rules
# ------------------------------------------------------------

def diagonal_key_commutes_with_key(diagonal_key, other_key):
    """
    Safe rule:

    A diagonal occupation operator depending on modes S commutes with another
    monomial if the other monomial has zero net occupation change on every
    mode in S.
    """
    support = key_modes(diagonal_key)
    delta = key_net_delta(other_key)

    return all(delta.get(mode, 0) == 0 for mode in support)


def no_cross_contractions_even_commute(key_a, key_b):
    """
    Safe rule for normal-ordered even fermionic monomials.

    If there are no possible cross contractions:
        annihilations(A) intersect creations(B) = empty
        annihilations(B) intersect creations(A) = empty

    then even monomials commute.

    This catches many cases beyond completely disjoint support.
    """
    if not is_even_key(key_a) or not is_even_key(key_b):
        return False

    a_ann = key_annihilations(key_a)
    a_cre = key_creations(key_a)

    b_ann = key_annihilations(key_b)
    b_cre = key_creations(key_b)

    return a_ann.isdisjoint(b_cre) and b_ann.isdisjoint(a_cre)


def monomial_pair_definitely_commutes(key_a, key_b):
    """
    Return (True, reason) only when we are sure two monomials commute.
    Return (False, None) if the rule cannot decide.

    Important:
        False here does NOT mean noncommuting.
        It only means "unknown; use exact symbolic fallback."
    """
    # Identity commutes with everything.
    if key_a == () or key_b == ():
        return True, "identity"

    # Any monomial commutes with itself.
    if key_a == key_b:
        return True, "same_monomial"

    # Diagonal occupation-like monomials commute with each other.
    if is_diagonal_key(key_a) and is_diagonal_key(key_b):
        return True, "diagonal_diagonal"

    # Diagonal with excitation-like term, if excitation preserves diagonal support.
    if is_diagonal_key(key_a) and diagonal_key_commutes_with_key(key_a, key_b):
        return True, "diagonal_support_preserved"

    if is_diagonal_key(key_b) and diagonal_key_commutes_with_key(key_b, key_a):
        return True, "diagonal_support_preserved"

    # Even monomials with no cross contractions commute.
    if no_cross_contractions_even_commute(key_a, key_b):
        return True, "no_cross_contractions_even"

    return False, None


# ------------------------------------------------------------
# Operator-level metadata and precheck
# ------------------------------------------------------------

def operator_metadata(op):
    """
    Precompute simple structural data for one FermionOperator.
    """
    keys = list(op.terms.keys())

    modes = set()
    for key in keys:
        modes.update(key_modes(key))

    return {
        "is_zero": len(keys) == 0,
        "only_identity": len(keys) == 1 and keys[0] == (),
        "modes": frozenset(modes),
        "is_even": all(is_even_key(key) for key in keys),
        "is_diagonal": all(is_diagonal_key(key) for key in keys),
        "number_of_monomials": len(keys),
    }


def operator_pair_definitely_commutes(A, B, meta_A, meta_B):
    """
    Return (True, reason) only for guaranteed-commuting pairs.
    Return (False, None) when unresolved.
    """
    if meta_A["is_zero"] or meta_B["is_zero"]:
        return True, "zero"

    if meta_A["only_identity"] or meta_B["only_identity"]:
        return True, "identity"

    # Very cheap global rule:
    # disjoint even fermionic operators commute.
    if (
        meta_A["is_even"]
        and meta_B["is_even"]
        and meta_A["modes"].isdisjoint(meta_B["modes"])
    ):
        return True, "disjoint_even_support"

    # Diagonal occupation-like operators commute with each other.
    if meta_A["is_diagonal"] and meta_B["is_diagonal"]:
        return True, "diagonal_diagonal"

    # More detailed but still cheap:
    # if every monomial pair has a safe commuting reason, the sums commute.
    reasons = Counter()

    for key_a in A.terms:
        for key_b in B.terms:
            ok, reason = monomial_pair_definitely_commutes(key_a, key_b)

            if not ok:
                return False, None

            reasons[reason] += 1

    if len(reasons) > 0:
        main_reason = reasons.most_common(1)[0][0]
        return True, f"all_monomial_pairs_{main_reason}"

    return False, None


# ------------------------------------------------------------
# Exact symbolic fallback
# ------------------------------------------------------------

def exact_symbolic_fermionic_commutator(A, B, tol=1e-12):
    """
    Exact symbolic commutator in fermionic algebra.

    This does not build a 2^n matrix.
    """
    C = normal_ordered(commutator(A, B))
    C.compress(abs_tol=tol)
    return C


# ------------------------------------------------------------
# Alpha graph builder
# ------------------------------------------------------------

def build_fermionic_noncommutation_graph_alpha(
    hermitian_terms,
    tol=1e-12,
    store_commutators=False,
):
    """
    Build noncommutation graph using:
        fast safe index rules first,
        exact symbolic OpenFermion fallback only when needed.

    Parameters
    ----------
    hermitian_terms:
        list of FermionOperator terms T_i from Cell 1.

    tol:
        numerical compression tolerance.

    store_commutators:
        False is recommended for large molecules.
        True is useful for H2 debugging, but can be memory-heavy.

    Returns
    -------
    G:
        networkx.Graph

    stats_df:
        pandas.DataFrame with timing and skip counts
    """
    t_start = time.perf_counter()

    G = nx.Graph()
    stats = Counter()

    metadata = [operator_metadata(T) for T in hermitian_terms]

    # Add vertices.
    for i, T in enumerate(hermitian_terms):
        G.add_node(
            i,
            label=f"T_{i}",
            operator=T,
            operator_string=operator_to_string(T),
            number_of_monomials=len(T.terms),
            modes=sorted(metadata[i]["modes"]),
            is_diagonal=metadata[i]["is_diagonal"],
            is_even=metadata[i]["is_even"],
        )

    n = len(hermitian_terms)

    # Pairwise graph construction.
    for i in range(n):
        A = hermitian_terms[i]
        meta_A = metadata[i]

        for j in range(i + 1, n):
            B = hermitian_terms[j]
            meta_B = metadata[j]

            stats["total_pairs"] += 1

            # 1. Fast guaranteed-commuting rules.
            definitely_commutes, reason = operator_pair_definitely_commutes(
                A, B, meta_A, meta_B
            )

            if definitely_commutes:
                stats["pairs_skipped_by_index_rules"] += 1
                stats[f"skip_{reason}"] += 1
                continue

            # 2. Exact symbolic fallback.
            stats["pairs_sent_to_exact_symbolic"] += 1

            Cij = exact_symbolic_fermionic_commutator(A, B, tol=tol)

            if len(Cij.terms) != 0:
                stats["noncommuting_edges"] += 1

                edge_data = {
                    "method": "exact_symbolic_fallback",
                    "meaning": f"[T_{i}, T_{j}] != 0",
                }

                if store_commutators:
                    edge_data["commutator"] = Cij
                    edge_data["commutator_string"] = operator_to_string(Cij)
                else:
                    edge_data["commutator_string"] = (
                        "(not stored; rerun with store_commutators=True)"
                    )

                G.add_edge(i, j, **edge_data)

            else:
                stats["exact_symbolic_found_commuting"] += 1

    elapsed = time.perf_counter() - t_start

    stats["vertices"] = n
    stats["edges"] = G.number_of_edges()
    stats["commuting_pairs"] = stats["total_pairs"] - G.number_of_edges()
    stats["elapsed_seconds"] = elapsed

    stats_df = pd.DataFrame([dict(stats)])

    return G, stats_df


# ------------------------------------------------------------
# Run alpha graph builder
# ------------------------------------------------------------

# For H2 debugging, you can set store_commutators=True.
# For larger molecules, keep this False.
G_alpha, stats_df = build_fermionic_noncommutation_graph_alpha(
    hermitian_terms,
    tol=1e-12,
    store_commutators=False,
)

print("=== Fermionic noncommutation graph alpha summary ===")
display(stats_df)

print("Number of vertices / fermionic terms:", G_alpha.number_of_nodes())
print("Number of noncommuting pairs / edges:", G_alpha.number_of_edges())
print("Is graph bipartite?", nx.is_bipartite(G_alpha))


# ------------------------------------------------------------
# Vertex table
# ------------------------------------------------------------

vertex_rows = []

for i, data in G_alpha.nodes(data=True):
    vertex_rows.append(
        {
            "vertex": f"T_{i}",
            "degree": G_alpha.degree[i],
            "commutes_with_all": G_alpha.degree[i] == 0,
            "number_of_monomials": data["number_of_monomials"],
            "modes": data["modes"],
            "is_diagonal": data["is_diagonal"],
            "fermionic_term": data["operator_string"],
        }
    )

vertex_df_alpha = pd.DataFrame(vertex_rows)

print("\n=== Alpha vertices: fermionic terms ===")
display(vertex_df_alpha)


# ------------------------------------------------------------
# Edge table
# ------------------------------------------------------------

edge_rows = []

for i, j, data in G_alpha.edges(data=True):
    edge_rows.append(
        {
            "source": f"T_{i}",
            "target": f"T_{j}",
            "meaning": data["meaning"],
            "method": data["method"],
            "commutator": data["commutator_string"],
        }
    )

edge_df_alpha = pd.DataFrame(edge_rows)

print("\n=== Alpha edges: noncommuting pairs ===")
display(edge_df_alpha)

# The commutation graph is too large for this.

# # ------------------------------------------------------------
# # Draw graph
# # ------------------------------------------------------------

# plt.figure(figsize=(12, 8))

# pos = nx.kamada_kawai_layout(G_alpha)

# node_labels = {
#     i: f"T_{i}"
#     for i in G_alpha.nodes()
# }

# node_sizes = [
#     1000 + 250 * G_alpha.degree[i]
#     for i in G_alpha.nodes()
# ]

# nx.draw_networkx_nodes(G_alpha, pos, node_size=node_sizes)
# nx.draw_networkx_edges(G_alpha, pos, width=1.5)
# nx.draw_networkx_labels(
#     G_alpha,
#     pos,
#     labels=node_labels,
#     font_size=11,
#     font_weight="bold",
# )

# plt.title("Fermionic Noncommutation Graph Alpha")
# plt.axis("off")
# plt.show()

=== Fermionic noncommutation graph alpha summary ===

,total_pairs,pairs_skipped_by_index_rules,skip_identity,pairs_sent_to_exact_symbolic,noncommuting_edges,skip_disjoint_even_support,skip_diagonal_diagonal,skip_all_monomial_pairs_diagonal_support_preserved,exact_symbolic_found_commuting,vertices,edges,commuting_pairs,elapsed_seconds
0,2910078,1081006,2412,1829072,1663978,1068218,1920,8456,165094,2413,1663978,1246100,104.862653

Number of vertices / fermionic terms: 2413
Number of noncommuting pairs / edges: 1663978
Is graph bipartite? False

=== Alpha vertices: fermionic terms ===

,vertex,degree,commutes_with_all,number_of_monomials,modes,is_diagonal,fermionic_term
0,T_0,0,True,1,[],True,-22.40891512 I
1,T_1,428,False,1,[0],True,-4.00514475 a_0^dagger a_0
2,T_2,838,False,2,"[0, 14]",False,-0.53295796 a_0^dagger a_14 + -0.53295796 a_14^dagger a_0
3,T_3,428,False,1,[1],True,-4.00514475 a_1^dagger a_1
4,T_4,838,False,2,"[1, 15]",False,-0.53295796 a_1^dagger a_15 + -0.53295796 a_15^dagger a_1
...,...,...,...,...,...,...,...
2408,T_2408,1424,False,2,"[12, 13, 14, 15]",False,+0.10185535 a_14^dagger a_13^dagger a_15 a_12 + +0.10185535 a_15^dagger a_12^dagger a_14 a_13
2409,T_2409,817,False,1,"[12, 15]",True,-0.47820478 a_15^dagger a_12^dagger a_15 a_12
2410,T_2410,817,False,1,"[13, 14]",True,-0.47820478 a_14^dagger a_13^dagger a_14 a_13
2411,T_2411,785,False,1,"[13, 15]",True,-0.37634943 a_15^dagger a_13^dagger a_15 a_13
2412,T_2412,781,False,1,"[14, 15]",True,-0.46242426 a_15^dagger a_14^dagger a_15 a_14

=== Alpha edges: noncommuting pairs ===

,source,target,meaning,method,commutator
0,T_1,T_2,"[T_1, T_2] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
1,T_1,T_38,"[T_1, T_38] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
2,T_1,T_39,"[T_1, T_39] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
3,T_1,T_40,"[T_1, T_40] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
4,T_1,T_41,"[T_1, T_41] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
...,...,...,...,...,...
1663973,T_2405,T_2410,"[T_2405, T_2410] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
1663974,T_2405,T_2412,"[T_2405, T_2412] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
1663975,T_2406,T_2412,"[T_2406, T_2412] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
1663976,T_2408,T_2409,"[T_2408, T_2409] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
1663977,T_2408,T_2410,"[T_2408, T_2410] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)

In [14]:
print("Same edge set?")
print(set(G.edges()) == set(G_alpha.edges()))

Same edge set?
True

In [15]:
# Cell 3: Color graph, build commuting blocks, map JW/BK, verify commutation

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from itertools import combinations
from openfermion.ops import FermionOperator
from openfermion.transforms import normal_ordered, jordan_wigner, bravyi_kitaev

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# 1. Color the noncommutation graph
# ------------------------------------------------------------
# Since edges mean noncommutation, each color class is a commuting group.

coloring = nx.coloring.greedy_color(G, strategy="largest_first")

color_groups = {}

for node, color in coloring.items():
    color_groups.setdefault(color, []).append(node)

for color in color_groups:
    color_groups[color] = sorted(color_groups[color])

color_names = [
    "red",
    "blue",
    "green",
    "orange",
    "purple",
    "brown",
    "pink",
    "gray",
]

color_name = {
    color: color_names[color] if color < len(color_names) else f"color_{color}"
    for color in color_groups
}

num_grouped_terms = sum(len(nodes) for nodes in color_groups.values())

print("Number of fermionic terms / vertices:", G.number_of_nodes())
print("Number of colors / commuting groups:", len(color_groups))
print("Number of grouped terms:", num_grouped_terms)

assert num_grouped_terms == G.number_of_nodes()


# ------------------------------------------------------------
# 2. Verify each color group is mutually commuting
# ------------------------------------------------------------

def verify_commuting_group(nodes, tol=1e-12):
    for i, j in combinations(nodes, 2):
        A = G.nodes[i]["operator"]
        B = G.nodes[j]["operator"]

        if not commute(A, B, tol=tol):
            return False

    return True


group_summary_rows = []

for color, nodes in sorted(color_groups.items()):
    group_summary_rows.append(
        {
            "color_id": color,
            "color_name": color_name[color],
            "number_of_terms": len(nodes),
            "vertices": [f"T_{i}" for i in nodes],
            "verified_mutually_commuting": verify_commuting_group(nodes),
        }
    )

group_summary_df = pd.DataFrame(group_summary_rows)

print("\n=== Commuting groups from graph coloring ===")
display(group_summary_df)


# ------------------------------------------------------------
# 3. Build Hamiltonian pieces by color
# ------------------------------------------------------------

H_by_color = {}

for color, nodes in sorted(color_groups.items()):
    H_color = FermionOperator.zero()

    for node in nodes:
        H_color += G.nodes[node]["operator"]

    H_color = normal_ordered(H_color)
    H_color.compress(abs_tol=1e-12)

    H_by_color[color] = H_color


color_block_rows = []

for color, nodes in sorted(color_groups.items()):
    for local_index, node in enumerate(nodes, start=1):
        color_block_rows.append(
            {
                "color_block": f"H_{color_name[color]}",
                "local_term_name": f"{color_name[color][0].upper()}_{local_index}",
                "vertex": f"T_{node}",
                "fermionic_term": G.nodes[node]["operator_string"],
            }
        )

color_block_df = pd.DataFrame(color_block_rows)

print("\n=== Which T_i belongs to which color block ===")
display(color_block_df)


print("\n=== Hamiltonian split by commuting color groups ===")

for color, H_color in H_by_color.items():
    nodes = color_groups[color]

    print("\n" + "=" * 80)
    print(f"H_{color_name[color]} consists of:")
    print(" + ".join([f"T_{node}" for node in nodes]))

    print(f"\nSummed operator H_{color_name[color]} =")
    print(H_color)


# ------------------------------------------------------------
# 4. Trotter ordering induced by color groups
# ------------------------------------------------------------

trotter_order = []

for color, nodes in sorted(color_groups.items()):
    for node in nodes:
        trotter_order.append(node)

print("\n=== Trotter order by commuting color groups ===")
print([f"T_{i}" for i in trotter_order])


# ------------------------------------------------------------
# 5. Helper functions for JW/BK output
# ------------------------------------------------------------

def sort_qubit_key(term):
    return (len(term), term)


def format_qubit_term(term):
    if term == ():
        return "I"

    return " ".join([f"{pauli}{qubit}" for qubit, pauli in term])


def qubit_coeff_to_str(c, digits=8):
    c = complex(c)
    if abs(c.imag) < 1e-12:
        return f"{c.real:+.{digits}f}"
    return f"{c.real:+.{digits}f}{c.imag:+.{digits}f}j"


def qubit_operator_to_string(op, digits=8):
    pieces = []

    for term, coeff in sorted(op.terms.items(), key=lambda item: sort_qubit_key(item[0])):
        pieces.append(f"{qubit_coeff_to_str(coeff, digits)} {format_qubit_term(term)}")

    if len(pieces) == 0:
        return "0"

    return " + ".join(pieces)


def apply_bk(op, n_qubits):
    try:
        return bravyi_kitaev(op, n_qubits=n_qubits)
    except TypeError:
        return bravyi_kitaev(op, n_qubits)


def qubit_commutator(A, B, tol=1e-12):
    C = A * B - B * A
    C.compress(abs_tol=tol)
    return C


def qubit_commute(A, B, tol=1e-12):
    C = qubit_commutator(A, B, tol=tol)
    return len(C.terms) == 0


n_qubits = molecule.n_qubits

print("\nNumber of qubits / spin orbitals:", n_qubits)


# ------------------------------------------------------------
# 6. Map each fermionic vertex T_i to JW(T_i) and BK(T_i)
# ------------------------------------------------------------

mapped_rows = []

for node in sorted(G.nodes()):
    T_i = G.nodes[node]["operator"]

    JW_T_i = jordan_wigner(T_i)
    JW_T_i.compress(abs_tol=1e-12)

    BK_T_i = apply_bk(T_i, n_qubits=n_qubits)
    BK_T_i.compress(abs_tol=1e-12)

    G.nodes[node]["JW_operator"] = JW_T_i
    G.nodes[node]["BK_operator"] = BK_T_i
    G.nodes[node]["JW_operator_string"] = qubit_operator_to_string(JW_T_i)
    G.nodes[node]["BK_operator_string"] = qubit_operator_to_string(BK_T_i)

    node_color = coloring[node]
    node_color_name = color_name[node_color]

    mapped_rows.append(
        {
            "color": node_color_name,
            "vertex": f"T_{node}",
            "fermionic_term": G.nodes[node]["operator_string"],
            "number_of_JW_Pauli_strings": len(JW_T_i.terms),
            "JW_transform": qubit_operator_to_string(JW_T_i),
            "number_of_BK_Pauli_strings": len(BK_T_i.terms),
            "BK_transform": qubit_operator_to_string(BK_T_i),
        }
    )

mapped_terms_df = pd.DataFrame(mapped_rows)

print("\n=== Fermionic terms mapped to JW and BK ===")
display(mapped_terms_df)


# ------------------------------------------------------------
# 7. Map each color block H_color to JW and BK
# ------------------------------------------------------------

JW_by_color = {}
BK_by_color = {}

block_rows = []

for color, H_color in sorted(H_by_color.items()):
    JW_color = jordan_wigner(H_color)
    JW_color.compress(abs_tol=1e-12)

    BK_color = apply_bk(H_color, n_qubits=n_qubits)
    BK_color.compress(abs_tol=1e-12)

    JW_by_color[color] = JW_color
    BK_by_color[color] = BK_color

    block_rows.append(
        {
            "color_block": f"H_{color_name[color]}",
            "fermionic_vertices": " + ".join([f"T_{node}" for node in color_groups[color]]),
            "number_of_fermionic_terms": len(color_groups[color]),
            "number_of_JW_Pauli_strings": len(JW_color.terms),
            "JW_block": qubit_operator_to_string(JW_color),
            "number_of_BK_Pauli_strings": len(BK_color.terms),
            "BK_block": qubit_operator_to_string(BK_color),
        }
    )

block_map_df = pd.DataFrame(block_rows)

print("\n=== Color blocks mapped to JW and BK ===")
display(block_map_df)


# ------------------------------------------------------------
# 8. Verify same-color terms commute after JW and BK
# ------------------------------------------------------------

verification_rows = []

for color, nodes in sorted(color_groups.items()):
    for i, j in combinations(nodes, 2):
        Ti = G.nodes[i]["operator"]
        Tj = G.nodes[j]["operator"]

        JW_Ti = G.nodes[i]["JW_operator"]
        JW_Tj = G.nodes[j]["JW_operator"]

        BK_Ti = G.nodes[i]["BK_operator"]
        BK_Tj = G.nodes[j]["BK_operator"]

        verification_rows.append(
            {
                "color_group": color_name[color],
                "pair": f"T_{i}, T_{j}",
                "fermionic_commute": commute(Ti, Tj),
                "JW_commute": qubit_commute(JW_Ti, JW_Tj),
                "BK_commute": qubit_commute(BK_Ti, BK_Tj),
            }
        )

verification_df = pd.DataFrame(verification_rows)

print("\n=== Verify commuting groups after JW/BK mapping ===")
display(verification_df)

Number of fermionic terms / vertices: 2413
Number of colors / commuting groups: 267
Number of grouped terms: 2413

=== Commuting groups from graph coloring ===

,color_id,color_name,number_of_terms,vertices,verified_mutually_commuting
0,0,red,13,"[T_0, T_64, T_466, T_471, T_905, T_915, T_966, T_1020, T_1347, T_1679, T_1797, T_2295, T_2307]",True
1,1,blue,12,"[T_2, T_4, T_470, T_901, T_921, T_962, T_1022, T_1398, T_1878, T_1980, T_2298, T_2321]",True
2,2,green,16,"[T_1, T_35, T_63, T_461, T_895, T_897, T_955, T_979, T_1028, T_1380, T_1520, T_1895, T_2135, T_2305, T_2314, T_2324]",True
3,3,orange,10,"[T_463, T_903, T_1045, T_1100, T_1307, T_1349, T_1350, T_1651, T_2315, T_2325]",True
4,4,purple,10,"[T_465, T_899, T_980, T_1021, T_1029, T_1318, T_1404, T_1893, T_2348, T_2355]",True
...,...,...,...,...,...
262,262,color_262,6,"[T_619, T_784, T_1543, T_1551, T_1780, T_1816]",True
263,263,color_263,3,"[T_1362, T_1960, T_2374]",True
264,264,color_264,2,"[T_1976, T_2292]",True
265,265,color_265,7,"[T_553, T_621, T_689, T_751, T_810, T_869, T_2404]",True
266,266,color_266,1,[T_1040],True

=== Which T_i belongs to which color block ===

,color_block,local_term_name,vertex,fermionic_term
0,H_red,R_1,T_0,-22.40891512 I
1,H_red,R_2,T_64,-0.07342357 a_1^dagger a_0^dagger a_15 a_14 + -0.07342357 a_15^dagger a_14^dagger a_1 a_0
2,H_red,R_3,T_466,+0.04316516 a_10^dagger a_4^dagger a_14 a_0 + +0.04316516 a_14^dagger a_0^dagger a_10 a_4
3,H_red,R_4,T_471,+0.07342357 a_14^dagger a_1^dagger a_15 a_0 + +0.07342357 a_15^dagger a_0^dagger a_14 a_1
4,H_red,R_5,T_905,-0.00551298 a_13^dagger a_7^dagger a_15 a_1 + -0.00551298 a_15^dagger a_1^dagger a_13 a_7
...,...,...,...,...
2408,H_color_265,C_4,T_751,+0.07289402 a_9^dagger a_1^dagger a_15 a_9 + +0.07289402 a_15^dagger a_9^dagger a_9 a_1
2409,H_color_265,C_5,T_810,+0.07289402 a_11^dagger a_1^dagger a_15 a_11 + +0.07289402 a_15^dagger a_11^dagger a_11 a_1
2410,H_color_265,C_6,T_869,+0.07289402 a_13^dagger a_1^dagger a_15 a_13 + +0.07289402 a_15^dagger a_13^dagger a_13 a_1
2411,H_color_265,C_7,T_2404,-0.01913183 a_13^dagger a_12^dagger a_14 a_13 + -0.01913183 a_14^dagger a_13^dagger a_13 a_12
2412,H_color_266,C_1,T_1040,-0.00033723 a_7^dagger a_2^dagger a_14 a_7 + -0.00033723 a_14^dagger a_7^dagger a_7 a_2

=== Hamiltonian split by commuting color groups ===

================================================================================
H_red consists of:
T_0 + T_64 + T_466 + T_471 + T_905 + T_915 + T_966 + T_1020 + T_1347 + T_1679 + T_1797 + T_2295 + T_2307

Summed operator H_red =
-22.408915115183795 [] +
-0.07342356567648453 [1^ 0^ 15 14] +
0.02207805822580939 [3^ 2^ 6 5] +
0.02207805822580939 [5^ 2^ 6 3] +
0.0020192893932280765 [5^ 3^ 11 9] +
-0.015810495673025112 [6^ 2^ 12 8] +
0.02207805822580939 [6^ 3^ 5 2] +
0.02207805822580939 [6^ 5^ 3 2] +
-0.0005647002437223717 [7^ 4^ 13 10] +
0.005528888690091464 [9^ 8^ 12 11] +
0.04316515655384267 [10^ 4^ 14 0] +
0.0005647002437223717 [10^ 7^ 13 4] +
0.005528888690091464 [11^ 8^ 12 9] +
0.0020192893932280765 [11^ 9^ 5 3] +
-0.015810495673025112 [12^ 8^ 6 2] +
0.005528888690091464 [12^ 9^ 11 8] +
0.005528888690091464 [12^ 11^ 9 8] +
0.0005647002437223717 [13^ 4^ 10 7] +
-0.005512979769186424 [13^ 7^ 15 1] +
-0.0005647002437223717 [13^ 10^ 7 4] +
0.043165156553842676 [14^ 0^ 10 4] +
0.07342356567648453 [14^ 1^ 15 0] +
0.07342356567648453 [15^ 0^ 14 1] +
-0.005512979769186424 [15^ 1^ 13 7] +
-0.07342356567648453 [15^ 14^ 1 0]

================================================================================
H_blue consists of:
T_2 + T_4 + T_470 + T_901 + T_921 + T_962 + T_1022 + T_1398 + T_1878 + T_1980 + T_2298 + T_2321

Summed operator H_blue =
-0.5329579619356528 [0^ 14] +
-0.5329579619356528 [1^ 15] +
-0.02207805822580939 [3^ 2^ 7 4] +
0.0020192893932280765 [4^ 2^ 10 8] +
0.02207805822580939 [4^ 3^ 7 2] +
-0.0005647002437223717 [6^ 5^ 12 11] +
0.02207805822580939 [7^ 2^ 4 3] +
-0.015810495673025112 [7^ 3^ 13 9] +
-0.02207805822580939 [7^ 4^ 3 2] +
-0.005528888690091464 [9^ 8^ 13 10] +
0.0020192893932280765 [10^ 8^ 4 2] +
0.005528888690091464 [10^ 9^ 13 8] +
0.04316515655384267 [11^ 5^ 15 1] +
0.0005647002437223717 [11^ 6^ 12 5] +
0.0005647002437223717 [12^ 5^ 11 6] +
-0.005512979769186424 [12^ 6^ 14 0] +
-0.0005647002437223717 [12^ 11^ 6 5] +
0.005528888690091464 [13^ 8^ 10 9] +
-0.015810495673025112 [13^ 9^ 7 3] +
-0.005528888690091464 [13^ 10^ 9 8] +
-0.5329579619356531 [14^ 0] +
-0.005512979769186424 [14^ 0^ 12 6] +
-0.5329579619356531 [15^ 1] +
0.043165156553842676 [15^ 1^ 11 5]

================================================================================
H_green consists of:
T_1 + T_35 + T_63 + T_461 + T_895 + T_897 + T_955 + T_979 + T_1028 + T_1380 + T_1520 + T_1895 + T_2135 + T_2305 + T_2314 + T_2324

Summed operator H_green =
-4.005144750335747 [0^ 0] +
-0.08766213261681724 [1^ 0^ 15 0] +
-0.40539545062948423 [4^ 2^ 4 2] +
-0.005103652632325066 [5^ 2^ 7 4] +
-0.005103652632325066 [5^ 4^ 7 2] +
0.026685893024554232 [6^ 3^ 12 9] +
-0.005103652632325066 [7^ 2^ 5 4] +
-0.005103652632325066 [7^ 4^ 5 2] +
0.004220219974669236 [7^ 5^ 13 11] +
-0.011521868742486754 [9^ 3^ 15 1] +
-0.026685893024554232 [9^ 6^ 12 3] +
-0.44045461388833873 [10^ 8^ 10 8] +
0.004660698533864024 [11^ 8^ 13 10] +
0.004660698533864024 [11^ 10^ 13 8] +
-0.026685893024554232 [12^ 3^ 9 6] +
-0.42420741164527215 [12^ 6^ 12 6] +
0.026685893024554232 [12^ 9^ 6 3] +
0.004660698533864024 [13^ 8^ 11 10] +
0.004660698533864024 [13^ 10^ 11 8] +
0.004220219974669236 [13^ 11^ 7 5] +
-0.39724032855832725 [14^ 0^ 14 0] +
0.06588115430022344 [14^ 1^ 15 14] +
-2.734900764220156 [14^ 14] +
-0.08766213261681724 [15^ 0^ 1 0] +
-0.011521868742486755 [15^ 1^ 9 3] +
0.06588115430022344 [15^ 14^ 14 1]

================================================================================
H_orange consists of:
T_463 + T_903 + T_1045 + T_1100 + T_1307 + T_1349 + T_1350 + T_1651 + T_2315 + T_2325

Summed operator H_orange =
-0.005103652632325066 [4^ 3^ 6 5] +
-0.015832623078611538 [5^ 3^ 13 11] +
0.005103652632325066 [5^ 4^ 6 3] +
0.005103652632325066 [6^ 3^ 5 4] +
-0.0021857972861719765 [6^ 4^ 12 8] +
-0.005103652632325066 [6^ 5^ 4 3] +
-0.002831424706269629 [7^ 2^ 10 9] +
-0.002831424706269629 [9^ 2^ 10 7] +
0.043225567874650886 [9^ 7^ 15 1] +
-0.005967572681073615 [10^ 2^ 14 0] +
-0.002831424706269629 [10^ 7^ 9 2] +
-0.002831424706269629 [10^ 9^ 7 2] +
-0.008088165489688496 [11^ 8^ 13 12] +
-0.0021857972861719765 [12^ 8^ 6 4] +
0.008088165489688496 [12^ 11^ 13 8] +
0.008088165489688496 [13^ 8^ 12 11] +
-0.015832623078611538 [13^ 11^ 5 3] +
-0.008088165489688496 [13^ 12^ 11 8] +
-0.005967572681073616 [14^ 0^ 10 2] +
0.043225567874650886 [15^ 1^ 9 7]

================================================================================
H_purple consists of:
T_465 + T_899 + T_980 + T_1021 + T_1029 + T_1318 + T_1404 + T_1893 + T_2348 + T_2355

Summed operator H_purple =
-0.04036273112504216 [4^ 3^ 13 8] +
-0.0004479668192009238 [5^ 2^ 7 6] +
0.011846802822838181 [6^ 2^ 12 10] +
0.0004479668192009238 [6^ 5^ 7 2] +
0.0004479668192009238 [7^ 2^ 6 5] +
0.019653014549843292 [7^ 5^ 11 9] +
-0.0004479668192009238 [7^ 6^ 5 2] +
-0.04036273112504216 [8^ 3^ 13 4] +
0.03234364747860323 [8^ 4^ 14 0] +
0.004660698533864024 [10^ 9^ 12 11] +
0.019653014549843292 [11^ 9^ 7 5] +
-0.004660698533864024 [11^ 10^ 12 9] +
-0.004660698533864024 [12^ 9^ 11 10] +
0.011846802822838181 [12^ 10^ 6 2] +
0.004660698533864024 [12^ 11^ 10 9] +
-0.05365584149561277 [13^ 3^ 15 1] +
-0.04036273112504216 [13^ 4^ 8 3] +
-0.04036273112504216 [13^ 8^ 4 3] +
0.03234364747860323 [14^ 0^ 8 4] +
-0.05365584149561277 [15^ 1^ 13 3]

================================================================================
H_brown consists of:
T_3 + T_36 + T_38 + T_462 + T_497 + T_896 + T_995 + T_1155 + T_1308 + T_1351 + T_1390 + T_1652 + T_1966 + T_2349 + T_2356 + T_2365

Summed operator H_brown =
0.08766213261681724 [1^ 0^ 14 1] +
-4.005144750335747 [1^ 1] +
0.0004479668192009238 [4^ 3^ 7 6] +
0.009017630597833583 [5^ 2^ 11 8] +
0.0004479668192009238 [6^ 3^ 7 4] +
0.004220219974669236 [6^ 4^ 12 10] +
-0.4053954506294836 [7^ 3^ 7 3] +
0.0004479668192009238 [7^ 4^ 6 3] +
0.0004479668192009238 [7^ 6^ 4 3] +
-0.011521868742486754 [8^ 2^ 14 0] +
-0.009017630597833583 [8^ 5^ 11 2] +
0.008088165489688496 [10^ 9^ 13 12] +
-0.009017630597833583 [11^ 2^ 8 5] +
-0.4173715648246938 [11^ 5^ 11 5] +
0.009017630597833583 [11^ 8^ 5 2] +
0.008088165489688496 [12^ 9^ 13 10] +
0.004220219974669236 [12^ 10^ 6 4] +
-0.4404546138883405 [13^ 9^ 13 9] +
0.008088165489688496 [13^ 10^ 12 9] +
0.008088165489688496 [13^ 12^ 10 9] +
-0.011521868742486755 [14^ 0^ 8 2] +
0.08766213261681724 [14^ 1^ 1 0] +
-0.06588115430022344 [15^ 0^ 15 14] +
-0.39724032855832725 [15^ 1^ 15 1] +
-0.06588115430022344 [15^ 14^ 15 0] +
-2.734900764220156 [15^ 15]

================================================================================
H_pink consists of:
T_37 + T_496 + T_894 + T_914 + T_965 + T_1340 + T_2064 + T_2144 + T_2262 + T_2294 + T_2306 + T_2354 + T_2412

Summed operator H_pink =
-0.5040433677317613 [1^ 0^ 1 0] +
-0.04144414256907128 [3^ 2^ 5 4] +
0.04144414256907128 [4^ 3^ 5 2] +
0.04144414256907128 [5^ 2^ 4 3] +
-0.40539545062948423 [5^ 3^ 5 3] +
-0.04144414256907128 [5^ 4^ 3 2] +
-0.027200196668968394 [7^ 6^ 13 12] +
-0.04533761155366963 [9^ 8^ 11 10] +
0.04533761155366963 [10^ 9^ 11 8] +
0.04533761155366963 [11^ 8^ 10 9] +
-0.44045461388833873 [11^ 9^ 11 9] +
-0.04533761155366963 [11^ 10^ 9 8] +
0.027200196668968394 [12^ 7^ 13 6] +
0.027200196668968394 [13^ 6^ 12 7] +
-0.42420741164527215 [13^ 7^ 13 7] +
-0.027200196668968394 [13^ 12^ 7 6] +
-0.4706638942348118 [14^ 1^ 14 1] +
-0.4706638942348118 [15^ 0^ 15 0] +
-0.4624242574523326 [15^ 14^ 15 14]

================================================================================
H_gray consists of:
T_922 + T_1012 + T_1023 + T_1628 + T_1734 + T_1748 + T_2299 + T_2320 + T_2322

Summed operator H_gray =
-0.03166954947669902 [3^ 2^ 7 6] +
-0.09843627716323129 [5^ 4^ 11 10] +
-0.4053954506294836 [6^ 2^ 6 2] +
0.03166954947669902 [6^ 3^ 7 2] +
0.03166954947669902 [7^ 2^ 6 3] +
-0.03166954947669902 [7^ 6^ 3 2] +
-0.046681707954409124 [9^ 8^ 13 12] +
-0.4173715648246938 [10^ 4^ 10 4] +
0.09843627716323129 [10^ 5^ 11 4] +
0.09843627716323129 [11^ 4^ 10 5] +
-0.09843627716323129 [11^ 10^ 5 4] +
-0.4404546138883405 [12^ 8^ 12 8] +
0.046681707954409124 [12^ 9^ 13 8] +
0.046681707954409124 [13^ 8^ 12 9] +
-0.046681707954409124 [13^ 12^ 9 8]

================================================================================
H_color_8 consists of:
T_930 + T_1068 + T_1087 + T_1440 + T_1614 + T_1643 + T_1653 + T_1886 + T_2376 + T_2381 + T_2382 + T_2399

Summed operator H_color_8 =
-0.04928720881846882 [3^ 2^ 9 8] +
-0.02642311113739874 [5^ 4^ 7 6] +
-0.4053954506294839 [6^ 4^ 6 4] +
0.02642311113739874 [6^ 5^ 7 4] +
0.02642311113739874 [7^ 4^ 6 5] +
-0.4053954506294839 [7^ 5^ 7 5] +
-0.02642311113739874 [7^ 6^ 5 4] +
-0.4259482713327304 [8^ 2^ 8 2] +
0.04928720881846882 [8^ 3^ 9 2] +
0.04928720881846882 [9^ 2^ 8 3] +
-0.4259482713327304 [9^ 3^ 9 3] +
-0.04928720881846882 [9^ 8^ 3 2] +
-0.014572379917371779 [11^ 10^ 13 12] +
-0.44045461388834223 [12^ 10^ 12 10] +
0.014572379917371779 [12^ 11^ 13 10] +
0.014572379917371779 [13^ 10^ 12 11] +
-0.44045461388834223 [13^ 11^ 13 11] +
-0.014572379917371779 [13^ 12^ 11 10]

================================================================================
H_color_9 consists of:
T_219 + T_263 + T_432 + T_1111 + T_1165 + T_1420 + T_1469

Summed operator H_color_9 =
0.003014543426257326 [6^ 0^ 14 12] +
0.0050058226341118586 [7^ 0^ 13 6] +
0.0050058226341118586 [7^ 6^ 13 0] +
0.00608669641541279 [8^ 3^ 10 5] +
0.00608669641541279 [8^ 5^ 10 3] +
0.00608669641541279 [9^ 2^ 11 4] +
0.00608669641541279 [9^ 4^ 11 2] +
0.00608669641541279 [10^ 3^ 8 5] +
0.00608669641541279 [10^ 5^ 8 3] +
0.00608669641541279 [11^ 2^ 9 4] +
0.00608669641541279 [11^ 4^ 9 2] +
0.0050058226341118586 [13^ 0^ 7 6] +
0.0050058226341118586 [13^ 6^ 7 0] +
0.003014543426257326 [14^ 12^ 6 0]

================================================================================
H_color_10 consists of:
T_467 + T_902 + T_1019 + T_1112 + T_1166 + T_1397 + T_1421 + T_1470 + T_1635 + T_1793

Summed operator H_color_10 =
-0.03743709012522559 [5^ 4^ 13 12] +
-0.004302375710840531 [6^ 2^ 10 8] +
-0.004302375710840531 [7^ 3^ 11 9] +
0.001308942033707399 [8^ 3^ 10 7] +
0.001308942033707399 [8^ 7^ 10 3] +
0.001308942033707399 [9^ 2^ 11 6] +
0.001308942033707399 [9^ 6^ 11 2] +
0.001308942033707399 [10^ 3^ 8 7] +
0.001308942033707399 [10^ 7^ 8 3] +
-0.00430237571084053 [10^ 8^ 6 2] +
0.001308942033707399 [11^ 2^ 9 6] +
0.001308942033707399 [11^ 6^ 9 2] +
-0.00430237571084053 [11^ 9^ 7 3] +
-0.011746166910423248 [12^ 4^ 14 0] +
0.03743709012522559 [12^ 5^ 13 4] +
0.03743709012522559 [13^ 4^ 12 5] +
-0.011746166910423248 [13^ 5^ 15 1] +
-0.03743709012522559 [13^ 12^ 5 4] +
-0.01174616691042325 [14^ 0^ 12 4] +
-0.01174616691042325 [15^ 1^ 13 5]

================================================================================
H_color_11 consists of:
T_469 + T_904 + T_963 + T_1118 + T_1225 + T_1348 + T_1427 + T_1524 + T_2058 + T_2113

Summed operator H_color_11 =
-0.012412874933076594 [4^ 2^ 12 8] +
-0.012412874933076594 [5^ 3^ 13 9] +
-0.0667613202388769 [7^ 6^ 11 10] +
0.03153124894782827 [8^ 3^ 12 5] +
0.03153124894782827 [8^ 5^ 12 3] +
0.03153124894782827 [9^ 2^ 13 4] +
0.03153124894782827 [9^ 4^ 13 2] +
-0.03388911396899856 [10^ 6^ 14 0] +
0.0667613202388769 [10^ 7^ 11 6] +
0.0667613202388769 [11^ 6^ 10 7] +
-0.03388911396899856 [11^ 7^ 15 1] +
-0.0667613202388769 [11^ 10^ 7 6] +
0.03153124894782827 [12^ 3^ 8 5] +
0.03153124894782827 [12^ 5^ 8 3] +
-0.012412874933076594 [12^ 8^ 4 2] +
0.03153124894782827 [13^ 2^ 9 4] +
0.03153124894782827 [13^ 4^ 9 2] +
-0.012412874933076594 [13^ 9^ 5 3] +
-0.03388911396899856 [14^ 0^ 10 6] +
-0.03388911396899856 [15^ 1^ 11 7]

================================================================================
H_color_12 consists of:
T_149 + T_185 + T_361 + T_1119 + T_1226 + T_1428 + T_1525

Summed operator H_color_12 =
-0.023603068463999215 [4^ 0^ 14 10] +
-0.05585833172057725 [5^ 0^ 11 4] +
-0.05585833172057725 [5^ 4^ 11 0] +
0.029300695579915884 [8^ 3^ 12 7] +
0.029300695579915884 [8^ 7^ 12 3] +
0.029300695579915884 [9^ 2^ 13 6] +
0.029300695579915884 [9^ 6^ 13 2] +
-0.05585833172057725 [11^ 0^ 5 4] +
-0.05585833172057725 [11^ 4^ 5 0] +
0.029300695579915884 [12^ 3^ 8 7] +
0.029300695579915884 [12^ 7^ 8 3] +
0.029300695579915884 [13^ 2^ 9 6] +
0.029300695579915884 [13^ 6^ 9 2] +
-0.023603068463999215 [14^ 10^ 4 0]

================================================================================
H_color_13 consists of:
T_468 + T_964 + T_1179 + T_1231 + T_1483 + T_1530 + T_2052 + T_2080 + T_2208

Summed operator H_color_13 =
-0.015832623078611538 [4^ 2^ 12 10] +
-0.08658615846998884 [7^ 6^ 9 8] +
0.043225567874650886 [8^ 6^ 14 0] +
0.08658615846998884 [8^ 7^ 9 6] +
0.08658615846998884 [9^ 6^ 8 7] +
-0.41593929338098323 [9^ 7^ 9 7] +
-0.08658615846998884 [9^ 8^ 7 6] +
0.012299236416768361 [10^ 3^ 12 5] +
0.012299236416768361 [10^ 5^ 12 3] +
0.012299236416768361 [11^ 2^ 13 4] +
0.012299236416768361 [11^ 4^ 13 2] +
0.012299236416768361 [12^ 3^ 10 5] +
0.012299236416768361 [12^ 5^ 10 3] +
-0.015832623078611538 [12^ 10^ 4 2] +
0.012299236416768361 [13^ 2^ 11 4] +
0.012299236416768361 [13^ 4^ 11 2] +
0.043225567874650886 [14^ 0^ 8 6]

================================================================================
H_color_14 consists of:
T_898 + T_938 + T_1131 + T_1150 + T_1723 + T_1800 + T_1894 + T_1914 + T_1983

Summed operator H_color_14 =
-0.015350077975725383 [3^ 2^ 11 10] +
-0.0021857972861719765 [7^ 5^ 13 9] +
0.0011315426845846855 [8^ 5^ 12 7] +
0.0011315426845846855 [8^ 7^ 12 5] +
0.0011315426845846855 [9^ 4^ 13 6] +
0.0011315426845846855 [9^ 6^ 13 4] +
-0.4227751402015618 [10^ 2^ 10 2] +
0.015350077975725383 [10^ 3^ 11 2] +
0.015350077975725383 [11^ 2^ 10 3] +
-0.005967572681073615 [11^ 3^ 15 1] +
-0.015350077975725383 [11^ 10^ 3 2] +
0.0011315426845846855 [12^ 5^ 8 7] +
0.0011315426845846855 [12^ 7^ 8 5] +
0.0011315426845846855 [13^ 4^ 9 6] +
0.0011315426845846855 [13^ 6^ 9 4] +
-0.0021857972861719765 [13^ 9^ 7 5] +
-0.005967572681073616 [15^ 1^ 11 3]

================================================================================
H_color_15 consists of:
T_79 + T_107 + T_290 + T_1768 + T_1805 + T_1955 + T_1988

Summed operator H_color_15 =
0.00630025415112089 [2^ 0^ 14 8] +
0.052296061328588925 [3^ 0^ 9 2] +
0.052296061328588925 [3^ 2^ 9 0] +
0.052296061328588925 [9^ 0^ 3 2] +
0.052296061328588925 [9^ 2^ 3 0] +
-0.0023250976101290254 [10^ 5^ 12 7] +
-0.0023250976101290254 [10^ 7^ 12 5] +
-0.0023250976101290254 [11^ 4^ 13 6] +
-0.0023250976101290254 [11^ 6^ 13 4] +
-0.0023250976101290254 [12^ 5^ 10 7] +
-0.0023250976101290254 [12^ 7^ 10 5] +
-0.0023250976101290254 [13^ 4^ 11 6] +
-0.0023250976101290254 [13^ 6^ 11 4] +
0.00630025415112089 [14^ 8^ 2 0]

================================================================================
H_color_16 consists of:
T_464 + T_946 + T_1211 + T_1550 + T_1650 + T_1717 + T_1756 + T_1908 + T_1943

Summed operator H_color_16 =
-0.11591038858364026 [3^ 2^ 13 12] +
0.019653014549843292 [6^ 4^ 10 8] +
0.0005743975321582087 [8^ 5^ 10 7] +
0.0005743975321582087 [8^ 7^ 10 5] +
0.0005743975321582087 [9^ 4^ 11 6] +
0.0005743975321582087 [9^ 6^ 11 4] +
0.0005743975321582087 [10^ 5^ 8 7] +
0.0005743975321582087 [10^ 7^ 8 5] +
0.019653014549843292 [10^ 8^ 6 4] +
0.0005743975321582087 [11^ 4^ 9 6] +
0.0005743975321582087 [11^ 6^ 9 4] +
-0.05365584149561277 [12^ 2^ 14 0] +
0.11591038858364026 [12^ 3^ 13 2] +
0.11591038858364026 [13^ 2^ 12 3] +
-0.41100412995112395 [13^ 3^ 13 3] +
-0.11591038858364026 [13^ 12^ 3 2] +
-0.05365584149561277 [14^ 0^ 12 2]

================================================================================
H_color_17 consists of:
T_33 + T_336 + T_392 + T_447 + T_851 + T_981 + T_1030 + T_1309 + T_1352 + T_2407

Summed operator H_color_17 =
-0.0011735782867816201 [4^ 3^ 9 6] +
-0.0011735782867816201 [5^ 2^ 8 7] +
-0.0011735782867816201 [6^ 3^ 9 4] +
-0.0011735782867816201 [7^ 2^ 8 5] +
-0.001343297055773863 [8^ 2^ 10 0] +
-0.0011735782867816201 [8^ 5^ 7 2] +
-0.0011735782867816201 [8^ 7^ 5 2] +
-0.0011735782867816201 [9^ 4^ 6 3] +
-0.0011735782867816201 [9^ 6^ 4 3] +
-0.0013432970557738628 [10^ 0^ 8 2] +
0.005729745414569233 [11^ 0^ 13 10] +
0.005729745414569233 [11^ 10^ 13 0] +
0.08169107751542123 [12^ 1^ 15 12] +
-2.9240424656508006 [12^ 12] +
0.005729745414569233 [13^ 0^ 11 10] +
0.005729745414569233 [13^ 10^ 11 0] +
-0.37634942606531313 [14^ 12^ 14 12] +
0.08169107751542123 [15^ 12^ 12 1]

================================================================================
H_color_18 consists of:
T_274 + T_328 + T_440 + T_844 + T_982 + T_1031 + T_1310 + T_1353 + T_1496 + T_2409

Summed operator H_color_18 =
0.0012309638542146101 [4^ 3^ 11 6] +
0.0012309638542146101 [5^ 2^ 10 7] +
0.0012309638542146101 [6^ 3^ 11 4] +
0.0012309638542146101 [7^ 2^ 10 5] +
-0.0013432970557736895 [8^ 0^ 10 2] +
0.009690516805006434 [9^ 0^ 13 8] +
0.009690516805006434 [9^ 8^ 13 0] +
-0.0013432970557736895 [10^ 2^ 8 0] +
0.0012309638542146101 [10^ 5^ 7 2] +
0.0012309638542146101 [10^ 7^ 5 2] +
-0.4227751402015618 [11^ 3^ 11 3] +
0.0012309638542146101 [11^ 4^ 6 3] +
0.0012309638542146101 [11^ 6^ 4 3] +
-0.4936691697332932 [12^ 1^ 12 1] +
0.009690516805006434 [13^ 0^ 9 8] +
0.009690516805006434 [13^ 8^ 9 0] +
-0.47820477877945844 [15^ 12^ 15 12]

================================================================================
H_color_19 consists of:
T_31 + T_275 + T_322 + T_377 + T_786 + T_983 + T_1032 + T_1311 + T_1354 + T_2389

Summed operator H_color_19 =
-0.020923144699833383 [4^ 3^ 13 6] +
-0.020923144699833383 [5^ 2^ 12 7] +
-0.020923144699833383 [6^ 3^ 13 4] +
-0.020923144699833383 [7^ 2^ 12 5] +
-0.0252808255676009 [8^ 0^ 12 2] +
0.0138804726118051 [9^ 0^ 11 8] +
0.0138804726118051 [9^ 8^ 11 0] +
0.08169107751541957 [10^ 1^ 15 10] +
-2.92404246565079 [10^ 10] +
0.0138804726118051 [11^ 0^ 9 8] +
0.0138804726118051 [11^ 8^ 9 0] +
-0.0252808255676009 [12^ 2^ 8 0] +
-0.020923144699833383 [12^ 5^ 7 2] +
-0.020923144699833383 [12^ 7^ 5 2] +
-0.020923144699833383 [13^ 4^ 6 3] +
-0.020923144699833383 [13^ 6^ 4 3] +
-0.3763494260653114 [14^ 10^ 14 10] +
0.08169107751541957 [15^ 10^ 10 1]

================================================================================
H_color_20 consists of:
T_393 + T_403 + T_448 + T_900 + T_987 + T_1092 + T_1315 + T_1399 + T_1401

Summed operator H_color_20 =
0.0011735782867816165 [4^ 3^ 8 7] +
0.0011735782867816165 [5^ 2^ 9 6] +
-0.0011735782867816165 [6^ 5^ 9 2] +
0.011846802822838181 [7^ 3^ 13 11] +
-0.0011735782867816165 [7^ 4^ 8 3] +
-0.0011735782867816165 [8^ 3^ 7 4] +
0.0007473193734117119 [8^ 4^ 12 0] +
0.0011735782867816165 [8^ 7^ 4 3] +
-0.0011735782867816165 [9^ 2^ 6 5] +
0.03234364747860323 [9^ 5^ 15 1] +
0.0011735782867816165 [9^ 6^ 5 2] +
0.00641927410308798 [11^ 0^ 13 12] +
0.0007473193734117119 [12^ 0^ 8 4] +
-0.00641927410308798 [12^ 11^ 13 0] +
-0.00641927410308798 [13^ 0^ 12 11] +
0.011846802822838181 [13^ 11^ 7 3] +
0.00641927410308798 [13^ 12^ 11 0] +
0.03234364747860323 [15^ 1^ 9 5]

================================================================================
H_color_21 consists of:
T_29 + T_330 + T_404 + T_442 + T_721 + T_994 + T_1154 + T_1322 + T_1458 + T_2334

Summed operator H_color_21 =
-0.0012309638542146195 [4^ 3^ 10 7] +
-0.0012309638542146195 [5^ 2^ 11 6] +
0.0012309638542146195 [6^ 5^ 11 2] +
0.0012309638542146195 [7^ 4^ 10 3] +
0.08169107751542039 [8^ 1^ 15 8] +
-2.9240424656507784 [8^ 8] +
0.027969442467558656 [9^ 0^ 13 12] +
0.0012309638542146195 [10^ 3^ 7 4] +
0.0034176355003567417 [10^ 4^ 12 0] +
-0.0012309638542146195 [10^ 7^ 4 3] +
0.0012309638542146195 [11^ 2^ 6 5] +
-0.0012309638542146195 [11^ 6^ 5 2] +
0.0034176355003567417 [12^ 0^ 10 4] +
-0.027969442467558656 [12^ 9^ 13 0] +
-0.027969442467558656 [13^ 0^ 12 9] +
0.027969442467558656 [13^ 12^ 9 0] +
-0.3763494260653101 [14^ 8^ 14 8] +
0.08169107751542039 [15^ 8^ 8 1]


,color,vertex,fermionic_term,number_of_JW_Pauli_strings,JW_transform,number_of_BK_Pauli_strings,BK_transform
0,red,T_0,-22.40891512 I,1,-22.40891512 I,1,-22.40891512 I
1,green,T_1,-4.00514475 a_0^dagger a_0,2,-2.00257238 I + +2.00257238 Z0,2,-2.00257238 I + +2.00257238 Z0
2,blue,T_2,-0.53295796 a_0^dagger a_14 + -0.53295796 a_14^dagger a_0,2,-0.26647898 X0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 X14 + -0.26647898 Y0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Y14,2,-0.26647898 X0 X1 X3 Y7 Z11 Z13 Y14 + +0.26647898 Y0 X1 X3 Y7 Z11 Z13 X14
3,brown,T_3,-4.00514475 a_1^dagger a_1,2,-2.00257238 I + +2.00257238 Z1,2,-2.00257238 I + +2.00257238 Z0 Z1
4,blue,T_4,-0.53295796 a_1^dagger a_15 + -0.53295796 a_15^dagger a_1,2,-0.26647898 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 X15 + -0.26647898 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Y15,2,+0.26647898 Z0 X1 X3 X7 Z15 + +0.26647898 Y1 X3 Y7 Z11 Z13 Z14
...,...,...,...,...,...,...,...
2408,color_86,T_2408,+0.10185535 a_14^dagger a_13^dagger a_15 a_12 + +0.10185535 a_15^dagger a_12^dagger a_14 a_13,8,-0.01273192 X12 X13 X14 X15 + -0.01273192 X12 X13 Y14 Y15 + -0.01273192 X12 Y13 X14 Y15 + +0.01273192 X12 Y13 Y14 X15 + +0.01273192 Y12 X13 X14 Y15 + -0.01273192 Y12 X13 Y14 X15 + -0.01273192 Y12 Y13 X14 X15 + -0.01273192 Y12 Y13 Y14 Y15,8,-0.01273192 X12 X14 + -0.01273192 Y12 Y14 + +0.01273192 X12 Z13 X14 + +0.01273192 Y12 Z13 Y14 + -0.01273192 Z7 Z11 X12 X14 Z15 + -0.01273192 Z7 Z11 Y12 Y14 Z15 + +0.01273192 Z7 Z11 X12 Z13 X14 Z15 + +0.01273192 Z7 Z11 Y12 Z13 Y14 Z15
2409,color_18,T_2409,-0.47820478 a_15^dagger a_12^dagger a_15 a_12,4,+0.11955119 I + -0.11955119 Z12 + -0.11955119 Z15 + +0.11955119 Z12 Z15,4,+0.11955119 I + -0.11955119 Z12 + -0.11955119 Z7 Z11 Z13 Z14 Z15 + +0.11955119 Z7 Z11 Z12 Z13 Z14 Z15
2410,color_24,T_2410,-0.47820478 a_14^dagger a_13^dagger a_14 a_13,4,+0.11955119 I + -0.11955119 Z13 + -0.11955119 Z14 + +0.11955119 Z13 Z14,4,+0.11955119 I + -0.11955119 Z14 + -0.11955119 Z12 Z13 + +0.11955119 Z12 Z13 Z14
2411,color_23,T_2411,-0.37634943 a_15^dagger a_13^dagger a_15 a_13,4,+0.09408736 I + -0.09408736 Z13 + -0.09408736 Z15 + +0.09408736 Z13 Z15,4,+0.09408736 I + -0.09408736 Z12 Z13 + +0.09408736 Z7 Z11 Z12 Z14 Z15 + -0.09408736 Z7 Z11 Z13 Z14 Z15
2412,pink,T_2412,-0.46242426 a_15^dagger a_14^dagger a_15 a_14,4,+0.11560606 I + -0.11560606 Z14 + -0.11560606 Z15 + +0.11560606 Z14 Z15,4,+0.11560606 I + -0.11560606 Z14 + +0.11560606 Z7 Z11 Z13 Z15 + -0.11560606 Z7 Z11 Z13 Z14 Z15

=== Color blocks mapped to JW and BK ===

,color_block,fermionic_vertices,number_of_fermionic_terms,number_of_JW_Pauli_strings,JW_block,number_of_BK_Pauli_strings,BK_block
0,H_red,T_0 + T_64 + T_466 + T_471 + T_905 + T_915 + T_966 + T_1020 + T_1347 + T_1679 + T_1797 + T_2295 + T_2307,13,49,-22.40891512 I + -0.01835589 X0 X1 Y14 Y15 + +0.01835589 X0 Y1 Y14 X15 + +0.01835589 Y0 X1 X14 Y15 + -0.01835589 Y0 Y1 X14 X15 + -0.00551951 X2 X3 X5 X6 + -0.00551951 X2 Y3 Y5 X6 + -0.00551951 Y2 X3 X5 Y6 + -0.00551951 Y2 Y3 Y5 Y6 + -0.00138222 X8 X9 X11 X12 + -0.00138222 X8 Y9 Y11 X12 + -0.00138222 Y8 X9 X11 Y12 + -0.00138222 Y8 Y9 Y11 Y12 + -0.00025241 X3 Z4 X5 X9 Z10 X11 + +0.00025241 X3 Z4 X5 Y9 Z10 Y11 + -0.00025241 X3 Z4 Y5 X9 Z10 Y11 + -0.00025241 X3 Z4 Y5 Y9 Z10 X11 + -0.00025241 Y3 Z4 X5 X9 Z10 Y11 + -0.00025241 Y3 Z4 X5 Y9 Z10 X11 + +0.00025241 Y3 Z4 Y5 X9 Z10 X11 + -0.00025241 Y3 Z4 Y5 Y9 Z10 Y11 + -0.00014118 X4 Z5 Z6 X7 Y10 Z11 Z12 Y13 + +0.00014118 X4 Z5 Z6 Y7 Y10 Z11 Z12 X13 + +0.00014118 Y4 Z5 Z6 X7 X10 Z11 Z12 Y13 + -0.00014118 Y4 Z5 Z6 Y7 X10 Z11 Z12 X13 + -0.00539564 X0 Z1 Z2 Z3 X4 X10 Z11 Z12 Z13 X14 + -0.00539564 X0 Z1 Z2 Z3 X4 Y10 Z11 Z12 Z13 Y14 + -0.00539564 X0 Z1 Z2 Z3 Y4 X10 Z11 Z12 Z13 Y14 + +0.00539564 X0 Z1 Z2 Z3 Y4 Y10 Z11 Z12 Z13 X14 + +0.00539564 Y0 Z1 Z2 Z3 X4 X10 Z11 Z12 Z13 Y14 + -0.00539564 Y0 Z1 Z2 Z3 X4 Y10 Z11 Z12 Z13 X14 + -0.00539564 Y0 Z1 Z2 Z3 Y4 X10 Z11 Z12 Z13 X14 + -0.00539564 Y0 Z1 Z2 Z3 Y4 Y10 Z11 Z12 Z13 Y14 + +0.00068912 X1 Z2 Z3 Z4 Z5 Z6 X7 X13 Z14 X15 + +0.00068912 X1 Z2 Z3 Z4 Z5 Z6 X7 Y13 Z14 Y15 + +0.00068912 X1 Z2 Z3 Z4 Z5 Z6 Y7 X13 Z14 Y15 + -0.00068912 X1 Z2 Z3 Z4 Z5 Z6 Y7 Y13 Z14 X15 + -0.00068912 Y1 Z2 Z3 Z4 Z5 Z6 X7 X13 Z14 Y15 + +0.00068912 Y1 Z2 Z3 Z4 Z5 Z6 X7 Y13 Z14 X15 + +0.00068912 Y1 Z2 Z3 Z4 Z5 Z6 Y7 X13 Z14 X15 + +0.00068912 Y1 Z2 Z3 Z4 Z5 Z6 Y7 Y13 Z14 Y15 + +0.00197631 X2 Z3 Z4 Z5 X6 X8 Z9 Z10 Z11 X12 + -0.00197631 X2 Z3 Z4 Z5 X6 Y8 Z9 Z10 Z11 Y12 + +0.00197631 X2 Z3 Z4 Z5 Y6 X8 Z9 Z10 Z11 Y12 + +0.00197631 X2 Z3 Z4 Z5 Y6 Y8 Z9 Z10 Z11 X12 + +0.00197631 Y2 Z3 Z4 Z5 X6 X8 Z9 Z10 Z11 Y12 + +0.00197631 Y2 Z3 Z4 Z5 X6 Y8 Z9 Z10 Z11 X12 + -0.00197631 Y2 Z3 Z4 Z5 Y6 X8 Z9 Z10 Z11 X12 + +0.00197631 Y2 Z3 Z4 Z5 Y6 Y8 Z9 Z10 Z11 Y12,49,-22.40891512 I + +0.01835589 X0 Z1 X14 + +0.01835589 Y0 Z1 Y14 + -0.00551951 X2 X5 X6 + -0.00551951 Y2 X5 Y6 + -0.00025241 X3 Y5 Y9 Z11 + -0.00138222 X8 X11 X12 X13 + -0.00138222 Y8 X11 Y12 X13 + +0.00068912 Y1 X3 Z11 Y13 Z15 + -0.00025241 X3 Z4 X5 X9 Z10 + -0.00025241 X3 Y5 Z8 Y9 Z10 + +0.00138222 X8 Z10 Y11 Y12 X13 + -0.00138222 Y8 Z10 Y11 X12 X13 + +0.01835589 X0 Z7 Z11 Z13 X14 Z15 + +0.01835589 Y0 Z7 Z11 Z13 Y14 Z15 + -0.00068912 Z0 X1 X3 Z7 X13 Z14 + -0.00068912 Y1 X3 Z7 Z12 Y13 Z14 + -0.00068912 Y1 Y3 Z5 Z6 X13 Z14 + +0.00551951 Z1 X2 Z3 Z4 Y5 Y6 + -0.00551951 Z1 Y2 Z3 Z4 Y5 X6 + +0.00025241 Z1 Z2 Y3 Y5 X9 Z10 + -0.00025241 X3 Z4 X5 Z8 X9 Z11 + +0.00068912 Z0 X1 X3 Z11 Z12 X13 Z15 + -0.00025241 Z1 Z2 Y3 Z4 X5 Y9 Z11 + +0.00025241 Z1 Z2 Y3 Y5 Z8 X9 Z11 + -0.00014118 X4 Y5 Z6 Z9 Y10 Y11 Y13 + +0.00014118 Y4 Y5 Z6 Z9 X10 Y11 Y13 + +0.00068912 Z0 X1 Y3 Z5 Z6 Z12 Y13 Z14 + -0.00025241 Z1 Z2 Y3 Z4 X5 Z8 Y9 Z10 + -0.00068912 Z0 X1 Y3 Z5 Z6 Z7 Z11 Y13 Z15 + +0.00068912 Y1 Y3 Z5 Z6 Z7 Z11 Z12 X13 Z15 + -0.00014118 Z3 X4 X5 Z7 Z9 Y10 Y11 Z12 X13 + +0.00014118 Z3 Y4 X5 Z7 Z9 X10 Y11 Z12 X13 + -0.00539564 X0 X1 Y3 X4 X5 Z9 X10 Y11 Z13 X14 + -0.00539564 X0 X1 Y3 X4 X5 Z9 Y10 Y11 Z13 Y14 + -0.00539564 X0 X1 Y3 Y4 X5 Z9 X10 Y11 Z13 Y14 + +0.00539564 X0 X1 Y3 Y4 X5 Z9 Y10 Y11 Z13 X14 + +0.00539564 Y0 X1 Y3 X4 X5 Z9 X10 Y11 Z13 Y14 + -0.00539564 Y0 X1 Y3 X4 X5 Z9 Y10 Y11 Z13 X14 + -0.00539564 Y0 X1 Y3 Y4 X5 Z9 X10 Y11 Z13 X14 + -0.00539564 Y0 X1 Y3 Y4 X5 Z9 Y10 Y11 Z13 Y14 + +0.00197631 Z1 X2 Y3 Z5 X6 X8 X9 Y11 X12 X13 + -0.00197631 Z1 X2 Y3 Z5 X6 Y8 X9 Y11 Y12 X13 + +0.00197631 Z1 X2 Y3 Z5 Y6 X8 X9 Y11 Y12 X13 + +0.00197631 Z1 X2 Y3 Z5 Y6 Y8 X9 Y11 X12 X13 + +0.00197631 Z1 Y2 Y3 Z5 X6 X8 X9 Y11 Y12 X13 + +0.00197631 Z1 Y2 Y3 Z5 X6 Y8 X9 Y11 X12 X13 + -0.00197631 Z1 Y2 Y3 Z5 Y6 X8 X9 Y11 X12 X13 + +0.00197631 Z1 Y2 Y3 Z5 Y6 Y8 X9 Y11 Y12 X13
1,H_blue,T_2 + T_4 + T_470 + T_901 + T_921 + T_962 + T_1022 + T_1398 + T_1878 + T_1980 + T_2298 + T_2321,12,48,-0.00014118 X5 X6 Y11 Y12 + +0.00014118 X5 Y6 Y11 X12 + +0.00014118 Y5 X6 X11 Y12 + -0.00014118 Y5 Y6 X11 X12 + -0.00551951 X2 X3 Y4 Z5 Z6 Y7 + +0.00551951 X2 Y3 Y4 Z5 Z6 X7 + -0.00025241 X2 Z3 X4 X8 Z9 X10 + +0.00025241 X2 Z3 X4 Y8 Z9 Y10 + -0.00025241 X2 Z3 Y4 X8 Z9 Y10 + -0.00025241 X2 Z3 Y4 Y8 Z9 X10 + +0.00551951 Y2 X3 X4 Z5 Z6 Y7 + -0.00551951 Y2 Y3 X4 Z5 Z6 X7 + -0.00025241 Y2 Z3 X4 X8 Z9 Y10 + -0.00025241 Y2 Z3 X4 Y8 Z9 X10 + +0.00025241 Y2 Z3 Y4 X8 Z9 X10 + -0.00025241 Y2 Z3 Y4 Y8 Z9 Y10 + -0.00138222 X8 X9 Y10 Z11 Z12 Y13 + +0.00138222 X8 Y9 Y10 Z11 Z12 X13 + +0.00138222 Y8 X9 X10 Z11 Z12 Y13 + -0.00138222 Y8 Y9 X10 Z11 Z12 X13 + +0.00068912 X0 Z1 Z2 Z3 Z4 Z5 X6 X12 Z13 X14 + +0.00068912 X0 Z1 Z2 Z3 Z4 Z5 X6 Y12 Z13 Y14 + +0.00068912 X0 Z1 Z2 Z3 Z4 Z5 Y6 X12 Z13 Y14 + -0.00068912 X0 Z1 Z2 Z3 Z4 Z5 Y6 Y12 Z13 X14 + -0.00068912 Y0 Z1 Z2 Z3 Z4 Z5 X6 X12 Z13 Y14 + +0.00068912 Y0 Z1 Z2 Z3 Z4 Z5 X6 Y12 Z13 X14 + +0.00068912 Y0 Z1 Z2 Z3 Z4 Z5 Y6 X12 Z13 X14 + +0.00068912 Y0 Z1 Z2 Z3 Z4 Z5 Y6 Y12 Z13 Y14 + -0.00539564 X1 Z2 Z3 Z4 X5 X11 Z12 Z13 Z14 X15 + -0.00539564 X1 Z2 Z3 Z4 X5 Y11 Z12 Z13 Z14 Y15 + -0.00539564 X1 Z2 Z3 Z4 Y5 X11 Z12 Z13 Z14 Y15 + +0.00539564 X1 Z2 Z3 Z4 Y5 Y11 Z12 Z13 Z14 X15 + +0.00539564 Y1 Z2 Z3 Z4 X5 X11 Z12 Z13 Z14 Y15 + -0.00539564 Y1 Z2 Z3 Z4 X5 Y11 Z12 Z13 Z14 X15 + -0.00539564 Y1 Z2 Z3 Z4 Y5 X11 Z12 Z13 Z14 X15 + -0.00539564 Y1 Z2 Z3 Z4 Y5 Y11 Z12 Z13 Z14 Y15 + +0.00197631 X3 Z4 Z5 Z6 X7 X9 Z10 Z11 Z12 X13 + -0.00197631 X3 Z4 Z5 Z6 X7 Y9 Z10 Z11 Z12 Y13 + +0.00197631 X3 Z4 Z5 Z6 Y7 X9 Z10 Z11 Z12 Y13 + +0.00197631 X3 Z4 Z5 Z6 Y7 Y9 Z10 Z11 Z12 X13 + +0.00197631 Y3 Z4 Z5 Z6 X7 X9 Z10 Z11 Z12 Y13 + +0.00197631 Y3 Z4 Z5 Z6 X7 Y9 Z10 Z11 Z12 X13 + -0.00197631 Y3 Z4 Z5 Z6 Y7 X9 Z10 Z11 Z12 X13 + +0.00197631 Y3 Z4 Z5 Z6 Y7 Y9 Z10 Z11 Z12 Y13 + -0.26647898 X0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 X14 + -0.26647898 Y0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Y14 + -0.26647898 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 X15 + -0.26647898 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Y15,48,+0.26647898 Z0 X1 X3 X7 Z15 + +0.00551951 X2 Z3 X4 X5 Z7 + +0.00551951 Y2 Z3 Y4 X5 Z7 + -0.00197631 Y3 Z7 Y9 Y11 Y13 + -0.00138222 X8 Z9 X10 Y11 Y13 + -0.00138222 X8 Y10 Y11 Z12 X13 + -0.00138222 Y8 Z9 Y10 Y11 Y13 + +0.00138222 Y8 X10 Y11 Z12 X13 + +0.26647898 Y1 X3 Y7 Z11 Z13 Z14 + +0.00539564 Y1 Y3 Y5 Z7 Y11 Z15 + -0.00551951 Z1 X2 Z3 Y4 Y5 Z6 + +0.00551951 Z1 Y2 Z3 X4 Y5 Z6 + +0.00014118 Z4 Y5 X6 X11 Y12 X13 + -0.00014118 Z4 Y5 Y6 X11 X12 X13 + -0.26647898 X0 X1 X3 Y7 Z11 Z13 Y14 + +0.26647898 Y0 X1 X3 Y7 Z11 Z13 X14 + -0.00539564 Z0 X1 Y3 Y5 X11 Z13 Z14 + +0.00539564 Y1 Y3 Z4 X5 X11 Z13 Z14 + -0.00197631 X3 Z5 Z6 Z8 X9 Y11 Y13 + -0.00197631 X3 Z5 Z6 Y9 Y11 Z12 X13 + +0.00197631 Y3 Z7 Z8 X9 Y11 Z12 X13 + -0.00014118 X5 X6 Z9 Z10 Y11 Y12 X13 + +0.00014118 X5 Y6 Z9 Z10 Y11 X12 X13 + +0.00068912 X0 X1 Y3 Z5 X6 X12 Y13 X14 + +0.00068912 X0 X1 Y3 Z5 X6 Y12 Y13 Y14 + +0.00068912 X0 X1 Y3 Z5 Y6 X12 Y13 Y14 + -0.00068912 X0 X1 Y3 Z5 Y6 Y12 Y13 X14 + -0.00068912 Y0 X1 Y3 Z5 X6 X12 Y13 Y14 + +0.00068912 Y0 X1 Y3 Z5 X6 Y12 Y13 X14 + +0.00068912 Y0 X1 Y3 Z5 Y6 X12 Y13 X14 + +0.00068912 Y0 X1 Y3 Z5 Y6 Y12 Y13 Y14 + +0.00539564 Z0 X1 Y3 Z4 X5 Z7 Y11 Z15 + -0.00539564 Y1 Y3 Y5 Z9 Z10 Y11 Z13 Z14 + -0.00025241 Z1 X2 Y3 X4 X5 X8 Y9 X10 + +0.00025241 Z1 X2 Y3 X4 X5 Y8 Y9 Y10 + -0.00025241 Z1 X2 Y3 Y4 X5 X8 Y9 Y10 + -0.00025241 Z1 X2 Y3 Y4 X5 Y8 Y9 X10 + -0.00025241 Z1 Y2 Y3 X4 X5 X8 Y9 Y10 + -0.00025241 Z1 Y2 Y3 X4 X5 Y8 Y9 X10 + +0.00025241 Z1 Y2 Y3 Y4 X5 X8 Y9 X10 + -0.00025241 Z1 Y2 Y3 Y4 X5 Y8 Y9 Y10 + -0.00197631 Z1 Z2 X3 Z7 Z8 X9 Y11 Y13 + -0.00197631 Z1 Z2 X3 Z7 Y9 Y11 Z12 X13 + -0.00197631 Z1 Z2 Y3 Z5 Z6 Y9 Y11 Y13 + +0.00539564 Z0 X1 Y3 Y5 Z7 Z9 Z10 X11 Z15 + -0.00539564 Y1 Y3 Z4 X5 Z7 Z9 Z10 X11 Z15 + -0.00539564 Z0 X1 Y3 Z4 X5 Z9 Z10 Y11 Z13 Z14 + +0.00197631 Z1 Z2 Y3 Z5 Z6 Z8 X9 Y11 Z12 X13
2,H_green,T_1 + T_35 + T_63 + T_461 + T_895 + T_897 + T_955 + T_979 + T_1028 + T_1380 + T_1520 + T_1895 + T_2135 + T_2305 + T_2314 + T_2324,16,47,-2.95319831 I + +1.90326229 Z0 + -0.10134886 Z2 + -0.10134886 Z4 + -0.10605185 Z6 + -0.11011365 Z8 + -0.11011365 Z10 + -0.10605185 Z12 + +1.26814030 Z14 + +0.09931008 Z0 Z14 + +0.10134886 Z2 Z4 + +0.10605185 Z6 Z12 + +0.11011365 Z8 Z10 + +0.00127591 X2 Z3 X4 X5 Z6 X7 + +0.00127591 X2 Z3 X4 Y5 Z6 Y7 + +0.00127591 Y2 Z3 Y4 X5 Z6 X7 + +0.00127591 Y2 Z3 Y4 Y5 Z6 Y7 + -0.00052753 X5 Z6 X7 X11 Z12 X13 + +0.00052753 X5 Z6 X7 Y11 Z12 Y13 + -0.00052753 X5 Z6 Y7 X11 Z12 Y13 + -0.00052753 X5 Z6 Y7 Y11 Z12 X13 + -0.00052753 Y5 Z6 X7 X11 Z12 Y13 + -0.00052753 Y5 Z6 X7 Y11 Z12 X13 + +0.00052753 Y5 Z6 Y7 X11 Z12 X13 + -0.00052753 Y5 Z6 Y7 Y11 Z12 Y13 + -0.00116517 X8 Z9 X10 X11 Z12 X13 + -0.00116517 X8 Z9 X10 Y11 Z12 Y13 + -0.00116517 Y8 Z9 Y10 X11 Z12 X13 + -0.00116517 Y8 Z9 Y10 Y11 Z12 Y13 + +0.00667147 X3 Z4 Z5 X6 Y9 Z10 Z11 Y12 + -0.00667147 X3 Z4 Z5 Y6 Y9 Z10 Z11 X12 + -0.00667147 Y3 Z4 Z5 X6 X9 Z10 Z11 Y12 + +0.00667147 Y3 Z4 Z5 Y6 X9 Z10 Z11 X12 + +0.00144023 X1 Z2 X3 X9 Z10 Z11 Z12 Z13 Z14 X15 + +0.00144023 X1 Z2 X3 Y9 Z10 Z11 Z12 Z13 Z14 Y15 + +0.00144023 X1 Z2 Y3 X9 Z10 Z11 Z12 Z13 Z14 Y15 + -0.00144023 X1 Z2 Y3 Y9 Z10 Z11 Z12 Z13 Z14 X15 + -0.00144023 Y1 Z2 X3 X9 Z10 Z11 Z12 Z13 Z14 Y15 + +0.00144023 Y1 Z2 X3 Y9 Z10 Z11 Z12 Z13 Z14 X15 + +0.00144023 Y1 Z2 Y3 X9 Z10 Z11 Z12 Z13 Z14 X15 + +0.00144023 Y1 Z2 Y3 Y9 Z10 Z11 Z12 Z13 Z14 Y15 + -0.01647029 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 X15 + -0.01647029 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Y15 + +0.03838582 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 X15 + +0.03838582 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Y15 + -0.02191553 Z0 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 X15 + -0.02191553 Z0 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Y15,47,-2.95319831 I + +1.90326229 Z0 + -0.10134886 Z2 + -0.10134886 Z4 + -0.10605185 Z6 + -0.11011365 Z8 + -0.11011365 Z10 + -0.10605185 Z12 + +1.26814030 Z14 + +0.09931008 Z0 Z14 + +0.10134886 Z2 Z4 + +0.10605185 Z6 Z12 + +0.11011365 Z8 Z10 + +0.02191553 X1 X3 X7 Z15 + -0.03838582 Z0 X1 X3 X7 Z15 + +0.01647029 Y1 X3 Y7 Z11 Z13 + +0.00127591 Z1 X2 X3 X4 Z7 + +0.00127591 Z1 X2 Y3 Y4 Z6 + +0.00127591 Z1 Y2 X3 Y4 Z7 + -0.00127591 Z1 Y2 Y3 X4 Z6 + -0.00052753 Z3 Y5 Z7 X11 Y13 + -0.00052753 Z4 Y5 Z6 X11 Y13 + -0.00052753 X5 Z6 X11 Z12 X13 + +0.00116517 X8 X9 X10 Y11 Y13 + +0.00116517 Y8 X9 Y10 Y11 Y13 + +0.01647029 Z0 X1 X3 X7 Z14 Z15 + -0.00144023 X1 Z2 Y9 Y11 Z13 Z14 + -0.03838582 Y1 X3 Y7 Z11 Z13 Z14 + +0.00144023 Y1 Z3 Z7 Y9 X11 Z15 + +0.00052753 X5 Z6 Z9 Z10 Y11 Y13 + -0.00116517 X8 Y9 Y10 X11 Z12 X13 + +0.00116517 Y8 Y9 X10 X11 Z12 X13 + +0.00144023 Z0 X1 Z3 Y9 Y11 Z13 Z14 + -0.00144023 Z0 Y1 Z2 Z7 Y9 X11 Z15 + +0.02191553 Z0 Y1 X3 Y7 Z11 Z13 Z14 + -0.00144023 X1 Z2 Z7 Z8 X9 X11 Z15 + -0.00144023 Y1 Z3 Z8 X9 Y11 Z13 Z14 + -0.00052753 Z3 Z4 X5 Z7 X11 Z12 X13 + +0.00144023 Z0 X1 Z3 Z7 Z8 X9 X11 Z15 + +0.00144023 Z0 Y1 Z2 Z8 X9 Y11 Z13 Z14 + +0.00667147 X3 Z5 X6 Z8 X9 Y11 Y12 X13 + -0.00667147 X3 Z5 Y6 Z8 X9 Y11 X12 X13 + +0.00052753 Z3 Z4 X5 Z7 Z9 Z10 Y11 Y13 + -0.00052753 Z3 Y5 Z7 Z9 Z10 Y11 Z12 X13 + -0.00052753 Z4 Y5 Z6 Z9 Z10 Y11 Z12 X13 + +0.00667147 Z1 Z2 Y3 Z5 X6 Y9 Y11 Y12 X13 + -0.00667147 Z1 Z2 Y3 Z5 Y6 Y9 Y11 X12 X13
3,H_orange,T_463 + T_903 + T_1045 + T_1100 + T_1307 + T_1349 + T_1350 + T_1651 + T_2315 + T_2325,10,44,-0.00127591 X3 X4 Y5 Y6 + +0.00127591 X3 Y4 Y5 X6 + +0.00127591 Y3 X4 X5 Y6 + -0.00127591 Y3 Y4 X5 X6 + +0.00197908 X3 Z4 X5 X11 Z12 X13 + -0.00197908 X3 Z4 X5 Y11 Z12 Y13 + +0.00197908 X3 Z4 Y5 X11 Z12 Y13 + +0.00197908 X3 Z4 Y5 Y11 Z12 X13 + +0.00197908 Y3 Z4 X5 X11 Z12 Y13 + +0.00197908 Y3 Z4 X5 Y11 Z12 X13 + -0.00197908 Y3 Z4 Y5 X11 Z12 X13 + +0.00197908 Y3 Z4 Y5 Y11 Z12 Y13 + -0.00202204 X8 Z9 Z10 X11 Y12 Y13 + +0.00202204 X8 Z9 Z10 Y11 Y12 X13 + +0.00202204 Y8 Z9 Z10 X11 X12 Y13 + -0.00202204 Y8 Z9 Z10 Y11 X12 X13 + +0.00074595 X0 Z1 X2 X10 Z11 Z12 Z13 X14 + +0.00074595 X0 Z1 X2 Y10 Z11 Z12 Z13 Y14 + +0.00074595 X0 Z1 Y2 X10 Z11 Z12 Z13 Y14 + -0.00074595 X0 Z1 Y2 Y10 Z11 Z12 Z13 X14 + -0.00074595 Y0 Z1 X2 X10 Z11 Z12 Z13 Y14 + +0.00074595 Y0 Z1 X2 Y10 Z11 Z12 Z13 X14 + +0.00074595 Y0 Z1 Y2 X10 Z11 Z12 Z13 X14 + +0.00074595 Y0 Z1 Y2 Y10 Z11 Z12 Z13 Y14 + +0.00070786 X2 Z3 Z4 Z5 Z6 X7 X9 X10 + +0.00070786 X2 Z3 Z4 Z5 Z6 Y7 Y9 X10 + +0.00070786 Y2 Z3 Z4 Z5 Z6 X7 X9 Y10 + +0.00070786 Y2 Z3 Z4 Z5 Z6 Y7 Y9 Y10 + +0.00027322 X4 Z5 X6 X8 Z9 Z10 Z11 X12 + -0.00027322 X4 Z5 X6 Y8 Z9 Z10 Z11 Y12 + +0.00027322 X4 Z5 Y6 X8 Z9 Z10 Z11 Y12 + +0.00027322 X4 Z5 Y6 Y8 Z9 Z10 Z11 X12 + +0.00027322 Y4 Z5 X6 X8 Z9 Z10 Z11 Y12 + +0.00027322 Y4 Z5 X6 Y8 Z9 Z10 Z11 X12 + -0.00027322 Y4 Z5 Y6 X8 Z9 Z10 Z11 X12 + +0.00027322 Y4 Z5 Y6 Y8 Z9 Z10 Z11 Y12 + -0.00540320 X1 Z2 Z3 Z4 Z5 Z6 X7 X9 Z10 Z11 Z12 Z13 Z14 X15 + -0.00540320 X1 Z2 Z3 Z4 Z5 Z6 X7 Y9 Z10 Z11 Z12 Z13 Z14 Y15 + -0.00540320 X1 Z2 Z3 Z4 Z5 Z6 Y7 X9 Z10 Z11 Z12 Z13 Z14 Y15 + +0.00540320 X1 Z2 Z3 Z4 Z5 Z6 Y7 Y9 Z10 Z11 Z12 Z13 Z14 X15 + +0.00540320 Y1 Z2 Z3 Z4 Z5 Z6 X7 X9 Z10 Z11 Z12 Z13 Z14 Y15 + -0.00540320 Y1 Z2 Z3 Z4 Z5 Z6 X7 Y9 Z10 Z11 Z12 Z13 Z14 X15 + -0.00540320 Y1 Z2 Z3 Z4 Z5 Z6 Y7 X9 Z10 Z11 Z12 Z13 Z14 X15 + -0.00540320 Y1 Z2 Z3 Z4 Z5 Z6 Y7 Y9 Z10 Z11 Z12 Z13 Z14 Y15,44,-0.00127591 X3 X4 Z5 X6 + -0.00127591 X3 Y4 Z5 Y6 + +0.00197908 X3 Y5 X11 Y13 + +0.00202204 X8 X9 Z11 X12 + +0.00202204 Y8 X9 Z11 Y12 + -0.00540320 Y1 X3 Y9 X11 Z15 + +0.00127591 Z1 Z2 Y3 X4 Y6 + -0.00127591 Z1 Z2 Y3 Y4 X6 + +0.00202204 X8 Y9 Z10 Y12 Z13 + -0.00202204 Y8 Y9 Z10 X12 Z13 + +0.00197908 X3 Z4 X5 X11 Z12 X13 + -0.00540320 Z0 X1 X3 Z8 X9 X11 Z15 + -0.00070786 Z1 X2 X3 Z7 Z8 Y9 Y10 + +0.00070786 Z1 X2 Y3 Z5 Z6 X9 Y10 + +0.00070786 Z1 Y2 X3 Z7 Z8 Y9 X10 + -0.00070786 Z1 Y2 Y3 Z5 Z6 X9 X10 + +0.00197908 Z1 Z2 Y3 Z4 X5 X11 Y13 + -0.00197908 Z1 Z2 Y3 Y5 X11 Z12 X13 + -0.00197908 X3 Z4 X5 Z9 Z10 Y11 Y13 + +0.00197908 X3 Y5 Z9 Z10 Y11 Z12 X13 + +0.00074595 X0 Y1 X2 Z9 X10 Y11 Z13 X14 + +0.00074595 X0 Y1 X2 Z9 Y10 Y11 Z13 Y14 + +0.00074595 X0 Y1 Y2 Z9 X10 Y11 Z13 Y14 + -0.00074595 X0 Y1 Y2 Z9 Y10 Y11 Z13 X14 + -0.00074595 Y0 Y1 X2 Z9 X10 Y11 Z13 Y14 + +0.00074595 Y0 Y1 X2 Z9 Y10 Y11 Z13 X14 + +0.00074595 Y0 Y1 Y2 Z9 X10 Y11 Z13 X14 + +0.00074595 Y0 Y1 Y2 Z9 Y10 Y11 Z13 Y14 + -0.00540320 Z0 X1 X3 Z7 Y9 Y11 Z13 Z14 + +0.00540320 Y1 X3 Z7 Z8 X9 Y11 Z13 Z14 + -0.00540320 Y1 Y3 Z5 Z6 Y9 Y11 Z13 Z14 + +0.00197908 Z1 Z2 Y3 Y5 Z9 Z10 Y11 Y13 + +0.00027322 X4 Y5 X6 X8 X9 Y11 X12 X13 + -0.00027322 X4 Y5 X6 Y8 X9 Y11 Y12 X13 + +0.00027322 X4 Y5 Y6 X8 X9 Y11 Y12 X13 + +0.00027322 X4 Y5 Y6 Y8 X9 Y11 X12 X13 + +0.00027322 Y4 Y5 X6 X8 X9 Y11 Y12 X13 + +0.00027322 Y4 Y5 X6 Y8 X9 Y11 X12 X13 + -0.00027322 Y4 Y5 Y6 X8 X9 Y11 X12 X13 + +0.00027322 Y4 Y5 Y6 Y8 X9 Y11 Y12 X13 + +0.00540320 Z0 X1 Y3 Z5 Z6 Z7 Y9 X11 Z15 + -0.00540320 Y1 Y3 Z5 Z6 Z7 Z8 X9 X11 Z15 + -0.00540320 Z0 X1 Y3 Z5 Z6 Z8 X9 Y11 Z13 Z14 + +0.00197908 Z1 Z2 Y3 Z4 X5 Z9 Z10 Y11 Z12 X13
4,H_purple,T_465 + T_899 + T_980 + T_1021 + T_1029 + T_1318 + T_1404 + T_1893 + T_2348 + T_2355,10,44,+0.00116517 X9 X10 Y11 Y12 + -0.00116517 X9 Y10 Y11 X12 + -0.00116517 Y9 X10 X11 Y12 + +0.00116517 Y9 Y10 X11 X12 + +0.00670698 X1 Z2 X3 X13 Z14 X15 + +0.00670698 X1 Z2 X3 Y13 Z14 Y15 + +0.00670698 X1 Z2 Y3 X13 Z14 Y15 + -0.00670698 X1 Z2 Y3 Y13 Z14 X15 + -0.00670698 Y1 Z2 X3 X13 Z14 Y15 + +0.00670698 Y1 Z2 X3 Y13 Z14 X15 + +0.00670698 Y1 Z2 Y3 X13 Z14 X15 + +0.00670698 Y1 Z2 Y3 Y13 Z14 Y15 + -0.00011199 X2 Z3 Z4 X5 Y6 Y7 + +0.00011199 X2 Z3 Z4 Y5 Y6 X7 + +0.00011199 Y2 Z3 Z4 X5 X6 Y7 + -0.00011199 Y2 Z3 Z4 Y5 X6 X7 + -0.00245663 X5 Z6 X7 X9 Z10 X11 + +0.00245663 X5 Z6 X7 Y9 Z10 Y11 + -0.00245663 X5 Z6 Y7 X9 Z10 Y11 + -0.00245663 X5 Z6 Y7 Y9 Z10 X11 + -0.00245663 Y5 Z6 X7 X9 Z10 Y11 + -0.00245663 Y5 Z6 X7 Y9 Z10 X11 + +0.00245663 Y5 Z6 Y7 X9 Z10 X11 + -0.00245663 Y5 Z6 Y7 Y9 Z10 Y11 + -0.00148085 X2 Z3 Z4 Z5 X6 X10 Z11 X12 + +0.00148085 X2 Z3 Z4 Z5 X6 Y10 Z11 Y12 + -0.00148085 X2 Z3 Z4 Z5 Y6 X10 Z11 Y12 + -0.00148085 X2 Z3 Z4 Z5 Y6 Y10 Z11 X12 + -0.00148085 Y2 Z3 Z4 Z5 X6 X10 Z11 Y12 + -0.00148085 Y2 Z3 Z4 Z5 X6 Y10 Z11 X12 + +0.00148085 Y2 Z3 Z4 Z5 Y6 X10 Z11 X12 + -0.00148085 Y2 Z3 Z4 Z5 Y6 Y10 Z11 Y12 + +0.01009068 X3 X4 X8 Z9 Z10 Z11 Z12 X13 + +0.01009068 X3 Y4 Y8 Z9 Z10 Z11 Z12 X13 + +0.01009068 Y3 X4 X8 Z9 Z10 Z11 Z12 Y13 + +0.01009068 Y3 Y4 Y8 Z9 Z10 Z11 Z12 Y13 + -0.00404296 X0 Z1 Z2 Z3 X4 X8 Z9 Z10 Z11 Z12 Z13 X14 + -0.00404296 X0 Z1 Z2 Z3 X4 Y8 Z9 Z10 Z11 Z12 Z13 Y14 + -0.00404296 X0 Z1 Z2 Z3 Y4 X8 Z9 Z10 Z11 Z12 Z13 Y14 + +0.00404296 X0 Z1 Z2 Z3 Y4 Y8 Z9 Z10 Z11 Z12 Z13 X14 + +0.00404296 Y0 Z1 Z2 Z3 X4 X8 Z9 Z10 Z11 Z12 Z13 Y14 + -0.00404296 Y0 Z1 Z2 Z3 X4 Y8 Z9 Z10 Z11 Z12 Z13 X14 + -0.00404296 Y0 Z1 Z2 Z3 Y4 X8 Z9 Z10 Z11 Z12 Z13 X14 + -0.00404296 Y0 Z1 Z2 Z3 Y4 Y8 Z9 Z10 Z11 Z12 Z13 Y14,44,+0.00670698 X1 Z2 X13 Z14 + -0.00245663 X5 Z6 X9 Z10 + -0.00670698 Z0 X1 Z3 X13 Z14 + -0.00670698 Y1 Z3 Z12 Y13 Z14 + -0.00011199 Z1 X2 Y3 Y5 X6 + -0.00011199 Z1 Y2 Y3 Y5 Y6 + -0.00245663 Z3 Y5 Z7 Y9 Z11 + -0.00245663 Z4 Y5 Z6 Y9 Z11 + -0.00245663 X5 Z6 Z8 X9 Z11 + -0.00116517 Y9 X10 Y11 X12 X13 + -0.00116517 Y9 Y10 Y11 Y12 X13 + +0.00670698 Z0 Y1 Z2 Z12 Y13 Z14 + +0.00670698 Y1 Z3 Z7 Z11 Y13 Z15 + -0.00245663 Z3 Z4 X5 Z7 X9 Z10 + -0.00245663 Z3 Y5 Z7 Z8 Y9 Z10 + -0.00245663 Z4 Y5 Z6 Z8 Y9 Z10 + -0.00116517 Z8 Y9 X10 X11 Y12 X13 + +0.00116517 Z8 Y9 Y10 X11 X12 X13 + -0.00670698 Z0 Y1 Z2 Z7 Z11 Y13 Z15 + -0.00670698 X1 Z2 Z7 Z11 Z12 X13 Z15 + +0.00011199 Z1 X2 X3 Z4 Y5 Y6 Z7 + -0.00011199 Z1 Y2 X3 Z4 Y5 X6 Z7 + -0.00245663 Z3 Z4 X5 Z7 Z8 X9 Z11 + +0.00670698 Z0 X1 Z3 Z7 Z11 Z12 X13 Z15 + -0.01009068 X3 X4 X5 Y8 X9 Y11 Z12 X13 + +0.01009068 X3 Y4 X5 X8 X9 Y11 Z12 X13 + -0.01009068 Z1 Z2 Y3 X4 X5 Y8 X9 Y11 Y13 + +0.01009068 Z1 Z2 Y3 Y4 X5 X8 X9 Y11 Y13 + -0.00404296 X0 X1 Y3 X4 X5 X8 X9 Y11 Z13 X14 + -0.00404296 X0 X1 Y3 X4 X5 Y8 X9 Y11 Z13 Y14 + -0.00404296 X0 X1 Y3 Y4 X5 X8 X9 Y11 Z13 Y14 + +0.00404296 X0 X1 Y3 Y4 X5 Y8 X9 Y11 Z13 X14 + +0.00404296 Y0 X1 Y3 X4 X5 X8 X9 Y11 Z13 Y14 + -0.00404296 Y0 X1 Y3 X4 X5 Y8 X9 Y11 Z13 X14 + -0.00404296 Y0 X1 Y3 Y4 X5 X8 X9 Y11 Z13 X14 + -0.00404296 Y0 X1 Y3 Y4 X5 Y8 X9 Y11 Z13 Y14 + -0.00148085 Z1 X2 Y3 Z5 X6 Z9 X10 Y11 X12 X13 + +0.00148085 Z1 X2 Y3 Z5 X6 Z9 Y10 Y11 Y12 X13 + -0.00148085 Z1 X2 Y3 Z5 Y6 Z9 X10 Y11 Y12 X13 + -0.00148085 Z1 X2 Y3 Z5 Y6 Z9 Y10 Y11 X12 X13 + -0.00148085 Z1 Y2 Y3 Z5 X6 Z9 X10 Y11 Y12 X13 + -0.00148085 Z1 Y2 Y3 Z5 X6 Z9 Y10 Y11 X12 X13 + +0.00148085 Z1 Y2 Y3 Z5 Y6 Z9 X10 Y11 X12 X13 + -0.00148085 Z1 Y2 Y3 Z5 Y6 Z9 Y10 Y11 Y12 X13
...,...,...,...,...,...,...,...
262,H_color_262,T_619 + T_784 + T_1543 + T_1551 + T_1780 + T_1816,6,18,-0.00097739 X12 Z13 X14 + -0.00097739 Y12 Z13 Y14 + -0.00104306 X13 Z14 X15 + -0.00104306 Y13 Z14 Y15 + +0.00058279 Z3 X12 Z13 X14 + +0.00058279 Z3 Y12 Z13 Y14 + +0.00031653 Z3 X13 Z14 X15 + +0.00031653 Z3 Y13 Z14 Y15 + +0.00039460 Z4 X12 Z13 X14 + +0.00039460 Z4 Y12 Z13 Y14 + +0.00072654 Z4 X13 Z14 X15 + +0.00072654 Z4 Y13 Z14 Y15 + -0.00507494 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 X11 + +0.00856977 X1 Z2 Z3 Z4 Z6 Z7 Z8 Z9 Z10 X11 + -0.00507494 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Y11 + +0.00856977 Y1 Z2 Z3 Z4 Z6 Z7 Z8 Z9 Z10 Y11 + -0.00349483 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 X11 + -0.00349483 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Y11,18,-0.00104306 X13 Z14 + +0.00072654 Z4 X13 Z14 + -0.00097739 X12 Y13 Y14 + +0.00097739 Y12 Y13 X14 + +0.00039460 Z4 X12 Y13 Y14 + -0.00039460 Z4 Y12 Y13 X14 + -0.00349483 Z0 X1 X3 Y7 Y11 + +0.00507494 Y1 X3 Y7 Z9 X11 + +0.00031653 Z1 Z2 Z3 X13 Z14 + +0.00104306 Z7 Z11 Z12 X13 Z15 + -0.00507494 Z0 X1 X3 Y7 Z10 Y11 + +0.00349483 Y1 X3 Y7 Z9 Z10 X11 + +0.00058279 Z1 Z2 Z3 X12 Y13 Y14 + -0.00058279 Z1 Z2 Z3 Y12 Y13 X14 + -0.00072654 Z4 Z7 Z11 Z12 X13 Z15 + +0.00856977 Z0 X1 X3 Z4 Z5 Y7 Y11 + -0.00856977 Y1 X3 Z4 Z5 Y7 Z9 Z10 X11 + -0.00031653 Z1 Z2 Z3 Z7 Z11 Z12 X13 Z15

=== Verify commuting groups after JW/BK mapping ===

      color_group           pair  fermionic_commute  JW_commute  BK_commute
0             red      T_0, T_64               True        True        True
1             red     T_0, T_466               True        True        True
2             red     T_0, T_471               True        True        True
3             red     T_0, T_905               True        True        True
4             red     T_0, T_915               True        True        True
...           ...            ...                ...         ...         ...
10588   color_265   T_751, T_869               True        True        True
10589   color_265  T_751, T_2404               True        True        True
10590   color_265   T_810, T_869               True        True        True
10591   color_265  T_810, T_2404               True        True        True
10592   color_265  T_869, T_2404               True        True        True

[10593 rows x 5 columns]

In [16]:
# Find duplicated JW Pauli strings across fermionic terms T_i

from collections import defaultdict
import pandas as pd

pauli_usage = defaultdict(list)

for node in sorted(G.nodes()):
    JW_T = G.nodes[node]["JW_operator"]

    for pauli_key, coeff in JW_T.terms.items():
        pauli_string = format_qubit_term(pauli_key)

        pauli_usage[pauli_string].append(
            {
                "vertex": f"T_{node}",
                "coefficient": coeff,
                "fermionic_term": G.nodes[node]["operator_string"],
            }
        )

duplicate_rows = []

for pauli_string, appearances in pauli_usage.items():
    if len(appearances) > 1:
        duplicate_rows.append(
            {
                "JW_Pauli_string": pauli_string,
                "number_of_appearances": len(appearances),
                "appears_in_vertices": [x["vertex"] for x in appearances],
                "coefficients": [x["coefficient"] for x in appearances],
            }
        )

duplicate_jw_df = pd.DataFrame(duplicate_rows)
duplicate_jw_df = duplicate_jw_df.sort_values(
    "number_of_appearances",
    ascending=False
).reset_index(drop=True)

print("Total JW Pauli-string appearances:", sum(len(G.nodes[node]["JW_operator"].terms) for node in G.nodes()))
print("Number of unique JW Pauli strings:", len(pauli_usage))
print("Number of duplicated JW Pauli strings:", len(duplicate_jw_df))

display(duplicate_jw_df)

Total JW Pauli-string appearances: 16185
Number of unique JW Pauli strings: 7921
Number of duplicated JW Pauli strings: 6593

,JW_Pauli_string,number_of_appearances,appears_in_vertices,coefficients
0,I,137,"[T_0, T_1, T_3, T_5, T_9, T_13, T_17, T_21, T_25, T_29, T_30, T_31, T_32, T_33, T_34, T_35, T_36, T_37, T_65, T_86, T_134, T_161, T_203, T_236, T_272, T_311, T_335, T_380, T_398, T_449, T_461, T_496, T_498, T_546, T_569, T_611, T_640, T_676, T_714, T_738, T_779, T_797, T_844, T_856, T_894, T_896, T_906, T_955, T_971, T_1012, T_1034, T_1068, T_1103, T_1131, T_1171, T_1192, T_1237, T_1251, T_1295, T_1299, T_1340, T_1356, T_1390, T_1412, T_1440, T_1475, T_1496, T_1536, T_1550, T_1593, T_1597, T_1607, T_1643, T_1658, T_1687, T_1710, T_1734, T_1761, T_1779, T_1810, T_1822, T_1853, T_1857, T_1886, T_1901, T_1925, T_1948, T_1966, T_1993, T_2005, T_2035, T_2039, T_2046, T_2071, T_2084, T_2104, T_2120, T_2135, T_2154, T_2164, ...]","[-22.408915115183795, -2.0025723751678735, -2.0025723751678735, -1.8076608544243982, -1.8076608544243982, -1.8076608544243995, -1.8076608544243995, -1.8076608544243968, -1.8076608544243968, -1.4620212328253892, -1.4620212328253892, -1.462021232825395, -1.462021232825395, -1.4620212328254003, -1.4620212328254003, -1.367450382110078, -1.367450382110078, 0.12601084193294032, 0.09441778014524217, 0.12150482690042828, 0.09441778014524223, 0.1215048269004284, 0.09441778014524212, 0.1215048269004282, 0.11151132357155509, 0.12341729243332238, 0.11151132357155553, 0.12341729243332288, 0.11151132357155592, 0.1234172924333233, 0.09931008213958181, 0.11766597355870295, 0.12150482690042828, 0.09441778014524217, 0.1215048269004284, 0.09441778014524223, 0.1215048269004282, 0.09441778014524212, 0.12341729243332238, 0.11151132357155509, 0.12341729243332288, 0.11151132357155553, 0.1234172924333233, 0.11151132357155592, 0.11766597355870295, 0.09931008213958181, 0.13450436113594946, 0.10134886265737106, 0.11170989829963887, 0.1013488626573709, 0.10926625002654566, 0.1064870678331826, 0.1188088700377998, 0.10569378505039045, 0.1095313045443218, 0.10275103248778099, 0.13172862963369106, 0.10338461264647633, 0.11511605099515307, 0.11170989829963887, 0.10134886265737106, 0.10926625002654566, 0.1013488626573709, 0.1188088700377998, 0.1064870678331826, 0.1095313045443218, 0.10569378505039045, 0.13172862963369106, 0.10275103248778099, 0.11511605099515307, 0.10338461264647633, 0.13581597072077464, 0.10134886265737097, 0.10795464044172066, 0.10445999419292423, 0.11562857121526804, 0.10434289120617345, 0.12895196049698127, 0.10612899997225601, 0.11548827250356242, 0.10338461264647705, 0.11511605099515433, 0.10795464044172066, 0.10134886265737097, 0.11562857121526804, 0.10445999419292423, 0.12895196049698127, 0.10434289120617345, 0.11548827250356242, 0.10612899997225601, 0.11511605099515433, 0.10338461264647705, 0.1382596189938675, 0.10398482334524581, 0.12563136296274302, 0.10489520911479004, 0.12158553917450926, 0.10605185291131804, 0.11285190207856013, 0.10338461264647632, ...]"
1,Z3,16,"[T_9, T_86, T_546, T_906, T_1299, T_1340, T_1356, T_1390, T_1412, T_1440, T_1475, T_1496, T_1536, T_1550, T_1593, T_1597]","[1.8076608544243982, -0.12150482690042828, -0.09441778014524217, -0.13450436113594946, -0.11170989829963887, -0.10134886265737106, -0.10926625002654566, -0.1013488626573709, -0.1188088700377998, -0.1064870678331826, -0.1095313045443218, -0.10569378505039045, -0.13172862963369106, -0.10275103248778099, -0.11511605099515307, -0.10338461264647633]"
2,Z0,16,"[T_1, T_37, T_65, T_86, T_134, T_161, T_203, T_236, T_272, T_311, T_335, T_380, T_398, T_449, T_461, T_496]","[2.0025723751678735, -0.12601084193294032, -0.09441778014524217, -0.12150482690042828, -0.09441778014524223, -0.1215048269004284, -0.09441778014524212, -0.1215048269004282, -0.11151132357155509, -0.12341729243332238, -0.11151132357155553, -0.12341729243332288, -0.11151132357155592, -0.1234172924333233, -0.09931008213958181, -0.11766597355870295]"
3,Z15,16,"[T_36, T_496, T_896, T_1295, T_1597, T_1853, T_2039, T_2184, T_2285, T_2342, T_2371, T_2393, T_2402, T_2409, T_2411, T_2412]","[1.367450382110078, -0.11766597355870295, -0.09931008213958181, -0.11511605099515307, -0.10338461264647633, -0.11511605099515433, -0.10338461264647705, -0.11511605099515303, -0.10338461264647632, -0.11955119469486376, -0.09408735651632752, -0.11955119469486489, -0.09408735651632785, -0.11955119469486461, -0.09408735651632828, -0.11560606436308316]"
4,Z14,16,"[T_35, T_461, T_894, T_1251, T_1593, T_1822, T_2035, T_2164, T_2281, T_2334, T_2370, T_2389, T_2401, T_2407, T_2410, T_2412]","[1.367450382110078, -0.09931008213958181, -0.11766597355870295, -0.10338461264647633, -0.11511605099515307, -0.10338461264647705, -0.11511605099515433, -0.10338461264647632, -0.11511605099515303, -0.09408735651632752, -0.11955119469486376, -0.09408735651632785, -0.11955119469486489, -0.09408735651632828, -0.11955119469486461, -0.11560606436308316]"
...,...,...,...,...
6588,Y1 Z2 Z3 Z4 Z5 X6 X12 Y13,2,"[T_670, T_830]","[0.0004804985435342776, 0.0004804985435342776]"
6589,Y1 Z2 Z3 Z4 Z5 X6 Y12 X13,2,"[T_670, T_830]","[0.0004804985435342776, -0.0004804985435342776]"
6590,X1 Z2 Z3 Z4 Z5 Y6 X11 Y12,2,"[T_669, T_829]","[7.42976797453138e-05, -7.42976797453138e-05]"
6591,X1 Z2 Z3 Z4 Z5 Y6 Y11 X12,2,"[T_669, T_829]","[7.42976797453138e-05, 7.42976797453138e-05]"
6592,X12 Y13 X14 Y15,2,"[T_2406, T_2408]","[0.012731919089268165, -0.012731919089268165]"

In [17]:
# Compute Pauli-duplication ratio for JW and BK

from collections import defaultdict
import pandas as pd

from openfermion.ops import FermionOperator
from openfermion.transforms import jordan_wigner, bravyi_kitaev, normal_ordered


def pauli_support(qubit_op, tol=1e-12, include_identity=True):
    """
    Return the set of Pauli strings with nonzero coefficients.
    """
    qubit_op.compress(abs_tol=tol)

    support = set()

    for pauli_key, coeff in qubit_op.terms.items():
        if abs(coeff) <= tol:
            continue

        if not include_identity and pauli_key == ():
            continue

        support.add(pauli_key)

    return support


def map_fermion_to_qubit(op, mapping="JW", n_qubits=None):
    """
    Map a FermionOperator to a QubitOperator using JW or BK.
    """
    mapping = mapping.upper()

    if mapping == "JW":
        qop = jordan_wigner(op)

    elif mapping == "BK":
        if n_qubits is None:
            raise ValueError("n_qubits is required for BK.")

        try:
            qop = bravyi_kitaev(op, n_qubits=n_qubits)
        except TypeError:
            qop = bravyi_kitaev(op, n_qubits)

    else:
        raise ValueError("mapping must be 'JW' or 'BK'.")

    qop.compress(abs_tol=1e-12)
    return qop


def pauli_duplication_ratio(
    fermionic_terms,
    mapping="JW",
    n_qubits=None,
    include_identity=True,
    tol=1e-12,
):
    """
    Compute

        sum_alpha #mapping(H_alpha) / #mapping(H)

    where H = sum_alpha H_alpha.

    Also returns a duplicate-use table.
    """

    H_full = FermionOperator.zero()

    numerator = 0
    union_support = set()
    pauli_usage = defaultdict(list)

    for alpha, H_alpha in enumerate(fermionic_terms):
        H_full += H_alpha

        Q_alpha = map_fermion_to_qubit(
            H_alpha,
            mapping=mapping,
            n_qubits=n_qubits,
        )

        support_alpha = pauli_support(
            Q_alpha,
            tol=tol,
            include_identity=include_identity,
        )

        numerator += len(support_alpha)
        union_support |= support_alpha

        for pauli_key, coeff in Q_alpha.terms.items():
            if abs(coeff) <= tol:
                continue

            if not include_identity and pauli_key == ():
                continue

            pauli_usage[pauli_key].append(
                {
                    "vertex": f"T_{alpha}",
                    "coefficient": coeff,
                }
            )

    H_full = normal_ordered(H_full)
    H_full.compress(abs_tol=tol)

    Q_full = map_fermion_to_qubit(
        H_full,
        mapping=mapping,
        n_qubits=n_qubits,
    )

    full_support = pauli_support(
        Q_full,
        tol=tol,
        include_identity=include_identity,
    )

    denominator = len(full_support)

    duplication_ratio = numerator / denominator
    union_ratio = numerator / len(union_support)

    summary_df = pd.DataFrame(
        [
            {
                "mapping": mapping.upper(),
                "include_identity": include_identity,
                "sum_alpha_number_of_Pauli_strings": numerator,
                "number_of_unique_Pauli_strings_before_cancellation": len(union_support),
                "number_of_Pauli_strings_in_full_H": denominator,
                "duplication_ratio": duplication_ratio,
                "raw_reuse_ratio_before_cancellation": union_ratio,
            }
        ]
    )

    duplicate_rows = []

    for pauli_key, appearances in pauli_usage.items():
        if len(appearances) <= 1:
            continue

        combined_coeff = Q_full.terms.get(pauli_key, 0.0)

        duplicate_rows.append(
            {
                "Pauli_string": format_qubit_term(pauli_key),
                "number_of_appearances": len(appearances),
                "appears_in_vertices": [x["vertex"] for x in appearances],
                "individual_coefficients": [complex(x["coefficient"]) for x in appearances],
                "combined_coefficient_in_full_H": complex(combined_coeff),
                "survives_in_full_H": abs(combined_coeff) > tol,
            }
        )

    duplicate_df = pd.DataFrame(duplicate_rows)

    if len(duplicate_df) > 0:
        duplicate_df = duplicate_df.sort_values(
            "number_of_appearances",
            ascending=False,
        ).reset_index(drop=True)

    return summary_df, duplicate_df


# ------------------------------------------------------------
# Run for JW
# ------------------------------------------------------------

n_qubits = molecule.n_qubits

jw_summary_df, jw_duplicate_df = pauli_duplication_ratio(
    hermitian_terms,
    mapping="JW",
    n_qubits=n_qubits,
    include_identity=True,
)

print("=== JW Pauli-duplication ratio ===")
display(jw_summary_df)

print("\n=== Duplicated JW Pauli strings ===")
display(jw_duplicate_df)


# ------------------------------------------------------------
# Optional: run for BK too
# ------------------------------------------------------------

bk_summary_df, bk_duplicate_df = pauli_duplication_ratio(
    hermitian_terms,
    mapping="BK",
    n_qubits=n_qubits,
    include_identity=True,
)

print("=== BK Pauli-duplication ratio ===")
display(bk_summary_df)

print("\n=== Duplicated BK Pauli strings ===")
display(bk_duplicate_df)

=== JW Pauli-duplication ratio ===

,mapping,include_identity,sum_alpha_number_of_Pauli_strings,number_of_unique_Pauli_strings_before_cancellation,number_of_Pauli_strings_in_full_H,duplication_ratio,raw_reuse_ratio_before_cancellation
0,JW,True,16185,7921,4689,3.451695,2.043303

=== Duplicated JW Pauli strings ===

,Pauli_string,number_of_appearances,appears_in_vertices,individual_coefficients,combined_coefficient_in_full_H,survives_in_full_H
0,I,137,"[T_0, T_1, T_3, T_5, T_9, T_13, T_17, T_21, T_25, T_29, T_30, T_31, T_32, T_33, T_34, T_35, T_36, T_37, T_65, T_86, T_134, T_161, T_203, T_236, T_272, T_311, T_335, T_380, T_398, T_449, T_461, T_496, T_498, T_546, T_569, T_611, T_640, T_676, T_714, T_738, T_779, T_797, T_844, T_856, T_894, T_896, T_906, T_955, T_971, T_1012, T_1034, T_1068, T_1103, T_1131, T_1171, T_1192, T_1237, T_1251, T_1295, T_1299, T_1340, T_1356, T_1390, T_1412, T_1440, T_1475, T_1496, T_1536, T_1550, T_1593, T_1597, T_1607, T_1643, T_1658, T_1687, T_1710, T_1734, T_1761, T_1779, T_1810, T_1822, T_1853, T_1857, T_1886, T_1901, T_1925, T_1948, T_1966, T_1993, T_2005, T_2035, T_2039, T_2046, T_2071, T_2084, T_2104, T_2120, T_2135, T_2154, T_2164, ...]","[(-22.408915115183795+0j), (-2.0025723751678735+0j), (-2.0025723751678735+0j), (-1.8076608544243982+0j), (-1.8076608544243982+0j), (-1.8076608544243995+0j), (-1.8076608544243995+0j), (-1.8076608544243968+0j), (-1.8076608544243968+0j), (-1.4620212328253892+0j), (-1.4620212328253892+0j), (-1.462021232825395+0j), (-1.462021232825395+0j), (-1.4620212328254003+0j), (-1.4620212328254003+0j), (-1.367450382110078+0j), (-1.367450382110078+0j), (0.12601084193294032+0j), (0.09441778014524217+0j), (0.12150482690042828+0j), (0.09441778014524223+0j), (0.1215048269004284+0j), (0.09441778014524212+0j), (0.1215048269004282+0j), (0.11151132357155509+0j), (0.12341729243332238+0j), (0.11151132357155553+0j), (0.12341729243332288+0j), (0.11151132357155592+0j), (0.1234172924333233+0j), (0.09931008213958181+0j), (0.11766597355870295+0j), (0.12150482690042828+0j), (0.09441778014524217+0j), (0.1215048269004284+0j), (0.09441778014524223+0j), (0.1215048269004282+0j), (0.09441778014524212+0j), (0.12341729243332238+0j), (0.11151132357155509+0j), (0.12341729243332288+0j), (0.11151132357155553+0j), (0.1234172924333233+0j), (0.11151132357155592+0j), (0.11766597355870295+0j), (0.09931008213958181+0j), (0.13450436113594946+0j), (0.10134886265737106+0j), (0.11170989829963887+0j), (0.1013488626573709+0j), (0.10926625002654566+0j), (0.1064870678331826+0j), (0.1188088700377998+0j), (0.10569378505039045+0j), (0.1095313045443218+0j), (0.10275103248778099+0j), (0.13172862963369106+0j), (0.10338461264647633+0j), (0.11511605099515307+0j), (0.11170989829963887+0j), (0.10134886265737106+0j), (0.10926625002654566+0j), (0.1013488626573709+0j), (0.1188088700377998+0j), (0.1064870678331826+0j), (0.1095313045443218+0j), (0.10569378505039045+0j), (0.13172862963369106+0j), (0.10275103248778099+0j), (0.11511605099515307+0j), (0.10338461264647633+0j), (0.13581597072077464+0j), (0.10134886265737097+0j), (0.10795464044172066+0j), (0.10445999419292423+0j), (0.11562857121526804+0j), (0.10434289120617345+0j), (0.12895196049698127+0j), (0.10612899997225601+0j), (0.11548827250356242+0j), (0.10338461264647705+0j), (0.11511605099515433+0j), (0.10795464044172066+0j), (0.10134886265737097+0j), (0.11562857121526804+0j), (0.10445999419292423+0j), (0.12895196049698127+0j), (0.10434289120617345+0j), (0.11548827250356242+0j), (0.10612899997225601+0j), (0.11511605099515433+0j), (0.10338461264647705+0j), (0.1382596189938675+0j), (0.10398482334524581+0j), (0.12563136296274302+0j), (0.10489520911479004+0j), (0.12158553917450926+0j), (0.10605185291131804+0j), (0.11285190207856013+0j), (0.10338461264647632+0j), ...]",-35.283310+ 0.000000j,True
1,Z3,16,"[T_9, T_86, T_546, T_906, T_1299, T_1340, T_1356, T_1390, T_1412, T_1440, T_1475, T_1496, T_1536, T_1550, T_1593, T_1597]","[(1.8076608544243982+0j), (-0.12150482690042828+0j), (-0.09441778014524217+0j), (-0.13450436113594946+0j), (-0.11170989829963887+0j), (-0.10134886265737106+0j), (-0.10926625002654566+0j), (-0.1013488626573709+0j), (-0.1188088700377998+0j), (-0.1064870678331826+0j), (-0.1095313045443218+0j), (-0.10569378505039045+0j), (-0.13172862963369106+0j), (-0.10275103248778099+0j), (-0.11511605099515307+0j), (-0.10338461264647633+0j)]",0.140059+ 0.000000j,True
2,Z0,16,"[T_1, T_37, T_65, T_86, T_134, T_161, T_203, T_236, T_272, T_311, T_335, T_380, T_398, T_449, T_461, T_496]","[(2.0025723751678735+0j), (-0.12601084193294032+0j), (-0.09441778014524217+0j), (-0.12150482690042828+0j), (-0.09441778014524223+0j), (-0.1215048269004284+0j), (-0.09441778014524212+0j), (-0.1215048269004282+0j), (-0.11151132357155509+0j), (-0.12341729243332238+0j), (-0.11151132357155553+0j), (-0.12341729243332288+0j), (-0.11151132357155592+0j), (-0.1234172924333233+0j), (-0.09931008213958181+0j), (-0.11766597355870295+0j)]",0.307032+ 0.000000j,True
3,Z15,16,"[T_36, T_496, T_896, T_1295, T_1597, T_1853, T_2039, T_2184, T_2285, T_2342, T_2371, T_2393, T_2402, T_2409, T_2411, T_2412]","[(1.367450382110078+0j), (-0.11766597355870295+0j), (-0.09931008213958181+0j), (-0.11511605099515307+0j), (-0.10338461264647633+0j), (-0.11511605099515433+0j), (-0.10338461264647705+0j), (-0.11511605099515303+0j), (-0.10338461264647632+0j), (-0.11955119469486376+0j), (-0.09408735651632752+0j), (-0.11955119469486489+0j), (-0.09408735651632785+0j), (-0.11955119469486461+0j), (-0.09408735651632828+0j), (-0.11560606436308316+0j)]",-0.261549+ 0.000000j,True
4,Z14,16,"[T_35, T_461, T_894, T_1251, T_1593, T_1822, T_2035, T_2164, T_2281, T_2334, T_2370, T_2389, T_2401, T_2407, T_2410, T_2412]","[(1.367450382110078+0j), (-0.09931008213958181+0j), (-0.11766597355870295+0j), (-0.10338461264647633+0j), (-0.11511605099515307+0j), (-0.10338461264647705+0j), (-0.11511605099515433+0j), (-0.10338461264647632+0j), (-0.11511605099515303+0j), (-0.09408735651632752+0j), (-0.11955119469486376+0j), (-0.09408735651632785+0j), (-0.11955119469486489+0j), (-0.09408735651632828+0j), (-0.11955119469486461+0j), (-0.11560606436308316+0j)]",-0.261549+ 0.000000j,True
...,...,...,...,...,...,...
6588,Y1 Z2 Z3 Z4 Z5 X6 X12 Y13,2,"[T_670, T_830]","[(0.0004804985435342776+0j), (0.0004804985435342776+0j)]",0.000961+ 0.000000j,True
6589,Y1 Z2 Z3 Z4 Z5 X6 Y12 X13,2,"[T_670, T_830]","[(0.0004804985435342776+0j), (-0.0004804985435342776+0j)]",0.000000+ 0.000000j,False
6590,X1 Z2 Z3 Z4 Z5 Y6 X11 Y12,2,"[T_669, T_829]","[(7.42976797453138e-05+0j), (-7.42976797453138e-05+0j)]",0.000000+ 0.000000j,False
6591,X1 Z2 Z3 Z4 Z5 Y6 Y11 X12,2,"[T_669, T_829]","[(7.42976797453138e-05+0j), (7.42976797453138e-05+0j)]",0.000149+ 0.000000j,True
6592,X12 Y13 X14 Y15,2,"[T_2406, T_2408]","[(0.012731919089268165+0j), (-0.012731919089268165+0j)]",0.000000+ 0.000000j,False

=== BK Pauli-duplication ratio ===

,mapping,include_identity,sum_alpha_number_of_Pauli_strings,number_of_unique_Pauli_strings_before_cancellation,number_of_Pauli_strings_in_full_H,duplication_ratio,raw_reuse_ratio_before_cancellation
0,BK,True,16185,7921,4689,3.451695,2.043303

=== Duplicated BK Pauli strings ===

,Pauli_string,number_of_appearances,appears_in_vertices,individual_coefficients,combined_coefficient_in_full_H,survives_in_full_H
0,I,137,"[T_0, T_1, T_3, T_5, T_9, T_13, T_17, T_21, T_25, T_29, T_30, T_31, T_32, T_33, T_34, T_35, T_36, T_37, T_65, T_86, T_134, T_161, T_203, T_236, T_272, T_311, T_335, T_380, T_398, T_449, T_461, T_496, T_498, T_546, T_569, T_611, T_640, T_676, T_714, T_738, T_779, T_797, T_844, T_856, T_894, T_896, T_906, T_955, T_971, T_1012, T_1034, T_1068, T_1103, T_1131, T_1171, T_1192, T_1237, T_1251, T_1295, T_1299, T_1340, T_1356, T_1390, T_1412, T_1440, T_1475, T_1496, T_1536, T_1550, T_1593, T_1597, T_1607, T_1643, T_1658, T_1687, T_1710, T_1734, T_1761, T_1779, T_1810, T_1822, T_1853, T_1857, T_1886, T_1901, T_1925, T_1948, T_1966, T_1993, T_2005, T_2035, T_2039, T_2046, T_2071, T_2084, T_2104, T_2120, T_2135, T_2154, T_2164, ...]","[(-22.408915115183795+0j), (-2.0025723751678735+0j), (-2.0025723751678735+0j), (-1.8076608544243982+0j), (-1.8076608544243982+0j), (-1.8076608544243995+0j), (-1.8076608544243995+0j), (-1.8076608544243968+0j), (-1.8076608544243968+0j), (-1.4620212328253892+0j), (-1.4620212328253892+0j), (-1.462021232825395+0j), (-1.462021232825395+0j), (-1.4620212328254003+0j), (-1.4620212328254003+0j), (-1.367450382110078+0j), (-1.367450382110078+0j), (0.12601084193294032+0j), (0.09441778014524217+0j), (0.12150482690042828+0j), (0.09441778014524223+0j), (0.1215048269004284+0j), (0.09441778014524212+0j), (0.1215048269004282+0j), (0.11151132357155509+0j), (0.12341729243332238+0j), (0.11151132357155553+0j), (0.12341729243332288+0j), (0.11151132357155592+0j), (0.1234172924333233+0j), (0.09931008213958181+0j), (0.11766597355870295+0j), (0.12150482690042828+0j), (0.09441778014524217+0j), (0.1215048269004284+0j), (0.09441778014524223+0j), (0.1215048269004282+0j), (0.09441778014524212+0j), (0.12341729243332238+0j), (0.11151132357155509+0j), (0.12341729243332288+0j), (0.11151132357155553+0j), (0.1234172924333233+0j), (0.11151132357155592+0j), (0.11766597355870295+0j), (0.09931008213958181+0j), (0.13450436113594946+0j), (0.10134886265737106+0j), (0.11170989829963887+0j), (0.1013488626573709+0j), (0.10926625002654566+0j), (0.1064870678331826+0j), (0.1188088700377998+0j), (0.10569378505039045+0j), (0.1095313045443218+0j), (0.10275103248778099+0j), (0.13172862963369106+0j), (0.10338461264647633+0j), (0.11511605099515307+0j), (0.11170989829963887+0j), (0.10134886265737106+0j), (0.10926625002654566+0j), (0.1013488626573709+0j), (0.1188088700377998+0j), (0.1064870678331826+0j), (0.1095313045443218+0j), (0.10569378505039045+0j), (0.13172862963369106+0j), (0.10275103248778099+0j), (0.11511605099515307+0j), (0.10338461264647633+0j), (0.13581597072077464+0j), (0.10134886265737097+0j), (0.10795464044172066+0j), (0.10445999419292423+0j), (0.11562857121526804+0j), (0.10434289120617345+0j), (0.12895196049698127+0j), (0.10612899997225601+0j), (0.11548827250356242+0j), (0.10338461264647705+0j), (0.11511605099515433+0j), (0.10795464044172066+0j), (0.10134886265737097+0j), (0.11562857121526804+0j), (0.10445999419292423+0j), (0.12895196049698127+0j), (0.10434289120617345+0j), (0.11548827250356242+0j), (0.10612899997225601+0j), (0.11511605099515433+0j), (0.10338461264647705+0j), (0.1382596189938675+0j), (0.10398482334524581+0j), (0.12563136296274302+0j), (0.10489520911479004+0j), (0.12158553917450926+0j), (0.10605185291131804+0j), (0.11285190207856013+0j), (0.10338461264647632+0j), ...]",-35.283310+ 0.000000j,True
1,Z1 Z2 Z3,16,"[T_9, T_86, T_546, T_906, T_1299, T_1340, T_1356, T_1390, T_1412, T_1440, T_1475, T_1496, T_1536, T_1550, T_1593, T_1597]","[(1.8076608544243982+0j), (-0.12150482690042828+0j), (-0.09441778014524217+0j), (-0.13450436113594946+0j), (-0.11170989829963887+0j), (-0.10134886265737106+0j), (-0.10926625002654566+0j), (-0.1013488626573709+0j), (-0.1188088700377998+0j), (-0.1064870678331826+0j), (-0.1095313045443218+0j), (-0.10569378505039045+0j), (-0.13172862963369106+0j), (-0.10275103248778099+0j), (-0.11511605099515307+0j), (-0.10338461264647633+0j)]",0.140059+ 0.000000j,True
2,Z0,16,"[T_1, T_37, T_65, T_86, T_134, T_161, T_203, T_236, T_272, T_311, T_335, T_380, T_398, T_449, T_461, T_496]","[(2.0025723751678735+0j), (-0.12601084193294032+0j), (-0.09441778014524217+0j), (-0.12150482690042828+0j), (-0.09441778014524223+0j), (-0.1215048269004284+0j), (-0.09441778014524212+0j), (-0.1215048269004282+0j), (-0.11151132357155509+0j), (-0.12341729243332238+0j), (-0.11151132357155553+0j), (-0.12341729243332288+0j), (-0.11151132357155592+0j), (-0.1234172924333233+0j), (-0.09931008213958181+0j), (-0.11766597355870295+0j)]",0.307032+ 0.000000j,True
3,Z7 Z11 Z13 Z14 Z15,16,"[T_36, T_496, T_896, T_1295, T_1597, T_1853, T_2039, T_2184, T_2285, T_2342, T_2371, T_2393, T_2402, T_2409, T_2411, T_2412]","[(1.367450382110078+0j), (-0.11766597355870295+0j), (-0.09931008213958181+0j), (-0.11511605099515307+0j), (-0.10338461264647633+0j), (-0.11511605099515433+0j), (-0.10338461264647705+0j), (-0.11511605099515303+0j), (-0.10338461264647632+0j), (-0.11955119469486376+0j), (-0.09408735651632752+0j), (-0.11955119469486489+0j), (-0.09408735651632785+0j), (-0.11955119469486461+0j), (-0.09408735651632828+0j), (-0.11560606436308316+0j)]",-0.261549+ 0.000000j,True
4,Z14,16,"[T_35, T_461, T_894, T_1251, T_1593, T_1822, T_2035, T_2164, T_2281, T_2334, T_2370, T_2389, T_2401, T_2407, T_2410, T_2412]","[(1.367450382110078+0j), (-0.09931008213958181+0j), (-0.11766597355870295+0j), (-0.10338461264647633+0j), (-0.11511605099515307+0j), (-0.10338461264647705+0j), (-0.11511605099515433+0j), (-0.10338461264647632+0j), (-0.11511605099515303+0j), (-0.09408735651632752+0j), (-0.11955119469486376+0j), (-0.09408735651632785+0j), (-0.11955119469486489+0j), (-0.09408735651632828+0j), (-0.11955119469486461+0j), (-0.11560606436308316+0j)]",-0.261549+ 0.000000j,True
...,...,...,...,...,...,...
6588,Z0 X1 Y3 Z5 X6 Y12 Z13,2,"[T_670, T_830]","[(0.0004804985435342776+0j), (0.0004804985435342776+0j)]",0.000961+ 0.000000j,True
6589,Z0 X1 Y3 Z5 X6 Y12,2,"[T_670, T_830]","[(0.0004804985435342776+0j), (-0.0004804985435342776+0j)]",0.000000+ 0.000000j,False
6590,Y1 Y3 Z5 Y6 X11 Y12 X13,2,"[T_669, T_829]","[(-7.42976797453138e-05+0j), (7.42976797453138e-05+0j)]",0.000000+ 0.000000j,False
6591,Y1 Y3 Z5 Y6 Z9 Z10 Y11 X12 X13,2,"[T_669, T_829]","[(-7.42976797453138e-05+0j), (-7.42976797453138e-05+0j)]",-0.000149+ 0.000000j,True
6592,Z7 Z11 Y12 Y14 Z15,2,"[T_2406, T_2408]","[(0.012731919089268165+0j), (-0.012731919089268165+0j)]",0.000000+ 0.000000j,False