In [1]:
# Cell 1: Build H2 fermionic Hamiltonian and Hermitian fermionic terms

import pandas as pd

from openfermion.chem import MolecularData
from openfermion.ops import FermionOperator
from openfermion.transforms import get_fermion_operator, normal_ordered
from openfermion.utils import hermitian_conjugated
from openfermionpyscf import run_pyscf

pd.set_option("display.max_colwidth", None)


def format_fermion_term(term):
    if term == ():
        return "I"

    pieces = []
    for orbital, action in term:
        if action == 1:
            pieces.append(f"a_{orbital}^dagger")
        else:
            pieces.append(f"a_{orbital}")
    return " ".join(pieces)


def sort_fermion_key(term):
    return (len(term), term)


def coeff_to_str(c, digits=8):
    c = complex(c)
    if abs(c.imag) < 1e-12:
        return f"{c.real:+.{digits}f}"
    return f"{c.real:+.{digits}f}{c.imag:+.{digits}f}j"


def operator_to_string(op, digits=8):
    pieces = []

    for term, coeff in sorted(op.terms.items(), key=lambda item: sort_fermion_key(item[0])):
        pieces.append(f"{coeff_to_str(coeff, digits)} {format_fermion_term(term)}")

    if len(pieces) == 0:
        return "0"

    return " + ".join(pieces)


def dagger_term_key(term):
    """
    Return the OpenFermion key for O^dagger, where O is one monomial.
    """
    O = FermionOperator(term, 1.0)
    O_dag = normal_ordered(hermitian_conjugated(O))
    O_dag.compress(abs_tol=1e-12)

    if len(O_dag.terms) != 1:
        raise ValueError(f"Expected one dagger term, got: {O_dag}")

    return next(iter(O_dag.terms.keys()))


def make_hermitian_fermionic_terms(fermion_hamiltonian, tol=1e-12):
    """
    Group raw monomials into Hermitian fermionic Hamiltonian terms.

    If O is self-adjoint, keep c O.
    If O is not self-adjoint, group c O + c* O^dagger.
    """
    used = set()
    hermitian_terms = []

    for term, coeff in fermion_hamiltonian.terms.items():
        if term in used:
            continue

        dag = dagger_term_key(term)

        if dag == term:
            T = FermionOperator(term, coeff)
            used.add(term)
        else:
            dag_coeff = fermion_hamiltonian.terms.get(dag, 0.0)

            T = FermionOperator(term, coeff)
            T += FermionOperator(dag, dag_coeff)

            used.add(term)
            used.add(dag)

        T = normal_ordered(T)
        T.compress(abs_tol=tol)
        hermitian_terms.append(T)

    return hermitian_terms


def build_h10_fermionic_hamiltonian(
    bond_length=0.7414,
    basis="sto-3g",
    multiplicity=1,
    charge=0,
):
    geometry = [
        ("H", (0.0, 0.0, 0.0 * bond_length)),
        ("H", (0.0, 0.0, 1.0 * bond_length)),
        ("H", (0.0, 0.0, 2.0 * bond_length)),
        ("H", (0.0, 0.0, 3.0 * bond_length)),
        ("H", (0.0, 0.0, 4.0 * bond_length)),
        ("H", (0.0, 0.0, 5.0 * bond_length)),
        ("H", (0.0, 0.0, 6.0 * bond_length)),
        ("H", (0.0, 0.0, 7.0 * bond_length)),
        ("H", (0.0, 0.0, 8.0 * bond_length)),
        ("H", (0.0, 0.0, 9.0 * bond_length)),
    ]

    molecule = MolecularData(
        geometry=geometry,
        basis=basis,
        multiplicity=multiplicity,
        charge=charge,
        description=f"H10_{bond_length}",
    )

    molecule = run_pyscf(
        molecule,
        run_scf=True,
        run_fci=False,
    )

    molecular_hamiltonian = molecule.get_molecular_hamiltonian()
    fermion_hamiltonian = get_fermion_operator(molecular_hamiltonian)

    fermion_hamiltonian = normal_ordered(fermion_hamiltonian)
    fermion_hamiltonian.compress(abs_tol=1e-12)

    return molecule, fermion_hamiltonian


molecule, Hf = build_h10_fermionic_hamiltonian(
    bond_length=0.7414,
    basis="sto-3g",
)

hermitian_terms = make_hermitian_fermionic_terms(Hf)

print("Molecule: H10")
print("Basis: STO-3G")
print("Number of electrons:", molecule.n_electrons)
print("Number of spatial orbitals:", molecule.n_orbitals)
print("Number of spin orbitals / fermionic modes:", molecule.n_qubits)
print("Number of raw OpenFermion monomial terms:", len(Hf.terms))
print("Number of Hermitian fermionic terms:", len(hermitian_terms))

print("\n=== Full fermionic Hamiltonian H_f ===")
print(Hf)


# ------------------------------------------------------------
# Tables
# ------------------------------------------------------------

raw_rows = []

for idx, (term, coeff) in enumerate(
    sorted(Hf.terms.items(), key=lambda item: sort_fermion_key(item[0]))
):
    raw_rows.append(
        {
            "raw_index": idx,
            "coefficient": coeff_to_str(coeff),
            "monomial": format_fermion_term(term),
            "OpenFermion_key": term,
        }
    )

raw_df = pd.DataFrame(raw_rows)

print("\n=== Raw fermionic monomials c_alpha O_alpha ===")
display(raw_df)


hermitian_rows = []

for i, T in enumerate(hermitian_terms):
    hermitian_rows.append(
        {
            "vertex": f"T_{i}",
            "number_of_monomials": len(T.terms),
            "fermionic_term": operator_to_string(T),
        }
    )

hermitian_df = pd.DataFrame(hermitian_rows)

print("\n=== Hermitian fermionic terms T_i ===")
display(hermitian_df)

Molecule: H10
Basis: STO-3G
Number of electrons: 10
Number of spatial orbitals: 10
Number of spin orbitals / fermionic modes: 20
Number of raw OpenFermion monomial terms: 7151
Number of Hermitian fermionic terms: 3681

=== Full fermionic Hamiltonian H_f ===
13.76808794966473 [] +
-3.5359549988639274 [0^ 0] +
0.1649426220344185 [0^ 4] +
-0.051806732853524017 [0^ 8] +
0.026106398124277494 [0^ 12] +
0.019992844863909835 [0^ 16] +
-0.40765568222464466 [1^ 0^ 1 0] +
-0.13135472084934996 [1^ 0^ 3 2] +
-0.07668556823757515 [1^ 0^ 4 1] +
0.07668556823757515 [1^ 0^ 5 0] +
-0.08917189612324626 [1^ 0^ 5 4] +
0.052053002836877624 [1^ 0^ 6 3] +
-0.052053002836877624 [1^ 0^ 7 2] +
-0.06438293979922091 [1^ 0^ 7 6] +
-0.004077256614803865 [1^ 0^ 8 1] +
0.04112529779298367 [1^ 0^ 8 5] +
0.004077256614803865 [1^ 0^ 9 0] +
-0.04112529779298367 [1^ 0^ 9 4] +
-0.05952844459691587 [1^ 0^ 9 8] +
-0.006256112762920704 [1^ 0^ 10 3] +
-0.032168133955602515 [1^ 0^ 10 7] +
0.006256112762920704 [1^ 0^ 11 2] +
0.032168133955602515 [1^ 0^ 11 6] +
-0.051003531639871424 [1^ 0^ 11 10] +
0.0012011611350004514 [1^ 0^ 12 1] +
0.00038593329114264643 [1^ 0^ 12 5] +
0.02449231220768852 [1^ 0^ 12 9] +
-0.0012011611350004514 [1^ 0^ 13 0] +
-0.00038593329114264643 [1^ 0^ 13 4] +
-0.02449231220768852 [1^ 0^ 13 8] +
-0.03748072649406497 [1^ 0^ 13 12] +
0.0012824923117413915 [1^ 0^ 14 3] +
0.002220019197737025 [1^ 0^ 14 7] +
-0.022962817666105438 [1^ 0^ 14 11] +
-0.0012824923117413915 [1^ 0^ 15 2] +
-0.002220019197737025 [1^ 0^ 15 6] +
0.022962817666105438 [1^ 0^ 15 10] +
-0.03516730507474533 [1^ 0^ 15 14] +
-0.0010598283607236737 [1^ 0^ 16 1] +
0.0006547185155252231 [1^ 0^ 16 5] +
-0.002376317579986217 [1^ 0^ 16 9] +
-0.01842076320939725 [1^ 0^ 16 13] +
0.0010598283607236737 [1^ 0^ 17 0] +
-0.0006547185155252231 [1^ 0^ 17 4] +
0.002376317579986217 [1^ 0^ 17 8] +
0.01842076320939725 [1^ 0^ 17 12] +
-0.03102463937596435 [1^ 0^ 17 16] +
-0.0005515350388966428 [1^ 0^ 18 3] +
0.00029256573204212034 [1^ 0^ 18 7] +
0.0010871481378324356 [1^ 0^ 18 11] +
-0.015527477468718477 [1^ 0^ 18 15] +
0.0005515350388966428 [1^ 0^ 19 2] +
-0.00029256573204212034 [1^ 0^ 19 6] +
-0.0010871481378324356 [1^ 0^ 19 10] +
0.015527477468718477 [1^ 0^ 19 14] +
-0.03973523357386012 [1^ 0^ 19 18] +
-3.5359549988639274 [1^ 1] +
0.1649426220344185 [1^ 5] +
-0.051806732853524017 [1^ 9] +
0.026106398124277494 [1^ 13] +
0.019992844863909835 [1^ 17] +
-0.1975653695960713 [2^ 0^ 2 0] +
-0.06695010090326614 [2^ 0^ 4 2] +
-0.03030492757837918 [2^ 0^ 6 0] +
0.03855219248062817 [2^ 0^ 6 4] +
-0.0162605885852059 [2^ 0^ 8 2] +
-0.025735903870675148 [2^ 0^ 8 6] +
0.001111365877328354 [2^ 0^ 10 0] +
-0.012048011922279464 [2^ 0^ 10 4] +
-0.021072973082281763 [2^ 0^ 10 8] +
0.0006261182012368594 [2^ 0^ 12 2] +
-0.004363970004917617 [2^ 0^ 12 6] +
0.013260780266498256 [2^ 0^ 12 10] +
-0.00074150128946751 [2^ 0^ 14 0] +
0.0015833312911977444 [2^ 0^ 14 4] +
0.006135012429678406 [2^ 0^ 14 8] +
0.010383924031991735 [2^ 0^ 14 12] +
-0.0002504763853312872 [2^ 0^ 16 2] +
-4.9283370759048146e-05 [2^ 0^ 16 6] +
-0.003773782399602372 [2^ 0^ 16 10] +
0.007887411292698881 [2^ 0^ 16 14] +
-0.002076431818923129 [2^ 0^ 18 0] +
0.00026546250737345645 [2^ 0^ 18 4] +
-0.00027208306961946504 [2^ 0^ 18 8] +
-0.0024237998427600266 [2^ 0^ 18 12] +
0.005485041108853771 [2^ 0^ 18 16] +
-0.32892009044542125 [2^ 1^ 2 1] +
0.13135472084934996 [2^ 1^ 3 0] +
-0.0848635402347235 [2^ 1^ 4 3] +
0.017913439331457368 [2^ 1^ 5 2] +
-0.08235793041525681 [2^ 1^ 6 1] +
0.05418875522576996 [2^ 1^ 6 5] +
0.052053002836877624 [2^ 1^ 7 0] +
-0.015636562745141802 [2^ 1^ 7 4] +
-0.05634258952501537 [2^ 1^ 8 3] +
-0.04538332254039984 [2^ 1^ 8 7] +
0.04008200093980947 [2^ 1^ 9 2] +
0.0196474186697247 [2^ 1^ 9 6] +
0.007367478640249058 [2^ 1^ 10 1] +
-0.04286752813548243 [2^ 1^ 10 5] +
-0.03261090171767932 [2^ 1^ 10 9] +
-0.006256112762920704 [2^ 1^ 11 0] +
0.030819516213202974 [2^ 1^ 11 4] +
0.011537928635397562 [2^ 1^ 11 8] +
-0.0009054610604836971 [2^ 1^ 12 3] +
-0.029016478207925828 [2^ 1^ 12 7] +
0.031206503077421566 [2^ 1^ 12 11] +
0.0015315792617205566 [2^ 1^ 13 2] +
0.02465250820300821 [2^ 1^ 13 6] +
-0.017945722810923312 [2^ 1^ 13 10] +
-0.002023993601208901 [2^ 1^ 14 1] +
0.0041972539416921025 [2^ 1^ 14 5] +
0.026311677216650182 [2^ 1^ 14 9] +
0.021808359159924337 [2^ 1^ 14 13] +
0.0012824923117413915 [2^ 1^ 15 0] +
-0.0026139226504943583 [2^ 1^ 15 4] +
-0.020176664786971776 [2^ 1^ 15 8] +
-0.011424435127932606 [2^ 1^ 15 12] +
-0.00020704362487683326 [2^ 1^ 16 3] +
0.0018858577874879307 [2^ 1^ 16 7] +
-0.022023116527355793 [2^ 1^ 16 11] +
0.02004823774570956 [2^ 1^ 16 15] +
-4.343276045445394e-05 [2^ 1^ 17 2] +
-0.001935141158246979 [2^ 1^ 17 6] +
0.018249334127753418 [2^ 1^ 17 10] +
-0.01216082645301068 [2^ 1^ 17 14] +
-0.0015248967800264863 [2^ 1^ 18 1] +
0.0007933790323691093 [2^ 1^ 18 5] +
-0.0019759385525187374 [2^ 1^ 18 9] +
-0.017149654520282196 [2^ 1^ 18 13] +
0.02795852453787427 [2^ 1^ 18 17] +
-0.0005515350388966428 [2^ 1^ 19 0] +
-0.0005279165249956529 [2^ 1^ 19 4] +
0.001703855482899272 [2^ 1^ 19 8] +
0.01472585467752217 [2^ 1^ 19 12] +
-0.022473483429020502 [2^ 1^ 19 16] +
-3.3110038724915642 [2^ 2] +
-0.2484218780306474 [2^ 6] +
-0.07833402979153675 [2^ 10] +
-0.0566023679054608 [2^ 14] +
-0.00710524693589893 [2^ 18] +
0.13135472084934996 [3^ 0^ 2 1] +
-0.32892009044542125 [3^ 0^ 3 0] +
0.017913439331457368 [3^ 0^ 4 3] +
-0.0848635402347235 [3^ 0^ 5 2] +
0.052053002836877624 [3^ 0^ 6 1] +
-0.015636562745141802 [3^ 0^ 6 5] +
-0.08235793041525681 [3^ 0^ 7 0] +
0.05418875522576996 [3^ 0^ 7 4] +
0.04008200093980947 [3^ 0^ 8 3] +
0.0196474186697247 [3^ 0^ 8 7] +
-0.05634258952501537 [3^ 0^ 9 2] +
-0.04538332254039984 [3^ 0^ 9 6] +
-0.006256112762920704 [3^ 0^ 10 1] +
0.030819516213202974 [3^ 0^ 10 5] +
0.011537928635397562 [3^ 0^ 10 9] +
0.007367478640249058 [3^ 0^ 11 0] +
-0.04286752813548243 [3^ 0^ 11 4] +
-0.03261090171767932 [3^ 0^ 11 8] +
0.0015315792617205566 [3^ 0^ 12 3] +
0.02465250820300821 [3^ 0^ 12 7] +
-0.017945722810923312 [3^ 0^ 12 11] +
-0.0009054610604836971 [3^ 0^ 13 2] +
-0.029016478207925828 [3^ 0^ 13 6] +
0.031206503077421566 [3^ 0^ 13 10] +
0.0012824923117413915 [3^ 0^ 14 1] +
-0.0026139226504943583 [3^ 0^ 14 5] +
-0.020176664786971776 [3^ 0^ 14 9] +
-0.011424435127932606 [3^ 0^ 14 13] +
-0.002023993601208901 [3^ 0^ 15 0] +
0.0041972539416921025 [3^ 0^ 15 4] +
0.026311677216650182 [3^ 0^ 15 8] +
0.021808359159924337 [3^ 0^ 15 12] +
-4.343276045445394e-05 [3^ 0^ 16 3] +
-0.001935141158246979 [3^ 0^ 16 7] +
0.018249334127753418 [3^ 0^ 16 11] +
-0.01216082645301068 [3^ 0^ 16 15] +
-0.00020704362487683326 [3^ 0^ 17 2] +
0.0018858577874879307 [3^ 0^ 17 6] +
-0.022023116527355793 [3^ 0^ 17 10] +
0.02004823774570956 [3^ 0^ 17 14] +
-0.0005515350388966428 [3^ 0^ 18 1] +
-0.0005279165249956529 [3^ 0^ 18 5] +
0.001703855482899272 [3^ 0^ 18 9] +
0.01472585467752217 [3^ 0^ 18 13] +
-0.022473483429020502 [3^ 0^ 18 17] +
-0.0015248967800264863 [3^ 0^ 19 0] +
0.0007933790323691093 [3^ 0^ 19 4] +
-0.0019759385525187374 [3^ 0^ 19 8] +
-0.017149654520282196 [3^ 0^ 19 12] +
0.02795852453787427 [3^ 0^ 19 16] +
-0.1975653695960713 [3^ 1^ 3 1] +
-0.06695010090326614 [3^ 1^ 5 3] +
-0.03030492757837918 [3^ 1^ 7 1] +
0.03855219248062817 [3^ 1^ 7 5] +
-0.0162605885852059 [3^ 1^ 9 3] +
-0.025735903870675148 [3^ 1^ 9 7] +
0.001111365877328354 [3^ 1^ 11 1] +
-0.012048011922279464 [3^ 1^ 11 5] +
-0.021072973082281763 [3^ 1^ 11 9] +
0.0006261182012368594 [3^ 1^ 13 3] +
-0.004363970004917617 [3^ 1^ 13 7] +
0.013260780266498256 [3^ 1^ 13 11] +
-0.00074150128946751 [3^ 1^ 15 1] +
0.0015833312911977444 [3^ 1^ 15 5] +
0.006135012429678406 [3^ 1^ 15 9] +
0.010383924031991735 [3^ 1^ 15 13] +
-0.0002504763853312872 [3^ 1^ 17 3] +
-4.9283370759048146e-05 [3^ 1^ 17 7] +
-0.003773782399602372 [3^ 1^ 17 11] +
0.007887411292698881 [3^ 1^ 17 15] +
-0.002076431818923129 [3^ 1^ 19 1] +
0.00026546250737345645 [3^ 1^ 19 5] +
-0.00027208306961946504 [3^ 1^ 19 9] +
-0.0024237998427600266 [3^ 1^ 19 13] +
0.005485041108853771 [3^ 1^ 19 17] +
-0.13135472084934996 [3^ 2^ 1 0] +
-0.3506765656719897 [3^ 2^ 3 2] +
0.0848635402347235 [3^ 2^ 4 1] +
-0.0848635402347235 [3^ 2^ 5 0] +
-0.11049482016852755 [3^ 2^ 5 4] +
0.02554946492159422 [3^ 2^ 6 3] +
-0.02554946492159422 [3^ 2^ 7 2] +
-0.08234631449163567 [3^ 2^ 7 6] +
0.05634258952501537 [3^ 2^ 8 1] +
0.01194878122123397 [3^ 2^ 8 5] +
-0.05634258952501537 [3^ 2^ 9 0] +
-0.01194878122123397 [3^ 2^ 9 4] +
-0.0657185007555982 [3^ 2^ 9 8] +
0.038710732867855445 [3^ 2^ 10 3] +
-0.009903252444674488 [3^ 2^ 10 7] +
-0.038710732867855445 [3^ 2^ 11 2] +
0.009903252444674488 [3^ 2^ 11 6] +
-0.05401389110132789 [3^ 2^ 11 10] +
0.0009054610604836971 [3^ 2^ 12 1] +
-0.03166726881036601 [3^ 2^ 12 5] +
0.004612805452215689 [3^ 2^ 12 9] +
-0.0009054610604836971 [3^ 2^ 13 0] +
0.03166726881036601 [3^ 2^ 13 4] +
-0.004612805452215689 [3^ 2^ 13 8] +
-0.04584829465883808 [3^ 2^ 13 12] +
-0.0027051072134396505 [3^ 2^ 14 3] +
-0.023737733775914614 [3^ 2^ 14 7] +
-0.0016477398184450774 [3^ 2^ 14 11] +
0.0027051072134396505 [3^ 2^ 15 2] +
0.023737733775914614 [3^ 2^ 15 6] +
0.0016477398184450774 [3^ 2^ 15 10] +
-0.037282261408551204 [3^ 2^ 15 14] +
0.00020704362487683326 [3^ 2^ 16 1] +
0.003432163692687654 [3^ 2^ 16 5] +
0.01927112423612708 [3^ 2^ 16 9] +
-0.003498862998879103 [3^ 2^ 16 13] +
-0.00020704362487683326 [3^ 2^ 17 0] +
-0.003432163692687654 [3^ 2^ 17 4] +
-0.01927112423612708 [3^ 2^ 17 8] +
0.003498862998879103 [3^ 2^ 17 12] +
-0.042387787256970885 [3^ 2^ 17 16] +
0.000471934811060252 [3^ 2^ 18 3] +
0.0017889393795801525 [3^ 2^ 18 7] +
-0.017123116659221588 [3^ 2^ 18 11] +
0.0093623446423475 [3^ 2^ 18 15] +
-0.000471934811060252 [3^ 2^ 19 2] +
-0.0017889393795801525 [3^ 2^ 19 6] +
0.017123116659221588 [3^ 2^ 19 10] +
-0.0093623446423475 [3^ 2^ 19 14] +
-0.029331395264309622 [3^ 2^ 19 18] +
-3.3110038724915642 [3^ 3] +
-0.2484218780306474 [3^ 7] +
-0.07833402979153675 [3^ 11] +
-0.0566023679054608 [3^ 15] +
-0.00710524693589893 [3^ 19] +
0.16494262203441845 [4^ 0] +
-0.22913177862035744 [4^ 0^ 4 0] +
0.06346348937483284 [4^ 0^ 6 2] +
-0.04708227454770572 [4^ 0^ 8 0] +
0.04295440180598768 [4^ 0^ 8 4] +
-0.02757628679199478 [4^ 0^ 10 2] +
-0.02897115440606253 [4^ 0^ 10 6] +
0.0022829339501623486 [4^ 0^ 12 0] +
0.01396656319509913 [4^ 0^ 12 4] +
0.021845611063805264 [4^ 0^ 12 8] +
0.0017463306745329895 [4^ 0^ 14 2] +
0.009839417216602232 [4^ 0^ 14 6] +
-0.015793784021587477 [4^ 0^ 14 10] +
0.0037387029719995997 [4^ 0^ 16 0] +
-0.0016800324193946275 [4^ 0^ 16 4] +
-0.00868151537924661 [4^ 0^ 16 8] +
-0.011414826349798528 [4^ 0^ 16 12] +
-0.0023042592679452852 [4^ 0^ 18 2] +
-0.0006084701754979607 [4^ 0^ 18 6] +
0.005480854565000287 [4^ 0^ 18 10] +
-0.009602011912127074 [4^ 0^ 18 14] +
-0.07668556823757515 [4^ 1^ 1 0] +
0.0848635402347235 [4^ 1^ 3 2] +
-0.31830367474360366 [4^ 1^ 4 1] +
0.08917189612324626 [4^ 1^ 5 0] +
-0.008416922350753961 [4^ 1^ 5 4] +
0.07910005211997465 [4^ 1^ 6 3] +
-0.015636562745141802 [4^ 1^ 7 2] +
0.0024936687843891267 [4^ 1^ 7 6] +
-0.08820757234068939 [4^ 1^ 8 1] +
0.060377249286410625 [4^ 1^ 8 5] +
0.04112529779298367 [4^ 1^ 9 0] +
-0.01742284748042295 [4^ 1^ 9 4] +
-0.005242561257717956 [4^ 1^ 9 8] +
-0.058395803005197755 [4^ 1^ 10 3] +
-0.0412544854402571 [4^ 1^ 10 7] +
0.030819516213202974 [4^ 1^ 11 2] +
0.012283331034194576 [4^ 1^ 11 6] +
-0.0041803263240537515 [4^ 1^ 11 10] +
0.0018970006590197021 [4^ 1^ 12 1] +
0.03841633563852024 [4^ 1^ 12 5] +
0.033775832929443014 [4^ 1^ 12 9] +
0.00038593329114264643 [4^ 1^ 13 0] +
-0.024449772443421107 [4^ 1^ 13 4] +
-0.011930221865637747 [4^ 1^ 13 8] +
0.003407452770109844 [4^ 1^ 13 12] +
0.0043602533250273485 [4^ 1^ 14 3] +
0.02993832060341741 [4^ 1^ 14 7] +
-0.031210134014934436 [4^ 1^ 14 11] +
-0.0026139226504943583 [4^ 1^ 15 2] +
-0.02009890338681518 [4^ 1^ 15 6] +
0.015416349993346958 [4^ 1^ 15 10] +
-0.001917140696075003 [4^ 1^ 15 14] +
0.003083984456474376 [4^ 1^ 16 1] +
-0.0037327643983090094 [4^ 1^ 16 5] +
-0.025287075637745873 [4^ 1^ 16 9] +
-0.022082398132483475 [4^ 1^ 16 13] +
0.0006547185155252231 [4^ 1^ 17 0] +
0.002052731978914382 [4^ 1^ 17 4] +
0.016605560258499262 [4^ 1^ 17 8] +
0.010667571782684945 [4^ 1^ 17 12] +
0.007568806750531809 [4^ 1^ 17 16] +
-0.0017763427429496324 [4^ 1^ 18 3] +
-0.0016559956636418528 [4^ 1^ 18 7] +
0.020197843916974302 [4^ 1^ 18 11] +
-0.03018431903602282 [4^ 1^ 18 15] +
-0.0005279165249956529 [4^ 1^ 19 2] +
0.0010475254881438922 [4^ 1^ 19 6] +
-0.014716989351974016 [4^ 1^ 19 10] +
0.02058230712389575 [4^ 1^ 19 14] +
-0.013971303393324936 [4^ 1^ 19 18] +
-0.06695010090326615 [4^ 2^ 2 0] +
-0.20110885495386316 [4^ 2^ 4 2] +
0.02491129689420467 [4^ 2^ 6 0] +
0.07931341431136951 [4^ 2^ 6 4] +
-0.013070141394996921 [4^ 2^ 8 2] +
-0.04910144656085922 [4^ 2^ 8 6] +
-0.015528274869715315 [4^ 2^ 10 0] +
-0.007114846996164351 [4^ 2^ 10 4] +
-0.03831746695331712 [4^ 2^ 10 8] +
0.011313742183441902 [4^ 2^ 12 2] +
0.00301311868346267 [4^ 2^ 12 6] +
0.023357878780959157 [4^ 2^ 12 10] +
0.0001629993833352451 [4^ 2^ 14 0] +
-0.004189037061564581 [4^ 2^ 14 4] +
0.0023496038495542356 [4^ 2^ 14 8] +
0.018531924538934045 [4^ 2^ 14 12] +
0.002446875286745814 [4^ 2^ 16 2] +
-0.003947197667585826 [4^ 2^ 16 6] +
-0.000178292619325457 [4^ 2^ 16 10] +
0.013887929832164862 [4^ 2^ 16 14] +
-0.0025697217753187416 [4^ 2^ 18 0] +
1.450272351982522e-05 [4^ 2^ 18 4] +
0.0026592488970504135 [4^ 2^ 18 8] +
0.0009698347329542248 [4^ 2^ 18 12] +
0.008480214688795513 [4^ 2^ 18 16] +
-0.0848635402347235 [4^ 3^ 2 1] +
0.017913439331457368 [4^ 3^ 3 0] +
-0.31160367512239073 [4^ 3^ 4 3] +
0.11049482016852755 [4^ 3^ 5 2] +
0.07910005211997465 [4^ 3^ 6 1] +
0.0878988047750946 [4^ 3^ 6 5] +
-0.05418875522576996 [4^ 3^ 7 0] +
-0.008585390463725091 [4^ 3^ 7 4] +
-0.02501892261623089 [4^ 3^ 8 3] +
-0.06382768383509593 [4^ 3^ 8 7] +
0.01194878122123397 [4^ 3^ 9 2] +
0.014726237274236713 [4^ 3^ 9 6] +
-0.058395803005197755 [4^ 3^ 10 1] +
-0.01743281657248395 [4^ 3^ 10 5] +
-0.044958493559067836 [4^ 3^ 10 9] +
0.04286752813548243 [4^ 3^ 11 0] +
0.010317969576319598 [4^ 3^ 11 4] +
0.006641026605750715 [4^ 3^ 11 8] +
0.04298101099380791 [4^ 3^ 12 3] +
-0.004833901193919136 [4^ 3^ 12 7] +
0.03878269617865811 [4^ 3^ 12 11] +
-0.03166726881036601 [4^ 3^ 13 2] +
0.007847019877381806 [4^ 3^ 13 6] +
-0.01542481739769895 [4^ 3^ 13 10] +
0.0043602533250273485 [4^ 3^ 14 1] +
-0.029267451145294776 [4^ 3^ 14 5] +
0.0055303847221815534 [4^ 3^ 14 9] +
0.03190191686312423 [4^ 3^ 14 13] +
-0.0041972539416921025 [4^ 3^ 15 0] +
0.02507841408373019 [4^ 3^ 15 4] +
-0.0031807808726273187 [4^ 3^ 15 8] +
-0.013369992324190182 [4^ 3^ 15 12] +
-0.00098528840594184 [4^ 3^ 16 3] +
-0.023008479879501043 [4^ 3^ 16 7] +
-0.00040242626745187857 [4^ 3^ 16 11] +
0.03204841550166918 [4^ 3^ 16 15] +
0.003432163692687654 [4^ 3^ 17 2] +
0.019061282211915217 [4^ 3^ 17 6] +
0.0002241336481264216 [4^ 3^ 17 10] +
-0.018160485669504317 [4^ 3^ 17 14] +
-0.0017763427429496324 [4^ 3^ 18 1] +
0.001133745762296353 [4^ 3^ 18 5] +
0.01786533783461245 [4^ 3^ 18 9] +
0.008393535847668276 [4^ 3^ 18 13] +
0.019048180683452424 [4^ 3^ 18 17] +
-0.0007933790323691093 [4^ 3^ 19 0] +
-0.0011192430387765278 [4^ 3^ 19 4] +
-0.015206088937562036 [4^ 3^ 19 8] +
-0.007423701114714052 [4^ 3^ 19 12] +
-0.010567965994656911 [4^ 3^ 19 16] +
-3.126180412542379 [4^ 4] +
-0.29485329732384935 [4^ 8] +
0.14243816850656651 [4^ 12] +
0.03462335195463318 [4^ 16] +
0.07668556823757515 [5^ 0^ 1 0] +
-0.0848635402347235 [5^ 0^ 3 2] +
0.08917189612324626 [5^ 0^ 4 1] +
-0.31830367474360366 [5^ 0^ 5 0] +
0.008416922350753961 [5^ 0^ 5 4] +
-0.015636562745141802 [5^ 0^ 6 3] +
0.07910005211997465 [5^ 0^ 7 2] +
-0.0024936687843891267 [5^ 0^ 7 6] +
0.04112529779298367 [5^ 0^ 8 1] +
-0.01742284748042295 [5^ 0^ 8 5] +
-0.08820757234068939 [5^ 0^ 9 0] +
0.060377249286410625 [5^ 0^ 9 4] +
0.005242561257717956 [5^ 0^ 9 8] +
0.030819516213202974 [5^ 0^ 10 3] +
0.012283331034194576 [5^ 0^ 10 7] +
-0.058395803005197755 [5^ 0^ 11 2] +
-0.0412544854402571 [5^ 0^ 11 6] +
0.0041803263240537515 [5^ 0^ 11 10] +
0.00038593329114264643 [5^ 0^ 12 1] +
-0.024449772443421107 [5^ 0^ 12 5] +
-0.011930221865637747 [5^ 0^ 12 9] +
0.0018970006590197021 [5^ 0^ 13 0] +
0.03841633563852024 [5^ 0^ 13 4] +
0.033775832929443014 [5^ 0^ 13 8] +
-0.003407452770109844 [5^ 0^ 13 12] +
-0.0026139226504943583 [5^ 0^ 14 3] +
-0.02009890338681518 [5^ 0^ 14 7] +
0.015416349993346958 [5^ 0^ 14 11] +
0.0043602533250273485 [5^ 0^ 15 2] +
0.02993832060341741 [5^ 0^ 15 6] +
-0.031210134014934436 [5^ 0^ 15 10] +
0.001917140696075003 [5^ 0^ 15 14] +
0.0006547185155252231 [5^ 0^ 16 1] +
0.002052731978914382 [5^ 0^ 16 5] +
0.016605560258499262 [5^ 0^ 16 9] +
0.010667571782684945 [5^ 0^ 16 13] +
0.003083984456474376 [5^ 0^ 17 0] +
-0.0037327643983090094 [5^ 0^ 17 4] +
-0.025287075637745873 [5^ 0^ 17 8] +
-0.022082398132483475 [5^ 0^ 17 12] +
-0.007568806750531809 [5^ 0^ 17 16] +
-0.0005279165249956529 [5^ 0^ 18 3] +
0.0010475254881438922 [5^ 0^ 18 7] +
-0.014716989351974016 [5^ 0^ 18 11] +
0.02058230712389575 [5^ 0^ 18 15] +
-0.0017763427429496324 [5^ 0^ 19 2] +
-0.0016559956636418528 [5^ 0^ 19 6] +
0.020197843916974302 [5^ 0^ 19 10] +
-0.03018431903602282 [5^ 0^ 19 14] +
0.013971303393324936 [5^ 0^ 19 18] +
0.16494262203441845 [5^ 1] +
-0.22913177862035744 [5^ 1^ 5 1] +
0.06346348937483284 [5^ 1^ 7 3] +
-0.04708227454770572 [5^ 1^ 9 1] +
0.04295440180598768 [5^ 1^ 9 5] +
-0.02757628679199478 [5^ 1^ 11 3] +
-0.02897115440606253 [5^ 1^ 11 7] +
0.0022829339501623486 [5^ 1^ 13 1] +
0.01396656319509913 [5^ 1^ 13 5] +
0.021845611063805264 [5^ 1^ 13 9] +
0.0017463306745329895 [5^ 1^ 15 3] +
0.009839417216602232 [5^ 1^ 15 7] +
-0.015793784021587477 [5^ 1^ 15 11] +
0.0037387029719995997 [5^ 1^ 17 1] +
-0.0016800324193946275 [5^ 1^ 17 5] +
-0.00868151537924661 [5^ 1^ 17 9] +
-0.011414826349798528 [5^ 1^ 17 13] +
-0.0023042592679452852 [5^ 1^ 19 3] +
-0.0006084701754979607 [5^ 1^ 19 7] +
0.005480854565000287 [5^ 1^ 19 11] +
-0.009602011912127074 [5^ 1^ 19 15] +
0.017913439331457368 [5^ 2^ 2 1] +
-0.0848635402347235 [5^ 2^ 3 0] +
0.11049482016852755 [5^ 2^ 4 3] +
-0.31160367512239073 [5^ 2^ 5 2] +
-0.05418875522576996 [5^ 2^ 6 1] +
-0.008585390463725091 [5^ 2^ 6 5] +
0.07910005211997465 [5^ 2^ 7 0] +
0.0878988047750946 [5^ 2^ 7 4] +
0.01194878122123397 [5^ 2^ 8 3] +
0.014726237274236713 [5^ 2^ 8 7] +
-0.02501892261623089 [5^ 2^ 9 2] +
-0.06382768383509593 [5^ 2^ 9 6] +
0.04286752813548243 [5^ 2^ 10 1] +
0.010317969576319598 [5^ 2^ 10 5] +
0.006641026605750715 [5^ 2^ 10 9] +
-0.058395803005197755 [5^ 2^ 11 0] +
-0.01743281657248395 [5^ 2^ 11 4] +
-0.044958493559067836 [5^ 2^ 11 8] +
-0.03166726881036601 [5^ 2^ 12 3] +
0.007847019877381806 [5^ 2^ 12 7] +
-0.01542481739769895 [5^ 2^ 12 11] +
0.04298101099380791 [5^ 2^ 13 2] +
-0.004833901193919136 [5^ 2^ 13 6] +
0.03878269617865811 [5^ 2^ 13 10] +
-0.0041972539416921025 [5^ 2^ 14 1] +
0.02507841408373019 [5^ 2^ 14 5] +
-0.0031807808726273187 [5^ 2^ 14 9] +
-0.013369992324190182 [5^ 2^ 14 13] +
0.0043602533250273485 [5^ 2^ 15 0] +
-0.029267451145294776 [5^ 2^ 15 4] +
0.0055303847221815534 [5^ 2^ 15 8] +
0.03190191686312423 [5^ 2^ 15 12] +
0.003432163692687654 [5^ 2^ 16 3] +
0.019061282211915217 [5^ 2^ 16 7] +
0.0002241336481264216 [5^ 2^ 16 11] +
-0.018160485669504317 [5^ 2^ 16 15] +
-0.00098528840594184 [5^ 2^ 17 2] +
-0.023008479879501043 [5^ 2^ 17 6] +
-0.00040242626745187857 [5^ 2^ 17 10] +
0.03204841550166918 [5^ 2^ 17 14] +
-0.0007933790323691093 [5^ 2^ 18 1] +
-0.0011192430387765278 [5^ 2^ 18 5] +
-0.015206088937562036 [5^ 2^ 18 9] +
-0.007423701114714052 [5^ 2^ 18 13] +
-0.010567965994656911 [5^ 2^ 18 17] +
-0.0017763427429496324 [5^ 2^ 19 0] +
0.001133745762296353 [5^ 2^ 19 4] +
0.01786533783461245 [5^ 2^ 19 8] +
0.008393535847668276 [5^ 2^ 19 12] +
0.019048180683452424 [5^ 2^ 19 16] +
-0.06695010090326615 [5^ 3^ 3 1] +
-0.20110885495386316 [5^ 3^ 5 3] +
0.02491129689420467 [5^ 3^ 7 1] +
0.07931341431136951 [5^ 3^ 7 5] +
-0.013070141394996921 [5^ 3^ 9 3] +

,raw_index,coefficient,monomial,OpenFermion_key
0,0,+13.76808795,I,()
1,1,-3.53595500,a_0^dagger a_0,"((0, 1), (0, 0))"
2,2,+0.16494262,a_0^dagger a_4,"((0, 1), (4, 0))"
3,3,-0.05180673,a_0^dagger a_8,"((0, 1), (8, 0))"
4,4,+0.02610640,a_0^dagger a_12,"((0, 1), (12, 0))"
...,...,...,...,...
7146,7146,-0.00194184,a_19^dagger a_18^dagger a_19 a_2,"((19, 1), (18, 1), (19, 0), (2, 0))"
7147,7147,-0.00054843,a_19^dagger a_18^dagger a_19 a_6,"((19, 1), (18, 1), (19, 0), (6, 0))"
7148,7148,+0.00061042,a_19^dagger a_18^dagger a_19 a_10,"((19, 1), (18, 1), (19, 0), (10, 0))"
7149,7149,+0.10174657,a_19^dagger a_18^dagger a_19 a_14,"((19, 1), (18, 1), (19, 0), (14, 0))"
7150,7150,-0.52703315,a_19^dagger a_18^dagger a_19 a_18,"((19, 1), (18, 1), (19, 0), (18, 0))"

=== Hermitian fermionic terms T_i ===

,vertex,number_of_monomials,fermionic_term
0,T_0,1,+13.76808795 I
1,T_1,1,-3.53595500 a_0^dagger a_0
2,T_2,2,+0.16494262 a_0^dagger a_4 + +0.16494262 a_4^dagger a_0
3,T_3,2,-0.05180673 a_0^dagger a_8 + -0.05180673 a_8^dagger a_0
4,T_4,2,+0.02610640 a_0^dagger a_12 + +0.02610640 a_12^dagger a_0
...,...,...,...
3676,T_3676,2,+0.18078400 a_18^dagger a_17^dagger a_19 a_16 + +0.18078400 a_19^dagger a_16^dagger a_18 a_17
3677,T_3677,1,-0.41614532 a_19^dagger a_16^dagger a_19 a_16
3678,T_3678,1,-0.41614532 a_18^dagger a_17^dagger a_18 a_17
3679,T_3679,1,-0.23536132 a_19^dagger a_17^dagger a_19 a_17
3680,T_3680,1,-0.52703315 a_19^dagger a_18^dagger a_19 a_18

In [3]:
# Cell 2 alpha: Faster H2 / molecular fermionic noncommutation graph
#
# Main idea:
#   1. Use cheap fermionic index rules first.
#   2. Only if rules cannot decide, use exact OpenFermion symbolic commutator.
#   3. Never build sparse/dense matrices.
#
# This cell assumes Cell 1 already defined:
#   hermitian_terms
#   operator_to_string

import time
from collections import Counter

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from openfermion.utils import commutator
from openfermion.transforms import normal_ordered

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# Fermionic key utilities
# ------------------------------------------------------------

def key_modes(key):
    """
    Modes appearing in one OpenFermion monomial key.

    Example:
        ((3, 1), (0, 1), (3, 0), (0, 0)) -> {0, 3}
    """
    return frozenset(mode for mode, action in key)


def key_creations(key):
    """
    Creation modes in one monomial.
    """
    return frozenset(mode for mode, action in key if action == 1)


def key_annihilations(key):
    """
    Annihilation modes in one monomial.
    """
    return frozenset(mode for mode, action in key if action == 0)


def key_net_delta(key):
    """
    Net occupation change caused by a monomial.

    creation contributes +1
    annihilation contributes -1

    For example:
        a_2^dagger a_1^dagger a_3 a_0
    has delta:
        +1 on modes 2 and 1
        -1 on modes 3 and 0
    """
    delta = Counter()

    for mode, action in key:
        if action == 1:
            delta[mode] += 1
        else:
            delta[mode] -= 1

    return delta


def is_diagonal_key(key):
    """
    True if a monomial preserves occupation mode-by-mode.

    Examples:
        a_p^dagger a_p is diagonal.
        a_p^dagger a_q^dagger a_q a_p is diagonal.
        a_p^dagger a_q is not diagonal when p != q.
    """
    delta = key_net_delta(key)
    return all(value == 0 for value in delta.values())


def is_even_key(key):
    """
    Electronic Hamiltonian terms normally have even fermionic parity:
    length 0, 2, or 4.
    """
    return len(key) % 2 == 0


# ------------------------------------------------------------
# Safe monomial-level commutation rules
# ------------------------------------------------------------

def diagonal_key_commutes_with_key(diagonal_key, other_key):
    """
    Safe rule:

    A diagonal occupation operator depending on modes S commutes with another
    monomial if the other monomial has zero net occupation change on every
    mode in S.
    """
    support = key_modes(diagonal_key)
    delta = key_net_delta(other_key)

    return all(delta.get(mode, 0) == 0 for mode in support)


def no_cross_contractions_even_commute(key_a, key_b):
    """
    Safe rule for normal-ordered even fermionic monomials.

    If there are no possible cross contractions:
        annihilations(A) intersect creations(B) = empty
        annihilations(B) intersect creations(A) = empty

    then even monomials commute.

    This catches many cases beyond completely disjoint support.
    """
    if not is_even_key(key_a) or not is_even_key(key_b):
        return False

    a_ann = key_annihilations(key_a)
    a_cre = key_creations(key_a)

    b_ann = key_annihilations(key_b)
    b_cre = key_creations(key_b)

    return a_ann.isdisjoint(b_cre) and b_ann.isdisjoint(a_cre)


def monomial_pair_definitely_commutes(key_a, key_b):
    """
    Return (True, reason) only when we are sure two monomials commute.
    Return (False, None) if the rule cannot decide.

    Important:
        False here does NOT mean noncommuting.
        It only means "unknown; use exact symbolic fallback."
    """
    # Identity commutes with everything.
    if key_a == () or key_b == ():
        return True, "identity"

    # Any monomial commutes with itself.
    if key_a == key_b:
        return True, "same_monomial"

    # Diagonal occupation-like monomials commute with each other.
    if is_diagonal_key(key_a) and is_diagonal_key(key_b):
        return True, "diagonal_diagonal"

    # Diagonal with excitation-like term, if excitation preserves diagonal support.
    if is_diagonal_key(key_a) and diagonal_key_commutes_with_key(key_a, key_b):
        return True, "diagonal_support_preserved"

    if is_diagonal_key(key_b) and diagonal_key_commutes_with_key(key_b, key_a):
        return True, "diagonal_support_preserved"

    # Even monomials with no cross contractions commute.
    if no_cross_contractions_even_commute(key_a, key_b):
        return True, "no_cross_contractions_even"

    return False, None


# ------------------------------------------------------------
# Operator-level metadata and precheck
# ------------------------------------------------------------

def operator_metadata(op):
    """
    Precompute simple structural data for one FermionOperator.
    """
    keys = list(op.terms.keys())

    modes = set()
    for key in keys:
        modes.update(key_modes(key))

    return {
        "is_zero": len(keys) == 0,
        "only_identity": len(keys) == 1 and keys[0] == (),
        "modes": frozenset(modes),
        "is_even": all(is_even_key(key) for key in keys),
        "is_diagonal": all(is_diagonal_key(key) for key in keys),
        "number_of_monomials": len(keys),
    }


def operator_pair_definitely_commutes(A, B, meta_A, meta_B):
    """
    Return (True, reason) only for guaranteed-commuting pairs.
    Return (False, None) when unresolved.
    """
    if meta_A["is_zero"] or meta_B["is_zero"]:
        return True, "zero"

    if meta_A["only_identity"] or meta_B["only_identity"]:
        return True, "identity"

    # Very cheap global rule:
    # disjoint even fermionic operators commute.
    if (
        meta_A["is_even"]
        and meta_B["is_even"]
        and meta_A["modes"].isdisjoint(meta_B["modes"])
    ):
        return True, "disjoint_even_support"

    # Diagonal occupation-like operators commute with each other.
    if meta_A["is_diagonal"] and meta_B["is_diagonal"]:
        return True, "diagonal_diagonal"

    # More detailed but still cheap:
    # if every monomial pair has a safe commuting reason, the sums commute.
    reasons = Counter()

    for key_a in A.terms:
        for key_b in B.terms:
            ok, reason = monomial_pair_definitely_commutes(key_a, key_b)

            if not ok:
                return False, None

            reasons[reason] += 1

    if len(reasons) > 0:
        main_reason = reasons.most_common(1)[0][0]
        return True, f"all_monomial_pairs_{main_reason}"

    return False, None


# ------------------------------------------------------------
# Exact symbolic fallback
# ------------------------------------------------------------

def exact_symbolic_fermionic_commutator(A, B, tol=1e-12):
    """
    Exact symbolic commutator in fermionic algebra.

    This does not build a 2^n matrix.
    """
    C = normal_ordered(commutator(A, B))
    C.compress(abs_tol=tol)
    return C


# ------------------------------------------------------------
# Alpha graph builder
# ------------------------------------------------------------

def build_fermionic_noncommutation_graph_alpha(
    hermitian_terms,
    tol=1e-12,
    store_commutators=False,
):
    """
    Build noncommutation graph using:
        fast safe index rules first,
        exact symbolic OpenFermion fallback only when needed.

    Parameters
    ----------
    hermitian_terms:
        list of FermionOperator terms T_i from Cell 1.

    tol:
        numerical compression tolerance.

    store_commutators:
        False is recommended for large molecules.
        True is useful for H2 debugging, but can be memory-heavy.

    Returns
    -------
    G:
        networkx.Graph

    stats_df:
        pandas.DataFrame with timing and skip counts
    """
    t_start = time.perf_counter()

    G = nx.Graph()
    stats = Counter()

    metadata = [operator_metadata(T) for T in hermitian_terms]

    # Add vertices.
    for i, T in enumerate(hermitian_terms):
        G.add_node(
            i,
            label=f"T_{i}",
            operator=T,
            operator_string=operator_to_string(T),
            number_of_monomials=len(T.terms),
            modes=sorted(metadata[i]["modes"]),
            is_diagonal=metadata[i]["is_diagonal"],
            is_even=metadata[i]["is_even"],
        )

    n = len(hermitian_terms)

    # Pairwise graph construction.
    for i in range(n):
        A = hermitian_terms[i]
        meta_A = metadata[i]

        for j in range(i + 1, n):
            B = hermitian_terms[j]
            meta_B = metadata[j]

            stats["total_pairs"] += 1

            # 1. Fast guaranteed-commuting rules.
            definitely_commutes, reason = operator_pair_definitely_commutes(
                A, B, meta_A, meta_B
            )

            if definitely_commutes:
                stats["pairs_skipped_by_index_rules"] += 1
                stats[f"skip_{reason}"] += 1
                continue

            # 2. Exact symbolic fallback.
            stats["pairs_sent_to_exact_symbolic"] += 1

            Cij = exact_symbolic_fermionic_commutator(A, B, tol=tol)

            if len(Cij.terms) != 0:
                stats["noncommuting_edges"] += 1

                edge_data = {
                    "method": "exact_symbolic_fallback",
                    "meaning": f"[T_{i}, T_{j}] != 0",
                }

                if store_commutators:
                    edge_data["commutator"] = Cij
                    edge_data["commutator_string"] = operator_to_string(Cij)
                else:
                    edge_data["commutator_string"] = (
                        "(not stored; rerun with store_commutators=True)"
                    )

                G.add_edge(i, j, **edge_data)

            else:
                stats["exact_symbolic_found_commuting"] += 1

    elapsed = time.perf_counter() - t_start

    stats["vertices"] = n
    stats["edges"] = G.number_of_edges()
    stats["commuting_pairs"] = stats["total_pairs"] - G.number_of_edges()
    stats["elapsed_seconds"] = elapsed

    stats_df = pd.DataFrame([dict(stats)])

    return G, stats_df


# ------------------------------------------------------------
# Run alpha graph builder
# ------------------------------------------------------------

# For H2 debugging, you can set store_commutators=True.
# For larger molecules, keep this False.
G_alpha, stats_df = build_fermionic_noncommutation_graph_alpha(
    hermitian_terms,
    tol=1e-12,
    store_commutators=False,
)

print("=== Fermionic noncommutation graph alpha summary ===")
display(stats_df)

print("Number of vertices / fermionic terms:", G_alpha.number_of_nodes())
print("Number of noncommuting pairs / edges:", G_alpha.number_of_edges())
print("Is graph bipartite?", nx.is_bipartite(G_alpha))


# ------------------------------------------------------------
# Vertex table
# ------------------------------------------------------------

vertex_rows = []

for i, data in G_alpha.nodes(data=True):
    vertex_rows.append(
        {
            "vertex": f"T_{i}",
            "degree": G_alpha.degree[i],
            "commutes_with_all": G_alpha.degree[i] == 0,
            "number_of_monomials": data["number_of_monomials"],
            "modes": data["modes"],
            "is_diagonal": data["is_diagonal"],
            "fermionic_term": data["operator_string"],
        }
    )

vertex_df_alpha = pd.DataFrame(vertex_rows)

print("\n=== Alpha vertices: fermionic terms ===")
display(vertex_df_alpha)


# ------------------------------------------------------------
# Edge table
# ------------------------------------------------------------

edge_rows = []

for i, j, data in G_alpha.edges(data=True):
    edge_rows.append(
        {
            "source": f"T_{i}",
            "target": f"T_{j}",
            "meaning": data["meaning"],
            "method": data["method"],
            "commutator": data["commutator_string"],
        }
    )

edge_df_alpha = pd.DataFrame(edge_rows)

print("\n=== Alpha edges: noncommuting pairs ===")
display(edge_df_alpha)


# # ------------------------------------------------------------
# # Draw graph
# # ------------------------------------------------------------

# plt.figure(figsize=(12, 8))

# pos = nx.kamada_kawai_layout(G_alpha)

# node_labels = {
#     i: f"T_{i}"
#     for i in G_alpha.nodes()
# }

# node_sizes = [
#     1000 + 250 * G_alpha.degree[i]
#     for i in G_alpha.nodes()
# ]

# nx.draw_networkx_nodes(G_alpha, pos, node_size=node_sizes)
# nx.draw_networkx_edges(G_alpha, pos, width=1.5)
# nx.draw_networkx_labels(
#     G_alpha,
#     pos,
#     labels=node_labels,
#     font_size=11,
#     font_weight="bold",
# )

# plt.title("Fermionic Noncommutation Graph Alpha")
# plt.axis("off")
# plt.show()

=== Fermionic noncommutation graph alpha summary ===

,total_pairs,pairs_skipped_by_index_rules,skip_identity,pairs_sent_to_exact_symbolic,noncommuting_edges,skip_disjoint_even_support,skip_diagonal_diagonal,skip_all_monomial_pairs_diagonal_support_preserved,exact_symbolic_found_commuting,vertices,edges,commuting_pairs,elapsed_seconds
0,6773040,3112975,3680,3660065,3379643,3092535,3800,12960,280422,3681,3379643,3393397,208.680862

Number of vertices / fermionic terms: 3681
Number of noncommuting pairs / edges: 3379643
Is graph bipartite? False

=== Alpha vertices: fermionic terms ===

,vertex,degree,commutes_with_all,number_of_monomials,modes,is_diagonal,fermionic_term
0,T_0,0,True,1,[],True,+13.76808795 I
1,T_1,618,False,1,[0],True,-3.53595500 a_0^dagger a_0
2,T_2,1210,False,2,"[0, 4]",False,+0.16494262 a_0^dagger a_4 + +0.16494262 a_4^dagger a_0
3,T_3,1210,False,2,"[0, 8]",False,-0.05180673 a_0^dagger a_8 + -0.05180673 a_8^dagger a_0
4,T_4,1210,False,2,"[0, 12]",False,+0.02610640 a_0^dagger a_12 + +0.02610640 a_12^dagger a_0
...,...,...,...,...,...,...,...
3676,T_3676,1974,False,2,"[16, 17, 18, 19]",False,+0.18078400 a_18^dagger a_17^dagger a_19 a_16 + +0.18078400 a_19^dagger a_16^dagger a_18 a_17
3677,T_3677,1113,False,1,"[16, 19]",True,-0.41614532 a_19^dagger a_16^dagger a_19 a_16
3678,T_3678,1113,False,1,"[17, 18]",True,-0.41614532 a_18^dagger a_17^dagger a_18 a_17
3679,T_3679,1056,False,1,"[17, 19]",True,-0.23536132 a_19^dagger a_17^dagger a_19 a_17
3680,T_3680,1113,False,1,"[18, 19]",True,-0.52703315 a_19^dagger a_18^dagger a_19 a_18

=== Alpha edges: noncommuting pairs ===

,source,target,meaning,method,commutator
0,T_1,T_2,"[T_1, T_2] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
1,T_1,T_3,"[T_1, T_3] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
2,T_1,T_4,"[T_1, T_4] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
3,T_1,T_5,"[T_1, T_5] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
4,T_1,T_62,"[T_1, T_62] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
...,...,...,...,...,...
3379638,T_3672,T_3676,"[T_3672, T_3676] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
3379639,T_3673,T_3674,"[T_3673, T_3674] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
3379640,T_3674,T_3680,"[T_3674, T_3680] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
3379641,T_3676,T_3677,"[T_3676, T_3677] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
3379642,T_3676,T_3678,"[T_3676, T_3678] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)

In [4]:
# Cell 2: Build the H2 fermionic noncommutation graph

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from openfermion.transforms import normal_ordered

pd.set_option("display.max_colwidth", None)


def fermionic_commutator(A, B, tol=1e-12):
    """
    Compute [A, B] = AB - BA directly in the fermionic algebra.
    """
    C = normal_ordered(A * B - B * A)
    C.compress(abs_tol=tol)
    return C


def commute(A, B, tol=1e-12):
    """
    Return True if [A, B] = 0.
    """
    C = fermionic_commutator(A, B, tol=tol)
    return len(C.terms) == 0


# ------------------------------------------------------------
# Build noncommutation graph
# ------------------------------------------------------------
# Vertex i = Hermitian fermionic term T_i
# Edge (i, j) exists if [T_i, T_j] != 0

G = nx.Graph()

for i, T in enumerate(hermitian_terms):
    G.add_node(
        i,
        label=f"T_{i}",
        operator=T,
        operator_string=operator_to_string(T),
        number_of_monomials=len(T.terms),
    )

for i in range(len(hermitian_terms)):
    for j in range(i + 1, len(hermitian_terms)):
        Cij = fermionic_commutator(hermitian_terms[i], hermitian_terms[j])

        if len(Cij.terms) != 0:
            G.add_edge(
                i,
                j,
                commutator=Cij,
                commutator_string=operator_to_string(Cij),
            )


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

n_vertices = G.number_of_nodes()
n_total_pairs = n_vertices * (n_vertices - 1) // 2
n_noncommuting_pairs = G.number_of_edges()
n_commuting_pairs = n_total_pairs - n_noncommuting_pairs

print("=== Fermionic noncommutation graph summary ===")
print("Number of vertices / fermionic terms:", n_vertices)
print("Number of total unordered pairs:", n_total_pairs)
print("Number of noncommuting pairs / edges:", n_noncommuting_pairs)
print("Number of commuting pairs:", n_commuting_pairs)
print("Is graph bipartite?", nx.is_bipartite(G))


# ------------------------------------------------------------
# Vertex table
# ------------------------------------------------------------

vertex_rows = []

for i, data in G.nodes(data=True):
    vertex_rows.append(
        {
            "vertex": f"T_{i}",
            "degree": G.degree[i],
            "commutes_with_all": G.degree[i] == 0,
            "fermionic_term": data["operator_string"],
        }
    )

vertex_df = pd.DataFrame(vertex_rows)

print("\n=== Vertices: fermionic terms ===")
display(vertex_df)


# ------------------------------------------------------------
# Edge table
# ------------------------------------------------------------

edge_rows = []

for i, j, data in G.edges(data=True):
    edge_rows.append(
        {
            "source": f"T_{i}",
            "target": f"T_{j}",
            "meaning": f"[T_{i}, T_{j}] != 0",
            "commutator": data["commutator_string"],
        }
    )

edge_df = pd.DataFrame(edge_rows)

print("\n=== Edges: noncommuting pairs ===")
display(edge_df)


# # ------------------------------------------------------------
# # Draw graph
# # ------------------------------------------------------------

# plt.figure(figsize=(12, 8))

# pos = nx.kamada_kawai_layout(G)

# node_labels = {
#     i: f"T_{i}"
#     for i in G.nodes()
# }

# node_sizes = [
#     1000 + 250 * G.degree[i]
#     for i in G.nodes()
# ]

# nx.draw_networkx_nodes(G, pos, node_size=node_sizes)
# nx.draw_networkx_edges(G, pos, width=1.5)
# nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=11, font_weight="bold")

# plt.title("H2 Fermionic Noncommutation Graph")
# plt.axis("off")
# plt.show()

=== Fermionic noncommutation graph summary ===
Number of vertices / fermionic terms: 3681
Number of total unordered pairs: 6773040
Number of noncommuting pairs / edges: 3379643
Number of commuting pairs: 3393397
Is graph bipartite? False

=== Vertices: fermionic terms ===

,vertex,degree,commutes_with_all,fermionic_term
0,T_0,0,True,+13.76808795 I
1,T_1,618,False,-3.53595500 a_0^dagger a_0
2,T_2,1210,False,+0.16494262 a_0^dagger a_4 + +0.16494262 a_4^dagger a_0
3,T_3,1210,False,-0.05180673 a_0^dagger a_8 + -0.05180673 a_8^dagger a_0
4,T_4,1210,False,+0.02610640 a_0^dagger a_12 + +0.02610640 a_12^dagger a_0
...,...,...,...,...
3676,T_3676,1974,False,+0.18078400 a_18^dagger a_17^dagger a_19 a_16 + +0.18078400 a_19^dagger a_16^dagger a_18 a_17
3677,T_3677,1113,False,-0.41614532 a_19^dagger a_16^dagger a_19 a_16
3678,T_3678,1113,False,-0.41614532 a_18^dagger a_17^dagger a_18 a_17
3679,T_3679,1056,False,-0.23536132 a_19^dagger a_17^dagger a_19 a_17
3680,T_3680,1113,False,-0.52703315 a_19^dagger a_18^dagger a_19 a_18

=== Edges: noncommuting pairs ===

,source,target,meaning,commutator
0,T_1,T_2,"[T_1, T_2] != 0",-0.58322969 a_0^dagger a_4 + +0.58322969 a_4^dagger a_0
1,T_1,T_3,"[T_1, T_3] != 0",+0.18318628 a_0^dagger a_8 + -0.18318628 a_8^dagger a_0
2,T_1,T_4,"[T_1, T_4] != 0",-0.09231105 a_0^dagger a_12 + +0.09231105 a_12^dagger a_0
3,T_1,T_5,"[T_1, T_5] != 0",-0.07069380 a_0^dagger a_16 + +0.07069380 a_16^dagger a_0
4,T_1,T_62,"[T_1, T_62] != 0",+0.27115672 a_1^dagger a_0^dagger a_4 a_1 + -0.27115672 a_4^dagger a_1^dagger a_1 a_0
...,...,...,...,...
3379638,T_3672,T_3676,"[T_3672, T_3676] != 0",-0.05024987 a_18^dagger a_17^dagger a_15^dagger a_19 a_16 a_15 + +0.05024987 a_19^dagger a_16^dagger a_15^dagger a_18 a_17 a_15
3379639,T_3673,T_3674,"[T_3673, T_3674] != 0",-0.07745133 a_17^dagger a_16^dagger a_19 a_18 + +0.07745133 a_19^dagger a_18^dagger a_17 a_16
3379640,T_3674,T_3680,"[T_3674, T_3680] != 0",-0.09527916 a_17^dagger a_16^dagger a_19 a_18 + +0.09527916 a_19^dagger a_18^dagger a_17 a_16
3379641,T_3676,T_3677,"[T_3676, T_3677] != 0",+0.07523242 a_18^dagger a_17^dagger a_19 a_16 + -0.07523242 a_19^dagger a_16^dagger a_18 a_17
3379642,T_3676,T_3678,"[T_3676, T_3678] != 0",-0.07523242 a_18^dagger a_17^dagger a_19 a_16 + +0.07523242 a_19^dagger a_16^dagger a_18 a_17

In [5]:
print("Same edge set?")
print(set(G.edges()) == set(G_alpha.edges()))

Same edge set?
True

In [6]:
# Cell 3: Color graph, build commuting blocks, map JW/BK, verify commutation

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from itertools import combinations
from openfermion.ops import FermionOperator
from openfermion.transforms import normal_ordered, jordan_wigner, bravyi_kitaev

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# 1. Color the noncommutation graph
# ------------------------------------------------------------
# Since edges mean noncommutation, each color class is a commuting group.

coloring = nx.coloring.greedy_color(G, strategy="largest_first")

color_groups = {}

for node, color in coloring.items():
    color_groups.setdefault(color, []).append(node)

for color in color_groups:
    color_groups[color] = sorted(color_groups[color])

color_names = [
    "red",
    "blue",
    "green",
    "orange",
    "purple",
    "brown",
    "pink",
    "gray",
]

color_name = {
    color: color_names[color] if color < len(color_names) else f"color_{color}"
    for color in color_groups
}

num_grouped_terms = sum(len(nodes) for nodes in color_groups.values())

print("Number of fermionic terms / vertices:", G.number_of_nodes())
print("Number of colors / commuting groups:", len(color_groups))
print("Number of grouped terms:", num_grouped_terms)

assert num_grouped_terms == G.number_of_nodes()


# ------------------------------------------------------------
# 2. Verify each color group is mutually commuting
# ------------------------------------------------------------

def verify_commuting_group(nodes, tol=1e-12):
    for i, j in combinations(nodes, 2):
        A = G.nodes[i]["operator"]
        B = G.nodes[j]["operator"]

        if not commute(A, B, tol=tol):
            return False

    return True


group_summary_rows = []

for color, nodes in sorted(color_groups.items()):
    group_summary_rows.append(
        {
            "color_id": color,
            "color_name": color_name[color],
            "number_of_terms": len(nodes),
            "vertices": [f"T_{i}" for i in nodes],
            "verified_mutually_commuting": verify_commuting_group(nodes),
        }
    )

group_summary_df = pd.DataFrame(group_summary_rows)

print("\n=== Commuting groups from graph coloring ===")
display(group_summary_df)


# ------------------------------------------------------------
# 3. Build Hamiltonian pieces by color
# ------------------------------------------------------------

H_by_color = {}

for color, nodes in sorted(color_groups.items()):
    H_color = FermionOperator.zero()

    for node in nodes:
        H_color += G.nodes[node]["operator"]

    H_color = normal_ordered(H_color)
    H_color.compress(abs_tol=1e-12)

    H_by_color[color] = H_color


color_block_rows = []

for color, nodes in sorted(color_groups.items()):
    for local_index, node in enumerate(nodes, start=1):
        color_block_rows.append(
            {
                "color_block": f"H_{color_name[color]}",
                "local_term_name": f"{color_name[color][0].upper()}_{local_index}",
                "vertex": f"T_{node}",
                "fermionic_term": G.nodes[node]["operator_string"],
            }
        )

color_block_df = pd.DataFrame(color_block_rows)

print("\n=== Which T_i belongs to which color block ===")
display(color_block_df)


print("\n=== Hamiltonian split by commuting color groups ===")

for color, H_color in H_by_color.items():
    nodes = color_groups[color]

    print("\n" + "=" * 80)
    print(f"H_{color_name[color]} consists of:")
    print(" + ".join([f"T_{node}" for node in nodes]))

    print(f"\nSummed operator H_{color_name[color]} =")
    print(H_color)


# ------------------------------------------------------------
# 4. Trotter ordering induced by color groups
# ------------------------------------------------------------

trotter_order = []

for color, nodes in sorted(color_groups.items()):
    for node in nodes:
        trotter_order.append(node)

print("\n=== Trotter order by commuting color groups ===")
print([f"T_{i}" for i in trotter_order])


# ------------------------------------------------------------
# 5. Helper functions for JW/BK output
# ------------------------------------------------------------

def sort_qubit_key(term):
    return (len(term), term)


def format_qubit_term(term):
    if term == ():
        return "I"

    return " ".join([f"{pauli}{qubit}" for qubit, pauli in term])


def qubit_coeff_to_str(c, digits=8):
    c = complex(c)
    if abs(c.imag) < 1e-12:
        return f"{c.real:+.{digits}f}"
    return f"{c.real:+.{digits}f}{c.imag:+.{digits}f}j"


def qubit_operator_to_string(op, digits=8):
    pieces = []

    for term, coeff in sorted(op.terms.items(), key=lambda item: sort_qubit_key(item[0])):
        pieces.append(f"{qubit_coeff_to_str(coeff, digits)} {format_qubit_term(term)}")

    if len(pieces) == 0:
        return "0"

    return " + ".join(pieces)


def apply_bk(op, n_qubits):
    try:
        return bravyi_kitaev(op, n_qubits=n_qubits)
    except TypeError:
        return bravyi_kitaev(op, n_qubits)


def qubit_commutator(A, B, tol=1e-12):
    C = A * B - B * A
    C.compress(abs_tol=tol)
    return C


def qubit_commute(A, B, tol=1e-12):
    C = qubit_commutator(A, B, tol=tol)
    return len(C.terms) == 0


n_qubits = molecule.n_qubits

print("\nNumber of qubits / spin orbitals:", n_qubits)


# ------------------------------------------------------------
# 6. Map each fermionic vertex T_i to JW(T_i) and BK(T_i)
# ------------------------------------------------------------

mapped_rows = []

for node in sorted(G.nodes()):
    T_i = G.nodes[node]["operator"]

    JW_T_i = jordan_wigner(T_i)
    JW_T_i.compress(abs_tol=1e-12)

    BK_T_i = apply_bk(T_i, n_qubits=n_qubits)
    BK_T_i.compress(abs_tol=1e-12)

    G.nodes[node]["JW_operator"] = JW_T_i
    G.nodes[node]["BK_operator"] = BK_T_i
    G.nodes[node]["JW_operator_string"] = qubit_operator_to_string(JW_T_i)
    G.nodes[node]["BK_operator_string"] = qubit_operator_to_string(BK_T_i)

    node_color = coloring[node]
    node_color_name = color_name[node_color]

    mapped_rows.append(
        {
            "color": node_color_name,
            "vertex": f"T_{node}",
            "fermionic_term": G.nodes[node]["operator_string"],
            "number_of_JW_Pauli_strings": len(JW_T_i.terms),
            "JW_transform": qubit_operator_to_string(JW_T_i),
            "number_of_BK_Pauli_strings": len(BK_T_i.terms),
            "BK_transform": qubit_operator_to_string(BK_T_i),
        }
    )

mapped_terms_df = pd.DataFrame(mapped_rows)

print("\n=== Fermionic terms mapped to JW and BK ===")
display(mapped_terms_df)


# ------------------------------------------------------------
# 7. Map each color block H_color to JW and BK
# ------------------------------------------------------------

JW_by_color = {}
BK_by_color = {}

block_rows = []

for color, H_color in sorted(H_by_color.items()):
    JW_color = jordan_wigner(H_color)
    JW_color.compress(abs_tol=1e-12)

    BK_color = apply_bk(H_color, n_qubits=n_qubits)
    BK_color.compress(abs_tol=1e-12)

    JW_by_color[color] = JW_color
    BK_by_color[color] = BK_color

    block_rows.append(
        {
            "color_block": f"H_{color_name[color]}",
            "fermionic_vertices": " + ".join([f"T_{node}" for node in color_groups[color]]),
            "number_of_fermionic_terms": len(color_groups[color]),
            "number_of_JW_Pauli_strings": len(JW_color.terms),
            "JW_block": qubit_operator_to_string(JW_color),
            "number_of_BK_Pauli_strings": len(BK_color.terms),
            "BK_block": qubit_operator_to_string(BK_color),
        }
    )

block_map_df = pd.DataFrame(block_rows)

print("\n=== Color blocks mapped to JW and BK ===")
display(block_map_df)


# ------------------------------------------------------------
# 8. Verify same-color terms commute after JW and BK
# ------------------------------------------------------------

verification_rows = []

for color, nodes in sorted(color_groups.items()):
    for i, j in combinations(nodes, 2):
        Ti = G.nodes[i]["operator"]
        Tj = G.nodes[j]["operator"]

        JW_Ti = G.nodes[i]["JW_operator"]
        JW_Tj = G.nodes[j]["JW_operator"]

        BK_Ti = G.nodes[i]["BK_operator"]
        BK_Tj = G.nodes[j]["BK_operator"]

        verification_rows.append(
            {
                "color_group": color_name[color],
                "pair": f"T_{i}, T_{j}",
                "fermionic_commute": commute(Ti, Tj),
                "JW_commute": qubit_commute(JW_Ti, JW_Tj),
                "BK_commute": qubit_commute(BK_Ti, BK_Tj),
            }
        )

verification_df = pd.DataFrame(verification_rows)

print("\n=== Verify commuting groups after JW/BK mapping ===")
display(verification_df)

Number of fermionic terms / vertices: 3681
Number of colors / commuting groups: 277
Number of grouped terms: 3681

=== Commuting groups from graph coloring ===

,color_id,color_name,number_of_terms,vertices,verified_mutually_commuting
0,0,red,17,"[T_0, T_72, T_190, T_206, T_849, T_1318, T_1425, T_3214, T_3254, T_3258, T_3385, T_3456, T_3485, T_3674, T_3675, T_3676, T_3679]",True
1,1,blue,20,"[T_57, T_58, T_59, T_60, T_73, T_207, T_332, T_861, T_1319, T_1426, T_1891, T_2306, T_2369, T_2385, T_2895, T_2953, T_3673, T_3677, T_3678, T_3680]",True
2,2,green,12,"[T_82, T_192, T_347, T_980, T_1320, T_1427, T_2542, T_2617, T_2692, T_2874, T_3244, T_3286]",True
3,3,orange,15,"[T_83, T_334, T_348, T_992, T_1321, T_1428, T_1886, T_2215, T_2368, T_2378, T_2894, T_2952, T_3653, T_3658, T_3661]",True
4,4,purple,12,"[T_84, T_349, T_468, T_981, T_1327, T_1538, T_2214, T_2285, T_2377, T_2688, T_3075, T_3128]",True
...,...,...,...,...,...
272,272,color_272,5,"[T_1745, T_3179, T_3428, T_3593, T_3614]",True
273,273,color_273,4,"[T_482, T_2873, T_3180, T_3360]",True
274,274,color_274,5,"[T_2459, T_2606, T_2945, T_3409, T_3556]",True
275,275,color_275,5,"[T_991, T_2196, T_3007, T_3256, T_3327]",True
276,276,color_276,2,"[T_3303, T_3515]",True

=== Which T_i belongs to which color block ===

,color_block,local_term_name,vertex,fermionic_term
0,H_red,R_1,T_0,+13.76808795 I
1,H_red,R_2,T_72,-0.08917190 a_1^dagger a_0^dagger a_5 a_4 + -0.08917190 a_5^dagger a_4^dagger a_1 a_0
2,H_red,R_3,T_190,+0.06346349 a_4^dagger a_0^dagger a_6 a_2 + +0.06346349 a_6^dagger a_2^dagger a_4 a_0
3,H_red,R_4,T_206,+0.08917190 a_4^dagger a_1^dagger a_5 a_0 + +0.08917190 a_5^dagger a_0^dagger a_4 a_1
4,H_red,R_5,T_849,+0.06346349 a_5^dagger a_1^dagger a_7 a_3 + +0.06346349 a_7^dagger a_3^dagger a_5 a_1
...,...,...,...,...
3676,H_color_275,C_3,T_3007,+0.00451985 a_18^dagger a_6^dagger a_18 a_14 + +0.00451985 a_18^dagger a_14^dagger a_18 a_6
3677,H_color_275,C_4,T_3256,+0.06584760 a_12^dagger a_8^dagger a_16 a_12 + +0.06584760 a_16^dagger a_12^dagger a_12 a_8
3678,H_color_275,C_5,T_3327,+0.00022904 a_18^dagger a_8^dagger a_18 a_16 + +0.00022904 a_18^dagger a_16^dagger a_18 a_8
3679,H_color_276,C_1,T_3303,-0.02327134 a_16^dagger a_8^dagger a_16 a_12 + -0.02327134 a_16^dagger a_12^dagger a_16 a_8
3680,H_color_276,C_2,T_3515,+0.06180430 a_18^dagger a_10^dagger a_18 a_14 + +0.06180430 a_18^dagger a_14^dagger a_18 a_10

=== Hamiltonian split by commuting color groups ===

================================================================================
H_red consists of:
T_0 + T_72 + T_190 + T_206 + T_849 + T_1318 + T_1425 + T_3214 + T_3254 + T_3258 + T_3385 + T_3456 + T_3485 + T_3674 + T_3675 + T_3676 + T_3679

Summed operator H_red =
13.76808794966473 [] +
-0.08917189612324626 [1^ 0^ 5 4] +
-0.08234631449163567 [3^ 2^ 7 6] +
0.06346348937483284 [4^ 0^ 6 2] +
0.08917189612324626 [4^ 1^ 5 0] +
0.08917189612324626 [5^ 0^ 4 1] +
0.06346348937483284 [5^ 1^ 7 3] +
-0.08917189612324626 [5^ 4^ 1 0] +
0.06346348937483284 [6^ 2^ 4 0] +
0.08234631449163567 [6^ 3^ 7 2] +
0.08234631449163567 [7^ 2^ 6 3] +
0.06346348937483284 [7^ 3^ 5 1] +
-0.08234631449163567 [7^ 6^ 3 2] +
-0.07488299483703216 [9^ 8^ 13 12] +
-0.08664522034359738 [11^ 10^ 15 14] +
0.08888469474343709 [12^ 8^ 14 10] +
0.07488299483703216 [12^ 9^ 13 8] +
0.07488299483703216 [13^ 8^ 12 9] +
0.08888469474343709 [13^ 9^ 15 11] +
-0.07488299483703216 [13^ 12^ 9 8] +
0.08888469474343709 [14^ 10^ 12 8] +
0.08664522034359738 [14^ 11^ 15 10] +
0.08664522034359738 [15^ 10^ 14 11] +
0.08888469474343709 [15^ 11^ 13 9] +
-0.08664522034359738 [15^ 14^ 11 10] +
-0.18078400058194347 [17^ 16^ 19 18] +
-0.23536131754871265 [18^ 16^ 18 16] +
0.18078400058194347 [18^ 17^ 19 16] +
0.18078400058194347 [19^ 16^ 18 17] +
-0.23536131754871265 [19^ 17^ 19 17] +
-0.18078400058194347 [19^ 18^ 17 16]

================================================================================
H_blue consists of:
T_57 + T_58 + T_59 + T_60 + T_73 + T_207 + T_332 + T_861 + T_1319 + T_1426 + T_1891 + T_2306 + T_2369 + T_2385 + T_2895 + T_2953 + T_3673 + T_3677 + T_3678 + T_3680

Summed operator H_blue =
0.04112529779298367 [1^ 0^ 8 5] +
-0.009903252444674488 [3^ 2^ 10 7] +
0.04112529779298367 [5^ 0^ 8 1] +
-0.015793784021587477 [5^ 1^ 15 11] +
-0.009903252444674488 [7^ 2^ 10 3] +
-0.03730414581095066 [7^ 3^ 13 9] +
-0.06440990709565318 [8^ 0^ 10 2] +
0.04112529779298367 [8^ 1^ 5 0] +
0.04112529779298367 [8^ 5^ 1 0] +
0.0038193996327045517 [9^ 4^ 13 12] +
-0.06440990709565318 [10^ 2^ 8 0] +
-0.009903252444674488 [10^ 3^ 7 2] +
-0.009903252444674488 [10^ 7^ 3 2] +
0.008039109461132865 [11^ 6^ 15 14] +
-0.08526326225265098 [12^ 4^ 14 6] +
-0.0038193996327045517 [12^ 9^ 13 4] +
-0.0038193996327045517 [13^ 4^ 12 9] +
-0.037304145810950665 [13^ 9^ 7 3] +
0.0038193996327045517 [13^ 12^ 9 4] +
-0.08526326225265098 [14^ 6^ 12 4] +
-0.008039109461132865 [14^ 11^ 15 6] +
-0.008039109461132865 [15^ 6^ 14 11] +
-0.015793784021587473 [15^ 11^ 5 1] +
0.008039109461132865 [15^ 14^ 11 6] +
-1.5928116999147799 [16^ 16] +
-0.42841918109234306 [17^ 16^ 17 16] +
-1.5928116999147799 [17^ 17] +
-0.41614531813065614 [18^ 17^ 18 17] +
-1.3346274846046098 [18^ 18] +
-0.41614531813065614 [19^ 16^ 19 16] +
-0.5270331502964435 [19^ 18^ 19 18] +
-1.3346274846046098 [19^ 19]

================================================================================
H_green consists of:
T_82 + T_192 + T_347 + T_980 + T_1320 + T_1427 + T_2542 + T_2617 + T_2692 + T_2874 + T_3244 + T_3286

Summed operator H_green =
-0.04112529779298367 [1^ 0^ 9 4] +
-0.023737733775914614 [3^ 2^ 14 7] +
0.0017463306745329895 [4^ 0^ 14 2] +
0.04112529779298367 [4^ 1^ 9 0] +
0.013101847559799042 [6^ 5^ 13 10] +
-0.023737733775914614 [7^ 2^ 14 3] +
-0.04521328153916422 [7^ 3^ 9 1] +
0.04112529779298367 [9^ 0^ 4 1] +
-0.04521328153916421 [9^ 1^ 7 3] +
-0.04112529779298367 [9^ 4^ 1 0] +
0.013101847559799042 [10^ 5^ 13 6] +
0.09063672153602949 [10^ 6^ 12 8] +
0.06569441334417352 [11^ 8^ 15 12] +
0.09063672153602947 [12^ 8^ 10 6] +
-0.06569441334417352 [12^ 11^ 15 8] +
0.010304776638963387 [13^ 5^ 15 11] +
0.013101847559799042 [13^ 6^ 10 5] +
0.013101847559799042 [13^ 10^ 6 5] +
0.0017463306745329897 [14^ 2^ 4 0] +
-0.023737733775914614 [14^ 3^ 7 2] +
-0.023737733775914614 [14^ 7^ 3 2] +
-0.06569441334417352 [15^ 8^ 12 11] +
0.010304776638963387 [15^ 11^ 13 5] +
0.06569441334417352 [15^ 12^ 11 8]

================================================================================
H_orange consists of:
T_83 + T_334 + T_348 + T_992 + T_1321 + T_1428 + T_1886 + T_2215 + T_2368 + T_2378 + T_2894 + T_2952 + T_3653 + T_3658 + T_3661

Summed operator H_orange =
-0.05952844459691587 [1^ 0^ 9 8] +
0.0017889393795801525 [3^ 2^ 18 7] +
-0.05244300010668274 [5^ 4^ 13 12] +
0.0017889393795801525 [7^ 2^ 18 3] +
-0.0013928043888039657 [7^ 3^ 13 5] +
-0.0019295728923311621 [8^ 0^ 18 2] +
0.05952844459691587 [8^ 1^ 9 0] +
0.05952844459691587 [9^ 0^ 8 1] +
-0.0030485357525685593 [9^ 1^ 15 11] +
-0.05952844459691587 [9^ 8^ 1 0] +
-0.0456097811344779 [10^ 6^ 12 4] +
-0.06337003459633271 [11^ 6^ 15 10] +
-0.06337003459633271 [11^ 10^ 15 6] +
-0.045609781134477896 [12^ 4^ 10 6] +
0.05244300010668274 [12^ 5^ 13 4] +
0.05244300010668274 [13^ 4^ 12 5] +
-0.0013928043888039657 [13^ 5^ 7 3] +
-0.05244300010668274 [13^ 12^ 5 4] +
-0.06337003459633271 [15^ 6^ 11 10] +
-0.06337003459633271 [15^ 10^ 11 6] +
-0.003048535752568559 [15^ 11^ 9 1] +
-0.2433519054412561 [16^ 14^ 16 14] +
-0.11484139870205867 [17^ 14^ 19 16] +
-0.11484139870205867 [17^ 16^ 19 14] +
-0.0019295728923311621 [18^ 2^ 8 0] +
0.0017889393795801525 [18^ 3^ 7 2] +
0.0017889393795801525 [18^ 7^ 3 2] +
-0.11484139870205867 [19^ 14^ 17 16] +
-0.11484139870205867 [19^ 16^ 17 14]

================================================================================
H_purple consists of:
T_84 + T_349 + T_468 + T_981 + T_1327 + T_1538 + T_2214 + T_2285 + T_2377 + T_2688 + T_3075 + T_3128

Summed operator H_purple =
0.02449231220768852 [1^ 0^ 12 9] +
0.009903252444674488 [3^ 2^ 11 6] +
-0.002853839441732839 [5^ 4^ 13 8] +
-0.022509840411923405 [6^ 2^ 12 0] +
-0.009903252444674488 [6^ 3^ 11 2] +
0.040336495980458534 [8^ 4^ 14 10] +
0.002853839441732839 [8^ 5^ 13 4] +
0.02449231220768852 [9^ 0^ 12 1] +
-0.06440990709565318 [9^ 1^ 11 3] +
-0.008039109461132865 [10^ 7^ 15 14] +
-0.009903252444674488 [11^ 2^ 6 3] +
-0.06440990709565318 [11^ 3^ 9 1] +
0.009903252444674488 [11^ 6^ 3 2] +
-0.02250984041192341 [12^ 0^ 6 2] +
0.02449231220768852 [12^ 1^ 9 0] +
0.02449231220768852 [12^ 9^ 1 0] +
0.002853839441732839 [13^ 4^ 8 5] +
-0.08526326225265098 [13^ 5^ 15 7] +
-0.002853839441732839 [13^ 8^ 5 4] +
-0.008039109461132865 [14^ 7^ 15 10] +
0.040336495980458534 [14^ 10^ 8 4] +
-0.08526326225265098 [15^ 7^ 13 5] +
-0.008039109461132865 [15^ 10^ 14 7] +
-0.008039109461132865 [15^ 14^ 10 7]

================================================================================
H_brown consists of:
T_85 + T_350 + T_602 + T_988 + T_1328 + T_1539 + T_1991 + T_2222 + T_2281 + T_2461 + T_2826 + T_2947 + T_3590 + T_3612 + T_3616 + T_3645

Summed operator H_brown =
-0.002376317579986217 [1^ 0^ 16 9] +
-0.05401389110132789 [3^ 2^ 11 10] +
-0.002117987376318929 [5^ 4^ 17 8] +
-0.05068479290907725 [7^ 6^ 15 14] +
-0.005311407070490388 [8^ 4^ 14 6] +
0.002117987376318929 [8^ 5^ 17 4] +
-0.002376317579986217 [9^ 0^ 16 1] +
0.03364636527056024 [9^ 1^ 15 7] +
-0.03589737379274035 [10^ 2^ 16 0] +
0.05401389110132789 [10^ 3^ 11 2] +
0.05401389110132789 [11^ 2^ 10 3] +
-0.007334311131213931 [11^ 3^ 17 5] +
-0.05401389110132789 [11^ 10^ 3 2] +
-0.07860755173718562 [13^ 12^ 19 18] +
-0.005311407070490387 [14^ 6^ 8 4] +
0.05068479290907725 [14^ 7^ 15 6] +
0.05068479290907725 [15^ 6^ 14 7] +
0.03364636527056023 [15^ 7^ 9 1] +
-0.05068479290907725 [15^ 14^ 7 6] +
-0.03589737379274035 [16^ 0^ 10 2] +
-0.002376317579986217 [16^ 1^ 9 0] +
-0.002376317579986217 [16^ 9^ 1 0] +
0.002117987376318929 [17^ 4^ 8 5] +
-0.007334311131213931 [17^ 5^ 11 3] +
-0.002117987376318929 [17^ 8^ 5 4] +
-0.2919061535735937 [18^ 12^ 18 12] +
0.07860755173718562 [18^ 13^ 19 12] +
0.07860755173718562 [19^ 12^ 18 13] +
-0.2919061535735937 [19^ 13^ 19 13] +
-0.07860755173718562 [19^ 18^ 13 12]

================================================================================
H_pink consists of:
T_93 + T_333 + T_485 + T_1108 + T_1329 + T_1540 + T_2207 + T_2290 + T_2366 + T_2608 + T_2825 + T_2871 + T_2946

Summed operator H_pink =
-0.02449231220768852 [1^ 0^ 13 8] +
-0.0016477398184450774 [3^ 2^ 14 11] +
0.002853839441732839 [5^ 4^ 12 9] +
-0.007130177700726229 [7^ 6^ 15 10] +
0.040355808284188666 [8^ 0^ 14 2] +
0.02449231220768852 [8^ 1^ 13 0] +
0.002853839441732839 [9^ 4^ 12 5] +
-0.005311407070490388 [9^ 5^ 15 7] +
-0.24360536826861992 [10^ 6^ 10 6] +
0.007130177700726229 [10^ 7^ 15 6] +
-0.0016477398184450774 [11^ 2^ 14 3] +
0.06447466866529208 [11^ 3^ 13 1] +
-0.270787444301926 [12^ 4^ 12 4] +
0.002853839441732839 [12^ 5^ 9 4] +
0.002853839441732839 [12^ 9^ 5 4] +
0.02449231220768852 [13^ 0^ 8 1] +
0.06447466866529207 [13^ 1^ 11 3] +
-0.02449231220768852 [13^ 8^ 1 0] +
0.04035580828418866 [14^ 2^ 8 0] +
-0.0016477398184450774 [14^ 3^ 11 2] +
-0.0016477398184450774 [14^ 11^ 3 2] +
0.007130177700726229 [15^ 6^ 10 7] +
-0.005311407070490387 [15^ 7^ 9 5] +
-0.007130177700726229 [15^ 10^ 7 6]

================================================================================
H_gray consists of:
T_94 + T_471 + T_486 + T_1116 + T_1330 + T_1541 + T_1989 + T_2206 + T_2280 + T_2289 + T_2832 + T_3008 + T_3650 + T_3655 + T_3667

Summed operator H_gray =
-0.03748072649406497 [1^ 0^ 13 12] +
-0.017123116659221588 [3^ 2^ 18 11] +
-0.08184484642324433 [5^ 4^ 9 8] +
0.003048966924395 [7^ 6^ 19 10] +
0.0783071306560898 [8^ 4^ 10 6] +
0.08184484642324433 [8^ 5^ 9 4] +
0.08184484642324433 [9^ 4^ 8 5] +
-0.03214600506153949 [9^ 5^ 11 3] +
-0.08184484642324433 [9^ 8^ 5 4] +
0.0783071306560898 [10^ 6^ 8 4] +
-0.003048966924395 [10^ 7^ 19 6] +
-0.017123116659221588 [11^ 2^ 18 3] +
-0.03214600506153949 [11^ 3^ 9 5] +
-0.038681333623135056 [12^ 0^ 18 2] +
0.03748072649406497 [12^ 1^ 13 0] +
0.03748072649406497 [13^ 0^ 12 1] +
-0.047316785358446675 [13^ 1^ 19 7] +
-0.03748072649406497 [13^ 12^ 1 0] +
-0.1308487500375221 [15^ 14^ 17 16] +
0.1308487500375221 [16^ 15^ 17 14] +
0.1308487500375221 [17^ 14^ 16 15] +
-0.2433519054412561 [17^ 15^ 17 15] +
-0.1308487500375221 [17^ 16^ 15 14] +
-0.038681333623135056 [18^ 2^ 12 0] +
-0.017123116659221588 [18^ 3^ 11 2] +
-0.017123116659221588 [18^ 11^ 3 2] +
-0.003048966924395 [19^ 6^ 10 7] +
-0.047316785358446675 [19^ 7^ 13 1] +
0.003048966924395 [19^ 10^ 7 6]

================================================================================
H_color_8 consists of:
T_95 + T_487 + T_601 + T_1109 + T_1336 + T_1647 + T_2223 + T_2373 + T_2462 + T_2763 + T_3074 + T_3127 + T_3224 + T_3321 + T_3330 + T_3443

Summed operator H_color_8 =
-0.01842076320939725 [1^ 0^ 16 13] +
0.023737733775914614 [3^ 2^ 15 6] +
-0.00876445401697894 [5^ 4^ 17 12] +
-0.0035243245488600465 [6^ 2^ 16 0] +
-0.023737733775914614 [6^ 3^ 15 2] +
-0.050860575277343265 [9^ 8^ 19 18] +
-0.06337003459633271 [10^ 7^ 14 11] +
0.0013708220092438581 [11^ 7^ 17 5] +
0.06337003459633271 [11^ 10^ 14 7] +
0.010304776638963387 [12^ 4^ 14 10] +
0.00876445401697894 [12^ 5^ 17 4] +
-0.01842076320939725 [13^ 0^ 16 1] +
0.07684679905955737 [13^ 1^ 15 3] +
0.06337003459633271 [14^ 7^ 11 10] +
0.010304776638963387 [14^ 10^ 12 4] +
-0.06337003459633271 [14^ 11^ 10 7] +
-0.023737733775914614 [15^ 2^ 6 3] +
0.07684679905955735 [15^ 3^ 13 1] +
0.023737733775914614 [15^ 6^ 3 2] +
-0.003524324548860047 [16^ 0^ 6 2] +
-0.01842076320939725 [16^ 1^ 13 0] +
-0.01842076320939725 [16^ 13^ 1 0] +
0.00876445401697894 [17^ 4^ 12 5] +
0.0013708220092438581 [17^ 5^ 11 7] +
-0.00876445401697894 [17^ 12^ 5 4] +
-0.32145741952015106 [18^ 8^ 18 8] +
0.050860575277343265 [18^ 9^ 19 8] +
0.050860575277343265 [19^ 8^ 18 9] +
-0.32145741952015106 [19^ 9^ 19 9] +
-0.050860575277343265 [19^ 18^ 9 8]

================================================================================
H_color_9 consists of:
T_49 + T_51 + T_103 + T_339 + T_618 + T_1232 + T_1337 + T_1528 + T_1648 + T_2208 + T_2291 + T_2607 + T_2819 + T_2881 + T_3583 + T_3620 + T_3643

Summed operator H_color_9 =
0.002376317579986217 [1^ 0^ 17 8] +
0.0016477398184450774 [3^ 2^ 15 10] +
0.002117987376318929 [5^ 4^ 16 9] +
0.007130177700726229 [7^ 6^ 14 11] +
0.03364636527056024 [8^ 0^ 14 6] +
-0.002376317579986217 [8^ 1^ 17 0] +
0.002117987376318929 [9^ 4^ 16 5] +
0.0783071306560898 [9^ 5^ 11 7] +
-0.007334311131213931 [10^ 2^ 16 4] +
-0.0016477398184450774 [10^ 3^ 15 2] +
0.007130177700726229 [11^ 6^ 14 7] +
0.0783071306560898 [11^ 7^ 9 5] +
-2.274883451576758 [12^ 12] +
-0.3502784334772662 [13^ 12^ 13 12] +
-2.274883451576758 [13^ 13] +
0.03364636527056023 [14^ 6^ 8 0] +
0.007130177700726229 [14^ 7^ 11 6] +
0.007130177700726229 [14^ 11^ 7 6] +
-0.0016477398184450774 [15^ 2^ 10 3] +
0.07552441827302582 [15^ 3^ 17 1] +
0.0016477398184450774 [15^ 10^ 3 2] +
-0.007334311131213931 [16^ 4^ 10 2] +
0.002117987376318929 [16^ 5^ 9 4] +
0.002117987376318929 [16^ 9^ 5 4] +
-0.002376317579986217 [17^ 0^ 8 1] +
0.0755244182730258 [17^ 1^ 15 3] +
0.002376317579986217 [17^ 8^ 1 0] +
-0.3705137053107793 [18^ 13^ 18 13] +
-0.3705137053107793 [19^ 12^ 19 12]

================================================================================
H_color_10 consists of:
T_37 + T_40 + T_104 + T_470 + T_619 + T_1237 + T_1338 + T_1649 + T_2090 + T_2216 + T_2379 + T_2452 + T_2818 + T_2880 + T_3207 + T_3341 + T_3440

Summed operator H_color_10 =
0.01842076320939725 [1^ 0^ 17 12] +
-0.037282261408551204 [3^ 2^ 15 14] +
0.00876445401697894 [5^ 4^ 16 13] +
-0.07432854139330318 [7^ 6^ 11 10] +
-2.8215353814457624 [8^ 8] +
-0.3358331388731805 [9^ 8^ 9 8] +
-2.8215353814457624 [9^ 9] +
0.0013708220092438581 [10^ 6^ 16 4] +
0.07432854139330318 [10^ 7^ 11 6] +
0.07432854139330318 [11^ 6^ 10 7] +
-0.018546561054026835 [11^ 7^ 17 1] +
-0.07432854139330318 [11^ 10^ 7 6] +
0.07684679905955737 [12^ 0^ 14 2] +
-0.01842076320939725 [12^ 1^ 17 0] +
0.00876445401697894 [13^ 4^ 16 5] +
0.06198524867742539 [13^ 5^ 15 3] +
0.07684679905955735 [14^ 2^ 12 0] +
0.037282261408551204 [14^ 3^ 15 2] +
0.037282261408551204 [15^ 2^ 14 3] +
0.061985248677425386 [15^ 3^ 13 5] +
-0.037282261408551204 [15^ 14^ 3 2] +
0.0013708220092438581 [16^ 4^ 10 6] +
0.00876445401697894 [16^ 5^ 13 4] +
0.00876445401697894 [16^ 13^ 5 4] +
-0.01842076320939725 [17^ 0^ 12 1] +
-0.018546561054026838 [17^ 1^ 11 7] +
0.01842076320939725 [17^ 12^ 1 0] +
-0.3723179947974943 [18^ 9^ 18 9] +
-0.3723179947974943 [19^ 8^ 19 8]

================================================================================
H_color_11 consists of:
T_105 + T_604 + T_620 + T_1229 + T_1339 + T_1650 + T_2089 + T_2258 + T_2277 + T_2339 + T_2541 + T_2616 + T_3084 + T_3589 + T_3591 + T_3615

Summed operator H_color_11 =
-0.03102463937596435 [1^ 0^ 17 16] +
0.0093623446423475 [3^ 2^ 18 15] +
0.06151008118909826 [6^ 5^ 10 9] +
0.06151008118909826 [7^ 4^ 11 8] +
-0.23357937518481936 [8^ 4^ 8 4] +
-0.06151008118909826 [8^ 7^ 11 4] +
0.00999400088357183 [9^ 5^ 15 3] +
-0.06151008118909826 [9^ 6^ 10 5] +
-0.06151008118909826 [10^ 5^ 9 6] +
0.06151008118909826 [10^ 9^ 6 5] +
-0.06151008118909826 [11^ 4^ 8 7] +
-0.24360536826861992 [11^ 7^ 11 7] +
0.06151008118909826 [11^ 8^ 7 4] +
0.0012449605946019335 [13^ 12^ 19 14] +
-0.23477287927077822 [14^ 12^ 14 12] +
-0.0012449605946019335 [14^ 13^ 19 12] +
0.0093623446423475 [15^ 2^ 18 3] +
0.009994000883571826 [15^ 3^ 9 5] +
0.12248568441726058 [16^ 0^ 18 2] +
0.03102463937596435 [16^ 1^ 17 0] +
0.03102463937596435 [17^ 0^ 16 1] +
-0.32850106900740583 [17^ 1^ 17 1] +
-0.03102463937596435 [17^ 16^ 1 0] +
0.12248568441726056 [18^ 2^ 16 0] +
0.0093623446423475 [18^ 3^ 15 2] +
0.0093623446423475 [18^ 15^ 3 2] +
-0.0012449605946019335 [19^ 12^ 14 13] +
0.0012449605946019335 [19^ 14^ 13 12]

================================================================================
H_color_12 consists of:
T_152 + T_203 + T_284 + T_741 + T_859 + T_865 + T_1420 + T_1893 + T_3215 + T_3259 + T_3457 + T_3486 + T_3610 + T_3618

Summed operator H_color_12 =
0.05418875522576996 [2^ 1^ 6 5] +
0.05418875522576996 [3^ 0^ 7 4] +
0.005480854565000287 [4^ 0^ 18 10] +
-0.05418875522576996 [4^ 3^ 7 0] +
0.021845611063805264 [5^ 1^ 13 9] +
-0.05418875522576996 [5^ 2^ 6 1] +
-0.05418875522576996 [6^ 1^ 5 2] +
-0.00011147418521139903 [6^ 2^ 16 8] +
0.05418875522576996 [6^ 5^ 2 1] +
-0.05418875522576996 [7^ 0^ 4 3] +
0.025644790917673573 [7^ 3^ 15 11] +
0.05418875522576996 [7^ 4^ 3 0] +
-0.008403376528763752 [9^ 8^ 16 13] +
-0.006518456417995144 [11^ 10^ 18 15] +
-0.008403376528763752 [13^ 8^ 16 9] +
0.021845611063805264 [13^ 9^ 5 1] +
-0.006518456417995144 [15^ 10^ 18 11] +
0.02564479091767357 [15^ 11^ 7 3] +
-0.00011147418521139903 [16^ 8^ 6 2] +
-0.008403376528763752 [16^ 9^ 13 8] +
-0.008403376528763752 [16^ 13^ 9 8] +
-0.10403275710737851 [17^ 12^ 19 14] +
-0.10403275710737851 [17^ 14^ 19 12] +
0.005480854565000286 [18^ 10^ 4 0] +
-0.006518456417995144 [18^ 11^ 15 10] +
-0.006518456417995144 [18^ 15^ 11 10] +
-0.10403275710737851 [19^ 12^ 17 14] +
-0.10403275710737851 [19^ 14^ 17 12]

================================================================================
H_color_13 consists of:
T_153 + T_285 + T_331 + T_742 + T_866 + T_993 + T_1887 + T_2224 + T_2457 + T_2463 + T_3461 + T_3516 + T_3586 + T_3596 + T_3628

Summed operator H_color_13 =
0.0196474186697247 [2^ 1^ 9 6] +
0.0196474186697247 [3^ 0^ 8 7] +
-0.03528539539224342 [5^ 4^ 17 16] +
0.0196474186697247 [6^ 1^ 9 2] +
-0.04521328153916422 [6^ 2^ 8 0] +
0.0196474186697247 [7^ 0^ 8 3] +
-0.013220215440336067 [7^ 3^ 17 5] +
-0.04521328153916421 [8^ 0^ 6 2] +
0.0196474186697247 [8^ 3^ 7 0] +
0.0196474186697247 [8^ 7^ 3 0] +
0.024356273212190326 [9^ 1^ 19 11] +
0.0196474186697247 [9^ 2^ 6 1] +
0.0196474186697247 [9^ 6^ 2 1] +
0.006518456417995144 [11^ 10^ 19 14] +
-0.0012449605946019335 [13^ 12^ 18 15] +
0.01326340591977588 [14^ 10^ 16 4] +
-0.006518456417995144 [14^ 11^ 19 10] +
-0.0012449605946019335 [15^ 12^ 18 13] +
-0.23477287927077822 [15^ 13^ 15 13] +
0.01326340591977588 [16^ 4^ 14 10] +
0.03528539539224342 [16^ 5^ 17 4] +
0.03528539539224342 [17^ 4^ 16 5] +
-0.013220215440336067 [17^ 5^ 7 3] +
-0.03528539539224342 [17^ 16^ 5 4] +
-0.0012449605946019335 [18^ 13^ 15 12] +
-0.0012449605946019335 [18^ 15^ 13 12] +
-0.006518456417995144 [19^ 10^ 14 11] +
0.024356273212190322 [19^ 11^ 9 1] +
0.006518456417995144 [19^ 14^ 11 10]

================================================================================
H_color_14 consists of:
T_154 + T_286 + T_481 + T_743 + T_867 + T_1107 + T_1413 + T_2313 + T_2468 + T_2716 + T_2722 + T_2752 + T_3427 + T_3462 + T_3517

Summed operator H_color_14 =
0.02465250820300821 [2^ 1^ 13 6] +
0.02465250820300821 [3^ 0^ 12 7] +
0.02465250820300821 [6^ 1^ 13 2] +
-0.07645879170954739 [6^ 2^ 8 4] +
0.02465250820300821 [7^ 0^ 12 3] +
-0.022509840411923405 [7^ 3^ 13 1] +
-0.07645879170954739 [8^ 4^ 6 2] +
-0.0017293728281211475 [9^ 4^ 17 8] +
-0.0017293728281211475 [9^ 8^ 17 4] +
-0.06444377541383067 [11^ 10^ 19 18] +
0.02096990126926023 [12^ 0^ 18 10] +
0.02465250820300821 [12^ 3^ 7 0] +
0.02465250820300821 [12^ 7^ 3 0] +
-0.02250984041192341 [13^ 1^ 7 3] +
0.02465250820300821 [13^ 2^ 6 1] +
0.02465250820300821 [13^ 6^ 2 1] +
0.02812104880955098 [14^ 5^ 16 15] +
-0.2935499941821788 [15^ 5^ 15 5] +
-0.02812104880955098 [15^ 14^ 16 5] +
-0.02812104880955098 [16^ 5^ 15 14] +
0.02812104880955098 [16^ 15^ 14 5] +
-0.0017293728281211475 [17^ 4^ 9 8] +
-0.0017293728281211475 [17^ 8^ 9 4] +
0.07999595505620467 [17^ 9^ 19 11] +
0.02096990126926023 [18^ 10^ 12 0] +
0.06444377541383067 [18^ 11^ 19 10] +
0.06444377541383067 [19^ 10^ 18 11] +
0.07999595505620467 [19^ 11^ 17 9] +
-0.06444377541383067 [19^ 18^ 11 10]

================================================================================
H_color_15 consists of:
T_155 + T_287 + T_613 + T_744 + T_868 + T_1230 + T_1409 + T_2305 + T_2384 + T_2643 + T_2682 + T_2783 + T_3388 + T_3495 + T_3520

Summed operator H_color_15 =
-0.001935141158246979 [2^ 1^ 17 6] +
-0.001935141158246979 [3^ 0^ 16 7] +
-0.001935141158246979 [6^ 1^ 17 2] +
-0.22911019852192666 [6^ 2^ 6 2] +
-0.001935141158246979 [7^ 0^ 16 3] +

,color,vertex,fermionic_term,number_of_JW_Pauli_strings,JW_transform,number_of_BK_Pauli_strings,BK_transform
0,red,T_0,+13.76808795 I,1,+13.76808795 I,1,+13.76808795 I
1,color_87,T_1,-3.53595500 a_0^dagger a_0,2,-1.76797750 I + +1.76797750 Z0,2,-1.76797750 I + +1.76797750 Z0
2,color_222,T_2,+0.16494262 a_0^dagger a_4 + +0.16494262 a_4^dagger a_0,2,+0.08247131 X0 Z1 Z2 Z3 X4 + +0.08247131 Y0 Z1 Z2 Z3 Y4,2,+0.08247131 X0 X1 Y3 Y4 X5 + -0.08247131 Y0 X1 Y3 X4 X5
3,color_93,T_3,-0.05180673 a_0^dagger a_8 + -0.05180673 a_8^dagger a_0,2,-0.02590337 X0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 X8 + -0.02590337 Y0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Y8,2,-0.02590337 X0 X1 X3 Y7 Y8 X9 X11 + +0.02590337 Y0 X1 X3 Y7 X8 X9 X11
4,color_212,T_4,+0.02610640 a_0^dagger a_12 + +0.02610640 a_12^dagger a_0,2,+0.01305320 X0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 X12 + +0.01305320 Y0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Y12,2,+0.01305320 X0 X1 X3 Y7 Z11 Y12 X13 + -0.01305320 Y0 X1 X3 Y7 Z11 X12 X13
...,...,...,...,...,...,...,...
3676,red,T_3676,+0.18078400 a_18^dagger a_17^dagger a_19 a_16 + +0.18078400 a_19^dagger a_16^dagger a_18 a_17,8,-0.02259800 X16 X17 X18 X19 + -0.02259800 X16 X17 Y18 Y19 + -0.02259800 X16 Y17 X18 Y19 + +0.02259800 X16 Y17 Y18 X19 + +0.02259800 Y16 X17 X18 Y19 + -0.02259800 Y16 X17 Y18 X19 + -0.02259800 Y16 Y17 X18 X19 + -0.02259800 Y16 Y17 Y18 Y19,8,-0.02259800 X16 X18 + -0.02259800 Y16 Y18 + +0.02259800 X16 Z17 X18 + -0.02259800 X16 X18 Z19 + +0.02259800 Y16 Z17 Y18 + -0.02259800 Y16 Y18 Z19 + +0.02259800 X16 Z17 X18 Z19 + +0.02259800 Y16 Z17 Y18 Z19
3677,blue,T_3677,-0.41614532 a_19^dagger a_16^dagger a_19 a_16,4,+0.10403633 I + -0.10403633 Z16 + -0.10403633 Z19 + +0.10403633 Z16 Z19,4,+0.10403633 I + -0.10403633 Z16 + -0.10403633 Z17 Z18 Z19 + +0.10403633 Z16 Z17 Z18 Z19
3678,blue,T_3678,-0.41614532 a_18^dagger a_17^dagger a_18 a_17,4,+0.10403633 I + -0.10403633 Z17 + -0.10403633 Z18 + +0.10403633 Z17 Z18,4,+0.10403633 I + -0.10403633 Z18 + -0.10403633 Z16 Z17 + +0.10403633 Z16 Z17 Z18
3679,red,T_3679,-0.23536132 a_19^dagger a_17^dagger a_19 a_17,4,+0.05884033 I + -0.05884033 Z17 + -0.05884033 Z19 + +0.05884033 Z17 Z19,4,+0.05884033 I + -0.05884033 Z16 Z17 + +0.05884033 Z16 Z18 Z19 + -0.05884033 Z17 Z18 Z19
3680,blue,T_3680,-0.52703315 a_19^dagger a_18^dagger a_19 a_18,4,+0.13175829 I + -0.13175829 Z18 + -0.13175829 Z19 + +0.13175829 Z18 Z19,4,+0.13175829 I + -0.13175829 Z18 + +0.13175829 Z17 Z19 + -0.13175829 Z17 Z18 Z19

=== Color blocks mapped to JW and BK ===

,color_block,fermionic_vertices,number_of_fermionic_terms,number_of_JW_Pauli_strings,JW_block,number_of_BK_Pauli_strings,BK_block
0,H_red,T_0 + T_72 + T_190 + T_206 + T_849 + T_1318 + T_1425 + T_3214 + T_3254 + T_3258 + T_3385 + T_3456 + T_3485 + T_3674 + T_3675 + T_3676 + T_3679,17,59,+13.88576861 I + -0.05884033 Z16 + -0.05884033 Z17 + -0.05884033 Z18 + -0.05884033 Z19 + +0.05884033 Z16 Z18 + +0.05884033 Z17 Z19 + -0.02229297 X0 X1 Y4 Y5 + +0.02229297 X0 Y1 Y4 X5 + +0.02229297 Y0 X1 X4 Y5 + -0.02229297 Y0 Y1 X4 X5 + -0.02058658 X2 X3 Y6 Y7 + +0.02058658 X2 Y3 Y6 X7 + +0.02058658 Y2 X3 X6 Y7 + -0.02058658 Y2 Y3 X6 X7 + -0.01872075 X8 X9 Y12 Y13 + +0.01872075 X8 Y9 Y12 X13 + +0.01872075 Y8 X9 X12 Y13 + -0.01872075 Y8 Y9 X12 X13 + -0.02166131 X10 X11 Y14 Y15 + +0.02166131 X10 Y11 Y14 X15 + +0.02166131 Y10 X11 X14 Y15 + -0.02166131 Y10 Y11 X14 X15 + -0.04519600 X16 X17 Y18 Y19 + +0.04519600 X16 Y17 Y18 X19 + +0.04519600 Y16 X17 X18 Y19 + -0.04519600 Y16 Y17 X18 X19 + -0.00793294 X0 Z1 X2 X4 Z5 X6 + -0.00793294 X0 Z1 X2 Y4 Z5 Y6 + +0.00793294 X0 Z1 Y2 X4 Z5 Y6 + -0.00793294 X0 Z1 Y2 Y4 Z5 X6 + -0.00793294 Y0 Z1 X2 X4 Z5 Y6 + +0.00793294 Y0 Z1 X2 Y4 Z5 X6 + -0.00793294 Y0 Z1 Y2 X4 Z5 X6 + -0.00793294 Y0 Z1 Y2 Y4 Z5 Y6 + -0.00793294 X1 Z2 X3 X5 Z6 X7 + -0.00793294 X1 Z2 X3 Y5 Z6 Y7 + +0.00793294 X1 Z2 Y3 X5 Z6 Y7 + -0.00793294 X1 Z2 Y3 Y5 Z6 X7 + -0.00793294 Y1 Z2 X3 X5 Z6 Y7 + +0.00793294 Y1 Z2 X3 Y5 Z6 X7 + -0.00793294 Y1 Z2 Y3 X5 Z6 X7 + -0.00793294 Y1 Z2 Y3 Y5 Z6 Y7 + -0.01111059 X8 Z9 X10 X12 Z13 X14 + -0.01111059 X8 Z9 X10 Y12 Z13 Y14 + +0.01111059 X8 Z9 Y10 X12 Z13 Y14 + -0.01111059 X8 Z9 Y10 Y12 Z13 X14 + -0.01111059 Y8 Z9 X10 X12 Z13 Y14 + +0.01111059 Y8 Z9 X10 Y12 Z13 X14 + -0.01111059 Y8 Z9 Y10 X12 Z13 X14 + -0.01111059 Y8 Z9 Y10 Y12 Z13 Y14 + -0.01111059 X9 Z10 X11 X13 Z14 X15 + -0.01111059 X9 Z10 X11 Y13 Z14 Y15 + +0.01111059 X9 Z10 Y11 X13 Z14 Y15 + -0.01111059 X9 Z10 Y11 Y13 Z14 X15 + -0.01111059 Y9 Z10 X11 X13 Z14 Y15 + +0.01111059 Y9 Z10 X11 Y13 Z14 X15 + -0.01111059 Y9 Z10 Y11 X13 Z14 X15 + -0.01111059 Y9 Z10 Y11 Y13 Z14 Y15,59,+13.88576861 I + -0.05884033 Z16 + -0.05884033 Z18 + -0.05884033 Z16 Z17 + +0.05884033 Z16 Z18 + +0.02229297 X0 Z1 X4 + +0.02229297 X0 X4 Z5 + +0.02229297 Y0 Z1 Y4 + +0.02229297 Y0 Y4 Z5 + +0.00793294 Y1 Y5 Z7 + +0.01872075 X8 Z9 X12 + +0.01872075 X8 X12 Z13 + +0.01872075 Y8 Z9 Y12 + +0.01872075 Y8 Y12 Z13 + +0.04519600 X16 Z17 X18 + +0.04519600 Y16 Z17 Y18 + +0.05884033 Z16 Z18 Z19 + -0.05884033 Z17 Z18 Z19 + -0.00793294 X1 Z2 X5 Z6 + +0.02058658 Z1 X2 Z3 X6 + +0.02058658 Z1 Y2 Z3 Y6 + +0.01111059 Z7 Y9 Y13 Z15 + -0.01111059 X9 Z10 X13 Z14 + +0.02166131 Z9 X10 Z11 X14 + +0.02166131 Z9 Y10 Z11 Y14 + +0.04519600 X16 Z17 X18 Z19 + +0.04519600 Y16 Z17 Y18 Z19 + +0.00793294 Z0 X1 Z3 X5 Z6 + -0.00793294 Z0 X1 Z4 X5 Z7 + -0.00793294 Y1 Z3 Z4 Y5 Z6 + +0.02058658 X2 Z3 Z5 X6 Z7 + +0.02058658 Y2 Z3 Z5 Y6 Z7 + +0.01111059 Z8 X9 Z11 X13 Z14 + -0.01111059 Y9 Z11 Z12 Y13 Z14 + +0.00793294 X0 Y1 X2 X4 Y5 X6 + +0.00793294 X0 Y1 X2 Y4 Y5 Y6 + -0.00793294 X0 Y1 Y2 X4 Y5 Y6 + +0.00793294 X0 Y1 Y2 Y4 Y5 X6 + +0.00793294 Y0 Y1 X2 X4 Y5 Y6 + -0.00793294 Y0 Y1 X2 Y4 Y5 X6 + +0.00793294 Y0 Y1 Y2 X4 Y5 X6 + +0.00793294 Y0 Y1 Y2 Y4 Y5 Y6 + -0.00793294 Z0 Y1 Z2 Z3 Y5 Z7 + +0.00793294 Z0 Y1 Z2 Z4 Y5 Z6 + +0.00793294 X1 Z2 Z3 Z4 X5 Z7 + -0.01111059 Z7 Z8 X9 Z12 X13 Z15 + +0.02166131 Z7 X10 Z11 Z13 X14 Z15 + +0.02166131 Z7 Y10 Z11 Z13 Y14 Z15 + +0.01111059 X8 Y9 X10 X12 Y13 X14 + +0.01111059 X8 Y9 X10 Y12 Y13 Y14 + -0.01111059 X8 Y9 Y10 X12 Y13 Y14 + +0.01111059 X8 Y9 Y10 Y12 Y13 X14 + +0.01111059 Y8 Y9 X10 X12 Y13 Y14 + -0.01111059 Y8 Y9 X10 Y12 Y13 X14 + +0.01111059 Y8 Y9 Y10 X12 Y13 X14 + +0.01111059 Y8 Y9 Y10 Y12 Y13 Y14 + +0.01111059 Z8 Y9 Z10 Z12 Y13 Z14 + -0.01111059 Z7 Z8 Y9 Z10 Z11 Y13 Z15 + +0.01111059 Z7 X9 Z10 Z11 Z12 X13 Z15
1,H_blue,T_57 + T_58 + T_59 + T_60 + T_73 + T_207 + T_332 + T_861 + T_1319 + T_1426 + T_1891 + T_2306 + T_2369 + T_2385 + T_2895 + T_2953 + T_3673 + T_3677 + T_3678 + T_3680,20,57,-2.48050344 I + +0.58526473 Z16 + +0.58526473 Z17 + +0.43151913 Z18 + +0.43151913 Z19 + +0.10710480 Z16 Z17 + +0.10403633 Z16 Z19 + +0.10403633 Z17 Z18 + +0.13175829 Z18 Z19 + -0.01028132 X0 X1 X5 Z6 Z7 X8 + -0.01028132 X0 Y1 Y5 Z6 Z7 X8 + +0.00805124 X0 Z1 X2 X8 Z9 X10 + +0.00805124 X0 Z1 X2 Y8 Z9 Y10 + -0.00805124 X0 Z1 Y2 X8 Z9 Y10 + +0.00805124 X0 Z1 Y2 Y8 Z9 X10 + -0.01028132 Y0 X1 X5 Z6 Z7 Y8 + -0.01028132 Y0 Y1 Y5 Z6 Z7 Y8 + +0.00805124 Y0 Z1 X2 X8 Z9 Y10 + -0.00805124 Y0 Z1 X2 Y8 Z9 X10 + +0.00805124 Y0 Z1 Y2 X8 Z9 X10 + +0.00805124 Y0 Z1 Y2 Y8 Z9 Y10 + +0.00247581 X2 X3 X7 Z8 Z9 X10 + +0.00247581 X2 Y3 Y7 Z8 Z9 X10 + +0.00247581 Y2 X3 X7 Z8 Z9 Y10 + +0.00247581 Y2 Y3 Y7 Z8 Z9 Y10 + +0.01065791 X4 Z5 X6 X12 Z13 X14 + +0.01065791 X4 Z5 X6 Y12 Z13 Y14 + -0.01065791 X4 Z5 Y6 X12 Z13 Y14 + +0.01065791 X4 Z5 Y6 Y12 Z13 X14 + +0.01065791 Y4 Z5 X6 X12 Z13 Y14 + -0.01065791 Y4 Z5 X6 Y12 Z13 X14 + +0.01065791 Y4 Z5 Y6 X12 Z13 X14 + +0.01065791 Y4 Z5 Y6 Y12 Z13 Y14 + +0.00095485 X4 Z5 Z6 Z7 Z8 X9 Y12 Y13 + -0.00095485 X4 Z5 Z6 Z7 Z8 Y9 Y12 X13 + -0.00095485 Y4 Z5 Z6 Z7 Z8 X9 X12 Y13 + +0.00095485 Y4 Z5 Z6 Z7 Z8 Y9 X12 X13 + +0.00200978 X6 Z7 Z8 Z9 Z10 X11 Y14 Y15 + -0.00200978 X6 Z7 Z8 Z9 Z10 Y11 Y14 X15 + -0.00200978 Y6 Z7 Z8 Z9 Z10 X11 X14 Y15 + +0.00200978 Y6 Z7 Z8 Z9 Z10 Y11 X14 X15 + +0.00197422 X1 Z2 Z3 Z4 X5 X11 Z12 Z13 Z14 X15 + -0.00197422 X1 Z2 Z3 Z4 X5 Y11 Z12 Z13 Z14 Y15 + +0.00197422 X1 Z2 Z3 Z4 Y5 X11 Z12 Z13 Z14 Y15 + +0.00197422 X1 Z2 Z3 Z4 Y5 Y11 Z12 Z13 Z14 X15 + +0.00197422 Y1 Z2 Z3 Z4 X5 X11 Z12 Z13 Z14 Y15 + +0.00197422 Y1 Z2 Z3 Z4 X5 Y11 Z12 Z13 Z14 X15 + -0.00197422 Y1 Z2 Z3 Z4 Y5 X11 Z12 Z13 Z14 X15 + +0.00197422 Y1 Z2 Z3 Z4 Y5 Y11 Z12 Z13 Z14 Y15 + +0.00466302 X3 Z4 Z5 Z6 X7 X9 Z10 Z11 Z12 X13 + -0.00466302 X3 Z4 Z5 Z6 X7 Y9 Z10 Z11 Z12 Y13 + +0.00466302 X3 Z4 Z5 Z6 Y7 X9 Z10 Z11 Z12 Y13 + +0.00466302 X3 Z4 Z5 Z6 Y7 Y9 Z10 Z11 Z12 X13 + +0.00466302 Y3 Z4 Z5 Z6 X7 X9 Z10 Z11 Z12 Y13 + +0.00466302 Y3 Z4 Z5 Z6 X7 Y9 Z10 Z11 Z12 X13 + -0.00466302 Y3 Z4 Z5 Z6 Y7 X9 Z10 Z11 Z12 X13 + +0.00466302 Y3 Z4 Z5 Z6 Y7 Y9 Z10 Z11 Z12 Y13,57,-2.48050344 I + +0.58526473 Z16 + +0.10710480 Z17 + +0.43151913 Z18 + +0.58526473 Z16 Z17 + +0.13175829 Z17 Z19 + +0.10403633 Z16 Z17 Z18 + +0.43151913 Z17 Z18 Z19 + +0.10403633 Z16 Z17 Z18 Z19 + +0.00247581 X2 X7 Z9 X10 X11 + +0.00247581 Y2 X7 Z9 Y10 X11 + -0.00466302 Y3 Z7 Y9 Y11 Y13 + -0.00805124 X0 Y1 X2 X8 Y9 X10 + -0.00805124 X0 Y1 X2 Y8 Y9 Y10 + +0.00805124 X0 Y1 Y2 X8 Y9 Y10 + -0.00805124 X0 Y1 Y2 Y8 Y9 X10 + -0.00805124 Y0 Y1 X2 X8 Y9 Y10 + +0.00805124 Y0 Y1 X2 Y8 Y9 X10 + -0.00805124 Y0 Y1 Y2 X8 Y9 X10 + -0.00805124 Y0 Y1 Y2 Y8 Y9 Y10 + -0.00197422 Y1 Y3 Y5 Z7 Y11 Z15 + +0.00200978 Z3 Z5 X6 Y7 Y11 X14 + +0.00200978 Z3 Z5 Y6 Y7 Y11 Y14 + -0.01065791 X4 Y5 X6 X12 Y13 X14 + -0.01065791 X4 Y5 X6 Y12 Y13 Y14 + +0.01065791 X4 Y5 Y6 X12 Y13 Y14 + -0.01065791 X4 Y5 Y6 Y12 Y13 X14 + -0.01065791 Y4 Y5 X6 X12 Y13 Y14 + +0.01065791 Y4 Y5 X6 Y12 Y13 X14 + -0.01065791 Y4 Y5 Y6 X12 Y13 X14 + -0.01065791 Y4 Y5 Y6 Y12 Y13 Y14 + +0.01028132 X0 Z3 Y5 Y7 X8 X9 X11 + +0.01028132 Y0 Z3 Y5 Y7 Y8 X9 X11 + -0.00197422 Z0 X1 Y3 Y5 X11 Z13 Z14 + -0.00197422 Y1 Y3 Z4 X5 X11 Z13 Z14 + -0.00466302 X3 Z5 Z6 Z8 X9 Y11 Y13 + -0.00466302 X3 Z5 Z6 Y9 Y11 Z12 X13 + +0.00466302 Y3 Z7 Z8 X9 Y11 Z12 X13 + +0.00095485 Z3 X4 X5 Y7 Y9 X11 X12 + +0.00095485 Z3 Y4 X5 Y7 Y9 X11 Y12 + +0.00197422 Z0 X1 Y3 Z4 X5 Z7 Y11 Z15 + -0.00197422 Y1 Y3 Y5 Z9 Z10 Y11 Z13 Z14 + -0.00247581 Z1 X2 Z5 Z6 Y7 Z9 Y10 X11 + +0.00247581 Z1 Y2 Z5 Z6 Y7 Z9 X10 X11 + -0.00466302 Z1 Z2 X3 Z7 Z8 X9 Y11 Y13 + -0.00466302 Z1 Z2 X3 Z7 Y9 Y11 Z12 X13 + -0.00466302 Z1 Z2 Y3 Z5 Z6 Y9 Y11 Y13 + +0.01028132 X0 Z1 Z3 Z4 X5 Y7 Y8 X9 X11 + -0.01028132 Y0 Z1 Z3 Z4 X5 Y7 X8 X9 X11 + -0.00197422 Z0 X1 Y3 Y5 Z7 Z9 Z10 X11 Z15 + -0.00197422 Y1 Y3 Z4 X5 Z7 Z9 Z10 X11 Z15 + -0.00095485 Z3 X4 X5 Y7 Z8 X9 X11 Y12 Z13 + +0.00095485 Z3 Y4 X5 Y7 Z8 X9 X11 X12 Z13 + +0.00197422 Z0 X1 Y3 Z4 X5 Z9 Z10 Y11 Z13 Z14 + +0.00466302 Z1 Z2 Y3 Z5 Z6 Z8 X9 Y11 Z12 X13 + -0.00200978 Z3 Z5 X6 X7 Z9 Z10 Y11 Z13 Y14 Z15 + +0.00200978 Z3 Z5 Y6 X7 Z9 Z10 Y11 Z13 X14 Z15
2,H_green,T_82 + T_192 + T_347 + T_980 + T_1320 + T_1427 + T_2542 + T_2617 + T_2692 + T_2874 + T_3244 + T_3286,12,48,+0.00565166 X1 Z2 X3 X7 Z8 X9 + +0.00565166 X1 Z2 X3 Y7 Z8 Y9 + +0.00565166 X1 Z2 Y3 X7 Z8 Y9 + -0.00565166 X1 Z2 Y3 Y7 Z8 X9 + -0.00565166 Y1 Z2 X3 X7 Z8 Y9 + +0.00565166 Y1 Z2 X3 Y7 Z8 X9 + +0.00565166 Y1 Z2 Y3 X7 Z8 X9 + +0.00565166 Y1 Z2 Y3 Y7 Z8 Y9 + -0.00327546 X5 X6 X10 Z11 Z12 X13 + -0.00327546 X5 Y6 Y10 Z11 Z12 X13 + -0.00327546 Y5 X6 X10 Z11 Z12 Y13 + -0.00327546 Y5 Y6 Y10 Z11 Z12 Y13 + -0.01132959 X6 Z7 X8 X10 Z11 X12 + -0.01132959 X6 Z7 X8 Y10 Z11 Y12 + +0.01132959 X6 Z7 Y8 X10 Z11 Y12 + -0.01132959 X6 Z7 Y8 Y10 Z11 X12 + -0.01132959 Y6 Z7 X8 X10 Z11 Y12 + +0.01132959 Y6 Z7 X8 Y10 Z11 X12 + -0.01132959 Y6 Z7 Y8 X10 Z11 X12 + -0.01132959 Y6 Z7 Y8 Y10 Z11 Y12 + -0.01028132 X0 X1 Y4 Z5 Z6 Z7 Z8 Y9 + +0.01028132 X0 Y1 Y4 Z5 Z6 Z7 Z8 X9 + +0.01028132 Y0 X1 X4 Z5 Z6 Z7 Z8 Y9 + -0.01028132 Y0 Y1 X4 Z5 Z6 Z7 Z8 X9 + +0.01642360 X8 Z9 Z10 X11 Y12 Z13 Z14 Y15 + -0.01642360 X8 Z9 Z10 Y11 Y12 Z13 Z14 X15 + -0.01642360 Y8 Z9 Z10 X11 X12 Z13 Z14 Y15 + +0.01642360 Y8 Z9 Z10 Y11 X12 Z13 Z14 X15 + +0.00593443 X2 X3 X7 Z8 Z9 Z10 Z11 Z12 Z13 X14 + +0.00593443 X2 Y3 Y7 Z8 Z9 Z10 Z11 Z12 Z13 X14 + +0.00593443 Y2 X3 X7 Z8 Z9 Z10 Z11 Z12 Z13 Y14 + +0.00593443 Y2 Y3 Y7 Z8 Z9 Z10 Z11 Z12 Z13 Y14 + -0.00128810 X5 Z6 Z7 Z8 Z9 Z10 X11 X13 Z14 X15 + -0.00128810 X5 Z6 Z7 Z8 Z9 Z10 X11 Y13 Z14 Y15 + +0.00128810 X5 Z6 Z7 Z8 Z9 Z10 Y11 X13 Z14 Y15 + -0.00128810 X5 Z6 Z7 Z8 Z9 Z10 Y11 Y13 Z14 X15 + -0.00128810 Y5 Z6 Z7 Z8 Z9 Z10 X11 X13 Z14 Y15 + +0.00128810 Y5 Z6 Z7 Z8 Z9 Z10 X11 Y13 Z14 X15 + -0.00128810 Y5 Z6 Z7 Z8 Z9 Z10 Y11 X13 Z14 X15 + -0.00128810 Y5 Z6 Z7 Z8 Z9 Z10 Y11 Y13 Z14 Y15 + -0.00021829 X0 Z1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 X14 + -0.00021829 X0 Z1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Y14 + +0.00021829 X0 Z1 Y2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Y14 + -0.00021829 X0 Z1 Y2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 X14 + -0.00021829 Y0 Z1 X2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Y14 + +0.00021829 Y0 Z1 X2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 X14 + -0.00021829 Y0 Z1 Y2 X4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 X14 + -0.00021829 Y0 Z1 Y2 Y4 Z5 Z6 Z7 Z8 Z9 Z10 Z11 Z12 Z13 Y14,48,+0.00565166 Y1 Z3 X7 Y9 X11 + +0.00593443 X2 X7 Z11 Z13 X14 + +0.00593443 Y2 X7 Z11 Z13 Y14 + -0.00565166 Z0 Y1 Z2 X7 Y9 X11 + +0.00565166 X1 Z2 X7 Z8 X9 X11 + +0.00128810 Z3 Y5 X7 X11 Y13 Z15 + +0.01642360 X8 X9 Z11 Y12 Y13 Z14 + -0.01642360 Y8 X9 Z11 X12 Y13 Z14 + -0.01028132 X0 Z3 X4 X5 Y7 Y9 X11 + -0.01028132 Y0 Z3 Y4 X5 Y7 Y9 X11 + -0.00565166 Z0 X1 Z3 X7 Z8 X9 X11 + -0.00565166 Z0 X1 Z5 Z6 Y7 Y9 X11 + -0.00565166 Y1 Z5 Z6 Y7 Z8 X9 X11 + -0.00128810 Z3 Z4 X5 Y7 Y11 X13 Z14 + +0.00128810 Z3 Y5 Y7 Y11 Z12 Y13 Z14 + +0.00327546 Z4 Y5 X6 Z9 Y10 Y11 Y13 + -0.00327546 Z4 Y5 Y6 Z9 X10 Y11 Y13 + +0.00327546 X5 X6 Z9 Y10 Y11 Z12 X13 + -0.00327546 X5 Y6 Z9 X10 Y11 Z12 X13 + +0.00565166 X1 Z2 Z3 Z5 Z6 Y7 Y9 X11 + -0.00593443 Z1 X2 Z5 Z6 Y7 Z11 Z13 Y14 + +0.00593443 Z1 Y2 Z5 Z6 Y7 Z11 Z13 X14 + -0.00128810 Z3 Z4 X5 X7 X11 Z12 X13 Z15 + +0.00128810 Z3 Y5 Y7 Z9 Z10 X11 X13 Z14 + -0.01642360 Z7 X8 Y9 Z10 Z11 Y12 X13 Z15 + +0.01642360 Z7 Y8 Y9 Z10 Z11 X12 X13 Z15 + -0.01028132 X0 Z1 Z3 Y4 X5 Y7 Z8 X9 X11 + +0.01028132 Y0 Z1 Z3 X4 X5 Y7 Z8 X9 X11 + -0.00128810 Z3 Z4 X5 X7 Z9 Z10 Y11 Y13 Z15 + -0.00128810 Z3 Y5 X7 Z9 Z10 Y11 Z12 X13 Z15 + +0.00021829 X0 Y1 X2 Z3 X4 X5 Y7 Z11 Z13 X14 + +0.00021829 X0 Y1 X2 Z3 Y4 X5 Y7 Z11 Z13 Y14 + -0.00021829 X0 Y1 Y2 Z3 X4 X5 Y7 Z11 Z13 Y14 + +0.00021829 X0 Y1 Y2 Z3 Y4 X5 Y7 Z11 Z13 X14 + +0.00021829 Y0 Y1 X2 Z3 X4 X5 Y7 Z11 Z13 Y14 + -0.00021829 Y0 Y1 X2 Z3 Y4 X5 Y7 Z11 Z13 X14 + +0.00021829 Y0 Y1 Y2 Z3 X4 X5 Y7 Z11 Z13 X14 + +0.00021829 Y0 Y1 Y2 Z3 Y4 X5 Y7 Z11 Z13 Y14 + +0.00565166 Z0 Y1 Z2 Z3 Z5 Z6 Y7 Z8 X9 X11 + +0.00128810 Z3 Z4 X5 Y7 Z9 Z10 X11 Z12 Y13 Z14 + +0.01132959 Z3 Z5 X6 Y7 X8 Y9 X10 Z11 X12 X13 + +0.01132959 Z3 Z5 X6 Y7 X8 Y9 Y10 Z11 Y12 X13 + -0.01132959 Z3 Z5 X6 Y7 Y8 Y9 X10 Z11 Y12 X13 + +0.01132959 Z3 Z5 X6 Y7 Y8 Y9 Y10 Z11 X12 X13 + +0.01132959 Z3 Z5 Y6 Y7 X8 Y9 X10 Z11 Y12 X13 + -0.01132959 Z3 Z5 Y6 Y7 X8 Y9 Y10 Z11 X12 X13 + +0.01132959 Z3 Z5 Y6 Y7 Y8 Y9 X10 Z11 X12 X13 + +0.01132959 Z3 Z5 Y6 Y7 Y8 Y9 Y10 Z11 Y12 X13
3,H_orange,T_83 + T_334 + T_348 + T_992 + T_1321 + T_1428 + T_1886 + T_2215 + T_2368 + T_2378 + T_2894 + T_2952 + T_3653 + T_3658 + T_3661,15,56,+0.06083798 I + -0.06083798 Z14 + -0.06083798 Z16 + +0.06083798 Z14 Z16 + -0.01488211 X0 X1 Y8 Y9 + +0.01488211 X0 Y1 Y8 X9 + +0.01488211 Y0 X1 X8 Y9 + -0.01488211 Y0 Y1 X8 X9 + -0.01311075 X4 X5 Y12 Y13 + +0.01311075 X4 Y5 Y12 X13 + +0.01311075 Y4 X5 X12 Y13 + -0.01311075 Y4 Y5 X12 X13 + +0.00570122 X4 Z5 X6 X10 Z11 X12 + +0.00570122 X4 Z5 X6 Y10 Z11 Y12 + +0.00570122 X4 Z5 Y6 X10 Z11 Y12 + -0.00570122 X4 Z5 Y6 Y10 Z11 X12 + -0.00570122 Y4 Z5 X6 X10 Z11 Y12 + +0.00570122 Y4 Z5 X6 Y10 Z11 X12 + +0.00570122 Y4 Z5 Y6 X10 Z11 X12 + +0.00570122 Y4 Z5 Y6 Y10 Z11 Y12 + +0.02871035 X14 Z15 X16 X17 Z18 X19 + +0.02871035 X14 Z15 X16 Y17 Z18 Y19 + +0.02871035 Y14 Z15 Y16 X17 Z18 X19 + +0.02871035 Y14 Z15 Y16 Y17 Z18 Y19 + +0.00017410 X3 Z4 X5 X7 Z8 Z9 Z10 Z11 Z12 X13 + +0.00017410 X3 Z4 X5 Y7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.00017410 X3 Z4 Y5 X7 Z8 Z9 Z10 Z11 Z12 Y13 + +0.00017410 X3 Z4 Y5 Y7 Z8 Z9 Z10 Z11 Z12 X13 + +0.00017410 Y3 Z4 X5 X7 Z8 Z9 Z10 Z11 Z12 Y13 + -0.00017410 Y3 Z4 X5 Y7 Z8 Z9 Z10 Z11 Z12 X13 + +0.00017410 Y3 Z4 Y5 X7 Z8 Z9 Z10 Z11 Z12 X13 + +0.00017410 Y3 Z4 Y5 Y7 Z8 Z9 Z10 Z11 Z12 Y13 + +0.01584251 X6 Z7 Z8 Z9 X10 X11 Z12 Z13 Z14 X15 + +0.01584251 X6 Z7 Z8 Z9 X10 Y11 Z12 Z13 Z14 Y15 + +0.01584251 Y6 Z7 Z8 Z9 Y10 X11 Z12 Z13 Z14 X15 + +0.01584251 Y6 Z7 Z8 Z9 Y10 Y11 Z12 Z13 Z14 Y15 + +0.00024120 X0 Z1 X2 X8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 X18 + +0.00024120 X0 Z1 X2 Y8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 Y18 + -0.00024120 X0 Z1 Y2 X8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 Y18 + +0.00024120 X0 Z1 Y2 Y8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 X18 + +0.00024120 Y0 Z1 X2 X8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 Y18 + -0.00024120 Y0 Z1 X2 Y8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 X18 + +0.00024120 Y0 Z1 Y2 X8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 X18 + +0.00024120 Y0 Z1 Y2 Y8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 Y18 + +0.00038107 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 X9 X11 Z12 Z13 Z14 X15 + -0.00038107 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 X9 Y11 Z12 Z13 Z14 Y15 + +0.00038107 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Y9 X11 Z12 Z13 Z14 Y15 + +0.00038107 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Y9 Y11 Z12 Z13 Z14 X15 + +0.00038107 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 X9 X11 Z12 Z13 Z14 Y15 + +0.00038107 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 X9 Y11 Z12 Z13 Z14 X15 + -0.00038107 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Y9 X11 Z12 Z13 Z14 X15 + +0.00038107 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Y9 Y11 Z12 Z13 Z14 Y15 + -0.00044723 X2 X3 X7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 X18 + -0.00044723 X2 Y3 Y7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 X18 + -0.00044723 Y2 X3 X7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 Y18 + -0.00044723 Y2 Y3 Y7 Z8 Z9 Z10 Z11 Z12 Z13 Z14 Z15 Z16 Z17 Y18,56,+0.06083798 I + -0.06083798 Z14 + -0.06083798 Z16 + +0.06083798 Z14 Z16 + +0.01488211 X0 Z1 X8 + +0.01488211 X0 X8 Z9 + +0.01488211 Y0 Z1 Y8 + +0.01488211 Y0 Y8 Z9 + +0.01311075 X4 Z5 X12 + +0.01311075 X4 X12 Z13 + +0.01311075 Y4 Z5 Y12 + +0.01311075 Y4 Y12 Z13 + -0.00017410 X3 Y5 X7 Z11 Y13 + +0.00038107 Y1 X3 X7 Y9 Z11 Z15 + +0.00044723 X2 Y7 Y15 Z17 X18 X19 + +0.00044723 Y2 Y7 Y15 Z17 Y18 X19 + +0.01584251 Z3 Z5 X6 X7 X10 Z15 + +0.01584251 Z3 Z5 Y6 X7 Y10 Z15 + +0.00038107 Z0 X1 X3 X7 X9 Z10 Z15 + -0.00038107 Z0 X1 X3 Y7 Y9 Z13 Z14 + -0.00038107 Y1 X3 X7 Z8 Y9 Z10 Z15 + -0.00038107 Y1 X3 Y7 Z8 X9 Z13 Z14 + +0.00017410 X3 Z4 X5 X7 Z11 Z12 X13 + -0.00017410 Y3 Z4 Y5 Z6 Y7 Z11 Y13 + +0.00017410 Y3 X5 Z6 Y7 Z11 Z12 X13 + -0.02871035 Z7 Z11 Z13 X14 Y15 X16 Y19 + -0.02871035 Z7 Z11 Z13 Y14 Y15 Y16 Y19 + -0.00038107 Z0 X1 X3 X7 Z8 X9 Z11 Z15 + +0.00038107 Y1 X3 Y7 X9 Z10 Z11 Z13 Z14 + -0.00017410 Z1 Z2 X3 X5 Z6 Y7 Z11 Y13 + +0.00017410 Z1 Z2 Y3 Z4 X5 X7 Z11 Y13 + +0.00017410 Z1 Z2 Y3 Y5 X7 Z11 Z12 X13 + +0.01584251 Z3 Z5 X6 Y7 Z9 Y10 Z13 Z14 + -0.01584251 Z3 Z5 Y6 Y7 Z9 X10 Z13 Z14 + +0.00570122 X4 Y5 X6 Z9 X10 Y11 X12 X13 + +0.00570122 X4 Y5 X6 Z9 Y10 Y11 Y12 X13 + +0.00570122 X4 Y5 Y6 Z9 X10 Y11 Y12 X13 + -0.00570122 X4 Y5 Y6 Z9 Y10 Y11 X12 X13 + -0.00570122 Y4 Y5 X6 Z9 X10 Y11 Y12 X13 + +0.00570122 Y4 Y5 X6 Z9 Y10 Y11 X12 X13 + +0.00570122 Y4 Y5 Y6 Z9 X10 Y11 X12 X13 + +0.00570122 Y4 Y5 Y6 Z9 Y10 Y11 Y12 X13 + +0.02871035 Z7 Z11 Z13 X14 Y15 Y16 Z18 X19 + -0.02871035 Z7 Z11 Z13 Y14 Y15 X16 Z18 X19 + +0.00044723 Z1 X2 Z5 Z6 X7 Y15 Z17 Y18 X19 + -0.00044723 Z1 Y2 Z5 Z6 X7 Y15 Z17 X18 X19 + +0.00038107 Z0 X1 X3 Y7 Z8 Y9 Z10 Z11 Z13 Z14 + -0.00017410 Z1 Z2 X3 Z4 Y5 Z6 Y7 Z11 Z12 X13 + -0.00024120 X0 Y1 X2 Z7 X8 X9 X11 Y15 Z17 X18 X19 + -0.00024120 X0 Y1 X2 Z7 Y8 X9 X11 Y15 Z17 Y18 X19 + +0.00024120 X0 Y1 Y2 Z7 X8 X9 X11 Y15 Z17 Y18 X19 + -0.00024120 X0 Y1 Y2 Z7 Y8 X9 X11 Y15 Z17 X18 X19 + -0.00024120 Y0 Y1 X2 Z7 X8 X9 X11 Y15 Z17 Y18 X19 + +0.00024120 Y0 Y1 X2 Z7 Y8 X9 X11 Y15 Z17 X18 X19 + -0.00024120 Y0 Y1 Y2 Z7 X8 X9 X11 Y15 Z17 X18 X19 + -0.00024120 Y0 Y1 Y2 Z7 Y8 X9 X11 Y15 Z17 Y18 X19

=== Verify commuting groups after JW/BK mapping ===

      color_group            pair  fermionic_commute  JW_commute  BK_commute
0             red       T_0, T_72               True        True        True
1             red      T_0, T_190               True        True        True
2             red      T_0, T_206               True        True        True
3             red      T_0, T_849               True        True        True
4             red     T_0, T_1318               True        True        True
...           ...             ...                ...         ...         ...
25358   color_275  T_2196, T_3327               True        True        True
25359   color_275  T_3007, T_3256               True        True        True
25360   color_275  T_3007, T_3327               True        True        True
25361   color_275  T_3256, T_3327               True        True        True
25362   color_276  T_3303, T_3515               True        True        True

[25363 rows x 5 columns]

In [7]:
# Find duplicated JW Pauli strings across fermionic terms T_i

from collections import defaultdict
import pandas as pd

pauli_usage = defaultdict(list)

for node in sorted(G.nodes()):
    JW_T = G.nodes[node]["JW_operator"]

    for pauli_key, coeff in JW_T.terms.items():
        pauli_string = format_qubit_term(pauli_key)

        pauli_usage[pauli_string].append(
            {
                "vertex": f"T_{node}",
                "coefficient": coeff,
                "fermionic_term": G.nodes[node]["operator_string"],
            }
        )

duplicate_rows = []

for pauli_string, appearances in pauli_usage.items():
    if len(appearances) > 1:
        duplicate_rows.append(
            {
                "JW_Pauli_string": pauli_string,
                "number_of_appearances": len(appearances),
                "appears_in_vertices": [x["vertex"] for x in appearances],
                "coefficients": [x["coefficient"] for x in appearances],
            }
        )

duplicate_jw_df = pd.DataFrame(duplicate_rows)
duplicate_jw_df = duplicate_jw_df.sort_values(
    "number_of_appearances",
    ascending=False
).reset_index(drop=True)

print("Total JW Pauli-string appearances:", sum(len(G.nodes[node]["JW_operator"].terms) for node in G.nodes()))
print("Number of unique JW Pauli strings:", len(pauli_usage))
print("Number of duplicated JW Pauli strings:", len(duplicate_jw_df))

display(duplicate_jw_df)

Total JW Pauli-string appearances: 25441
Number of unique JW Pauli strings: 11691
Number of duplicated JW Pauli strings: 10061

,JW_Pauli_string,number_of_appearances,appears_in_vertices,coefficients
0,I,211,"[T_0, T_1, T_6, T_11, T_16, T_21, T_25, T_29, T_33, T_37, T_40, T_43, T_46, T_49, T_51, T_53, T_55, T_57, T_58, T_59, T_60, T_61, T_111, T_141, T_186, T_215, T_255, T_293, T_328, T_365, T_395, T_441, T_466, T_511, T_531, T_585, T_600, T_653, T_663, T_725, T_730, T_775, T_805, T_845, T_874, T_909, T_947, T_977, T_1014, T_1039, T_1085, T_1105, T_1150, T_1165, T_1219, T_1229, T_1282, T_1287, T_1308, T_1349, T_1373, T_1409, T_1433, T_1465, T_1496, T_1523, T_1554, T_1577, T_1615, T_1633, T_1671, T_1685, T_1730, T_1739, T_1784, T_1789, T_1825, T_1849, T_1881, T_1905, T_1932, T_1963, T_1986, T_2017, T_2035, T_2073, T_2087, T_2125, T_2134, T_2179, T_2184, T_2197, T_2229, T_2249, T_2277, T_2296, T_2320, T_2346, T_2366, T_2391, ...]","[13.76808794966473, -1.7679774994319637, -1.7679774994319637, -1.6555019362457821, -1.6555019362457821, -1.5630902062711896, -1.5630902062711896, -1.4664505063672386, -1.4664505063672386, -1.4107676907228812, -1.4107676907228812, -1.305051659990087, -1.305051659990087, -1.137441725788379, -1.137441725788379, -0.9816003783964337, -0.9816003783964337, -0.7964058499573899, -0.7964058499573899, -0.6673137423023049, -0.6673137423023049, 0.10191392055616116, 0.049391342399017824, 0.08223002261135531, 0.05728294465508936, 0.07957591868590091, 0.06114803594208264, 0.07724377089188787, 0.06878493495310864, 0.0836670461023376, 0.07252641022137937, 0.08527729313134724, 0.0726800491728012, 0.08205023079631743, 0.07795149507488103, 0.08674332134356735, 0.08212526725185146, 0.08988142709584254, 0.10140180050126363, 0.11133560889472865, 0.08223002261135531, 0.049391342399017824, 0.07957591868590091, 0.05728294465508936, 0.07724377089188787, 0.06114803594208264, 0.0836670461023376, 0.06878493495310864, 0.08527729313134724, 0.07252641022137937, 0.08205023079631743, 0.0726800491728012, 0.08674332134356735, 0.07795149507488103, 0.08988142709584254, 0.08212526725185146, 0.11133560889472865, 0.10140180050126363, 0.08766914141799742, 0.05027721373846579, 0.07790091878059768, 0.057277549630481664, 0.07786412825339058, 0.06340872425214235, 0.07983834944104189, 0.06768235920657868, 0.08118583198191065, 0.0703640306642336, 0.08182610432894313, 0.07440969213402784, 0.08373025748616564, 0.08314160859890551, 0.09373855541314824, 0.08294669631524386, 0.09027954513132128, 0.07790091878059768, 0.05027721373846579, 0.07786412825339058, 0.057277549630481664, 0.07983834944104189, 0.06340872425214235, 0.08118583198191065, 0.06768235920657868, 0.08182610432894313, 0.0703640306642336, 0.08373025748616564, 0.07440969213402784, 0.09373855541314824, 0.08314160859890551, 0.09027954513132128, 0.08294669631524386, 0.08285169886065757, 0.050657167395117, 0.0773669648739134, 0.05839484379620484, 0.07885605540201591, 0.0643686821298091, 0.07997402315436834, 0.0676968610754815, 0.08080761110215218, ...]"
1,Z11,20,"[T_46, T_441, T_1039, T_1554, T_1986, T_2346, T_2643, T_2886, T_3084, T_3237, T_3359, T_3450, T_3527, T_3537, T_3545, T_3553, T_3561, T_3566, T_3577, T_3580]","[1.305051659990087, -0.08527729313134724, -0.07252641022137937, -0.08118583198191065, -0.06768235920657868, -0.07997402315436834, -0.0643686821298091, -0.07948347741548079, -0.06090134206715498, -0.0826178707997248, -0.06063496885970733, -0.0859051639186294, -0.08351755713983326, -0.05515552756086485, -0.08634889311814015, -0.0646875880322408, -0.08942345882819708, -0.07170233442860685, -0.09557970288804435, -0.07946875903458667]"
2,Z4,20,"[T_21, T_186, T_805, T_1349, T_1789, T_2197, T_2229, T_2249, T_2277, T_2296, T_2320, T_2346, T_2366, T_2391, T_2407, T_2439, T_2451, T_2482, T_2490, T_2528]","[1.5630902062711896, -0.05728294465508936, -0.07957591868590091, -0.05027721373846579, -0.07790091878059768, -0.08285169886065757, -0.050657167395117, -0.0773669648739134, -0.05839484379620484, -0.07885605540201591, -0.0643686821298091, -0.07997402315436834, -0.0676968610754815, -0.08080761110215218, -0.0733874985455447, -0.08617981639699925, -0.07547674910735439, -0.08429809795541524, -0.07950001337933078, -0.0873544923591077]"
3,Z5,20,"[T_25, T_215, T_845, T_1373, T_1825, T_2197, T_2532, T_2560, T_2580, T_2604, T_2623, T_2643, T_2669, T_2685, T_2710, T_2722, T_2754, T_2762, T_2793, T_2797]","[1.5630902062711896, -0.07957591868590091, -0.05728294465508936, -0.07790091878059768, -0.05027721373846579, -0.08285169886065757, -0.0773669648739134, -0.050657167395117, -0.07885605540201591, -0.05839484379620484, -0.07997402315436834, -0.0643686821298091, -0.08080761110215218, -0.0676968610754815, -0.08617981639699925, -0.0733874985455447, -0.08429809795541524, -0.07547674910735439, -0.0873544923591077, -0.07950001337933078]"
4,Z6,20,"[T_29, T_255, T_874, T_1409, T_1849, T_2229, T_2532, T_2810, T_2835, T_2850, T_2871, T_2886, T_2904, T_2924, T_2938, T_2958, T_2969, T_2994, T_3001, T_3026]","[1.4664505063672386, -0.06114803594208264, -0.07724377089188787, -0.057277549630481664, -0.07786412825339058, -0.050657167395117, -0.0773669648739134, -0.08115611389054331, -0.050925979344543015, -0.07861234067025152, -0.06090134206715498, -0.07948347741548079, -0.06548105275580618, -0.0821024997555598, -0.06922555665629188, -0.08189675488356118, -0.07342586952132193, -0.08435995944602817, -0.07652138031824796, -0.08516154184552238]"
...,...,...,...,...
10056,Y2 Y3 X5 Z6 Z7 Z8 Z9 Z10 Z11 X12,2,"[T_1315, T_1371]","[-0.003958408601295751, 0.003958408601295751]"
10057,X2 X3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Y12,2,"[T_1315, T_1371]","[-0.003958408601295751, 0.003958408601295751]"
10058,X2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 X12,2,"[T_1315, T_1371]","[0.003958408601295751, 0.003958408601295751]"
10059,Y2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Y12,2,"[T_1315, T_1371]","[0.003958408601295751, 0.003958408601295751]"
10060,X16 Y17 X18 Y19,2,"[T_3674, T_3676]","[0.022598000072742933, -0.022598000072742933]"

In [8]:
# Compute Pauli-duplication ratio for JW and BK

from collections import defaultdict
import pandas as pd

from openfermion.ops import FermionOperator
from openfermion.transforms import jordan_wigner, bravyi_kitaev, normal_ordered


def pauli_support(qubit_op, tol=1e-12, include_identity=True):
    """
    Return the set of Pauli strings with nonzero coefficients.
    """
    qubit_op.compress(abs_tol=tol)

    support = set()

    for pauli_key, coeff in qubit_op.terms.items():
        if abs(coeff) <= tol:
            continue

        if not include_identity and pauli_key == ():
            continue

        support.add(pauli_key)

    return support


def map_fermion_to_qubit(op, mapping="JW", n_qubits=None):
    """
    Map a FermionOperator to a QubitOperator using JW or BK.
    """
    mapping = mapping.upper()

    if mapping == "JW":
        qop = jordan_wigner(op)

    elif mapping == "BK":
        if n_qubits is None:
            raise ValueError("n_qubits is required for BK.")

        try:
            qop = bravyi_kitaev(op, n_qubits=n_qubits)
        except TypeError:
            qop = bravyi_kitaev(op, n_qubits)

    else:
        raise ValueError("mapping must be 'JW' or 'BK'.")

    qop.compress(abs_tol=1e-12)
    return qop


def pauli_duplication_ratio(
    fermionic_terms,
    mapping="JW",
    n_qubits=None,
    include_identity=True,
    tol=1e-12,
):
    """
    Compute

        sum_alpha #mapping(H_alpha) / #mapping(H)

    where H = sum_alpha H_alpha.

    Also returns a duplicate-use table.
    """

    H_full = FermionOperator.zero()

    numerator = 0
    union_support = set()
    pauli_usage = defaultdict(list)

    for alpha, H_alpha in enumerate(fermionic_terms):
        H_full += H_alpha

        Q_alpha = map_fermion_to_qubit(
            H_alpha,
            mapping=mapping,
            n_qubits=n_qubits,
        )

        support_alpha = pauli_support(
            Q_alpha,
            tol=tol,
            include_identity=include_identity,
        )

        numerator += len(support_alpha)
        union_support |= support_alpha

        for pauli_key, coeff in Q_alpha.terms.items():
            if abs(coeff) <= tol:
                continue

            if not include_identity and pauli_key == ():
                continue

            pauli_usage[pauli_key].append(
                {
                    "vertex": f"T_{alpha}",
                    "coefficient": coeff,
                }
            )

    H_full = normal_ordered(H_full)
    H_full.compress(abs_tol=tol)

    Q_full = map_fermion_to_qubit(
        H_full,
        mapping=mapping,
        n_qubits=n_qubits,
    )

    full_support = pauli_support(
        Q_full,
        tol=tol,
        include_identity=include_identity,
    )

    denominator = len(full_support)

    duplication_ratio = numerator / denominator
    union_ratio = numerator / len(union_support)

    summary_df = pd.DataFrame(
        [
            {
                "mapping": mapping.upper(),
                "include_identity": include_identity,
                "sum_alpha_number_of_Pauli_strings": numerator,
                "number_of_unique_Pauli_strings_before_cancellation": len(union_support),
                "number_of_Pauli_strings_in_full_H": denominator,
                "duplication_ratio": duplication_ratio,
                "raw_reuse_ratio_before_cancellation": union_ratio,
            }
        ]
    )

    duplicate_rows = []

    for pauli_key, appearances in pauli_usage.items():
        if len(appearances) <= 1:
            continue

        combined_coeff = Q_full.terms.get(pauli_key, 0.0)

        duplicate_rows.append(
            {
                "Pauli_string": format_qubit_term(pauli_key),
                "number_of_appearances": len(appearances),
                "appears_in_vertices": [x["vertex"] for x in appearances],
                "individual_coefficients": [complex(x["coefficient"]) for x in appearances],
                "combined_coefficient_in_full_H": complex(combined_coeff),
                "survives_in_full_H": abs(combined_coeff) > tol,
            }
        )

    duplicate_df = pd.DataFrame(duplicate_rows)

    if len(duplicate_df) > 0:
        duplicate_df = duplicate_df.sort_values(
            "number_of_appearances",
            ascending=False,
        ).reset_index(drop=True)

    return summary_df, duplicate_df


# ------------------------------------------------------------
# Run for JW
# ------------------------------------------------------------

n_qubits = molecule.n_qubits

jw_summary_df, jw_duplicate_df = pauli_duplication_ratio(
    hermitian_terms,
    mapping="JW",
    n_qubits=n_qubits,
    include_identity=True,
)

print("=== JW Pauli-duplication ratio ===")
display(jw_summary_df)

print("\n=== Duplicated JW Pauli strings ===")
display(jw_duplicate_df)


# ------------------------------------------------------------
# Optional: run for BK too
# ------------------------------------------------------------

bk_summary_df, bk_duplicate_df = pauli_duplication_ratio(
    hermitian_terms,
    mapping="BK",
    n_qubits=n_qubits,
    include_identity=True,
)

print("=== BK Pauli-duplication ratio ===")
display(bk_summary_df)

print("\n=== Duplicated BK Pauli strings ===")
display(bk_duplicate_df)

=== JW Pauli-duplication ratio ===

,mapping,include_identity,sum_alpha_number_of_Pauli_strings,number_of_unique_Pauli_strings_before_cancellation,number_of_Pauli_strings_in_full_H,duplication_ratio,raw_reuse_ratio_before_cancellation
0,JW,True,25441,11691,7151,3.557684,2.176118

=== Duplicated JW Pauli strings ===

,Pauli_string,number_of_appearances,appears_in_vertices,individual_coefficients,combined_coefficient_in_full_H,survives_in_full_H
0,I,211,"[T_0, T_1, T_6, T_11, T_16, T_21, T_25, T_29, T_33, T_37, T_40, T_43, T_46, T_49, T_51, T_53, T_55, T_57, T_58, T_59, T_60, T_61, T_111, T_141, T_186, T_215, T_255, T_293, T_328, T_365, T_395, T_441, T_466, T_511, T_531, T_585, T_600, T_653, T_663, T_725, T_730, T_775, T_805, T_845, T_874, T_909, T_947, T_977, T_1014, T_1039, T_1085, T_1105, T_1150, T_1165, T_1219, T_1229, T_1282, T_1287, T_1308, T_1349, T_1373, T_1409, T_1433, T_1465, T_1496, T_1523, T_1554, T_1577, T_1615, T_1633, T_1671, T_1685, T_1730, T_1739, T_1784, T_1789, T_1825, T_1849, T_1881, T_1905, T_1932, T_1963, T_1986, T_2017, T_2035, T_2073, T_2087, T_2125, T_2134, T_2179, T_2184, T_2197, T_2229, T_2249, T_2277, T_2296, T_2320, T_2346, T_2366, T_2391, ...]","[(13.76808794966473+0j), (-1.7679774994319637+0j), (-1.7679774994319637+0j), (-1.6555019362457821+0j), (-1.6555019362457821+0j), (-1.5630902062711896+0j), (-1.5630902062711896+0j), (-1.4664505063672386+0j), (-1.4664505063672386+0j), (-1.4107676907228812+0j), (-1.4107676907228812+0j), (-1.305051659990087+0j), (-1.305051659990087+0j), (-1.137441725788379+0j), (-1.137441725788379+0j), (-0.9816003783964337+0j), (-0.9816003783964337+0j), (-0.7964058499573899+0j), (-0.7964058499573899+0j), (-0.6673137423023049+0j), (-0.6673137423023049+0j), (0.10191392055616116+0j), (0.049391342399017824+0j), (0.08223002261135531+0j), (0.05728294465508936+0j), (0.07957591868590091+0j), (0.06114803594208264+0j), (0.07724377089188787+0j), (0.06878493495310864+0j), (0.0836670461023376+0j), (0.07252641022137937+0j), (0.08527729313134724+0j), (0.0726800491728012+0j), (0.08205023079631743+0j), (0.07795149507488103+0j), (0.08674332134356735+0j), (0.08212526725185146+0j), (0.08988142709584254+0j), (0.10140180050126363+0j), (0.11133560889472865+0j), (0.08223002261135531+0j), (0.049391342399017824+0j), (0.07957591868590091+0j), (0.05728294465508936+0j), (0.07724377089188787+0j), (0.06114803594208264+0j), (0.0836670461023376+0j), (0.06878493495310864+0j), (0.08527729313134724+0j), (0.07252641022137937+0j), (0.08205023079631743+0j), (0.0726800491728012+0j), (0.08674332134356735+0j), (0.07795149507488103+0j), (0.08988142709584254+0j), (0.08212526725185146+0j), (0.11133560889472865+0j), (0.10140180050126363+0j), (0.08766914141799742+0j), (0.05027721373846579+0j), (0.07790091878059768+0j), (0.057277549630481664+0j), (0.07786412825339058+0j), (0.06340872425214235+0j), (0.07983834944104189+0j), (0.06768235920657868+0j), (0.08118583198191065+0j), (0.0703640306642336+0j), (0.08182610432894313+0j), (0.07440969213402784+0j), (0.08373025748616564+0j), (0.08314160859890551+0j), (0.09373855541314824+0j), (0.08294669631524386+0j), (0.09027954513132128+0j), (0.07790091878059768+0j), (0.05027721373846579+0j), (0.07786412825339058+0j), (0.057277549630481664+0j), (0.07983834944104189+0j), (0.06340872425214235+0j), (0.08118583198191065+0j), (0.06768235920657868+0j), (0.08182610432894313+0j), (0.0703640306642336+0j), (0.08373025748616564+0j), (0.07440969213402784+0j), (0.09373855541314824+0j), (0.08314160859890551+0j), (0.09027954513132128+0j), (0.08294669631524386+0j), (0.08285169886065757+0j), (0.050657167395117+0j), (0.0773669648739134+0j), (0.05839484379620484+0j), (0.07885605540201591+0j), (0.0643686821298091+0j), (0.07997402315436834+0j), (0.0676968610754815+0j), (0.08080761110215218+0j), ...]",3.060064+0.000000j,True
1,Z11,20,"[T_46, T_441, T_1039, T_1554, T_1986, T_2346, T_2643, T_2886, T_3084, T_3237, T_3359, T_3450, T_3527, T_3537, T_3545, T_3553, T_3561, T_3566, T_3577, T_3580]","[(1.305051659990087+0j), (-0.08527729313134724+0j), (-0.07252641022137937+0j), (-0.08118583198191065+0j), (-0.06768235920657868+0j), (-0.07997402315436834+0j), (-0.0643686821298091+0j), (-0.07948347741548079+0j), (-0.06090134206715498+0j), (-0.0826178707997248+0j), (-0.06063496885970733+0j), (-0.0859051639186294+0j), (-0.08351755713983326+0j), (-0.05515552756086485+0j), (-0.08634889311814015+0j), (-0.0646875880322408+0j), (-0.08942345882819708+0j), (-0.07170233442860685+0j), (-0.09557970288804435+0j), (-0.07946875903458667+0j)]",-0.141390+0.000000j,True
2,Z4,20,"[T_21, T_186, T_805, T_1349, T_1789, T_2197, T_2229, T_2249, T_2277, T_2296, T_2320, T_2346, T_2366, T_2391, T_2407, T_2439, T_2451, T_2482, T_2490, T_2528]","[(1.5630902062711896+0j), (-0.05728294465508936+0j), (-0.07957591868590091+0j), (-0.05027721373846579+0j), (-0.07790091878059768+0j), (-0.08285169886065757+0j), (-0.050657167395117+0j), (-0.0773669648739134+0j), (-0.05839484379620484+0j), (-0.07885605540201591+0j), (-0.0643686821298091+0j), (-0.07997402315436834+0j), (-0.0676968610754815+0j), (-0.08080761110215218+0j), (-0.0733874985455447+0j), (-0.08617981639699925+0j), (-0.07547674910735439+0j), (-0.08429809795541524+0j), (-0.07950001337933078+0j), (-0.0873544923591077+0j)]",0.170883+0.000000j,True
3,Z5,20,"[T_25, T_215, T_845, T_1373, T_1825, T_2197, T_2532, T_2560, T_2580, T_2604, T_2623, T_2643, T_2669, T_2685, T_2710, T_2722, T_2754, T_2762, T_2793, T_2797]","[(1.5630902062711896+0j), (-0.07957591868590091+0j), (-0.05728294465508936+0j), (-0.07790091878059768+0j), (-0.05027721373846579+0j), (-0.08285169886065757+0j), (-0.0773669648739134+0j), (-0.050657167395117+0j), (-0.07885605540201591+0j), (-0.05839484379620484+0j), (-0.07997402315436834+0j), (-0.0643686821298091+0j), (-0.08080761110215218+0j), (-0.0676968610754815+0j), (-0.08617981639699925+0j), (-0.0733874985455447+0j), (-0.08429809795541524+0j), (-0.07547674910735439+0j), (-0.0873544923591077+0j), (-0.07950001337933078+0j)]",0.170883+0.000000j,True
4,Z6,20,"[T_29, T_255, T_874, T_1409, T_1849, T_2229, T_2532, T_2810, T_2835, T_2850, T_2871, T_2886, T_2904, T_2924, T_2938, T_2958, T_2969, T_2994, T_3001, T_3026]","[(1.4664505063672386+0j), (-0.06114803594208264+0j), (-0.07724377089188787+0j), (-0.057277549630481664+0j), (-0.07786412825339058+0j), (-0.050657167395117+0j), (-0.0773669648739134+0j), (-0.08115611389054331+0j), (-0.050925979344543015+0j), (-0.07861234067025152+0j), (-0.06090134206715498+0j), (-0.07948347741548079+0j), (-0.06548105275580618+0j), (-0.0821024997555598+0j), (-0.06922555665629188+0j), (-0.08189675488356118+0j), (-0.07342586952132193+0j), (-0.08435995944602817+0j), (-0.07652138031824796+0j), (-0.08516154184552238+0j)]",0.095639+0.000000j,True
...,...,...,...,...,...,...
10056,Y2 Y3 X5 Z6 Z7 Z8 Z9 Z10 Z11 X12,2,"[T_1315, T_1371]","[(-0.003958408601295751+0j), (0.003958408601295751+0j)]",0.000000+0.000000j,False
10057,X2 X3 Y5 Z6 Z7 Z8 Z9 Z10 Z11 Y12,2,"[T_1315, T_1371]","[(-0.003958408601295751+0j), (0.003958408601295751+0j)]",0.000000+0.000000j,False
10058,X2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 X12,2,"[T_1315, T_1371]","[(0.003958408601295751+0j), (0.003958408601295751+0j)]",0.007917+0.000000j,True
10059,Y2 X3 X5 Z6 Z7 Z8 Z9 Z10 Z11 Y12,2,"[T_1315, T_1371]","[(0.003958408601295751+0j), (0.003958408601295751+0j)]",0.007917+0.000000j,True
10060,X16 Y17 X18 Y19,2,"[T_3674, T_3676]","[(0.022598000072742933+0j), (-0.022598000072742933+0j)]",0.000000+0.000000j,False

=== BK Pauli-duplication ratio ===

,mapping,include_identity,sum_alpha_number_of_Pauli_strings,number_of_unique_Pauli_strings_before_cancellation,number_of_Pauli_strings_in_full_H,duplication_ratio,raw_reuse_ratio_before_cancellation
0,BK,True,25441,11691,7151,3.557684,2.176118

=== Duplicated BK Pauli strings ===

,Pauli_string,number_of_appearances,appears_in_vertices,individual_coefficients,combined_coefficient_in_full_H,survives_in_full_H
0,I,211,"[T_0, T_1, T_6, T_11, T_16, T_21, T_25, T_29, T_33, T_37, T_40, T_43, T_46, T_49, T_51, T_53, T_55, T_57, T_58, T_59, T_60, T_61, T_111, T_141, T_186, T_215, T_255, T_293, T_328, T_365, T_395, T_441, T_466, T_511, T_531, T_585, T_600, T_653, T_663, T_725, T_730, T_775, T_805, T_845, T_874, T_909, T_947, T_977, T_1014, T_1039, T_1085, T_1105, T_1150, T_1165, T_1219, T_1229, T_1282, T_1287, T_1308, T_1349, T_1373, T_1409, T_1433, T_1465, T_1496, T_1523, T_1554, T_1577, T_1615, T_1633, T_1671, T_1685, T_1730, T_1739, T_1784, T_1789, T_1825, T_1849, T_1881, T_1905, T_1932, T_1963, T_1986, T_2017, T_2035, T_2073, T_2087, T_2125, T_2134, T_2179, T_2184, T_2197, T_2229, T_2249, T_2277, T_2296, T_2320, T_2346, T_2366, T_2391, ...]","[(13.76808794966473+0j), (-1.7679774994319637+0j), (-1.7679774994319637+0j), (-1.6555019362457821+0j), (-1.6555019362457821+0j), (-1.5630902062711896+0j), (-1.5630902062711896+0j), (-1.4664505063672386+0j), (-1.4664505063672386+0j), (-1.4107676907228812+0j), (-1.4107676907228812+0j), (-1.305051659990087+0j), (-1.305051659990087+0j), (-1.137441725788379+0j), (-1.137441725788379+0j), (-0.9816003783964337+0j), (-0.9816003783964337+0j), (-0.7964058499573899+0j), (-0.7964058499573899+0j), (-0.6673137423023049+0j), (-0.6673137423023049+0j), (0.10191392055616116+0j), (0.049391342399017824+0j), (0.08223002261135531+0j), (0.05728294465508936+0j), (0.07957591868590091+0j), (0.06114803594208264+0j), (0.07724377089188787+0j), (0.06878493495310864+0j), (0.0836670461023376+0j), (0.07252641022137937+0j), (0.08527729313134724+0j), (0.0726800491728012+0j), (0.08205023079631743+0j), (0.07795149507488103+0j), (0.08674332134356735+0j), (0.08212526725185146+0j), (0.08988142709584254+0j), (0.10140180050126363+0j), (0.11133560889472865+0j), (0.08223002261135531+0j), (0.049391342399017824+0j), (0.07957591868590091+0j), (0.05728294465508936+0j), (0.07724377089188787+0j), (0.06114803594208264+0j), (0.0836670461023376+0j), (0.06878493495310864+0j), (0.08527729313134724+0j), (0.07252641022137937+0j), (0.08205023079631743+0j), (0.0726800491728012+0j), (0.08674332134356735+0j), (0.07795149507488103+0j), (0.08988142709584254+0j), (0.08212526725185146+0j), (0.11133560889472865+0j), (0.10140180050126363+0j), (0.08766914141799742+0j), (0.05027721373846579+0j), (0.07790091878059768+0j), (0.057277549630481664+0j), (0.07786412825339058+0j), (0.06340872425214235+0j), (0.07983834944104189+0j), (0.06768235920657868+0j), (0.08118583198191065+0j), (0.0703640306642336+0j), (0.08182610432894313+0j), (0.07440969213402784+0j), (0.08373025748616564+0j), (0.08314160859890551+0j), (0.09373855541314824+0j), (0.08294669631524386+0j), (0.09027954513132128+0j), (0.07790091878059768+0j), (0.05027721373846579+0j), (0.07786412825339058+0j), (0.057277549630481664+0j), (0.07983834944104189+0j), (0.06340872425214235+0j), (0.08118583198191065+0j), (0.06768235920657868+0j), (0.08182610432894313+0j), (0.0703640306642336+0j), (0.08373025748616564+0j), (0.07440969213402784+0j), (0.09373855541314824+0j), (0.08314160859890551+0j), (0.09027954513132128+0j), (0.08294669631524386+0j), (0.08285169886065757+0j), (0.050657167395117+0j), (0.0773669648739134+0j), (0.05839484379620484+0j), (0.07885605540201591+0j), (0.0643686821298091+0j), (0.07997402315436834+0j), (0.0676968610754815+0j), (0.08080761110215218+0j), ...]",3.060064+0.000000j,True
1,Z9 Z10 Z11,20,"[T_46, T_441, T_1039, T_1554, T_1986, T_2346, T_2643, T_2886, T_3084, T_3237, T_3359, T_3450, T_3527, T_3537, T_3545, T_3553, T_3561, T_3566, T_3577, T_3580]","[(1.305051659990087+0j), (-0.08527729313134724+0j), (-0.07252641022137937+0j), (-0.08118583198191065+0j), (-0.06768235920657868+0j), (-0.07997402315436834+0j), (-0.0643686821298091+0j), (-0.07948347741548079+0j), (-0.06090134206715498+0j), (-0.0826178707997248+0j), (-0.06063496885970733+0j), (-0.0859051639186294+0j), (-0.08351755713983326+0j), (-0.05515552756086485+0j), (-0.08634889311814015+0j), (-0.0646875880322408+0j), (-0.08942345882819708+0j), (-0.07170233442860685+0j), (-0.09557970288804435+0j), (-0.07946875903458667+0j)]",-0.141390+0.000000j,True
2,Z4,20,"[T_21, T_186, T_805, T_1349, T_1789, T_2197, T_2229, T_2249, T_2277, T_2296, T_2320, T_2346, T_2366, T_2391, T_2407, T_2439, T_2451, T_2482, T_2490, T_2528]","[(1.5630902062711896+0j), (-0.05728294465508936+0j), (-0.07957591868590091+0j), (-0.05027721373846579+0j), (-0.07790091878059768+0j), (-0.08285169886065757+0j), (-0.050657167395117+0j), (-0.0773669648739134+0j), (-0.05839484379620484+0j), (-0.07885605540201591+0j), (-0.0643686821298091+0j), (-0.07997402315436834+0j), (-0.0676968610754815+0j), (-0.08080761110215218+0j), (-0.0733874985455447+0j), (-0.08617981639699925+0j), (-0.07547674910735439+0j), (-0.08429809795541524+0j), (-0.07950001337933078+0j), (-0.0873544923591077+0j)]",0.170883+0.000000j,True
3,Z4 Z5,20,"[T_25, T_215, T_845, T_1373, T_1825, T_2197, T_2532, T_2560, T_2580, T_2604, T_2623, T_2643, T_2669, T_2685, T_2710, T_2722, T_2754, T_2762, T_2793, T_2797]","[(1.5630902062711896+0j), (-0.07957591868590091+0j), (-0.05728294465508936+0j), (-0.07790091878059768+0j), (-0.05027721373846579+0j), (-0.08285169886065757+0j), (-0.0773669648739134+0j), (-0.050657167395117+0j), (-0.07885605540201591+0j), (-0.05839484379620484+0j), (-0.07997402315436834+0j), (-0.0643686821298091+0j), (-0.08080761110215218+0j), (-0.0676968610754815+0j), (-0.08617981639699925+0j), (-0.0733874985455447+0j), (-0.08429809795541524+0j), (-0.07547674910735439+0j), (-0.0873544923591077+0j), (-0.07950001337933078+0j)]",0.170883+0.000000j,True
4,Z6,20,"[T_29, T_255, T_874, T_1409, T_1849, T_2229, T_2532, T_2810, T_2835, T_2850, T_2871, T_2886, T_2904, T_2924, T_2938, T_2958, T_2969, T_2994, T_3001, T_3026]","[(1.4664505063672386+0j), (-0.06114803594208264+0j), (-0.07724377089188787+0j), (-0.057277549630481664+0j), (-0.07786412825339058+0j), (-0.050657167395117+0j), (-0.0773669648739134+0j), (-0.08115611389054331+0j), (-0.050925979344543015+0j), (-0.07861234067025152+0j), (-0.06090134206715498+0j), (-0.07948347741548079+0j), (-0.06548105275580618+0j), (-0.0821024997555598+0j), (-0.06922555665629188+0j), (-0.08189675488356118+0j), (-0.07342586952132193+0j), (-0.08435995944602817+0j), (-0.07652138031824796+0j), (-0.08516154184552238+0j)]",0.095639+0.000000j,True
...,...,...,...,...,...,...
10056,Z1 X2 Y5 Y7 Z11 X12 X13,2,"[T_1315, T_1371]","[(-0.003958408601295751+0j), (0.003958408601295751+0j)]",0.000000+0.000000j,False
10057,X2 Z3 Z4 X5 Y7 Z11 Y12 X13,2,"[T_1315, T_1371]","[(-0.003958408601295751+0j), (0.003958408601295751+0j)]",0.000000+0.000000j,False
10058,X2 Z3 Y5 Y7 Z11 X12 X13,2,"[T_1315, T_1371]","[(-0.003958408601295751+0j), (-0.003958408601295751+0j)]",-0.007917+0.000000j,True
10059,Y2 Z3 Y5 Y7 Z11 Y12 X13,2,"[T_1315, T_1371]","[(-0.003958408601295751+0j), (-0.003958408601295751+0j)]",-0.007917+0.000000j,True
10060,Y16 Y18 Z19,2,"[T_3674, T_3676]","[(0.022598000072742933+0j), (-0.022598000072742933+0j)]",0.000000+0.000000j,False