In [1]:
# Cell 1: Build N2 fermionic Hamiltonian and Hermitian fermionic terms

import pandas as pd

from openfermion.chem import MolecularData
from openfermion.ops import FermionOperator
from openfermion.transforms import get_fermion_operator, normal_ordered
from openfermion.utils import hermitian_conjugated
from openfermionpyscf import run_pyscf

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# Nitrogen molecule / N2 configuration
# ------------------------------------------------------------

N2_BOND_LENGTH = 1.098  # Angstrom, approximate N-N equilibrium bond length
BASIS = "sto-3g"
MULTIPLICITY = 1
CHARGE = 0

# Full N2/STO-3G should give 20 qubits:
# Each N has 5 STO-3G spatial orbitals.
# 10 spatial orbitals * 2 spin orbitals = 20 qubits.
USE_ACTIVE_SPACE = True

# Optional active-space example:
# Freeze the two lowest occupied core-like spatial orbitals and keep valence orbitals active.
# This usually reduces N2/STO-3G from 20 qubits to 16 qubits.
OCCUPIED_INDICES = [0, 1]
ACTIVE_INDICES = [2, 3, 4, 5, 6, 7, 8, 9]

# Set this smaller, e.g. 1e-10, if tiny numerical terms clutter the graph.
TERM_ABS_TOL = 1e-12

# For large molecules, printing the full Hamiltonian can be very large.
PRINT_FULL_HAMILTONIAN = True


def format_fermion_term(term):
    if term == ():
        return "I"

    pieces = []
    for orbital, action in term:
        if action == 1:
            pieces.append(f"a_{orbital}^dagger")
        else:
            pieces.append(f"a_{orbital}")
    return " ".join(pieces)


def sort_fermion_key(term):
    return (len(term), term)


def coeff_to_str(c, digits=8):
    c = complex(c)
    if abs(c.imag) < 1e-12:
        return f"{c.real:+.{digits}f}"
    return f"{c.real:+.{digits}f}{c.imag:+.{digits}f}j"


def operator_to_string(op, digits=8):
    pieces = []

    for term, coeff in sorted(op.terms.items(), key=lambda item: sort_fermion_key(item[0])):
        pieces.append(f"{coeff_to_str(coeff, digits)} {format_fermion_term(term)}")

    if len(pieces) == 0:
        return "0"

    return " + ".join(pieces)


def dagger_term_key(term):
    """
    Return the OpenFermion key for O^dagger, where O is one monomial.
    """
    O = FermionOperator(term, 1.0)
    O_dag = normal_ordered(hermitian_conjugated(O))
    O_dag.compress(abs_tol=TERM_ABS_TOL)

    if len(O_dag.terms) != 1:
        raise ValueError(f"Expected one dagger term, got: {O_dag}")

    return next(iter(O_dag.terms.keys()))


def make_hermitian_fermionic_terms(fermion_hamiltonian, tol=TERM_ABS_TOL):
    """
    Group raw monomials into Hermitian fermionic Hamiltonian terms.

    If O is self-adjoint, keep c O.
    If O is not self-adjoint, group c O + c* O^dagger using the
    coefficients already present in the Hamiltonian.
    """
    used = set()
    hermitian_terms = []

    for term, coeff in fermion_hamiltonian.terms.items():
        if term in used:
            continue

        dag = dagger_term_key(term)

        if dag == term:
            T = FermionOperator(term, coeff)
            used.add(term)
        else:
            dag_coeff = fermion_hamiltonian.terms.get(dag, 0.0)

            T = FermionOperator(term, coeff)
            T += FermionOperator(dag, dag_coeff)

            used.add(term)
            used.add(dag)

        T = normal_ordered(T)
        T.compress(abs_tol=tol)
        hermitian_terms.append(T)

    return hermitian_terms


def infer_n_qubits_from_fermion_operator(op):
    """
    Infer the number of spin orbitals used by the FermionOperator.

    This is important for active-space Hamiltonians, where the active
    modes may be reindexed and smaller than molecule.n_qubits.
    """
    max_orbital = -1

    for term in op.terms:
        for orbital, action in term:
            max_orbital = max(max_orbital, orbital)

    return max_orbital + 1


def build_n2_geometry(n2_bond_length=N2_BOND_LENGTH):
    """
    Build linear nitrogen molecule geometry.

    First nitrogen is placed at the origin.
    Second nitrogen is placed on the z-axis.
    """
    geometry = [
        ("N", (0.0, 0.0, 0.0)),
        ("N", (0.0, 0.0, n2_bond_length)),
    ]

    return geometry


def build_n2_fermionic_hamiltonian(
    n2_bond_length=N2_BOND_LENGTH,
    basis=BASIS,
    multiplicity=MULTIPLICITY,
    charge=CHARGE,
    use_active_space=USE_ACTIVE_SPACE,
    occupied_indices=OCCUPIED_INDICES,
    active_indices=ACTIVE_INDICES,
):
    """
    Build an N2 fermionic Hamiltonian using OpenFermion + PySCF.

    If use_active_space=True, molecule.get_molecular_hamiltonian is called
    with occupied_indices and active_indices.
    """
    geometry = build_n2_geometry(n2_bond_length=n2_bond_length)

    molecule = MolecularData(
        geometry=geometry,
        basis=basis,
        multiplicity=multiplicity,
        charge=charge,
        description=f"N2_{n2_bond_length}",
    )

    # FCI is not required for constructing the fermionic Hamiltonian.
    molecule = run_pyscf(
        molecule,
        run_scf=True,
        run_fci=False,
    )

    if use_active_space:
        molecular_hamiltonian = molecule.get_molecular_hamiltonian(
            occupied_indices=occupied_indices,
            active_indices=active_indices,
        )
    else:
        molecular_hamiltonian = molecule.get_molecular_hamiltonian()

    fermion_hamiltonian = get_fermion_operator(molecular_hamiltonian)
    fermion_hamiltonian = normal_ordered(fermion_hamiltonian)
    fermion_hamiltonian.compress(abs_tol=TERM_ABS_TOL)

    n_qubits = infer_n_qubits_from_fermion_operator(fermion_hamiltonian)

    return molecule, fermion_hamiltonian, n_qubits


# ------------------------------------------------------------
# Build N2 fermionic Hamiltonian
# ------------------------------------------------------------

molecule, Hf, n_qubits = build_n2_fermionic_hamiltonian()
hermitian_terms = make_hermitian_fermionic_terms(Hf)

print("Molecule: N2 / Nitrogen")
print("Basis:", BASIS)
print("N-N bond length [Angstrom]:", N2_BOND_LENGTH)
print("Use active space:", USE_ACTIVE_SPACE)
if USE_ACTIVE_SPACE:
    print("Frozen occupied spatial orbitals:", OCCUPIED_INDICES)
    print("Active spatial orbitals:", ACTIVE_INDICES)
print("Full molecule electrons:", molecule.n_electrons)
print("Full molecule spatial orbitals:", molecule.n_orbitals)
print("Full molecule spin orbitals / qubits:", molecule.n_qubits)
print("Hamiltonian spin orbitals / qubits used:", n_qubits)
print("Number of raw OpenFermion monomial terms:", len(Hf.terms))
print("Number of Hermitian fermionic terms:", len(hermitian_terms))

if PRINT_FULL_HAMILTONIAN:
    print("\n=== Full fermionic Hamiltonian H_f ===")
    print(Hf)


# ------------------------------------------------------------
# Tables
# ------------------------------------------------------------

raw_rows = []

for idx, (term, coeff) in enumerate(
    sorted(Hf.terms.items(), key=lambda item: sort_fermion_key(item[0]))
):
    raw_rows.append(
        {
            "raw_index": idx,
            "coefficient": coeff_to_str(coeff),
            "monomial": format_fermion_term(term),
            "OpenFermion_key": term,
        }
    )

raw_df = pd.DataFrame(raw_rows)

print("\n=== Raw fermionic monomials c_alpha O_alpha ===")
display(raw_df)


hermitian_rows = []

for i, T in enumerate(hermitian_terms):
    hermitian_rows.append(
        {
            "vertex": f"T_{i}",
            "number_of_monomials": len(T.terms),
            "fermionic_term": operator_to_string(T),
        }
    )

hermitian_df = pd.DataFrame(hermitian_rows)

print("\n=== Hermitian fermionic terms T_i ===")
display(hermitian_df)

Molecule: N2 / Nitrogen
Basis: sto-3g
N-N bond length [Angstrom]: 1.098
Use active space: True
Frozen occupied spatial orbitals: [0, 1]
Active spatial orbitals: [2, 3, 4, 5, 6, 7, 8, 9]
Full molecule electrons: 14
Full molecule spatial orbitals: 10
Full molecule spin orbitals / qubits: 20
Hamiltonian spin orbitals / qubits used: 16
Number of raw OpenFermion monomial terms: 1177
Number of Hermitian fermionic terms: 657

=== Full fermionic Hamiltonian H_f ===
-76.41243108300478 [] +
-6.452605112629839 [0^ 0] +
-0.4315615775999122 [0^ 8] +
-0.7480073008124315 [1^ 0^ 1 0] +
-0.05620697656185599 [1^ 0^ 3 2] +
-0.10510610517640354 [1^ 0^ 5 4] +
-0.10510610517640348 [1^ 0^ 7 6] +
0.10887328123739282 [1^ 0^ 8 1] +
-0.10887328123739282 [1^ 0^ 9 0] +
-0.05152200694044894 [1^ 0^ 9 8] +
-0.04418890184108795 [1^ 0^ 11 10] +
-0.04418890184108793 [1^ 0^ 13 12] +
0.05911257020782717 [1^ 0^ 14 3] +
-0.05911257020782717 [1^ 0^ 15 2] +
-0.1066654988912812 [1^ 0^ 15 14] +
-6.452605112629839 [1^ 1] +
-0.4315615775999122 [1^ 9] +
-0.45593364533748104 [2^ 0^ 2 0] +
0.09183016321356004 [2^ 0^ 8 2] +
-0.009273637226071687 [2^ 0^ 10 4] +
-0.029833534606111815 [2^ 0^ 10 6] +
-0.029833534606111826 [2^ 0^ 12 4] +
0.009273637226071692 [2^ 0^ 12 6] +
-0.0143310539535184 [2^ 0^ 14 0] +
-0.08659892439340204 [2^ 0^ 14 8] +
-0.5121406218993371 [2^ 1^ 2 1] +
0.05620697656185599 [2^ 1^ 3 0] +
0.09289720158874734 [2^ 1^ 8 3] +
-0.001067038375187298 [2^ 1^ 9 2] +
-0.021994017978638154 [2^ 1^ 10 5] +
-0.07075533369457629 [2^ 1^ 10 7] +
0.012720380752566469 [2^ 1^ 11 4] +
0.04092179908846447 [2^ 1^ 11 6] +
-0.07075533369457629 [2^ 1^ 12 5] +
0.021994017978638168 [2^ 1^ 12 7] +
0.04092179908846446 [2^ 1^ 13 4] +
-0.01272038075256648 [2^ 1^ 13 6] +
-0.07344362416134556 [2^ 1^ 14 1] +
-0.02957138804507832 [2^ 1^ 14 9] +
0.05911257020782717 [2^ 1^ 15 0] +
-0.05702753634832372 [2^ 1^ 15 8] +
-5.066036294053449 [2^ 2] +
-0.25596785072715916 [2^ 14] +
0.05620697656185599 [3^ 0^ 2 1] +
-0.5121406218993371 [3^ 0^ 3 0] +
-0.001067038375187298 [3^ 0^ 8 3] +
0.09289720158874734 [3^ 0^ 9 2] +
0.012720380752566469 [3^ 0^ 10 5] +
0.04092179908846447 [3^ 0^ 10 7] +
-0.021994017978638154 [3^ 0^ 11 4] +
-0.07075533369457629 [3^ 0^ 11 6] +
0.04092179908846446 [3^ 0^ 12 5] +
-0.01272038075256648 [3^ 0^ 12 7] +
-0.07075533369457629 [3^ 0^ 13 4] +
0.021994017978638168 [3^ 0^ 13 6] +
0.05911257020782717 [3^ 0^ 14 1] +
-0.05702753634832372 [3^ 0^ 14 9] +
-0.07344362416134556 [3^ 0^ 15 0] +
-0.02957138804507832 [3^ 0^ 15 8] +
-0.45593364533748104 [3^ 1^ 3 1] +
0.09183016321356004 [3^ 1^ 9 3] +
-0.009273637226071687 [3^ 1^ 11 5] +
-0.029833534606111815 [3^ 1^ 11 7] +
-0.029833534606111826 [3^ 1^ 13 5] +
0.009273637226071692 [3^ 1^ 13 7] +
-0.0143310539535184 [3^ 1^ 15 1] +
-0.08659892439340204 [3^ 1^ 15 9] +
-0.05620697656185599 [3^ 2^ 1 0] +
-0.5455977084784748 [3^ 2^ 3 2] +
-0.05080949375455382 [3^ 2^ 5 4] +
-0.05080949375455379 [3^ 2^ 7 6] +
-0.09289720158874734 [3^ 2^ 8 1] +
0.09289720158874734 [3^ 2^ 9 0] +
-0.22380686513530634 [3^ 2^ 9 8] +
-0.08236679300225276 [3^ 2^ 11 10] +
-0.08236679300225275 [3^ 2^ 13 12] +
-0.019888104189802962 [3^ 2^ 14 3] +
0.019888104189802962 [3^ 2^ 15 2] +
-0.04785324996201084 [3^ 2^ 15 14] +
-5.066036294053449 [3^ 3] +
-0.25596785072715916 [3^ 15] +
-0.5125509600166126 [4^ 0^ 4 0] +
0.06086463959229717 [4^ 0^ 8 4] +
-0.01589784753914661 [4^ 0^ 10 2] +
-0.05114379322370033 [4^ 0^ 12 2] +
0.02022649171929363 [4^ 0^ 14 10] +
0.06506915527936745 [4^ 0^ 14 12] +
-0.6176570651930161 [4^ 1^ 4 1] +
0.10510610517640354 [4^ 1^ 5 0] +
0.013880633434630217 [4^ 1^ 8 5] +
0.046984006157666944 [4^ 1^ 9 4] +
-0.02861822829171308 [4^ 1^ 10 3] +
0.012720380752566469 [4^ 1^ 11 2] +
-0.0920655923121648 [4^ 1^ 12 3] +
0.04092179908846446 [4^ 1^ 13 2] +
-0.010103437611907375 [4^ 1^ 14 11] +
-0.032503024249010054 [4^ 1^ 14 13] +
0.030329929331201006 [4^ 1^ 15 10] +
0.0975721795283775 [4^ 1^ 15 12] +
-0.4593323936212968 [4^ 2^ 4 2] +
-0.006624210313074922 [4^ 2^ 10 0] +
0.035613297215818886 [4^ 2^ 10 8] +
-0.0213102586175885 [4^ 2^ 12 0] +
0.11456891282515058 [4^ 2^ 12 8] +
0.0177840841251775 [4^ 2^ 14 4] +
-0.5101418873758505 [4^ 3^ 4 3] +
0.05080949375455382 [4^ 3^ 5 2] +
-0.02861822829171308 [4^ 3^ 10 1] +
0.046737898606760746 [4^ 3^ 10 9] +
0.021994017978638154 [4^ 3^ 11 0] +
-0.01112460139094186 [4^ 3^ 11 8] +
-0.0920655923121648 [4^ 3^ 12 1] +
0.1503570477807435 [4^ 3^ 12 9] +
0.07075533369457629 [4^ 3^ 13 0] +
-0.035788134955592896 [4^ 3^ 13 8] +
-0.02385389678171298 [4^ 3^ 14 5] +
0.04163798090689048 [4^ 3^ 15 4] +
-5.325226873329335 [4^ 4] +
0.10510610517640354 [5^ 0^ 4 1] +
-0.6176570651930161 [5^ 0^ 5 0] +
0.046984006157666944 [5^ 0^ 8 5] +
0.013880633434630217 [5^ 0^ 9 4] +
0.012720380752566469 [5^ 0^ 10 3] +
-0.02861822829171308 [5^ 0^ 11 2] +
0.04092179908846446 [5^ 0^ 12 3] +
-0.0920655923121648 [5^ 0^ 13 2] +
0.030329929331201006 [5^ 0^ 14 11] +
0.0975721795283775 [5^ 0^ 14 13] +
-0.010103437611907375 [5^ 0^ 15 10] +
-0.032503024249010054 [5^ 0^ 15 12] +
-0.5125509600166126 [5^ 1^ 5 1] +
0.06086463959229717 [5^ 1^ 9 5] +
-0.01589784753914661 [5^ 1^ 11 3] +
-0.05114379322370033 [5^ 1^ 13 3] +
0.02022649171929363 [5^ 1^ 15 11] +
0.06506915527936745 [5^ 1^ 15 13] +
0.05080949375455382 [5^ 2^ 4 3] +
-0.5101418873758505 [5^ 2^ 5 2] +
0.021994017978638154 [5^ 2^ 10 1] +
-0.01112460139094186 [5^ 2^ 10 9] +
-0.02861822829171308 [5^ 2^ 11 0] +
0.046737898606760746 [5^ 2^ 11 8] +
0.07075533369457629 [5^ 2^ 12 1] +
-0.035788134955592896 [5^ 2^ 12 9] +
-0.0920655923121648 [5^ 2^ 13 0] +
0.1503570477807435 [5^ 2^ 13 8] +
0.04163798090689048 [5^ 2^ 14 5] +
-0.02385389678171298 [5^ 2^ 15 4] +
-0.4593323936212968 [5^ 3^ 5 3] +
-0.006624210313074922 [5^ 3^ 11 1] +
0.035613297215818886 [5^ 3^ 11 9] +
-0.0213102586175885 [5^ 3^ 13 1] +
0.11456891282515058 [5^ 3^ 13 9] +
0.0177840841251775 [5^ 3^ 15 5] +
-0.10510610517640354 [5^ 4^ 1 0] +
-0.05080949375455382 [5^ 4^ 3 2] +
-0.5883608125693621 [5^ 4^ 5 4] +
-0.02401588474180662 [5^ 4^ 7 6] +
-0.013880633434630217 [5^ 4^ 8 1] +
0.013880633434630217 [5^ 4^ 9 0] +
-0.028068387899039274 [5^ 4^ 9 8] +
-0.03382179136523367 [5^ 4^ 11 10] +
0.04776369033869873 [5^ 4^ 12 11] +
-0.04776369033869873 [5^ 4^ 13 10] +
-0.17263168228463566 [5^ 4^ 13 12] +
0.02385389678171298 [5^ 4^ 14 3] +
-0.02385389678171298 [5^ 4^ 15 2] +
-0.03536732805262958 [5^ 4^ 15 14] +
-5.325226873329335 [5^ 5] +
-0.5125509600166122 [6^ 0^ 6 0] +
0.06086463959229712 [6^ 0^ 8 6] +
-0.051143793223700315 [6^ 0^ 10 2] +
0.015897847539146623 [6^ 0^ 12 2] +
0.06506915527936742 [6^ 0^ 14 10] +
-0.02022649171929365 [6^ 0^ 14 12] +
-0.6176570651930158 [6^ 1^ 6 1] +
0.10510610517640348 [6^ 1^ 7 0] +
0.01388063343463021 [6^ 1^ 8 7] +
0.046984006157666916 [6^ 1^ 9 6] +
-0.09206559231216477 [6^ 1^ 10 3] +
0.04092179908846447 [6^ 1^ 11 2] +
0.028618228291713104 [6^ 1^ 12 3] +
-0.01272038075256648 [6^ 1^ 13 2] +
-0.03250302424901006 [6^ 1^ 14 11] +
0.010103437611907382 [6^ 1^ 14 13] +
0.09757217952837749 [6^ 1^ 15 10] +
-0.030329929331201034 [6^ 1^ 15 12] +
-0.4593323936212965 [6^ 2^ 6 2] +
-0.021310258617588493 [6^ 2^ 10 0] +
0.11456891282515055 [6^ 2^ 10 8] +
0.006624210313074934 [6^ 2^ 12 0] +
-0.03561329721581891 [6^ 2^ 12 8] +
0.017784084125177638 [6^ 2^ 14 6] +
-0.5101418873758503 [6^ 3^ 6 3] +
0.05080949375455379 [6^ 3^ 7 2] +
-0.09206559231216477 [6^ 3^ 10 1] +
0.1503570477807435 [6^ 3^ 10 9] +
0.07075533369457629 [6^ 3^ 11 0] +
-0.035788134955592896 [6^ 3^ 11 8] +
0.028618228291713104 [6^ 3^ 12 1] +
-0.04673789860676078 [6^ 3^ 12 9] +
-0.021994017978638168 [6^ 3^ 13 0] +
0.011124601390941869 [6^ 3^ 13 8] +
-0.023853896781712965 [6^ 3^ 14 7] +
0.0416379809068906 [6^ 3^ 15 6] +
-0.5163131583439419 [6^ 4^ 6 4] +
0.13055493144496294 [6^ 4^ 12 10] +
-0.5403290430857484 [6^ 5^ 6 5] +
0.02401588474180662 [6^ 5^ 7 4] +
0.04776369033869877 [6^ 5^ 11 10] +
-0.0041274797372193054 [6^ 5^ 12 11] +
0.13468241118218222 [6^ 5^ 13 10] +
-0.04776369033869881 [6^ 5^ 13 12] +
-5.325226873329331 [6^ 6] +
0.10510610517640348 [7^ 0^ 6 1] +
-0.6176570651930158 [7^ 0^ 7 0] +
0.046984006157666916 [7^ 0^ 8 7] +
0.01388063343463021 [7^ 0^ 9 6] +
0.04092179908846447 [7^ 0^ 10 3] +
-0.09206559231216477 [7^ 0^ 11 2] +
-0.01272038075256648 [7^ 0^ 12 3] +
0.028618228291713104 [7^ 0^ 13 2] +
0.09757217952837749 [7^ 0^ 14 11] +
-0.030329929331201034 [7^ 0^ 14 13] +
-0.03250302424901006 [7^ 0^ 15 10] +
0.010103437611907382 [7^ 0^ 15 12] +
-0.5125509600166122 [7^ 1^ 7 1] +
0.06086463959229712 [7^ 1^ 9 7] +
-0.051143793223700315 [7^ 1^ 11 3] +
0.015897847539146623 [7^ 1^ 13 3] +
0.06506915527936742 [7^ 1^ 15 11] +
-0.02022649171929365 [7^ 1^ 15 13] +
0.05080949375455379 [7^ 2^ 6 3] +
-0.5101418873758503 [7^ 2^ 7 2] +
0.07075533369457629 [7^ 2^ 10 1] +
-0.035788134955592896 [7^ 2^ 10 9] +
-0.09206559231216477 [7^ 2^ 11 0] +
0.1503570477807435 [7^ 2^ 11 8] +
-0.021994017978638168 [7^ 2^ 12 1] +
0.011124601390941869 [7^ 2^ 12 9] +
0.028618228291713104 [7^ 2^ 13 0] +
-0.04673789860676078 [7^ 2^ 13 8] +
0.0416379809068906 [7^ 2^ 14 7] +
-0.023853896781712965 [7^ 2^ 15 6] +
-0.4593323936212965 [7^ 3^ 7 3] +
-0.021310258617588493 [7^ 3^ 11 1] +
0.11456891282515055 [7^ 3^ 11 9] +
0.006624210313074934 [7^ 3^ 13 1] +
-0.03561329721581891 [7^ 3^ 13 9] +
0.017784084125177638 [7^ 3^ 15 7] +
0.02401588474180662 [7^ 4^ 6 5] +
-0.5403290430857484 [7^ 4^ 7 4] +
-0.04776369033869877 [7^ 4^ 11 10] +
0.13468241118218222 [7^ 4^ 12 11] +
-0.0041274797372193054 [7^ 4^ 13 10] +
0.04776369033869881 [7^ 4^ 13 12] +
-0.5163131583439419 [7^ 5^ 7 5] +
0.13055493144496294 [7^ 5^ 13 11] +
-0.10510610517640348 [7^ 6^ 1 0] +
-0.05080949375455379 [7^ 6^ 3 2] +
-0.02401588474180662 [7^ 6^ 5 4] +
-0.5883608125693613 [7^ 6^ 7 6] +
-0.01388063343463021 [7^ 6^ 8 1] +
0.01388063343463021 [7^ 6^ 9 0] +
-0.02806838789903926 [7^ 6^ 9 8] +
-0.17263168228463566 [7^ 6^ 11 10] +
-0.047763690338698775 [7^ 6^ 12 11] +
0.047763690338698775 [7^ 6^ 13 10] +
-0.03382179136523368 [7^ 6^ 13 12] +
0.023853896781712965 [7^ 6^ 14 3] +
-0.023853896781712965 [7^ 6^ 15 2] +
-0.03536732805262955 [7^ 6^ 15 14] +
-5.325226873329331 [7^ 7] +
-0.4315615775999122 [8^ 0] +
-0.4911132667108007 [8^ 0^ 8 0] +
-0.1115646752961843 [8^ 0^ 14 2] +
0.10887328123739282 [8^ 1^ 1 0] +
-0.09289720158874734 [8^ 1^ 3 2] +
-0.013880633434630217 [8^ 1^ 5 4] +
-0.01388063343463021 [8^ 1^ 7 6] +
-0.5426352736512496 [8^ 1^ 8 1] +
0.05152200694044894 [8^ 1^ 9 0] +
0.016227880024196725 [8^ 1^ 9 8] +
-0.025006850068928048 [8^ 1^ 11 10] +
-0.025006850068928034 [8^ 1^ 13 12] +
-0.05453713894786058 [8^ 1^ 14 3] +
-0.05702753634832372 [8^ 1^ 15 2] +
0.058811364086791745 [8^ 1^ 15 14] +
0.09183016321356005 [8^ 2^ 2 0] +
-0.3335248903371633 [8^ 2^ 8 2] +
0.0004987645960558259 [8^ 2^ 10 4] +
0.0016045388097457383 [8^ 2^ 10 6] +
0.0016045388097457453 [8^ 2^ 12 4] +
-0.0004987645960558285 [8^ 2^ 12 6] +
-0.02496575090278226 [8^ 2^ 14 0] +
0.09677090359382164 [8^ 2^ 14 8] +
0.09289720158874734 [8^ 3^ 2 1] +
-0.001067038375187298 [8^ 3^ 3 0] +
-0.5573317554724697 [8^ 3^ 8 3] +
0.22380686513530634 [8^ 3^ 9 2] +
0.011623365986997687 [8^ 3^ 10 5] +
0.03739267376533864 [8^ 3^ 10 7] +
-0.01112460139094186 [8^ 3^ 11 4] +
-0.035788134955592896 [8^ 3^ 11 6] +
0.03739267376533864 [8^ 3^ 12 5] +
-0.011623365986997697 [8^ 3^ 12 7] +
-0.035788134955592896 [8^ 3^ 13 4] +
0.011124601390941869 [8^ 3^ 13 6] +
-0.05453713894786058 [8^ 3^ 14 1] +
0.12430466044960237 [8^ 3^ 14 9] +
0.02957138804507832 [8^ 3^ 15 0] +
-0.027533756855780717 [8^ 3^ 15 8] +
0.06086463959229717 [8^ 4^ 4 0] +
-0.48984828617584586 [8^ 4^ 8 4] +
-0.03511453261976306 [8^ 4^ 10 2] +
-0.11296437401540485 [8^ 4^ 12 2] +
-0.02860782708788833 [8^ 4^ 14 10] +
-0.09203213136618572 [8^ 4^ 14 12] +
0.013880633434630217 [8^ 5^ 4 1] +
0.046984006157666944 [8^ 5^ 5 0] +
-0.5179166740748852 [8^ 5^ 8 5] +
0.028068387899039274 [8^ 5^ 9 4] +
0.011623365986997687 [8^ 5^ 10 3] +
-0.046737898606760746 [8^ 5^ 11 2] +
0.03739267376533864 [8^ 5^ 12 3] +
-0.1503570477807435 [8^ 5^ 13 2] +
-0.027277038113972522 [8^ 5^ 14 11] +
-0.08775094827276778 [8^ 5^ 14 13] +
-0.0013307889739158111 [8^ 5^ 15 10] +
-0.004281183093417944 [8^ 5^ 15 12] +
0.060864639592297126 [8^ 6^ 6 0] +
-0.48984828617584564 [8^ 6^ 8 6] +
-0.11296437401540484 [8^ 6^ 10 2] +
0.035114532619763085 [8^ 6^ 12 2] +
-0.09203213136618572 [8^ 6^ 14 10] +
0.028607827087888355 [8^ 6^ 14 12] +
0.01388063343463021 [8^ 7^ 6 1] +
0.046984006157666916 [8^ 7^ 7 0] +
-0.5179166740748848 [8^ 7^ 8 7] +
0.02806838789903926 [8^ 7^ 9 6] +
0.03739267376533864 [8^ 7^ 10 3] +
-0.1503570477807435 [8^ 7^ 11 2] +
-0.011623365986997697 [8^ 7^ 12 3] +
0.04673789860676078 [8^ 7^ 13 2] +
-0.08775094827276778 [8^ 7^ 14 11] +
0.02727703811397254 [8^ 7^ 14 13] +
-0.004281183093417943 [8^ 7^ 15 10] +
0.0013307889739158129 [8^ 7^ 15 12] +
-5.064610459065998 [8^ 8] +
-0.10887328123739282 [9^ 0^ 1 0] +
0.09289720158874734 [9^ 0^ 3 2] +
0.013880633434630217 [9^ 0^ 5 4] +
0.01388063343463021 [9^ 0^ 7 6] +
0.05152200694044894 [9^ 0^ 8 1] +
-0.5426352736512496 [9^ 0^ 9 0] +
-0.016227880024196725 [9^ 0^ 9 8] +
0.025006850068928048 [9^ 0^ 11 10] +
0.025006850068928034 [9^ 0^ 13 12] +
-0.05702753634832372 [9^ 0^ 14 3] +
-0.05453713894786058 [9^ 0^ 15 2] +
-0.058811364086791745 [9^ 0^ 15 14] +
-0.4315615775999122 [9^ 1] +
-0.4911132667108007 [9^ 1^ 9 1] +
-0.1115646752961843 [9^ 1^ 15 3] +
-0.001067038375187298 [9^ 2^ 2 1] +
0.09289720158874734 [9^ 2^ 3 0] +
0.22380686513530634 [9^ 2^ 8 3] +
-0.5573317554724697 [9^ 2^ 9 2] +
-0.01112460139094186 [9^ 2^ 10 5] +
-0.035788134955592896 [9^ 2^ 10 7] +
0.011623365986997687 [9^ 2^ 11 4] +
0.03739267376533864 [9^ 2^ 11 6] +
-0.035788134955592896 [9^ 2^ 12 5] +
0.011124601390941869 [9^ 2^ 12 7] +
0.03739267376533864 [9^ 2^ 13 4] +
-0.011623365986997697 [9^ 2^ 13 6] +
0.02957138804507832 [9^ 2^ 14 1] +
-0.027533756855780717 [9^ 2^ 14 9] +
-0.05453713894786058 [9^ 2^ 15 0] +
0.12430466044960237 [9^ 2^ 15 8] +
0.09183016321356005 [9^ 3^ 3 1] +
-0.3335248903371633 [9^ 3^ 9 3] +
0.0004987645960558259 [9^ 3^ 11 5] +
0.0016045388097457383 [9^ 3^ 11 7] +
0.0016045388097457453 [9^ 3^ 13 5] +
-0.0004987645960558285 [9^ 3^ 13 7] +
-0.02496575090278226 [9^ 3^ 15 1] +
0.09677090359382164 [9^ 3^ 15 9] +
0.046984006157666944 [9^ 4^ 4 1] +
0.013880633434630217 [9^ 4^ 5 0] +
0.028068387899039274 [9^ 4^ 8 5] +
-0.5179166740748852 [9^ 4^ 9 4] +
-0.046737898606760746 [9^ 4^ 10 3] +
0.011623365986997687 [9^ 4^ 11 2] +
-0.1503570477807435 [9^ 4^ 12 3] +
0.03739267376533864 [9^ 4^ 13 2] +
-0.0013307889739158111 [9^ 4^ 14 11] +
-0.004281183093417944 [9^ 4^ 14 13] +
-0.027277038113972522 [9^ 4^ 15 10] +
-0.08775094827276778 [9^ 4^ 15 12] +
0.06086463959229717 [9^ 5^ 5 1] +
-0.48984828617584586 [9^ 5^ 9 5] +
-0.03511453261976306 [9^ 5^ 11 3] +
-0.11296437401540485 [9^ 5^ 13 3] +
-0.02860782708788833 [9^ 5^ 15 11] +
-0.09203213136618572 [9^ 5^ 15 13] +
0.046984006157666916 [9^ 6^ 6 1] +
0.01388063343463021 [9^ 6^ 7 0] +
0.02806838789903926 [9^ 6^ 8 7] +
-0.5179166740748848 [9^ 6^ 9 6] +
-0.1503570477807435 [9^ 6^ 10 3] +
0.03739267376533864 [9^ 6^ 11 2] +
0.04673789860676078 [9^ 6^ 12 3] +
-0.011623365986997697 [9^ 6^ 13 2] +
-0.004281183093417943 [9^ 6^ 14 11] +
0.0013307889739158129 [9^ 6^ 14 13] +
-0.08775094827276778 [9^ 6^ 15 10] +
0.02727703811397254 [9^ 6^ 15 12] +
0.060864639592297126 [9^ 7^ 7 1] +
-0.48984828617584564 [9^ 7^ 9 7] +
-0.11296437401540484 [9^ 7^ 11 3] +
0.035114532619763085 [9^ 7^ 13 3] +
-0.09203213136618572 [9^ 7^ 15 11] +
0.028607827087888355 [9^ 7^ 15 13] +
-0.05152200694044894 [9^ 8^ 1 0] +
-0.22380686513530634 [9^ 8^ 3 2] +
-0.028068387899039274 [9^ 8^ 5 4] +
-0.02806838789903926 [9^ 8^ 7 6] +
0.016227880024196725 [9^ 8^ 8 1] +
-0.016227880024196725 [9^ 8^ 9 0] +
-0.5851082672943152 [9^ 8^ 9 8] +
-0.0382262516203235 [9^ 8^ 11 10] +
-0.03822625162032347 [9^ 8^ 13 12] +
-0.12430466044960237 [9^ 8^ 14 3] +
0.12430466044960237 [9^ 8^ 15 2] +
-0.09160067945380962 [9^ 8^ 15 14] +
-5.064610459065998 [9^ 9] +
-0.006624210313074924 [10^ 0^ 4 2] +
-0.021310258617588493 [10^ 0^ 6 2] +
-0.5522216806681741 [10^ 0^ 10 0] +
-0.05425625692134651 [10^ 0^ 10 8] +
0.012001925546671824 [10^ 0^ 14 4] +
0.038610509814851326 [10^ 0^ 14 6] +
-0.02861822829171308 [10^ 1^ 4 3] +
0.021994017978638154 [10^ 1^ 5 2] +
-0.09206559231216477 [10^ 1^ 6 3] +
0.07075533369457629 [10^ 1^ 7 2] +
-0.596410582509262 [10^ 1^ 10 1] +
-0.029249406852418457 [10^ 1^ 10 9] +
0.04418890184108795 [10^ 1^ 11 0] +
-0.025006850068928048 [10^ 1^ 11 8] +
-0.01832800378452918 [10^ 1^ 14 5] +
-0.058961669713526156 [10^ 1^ 14 7] +
0.030329929331201006 [10^ 1^ 15 4] +
0.09757217952837749 [10^ 1^ 15 6] +
-0.01589784753914661 [10^ 2^ 4 0] +
-0.051143793223700315 [10^ 2^ 6 0] +
-0.03511453261976306 [10^ 2^ 8 4] +
-0.11296437401540484 [10^ 2^ 8 6] +
-0.4537100905908901 [10^ 2^ 10 2] +
-0.007689343339705857 [10^ 2^ 14 10] +
-0.02861822829171308 [10^ 3^ 4 1] +
0.012720380752566469 [10^ 3^ 5 0] +
-0.09206559231216477 [10^ 3^ 6 1] +
0.04092179908846447 [10^ 3^ 7 0] +
0.011623365986997687 [10^ 3^ 8 5] +
0.03739267376533864 [10^ 3^ 8 7] +
-0.046737898606760746 [10^ 3^ 9 4] +
-0.1503570477807435 [10^ 3^ 9 6] +
-0.5360768835931429 [10^ 3^ 10 3] +
0.08236679300225276 [10^ 3^ 11 2] +
-0.036108730531062935 [10^ 3^ 14 11] +
0.028419387191357084 [10^ 3^ 15 10] +
-0.009273637226071687 [10^ 4^ 2 0] +
0.0004987645960558259 [10^ 4^ 8 2] +
-0.5117731798973485 [10^ 4^ 10 4] +
0.03478850140252365 [10^ 4^ 10 6] +
0.03478850140252374 [10^ 4^ 12 4] +
0.11582829262353062 [10^ 4^ 12 6] +
-0.008224566172621805 [10^ 4^ 14 0] +
-0.0014401982141311529 [10^ 4^ 14 8] +
-0.021994017978638154 [10^ 5^ 2 1] +
0.012720380752566469 [10^ 5^ 3 0] +
0.011623365986997687 [10^ 5^ 8 3] +
-0.01112460139094186 [10^ 5^ 9 2] +
-0.545594971262582 [10^ 5^ 10 5] +
-0.012975188936175115 [10^ 5^ 10 7] +
0.03382179136523367 [10^ 5^ 11 4] +
0.04776369033869877 [10^ 5^ 11 6] +
-0.012975188936174987 [10^ 5^ 12 5] +
-0.018854118558651614 [10^ 5^ 12 7] +
0.04776369033869873 [10^ 5^ 13 4] +
0.13468241118218222 [10^ 5^ 13 6] +
-0.01832800378452918 [10^ 5^ 14 1] +
-0.00010940924021534177 [10^ 5^ 14 9] +
0.010103437611907375 [10^ 5^ 15 0] +
-0.0013307889739158111 [10^ 5^ 15 8] +
-0.029833534606111815 [10^ 6^ 2 0] +
0.0016045388097457383 [10^ 6^ 8 2] +
0.03478850140252365 [10^ 6^ 10 4] +
-0.4106715260952496 [10^ 6^ 10 6] +
-0.01472663882143231 [10^ 6^ 12 4] +
-0.03478850140252347 [10^ 6^ 12 6] +
-0.026458645464516095 [10^ 6^ 14 0] +
-0.004633155493741763 [10^ 6^ 14 8] +
-0.07075533369457629 [10^ 7^ 2 1] +
0.04092179908846447 [10^ 7^ 3 0] +
0.03739267376533864 [10^ 7^ 8 3] +
-0.035788134955592896 [10^ 7^ 9 2] +
-0.012975188936175115 [10^ 7^ 10 5] +
-0.5833032083798853 [10^ 7^ 10 7] +
0.04776369033869877 [10^ 7^ 11 4] +
0.17263168228463566 [10^ 7^ 11 6] +
-0.018854118558651614 [10^ 7^ 12 5] +
0.012975188936175299 [10^ 7^ 12 7] +
0.0041274797372193054 [10^ 7^ 13 4] +
-0.047763690338698775 [10^ 7^ 13 6] +
-0.058961669713526156 [10^ 7^ 14 1] +
-0.0003519724003238204 [10^ 7^ 14 9] +
0.03250302424901006 [10^ 7^ 15 0] +
-0.004281183093417943 [10^ 7^ 15 8] +
0.035613297215818886 [10^ 8^ 4 2] +
0.11456891282515058 [10^ 8^ 6 2] +
-0.0542562569213465 [10^ 8^ 10 0] +
-0.5025350300766592 [10^ 8^ 10 8] +
0.027167628873757177 [10^ 8^ 14 4] +
0.08739897587244395 [10^ 8^ 14 6] +
0.046737898606760746 [10^ 9^ 4 3] +
-0.01112460139094186 [10^ 9^ 5 2] +
0.1503570477807435 [10^ 9^ 6 3] +
-0.035788134955592896 [10^ 9^ 7 2] +
-0.029249406852418457 [10^ 9^ 10 1] +
-0.5407612816969827 [10^ 9^ 10 9] +
-0.025006850068928048 [10^ 9^ 11 0] +
0.0382262516203235 [10^ 9^ 11 8] +
-0.00010940924021534177 [10^ 9^ 14 5] +
-0.0003519724003238204 [10^ 9^ 14 7] +
0.027277038113972522 [10^ 9^ 15 4] +
0.08775094827276778 [10^ 9^ 15 6] +
-4.951966435522932 [10^ 10] +
0.021994017978638154 [11^ 0^ 4 3] +
-0.02861822829171308 [11^ 0^ 5 2] +
0.07075533369457629 [11^ 0^ 6 3] +
-0.09206559231216477 [11^ 0^ 7 2] +
0.04418890184108795 [11^ 0^ 10 1] +
-0.025006850068928048 [11^ 0^ 10 9] +
-0.596410582509262 [11^ 0^ 11 0] +
-0.029249406852418457 [11^ 0^ 11 8] +

,raw_index,coefficient,monomial,OpenFermion_key
0,0,-76.41243108,I,()
1,1,-6.45260511,a_0^dagger a_0,"((0, 1), (0, 0))"
2,2,-0.43156158,a_0^dagger a_8,"((0, 1), (8, 0))"
3,3,-6.45260511,a_1^dagger a_1,"((1, 1), (1, 0))"
4,4,-0.43156158,a_1^dagger a_9,"((1, 1), (9, 0))"
...,...,...,...,...
1172,1172,-0.04723612,a_15^dagger a_14^dagger a_11 a_10,"((15, 1), (14, 1), (11, 0), (10, 0))"
1173,1173,-0.04723612,a_15^dagger a_14^dagger a_13 a_12,"((15, 1), (14, 1), (13, 0), (12, 0))"
1174,1174,+0.04548694,a_15^dagger a_14^dagger a_14 a_3,"((15, 1), (14, 1), (14, 0), (3, 0))"
1175,1175,-0.04548694,a_15^dagger a_14^dagger a_15 a_2,"((15, 1), (14, 1), (15, 0), (2, 0))"
1176,1176,-0.76034873,a_15^dagger a_14^dagger a_15 a_14,"((15, 1), (14, 1), (15, 0), (14, 0))"

=== Hermitian fermionic terms T_i ===

,vertex,number_of_monomials,fermionic_term
0,T_0,1,-76.41243108 I
1,T_1,1,-6.45260511 a_0^dagger a_0
2,T_2,2,-0.43156158 a_0^dagger a_8 + -0.43156158 a_8^dagger a_0
3,T_3,1,-6.45260511 a_1^dagger a_1
4,T_4,2,-0.43156158 a_1^dagger a_9 + -0.43156158 a_9^dagger a_1
...,...,...,...
652,T_652,2,+0.04723612 a_14^dagger a_13^dagger a_15 a_12 + +0.04723612 a_15^dagger a_12^dagger a_14 a_13
653,T_653,1,-0.62168539 a_15^dagger a_12^dagger a_15 a_12
654,T_654,1,-0.62168539 a_14^dagger a_13^dagger a_14 a_13
655,T_655,1,-0.57444927 a_15^dagger a_13^dagger a_15 a_13
656,T_656,1,-0.76034873 a_15^dagger a_14^dagger a_15 a_14

In [2]:
# Cell 2: Build the H2 fermionic noncommutation graph

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from openfermion.transforms import normal_ordered

pd.set_option("display.max_colwidth", None)


def fermionic_commutator(A, B, tol=1e-12):
    """
    Compute [A, B] = AB - BA directly in the fermionic algebra.
    """
    C = normal_ordered(A * B - B * A)
    C.compress(abs_tol=tol)
    return C


def commute(A, B, tol=1e-12):
    """
    Return True if [A, B] = 0.
    """
    C = fermionic_commutator(A, B, tol=tol)
    return len(C.terms) == 0


# ------------------------------------------------------------
# Build noncommutation graph
# ------------------------------------------------------------
# Vertex i = Hermitian fermionic term T_i
# Edge (i, j) exists if [T_i, T_j] != 0

G = nx.Graph()

for i, T in enumerate(hermitian_terms):
    G.add_node(
        i,
        label=f"T_{i}",
        operator=T,
        operator_string=operator_to_string(T),
        number_of_monomials=len(T.terms),
    )

for i in range(len(hermitian_terms)):
    for j in range(i + 1, len(hermitian_terms)):
        Cij = fermionic_commutator(hermitian_terms[i], hermitian_terms[j])

        if len(Cij.terms) != 0:
            G.add_edge(
                i,
                j,
                commutator=Cij,
                commutator_string=operator_to_string(Cij),
            )


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

n_vertices = G.number_of_nodes()
n_total_pairs = n_vertices * (n_vertices - 1) // 2
n_noncommuting_pairs = G.number_of_edges()
n_commuting_pairs = n_total_pairs - n_noncommuting_pairs

print("=== Fermionic noncommutation graph summary ===")
print("Number of vertices / fermionic terms:", n_vertices)
print("Number of total unordered pairs:", n_total_pairs)
print("Number of noncommuting pairs / edges:", n_noncommuting_pairs)
print("Number of commuting pairs:", n_commuting_pairs)
print("Is graph bipartite?", nx.is_bipartite(G))


# ------------------------------------------------------------
# Vertex table
# ------------------------------------------------------------

vertex_rows = []

for i, data in G.nodes(data=True):
    vertex_rows.append(
        {
            "vertex": f"T_{i}",
            "degree": G.degree[i],
            "commutes_with_all": G.degree[i] == 0,
            "fermionic_term": data["operator_string"],
        }
    )

vertex_df = pd.DataFrame(vertex_rows)

print("\n=== Vertices: fermionic terms ===")
display(vertex_df)


# ------------------------------------------------------------
# Edge table
# ------------------------------------------------------------

edge_rows = []

for i, j, data in G.edges(data=True):
    edge_rows.append(
        {
            "source": f"T_{i}",
            "target": f"T_{j}",
            "meaning": f"[T_{i}, T_{j}] != 0",
            "commutator": data["commutator_string"],
        }
    )

edge_df = pd.DataFrame(edge_rows)

print("\n=== Edges: noncommuting pairs ===")
display(edge_df)


# # ------------------------------------------------------------
# # Draw graph
# # ------------------------------------------------------------

# plt.figure(figsize=(12, 8))

# pos = nx.kamada_kawai_layout(G)

# node_labels = {
#     i: f"T_{i}"
#     for i in G.nodes()
# }

# node_sizes = [
#     1000 + 250 * G.degree[i]
#     for i in G.nodes()
# ]

# nx.draw_networkx_nodes(G, pos, node_size=node_sizes)
# nx.draw_networkx_edges(G, pos, width=1.5)
# nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=11, font_weight="bold")

# plt.title("H2 Fermionic Noncommutation Graph")
# plt.axis("off")
# plt.show()

=== Fermionic noncommutation graph summary ===
Number of vertices / fermionic terms: 657
Number of total unordered pairs: 215496
Number of noncommuting pairs / edges: 107184
Number of commuting pairs: 108312
Is graph bipartite? False

=== Vertices: fermionic terms ===

,vertex,degree,commutes_with_all,fermionic_term
0,T_0,0,True,-76.41243108 I
1,T_1,126,False,-6.45260511 a_0^dagger a_0
2,T_2,250,False,-0.43156158 a_0^dagger a_8 + -0.43156158 a_8^dagger a_0
3,T_3,126,False,-6.45260511 a_1^dagger a_1
4,T_4,250,False,-0.43156158 a_1^dagger a_9 + -0.43156158 a_9^dagger a_1
...,...,...,...,...
652,T_652,380,False,+0.04723612 a_14^dagger a_13^dagger a_15 a_12 + +0.04723612 a_15^dagger a_12^dagger a_14 a_13
653,T_653,211,False,-0.62168539 a_15^dagger a_12^dagger a_15 a_12
654,T_654,211,False,-0.62168539 a_14^dagger a_13^dagger a_14 a_13
655,T_655,197,False,-0.57444927 a_15^dagger a_13^dagger a_15 a_13
656,T_656,225,False,-0.76034873 a_15^dagger a_14^dagger a_15 a_14

=== Edges: noncommuting pairs ===

,source,target,meaning,commutator
0,T_1,T_2,"[T_1, T_2] != 0",+2.78469644 a_0^dagger a_8 + -2.78469644 a_8^dagger a_0
1,T_1,T_22,"[T_1, T_22] != 0",-0.70251629 a_1^dagger a_0^dagger a_8 a_1 + +0.70251629 a_8^dagger a_1^dagger a_1 a_0
2,T_1,T_23,"[T_1, T_23] != 0",+0.36268142 a_1^dagger a_0^dagger a_3 a_2 + -0.36268142 a_3^dagger a_2^dagger a_1 a_0
3,T_1,T_24,"[T_1, T_24] != 0",-0.38143007 a_1^dagger a_0^dagger a_14 a_3 + +0.38143007 a_14^dagger a_3^dagger a_1 a_0
4,T_1,T_25,"[T_1, T_25] != 0",+0.67820819 a_1^dagger a_0^dagger a_5 a_4 + -0.67820819 a_5^dagger a_4^dagger a_1 a_0
...,...,...,...,...
107179,T_648,T_652,"[T_648, T_652] != 0",-0.02713476 a_14^dagger a_13^dagger a_11^dagger a_15 a_12 a_11 + +0.02713476 a_15^dagger a_12^dagger a_11^dagger a_14 a_13 a_11
107180,T_649,T_650,"[T_649, T_650] != 0",-0.02857934 a_13^dagger a_12^dagger a_15 a_14 + +0.02857934 a_15^dagger a_14^dagger a_13 a_12
107181,T_650,T_656,"[T_650, T_656] != 0",-0.03591593 a_13^dagger a_12^dagger a_15 a_14 + +0.03591593 a_15^dagger a_14^dagger a_13 a_12
107182,T_652,T_653,"[T_652, T_653] != 0",+0.02936601 a_14^dagger a_13^dagger a_15 a_12 + -0.02936601 a_15^dagger a_12^dagger a_14 a_13
107183,T_652,T_654,"[T_652, T_654] != 0",-0.02936601 a_14^dagger a_13^dagger a_15 a_12 + +0.02936601 a_15^dagger a_12^dagger a_14 a_13

In [3]:
# Cell 2 alpha: Faster H2 / molecular fermionic noncommutation graph
#
# Main idea:
#   1. Use cheap fermionic index rules first.
#   2. Only if rules cannot decide, use exact OpenFermion symbolic commutator.
#   3. Never build sparse/dense matrices.
#
# This cell assumes Cell 1 already defined:
#   hermitian_terms
#   operator_to_string

import time
from collections import Counter

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from openfermion.utils import commutator
from openfermion.transforms import normal_ordered

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# Fermionic key utilities
# ------------------------------------------------------------

def key_modes(key):
    """
    Modes appearing in one OpenFermion monomial key.

    Example:
        ((3, 1), (0, 1), (3, 0), (0, 0)) -> {0, 3}
    """
    return frozenset(mode for mode, action in key)


def key_creations(key):
    """
    Creation modes in one monomial.
    """
    return frozenset(mode for mode, action in key if action == 1)


def key_annihilations(key):
    """
    Annihilation modes in one monomial.
    """
    return frozenset(mode for mode, action in key if action == 0)


def key_net_delta(key):
    """
    Net occupation change caused by a monomial.

    creation contributes +1
    annihilation contributes -1

    For example:
        a_2^dagger a_1^dagger a_3 a_0
    has delta:
        +1 on modes 2 and 1
        -1 on modes 3 and 0
    """
    delta = Counter()

    for mode, action in key:
        if action == 1:
            delta[mode] += 1
        else:
            delta[mode] -= 1

    return delta


def is_diagonal_key(key):
    """
    True if a monomial preserves occupation mode-by-mode.

    Examples:
        a_p^dagger a_p is diagonal.
        a_p^dagger a_q^dagger a_q a_p is diagonal.
        a_p^dagger a_q is not diagonal when p != q.
    """
    delta = key_net_delta(key)
    return all(value == 0 for value in delta.values())


def is_even_key(key):
    """
    Electronic Hamiltonian terms normally have even fermionic parity:
    length 0, 2, or 4.
    """
    return len(key) % 2 == 0


# ------------------------------------------------------------
# Safe monomial-level commutation rules
# ------------------------------------------------------------

def diagonal_key_commutes_with_key(diagonal_key, other_key):
    """
    Safe rule:

    A diagonal occupation operator depending on modes S commutes with another
    monomial if the other monomial has zero net occupation change on every
    mode in S.
    """
    support = key_modes(diagonal_key)
    delta = key_net_delta(other_key)

    return all(delta.get(mode, 0) == 0 for mode in support)


def no_cross_contractions_even_commute(key_a, key_b):
    """
    Safe rule for normal-ordered even fermionic monomials.

    If there are no possible cross contractions:
        annihilations(A) intersect creations(B) = empty
        annihilations(B) intersect creations(A) = empty

    then even monomials commute.

    This catches many cases beyond completely disjoint support.
    """
    if not is_even_key(key_a) or not is_even_key(key_b):
        return False

    a_ann = key_annihilations(key_a)
    a_cre = key_creations(key_a)

    b_ann = key_annihilations(key_b)
    b_cre = key_creations(key_b)

    return a_ann.isdisjoint(b_cre) and b_ann.isdisjoint(a_cre)


def monomial_pair_definitely_commutes(key_a, key_b):
    """
    Return (True, reason) only when we are sure two monomials commute.
    Return (False, None) if the rule cannot decide.

    Important:
        False here does NOT mean noncommuting.
        It only means "unknown; use exact symbolic fallback."
    """
    # Identity commutes with everything.
    if key_a == () or key_b == ():
        return True, "identity"

    # Any monomial commutes with itself.
    if key_a == key_b:
        return True, "same_monomial"

    # Diagonal occupation-like monomials commute with each other.
    if is_diagonal_key(key_a) and is_diagonal_key(key_b):
        return True, "diagonal_diagonal"

    # Diagonal with excitation-like term, if excitation preserves diagonal support.
    if is_diagonal_key(key_a) and diagonal_key_commutes_with_key(key_a, key_b):
        return True, "diagonal_support_preserved"

    if is_diagonal_key(key_b) and diagonal_key_commutes_with_key(key_b, key_a):
        return True, "diagonal_support_preserved"

    # Even monomials with no cross contractions commute.
    if no_cross_contractions_even_commute(key_a, key_b):
        return True, "no_cross_contractions_even"

    return False, None


# ------------------------------------------------------------
# Operator-level metadata and precheck
# ------------------------------------------------------------

def operator_metadata(op):
    """
    Precompute simple structural data for one FermionOperator.
    """
    keys = list(op.terms.keys())

    modes = set()
    for key in keys:
        modes.update(key_modes(key))

    return {
        "is_zero": len(keys) == 0,
        "only_identity": len(keys) == 1 and keys[0] == (),
        "modes": frozenset(modes),
        "is_even": all(is_even_key(key) for key in keys),
        "is_diagonal": all(is_diagonal_key(key) for key in keys),
        "number_of_monomials": len(keys),
    }


def operator_pair_definitely_commutes(A, B, meta_A, meta_B):
    """
    Return (True, reason) only for guaranteed-commuting pairs.
    Return (False, None) when unresolved.
    """
    if meta_A["is_zero"] or meta_B["is_zero"]:
        return True, "zero"

    if meta_A["only_identity"] or meta_B["only_identity"]:
        return True, "identity"

    # Very cheap global rule:
    # disjoint even fermionic operators commute.
    if (
        meta_A["is_even"]
        and meta_B["is_even"]
        and meta_A["modes"].isdisjoint(meta_B["modes"])
    ):
        return True, "disjoint_even_support"

    # Diagonal occupation-like operators commute with each other.
    if meta_A["is_diagonal"] and meta_B["is_diagonal"]:
        return True, "diagonal_diagonal"

    # More detailed but still cheap:
    # if every monomial pair has a safe commuting reason, the sums commute.
    reasons = Counter()

    for key_a in A.terms:
        for key_b in B.terms:
            ok, reason = monomial_pair_definitely_commutes(key_a, key_b)

            if not ok:
                return False, None

            reasons[reason] += 1

    if len(reasons) > 0:
        main_reason = reasons.most_common(1)[0][0]
        return True, f"all_monomial_pairs_{main_reason}"

    return False, None


# ------------------------------------------------------------
# Exact symbolic fallback
# ------------------------------------------------------------

def exact_symbolic_fermionic_commutator(A, B, tol=1e-12):
    """
    Exact symbolic commutator in fermionic algebra.

    This does not build a 2^n matrix.
    """
    C = normal_ordered(commutator(A, B))
    C.compress(abs_tol=tol)
    return C


# ------------------------------------------------------------
# Alpha graph builder
# ------------------------------------------------------------

def build_fermionic_noncommutation_graph_alpha(
    hermitian_terms,
    tol=1e-12,
    store_commutators=False,
):
    """
    Build noncommutation graph using:
        fast safe index rules first,
        exact symbolic OpenFermion fallback only when needed.

    Parameters
    ----------
    hermitian_terms:
        list of FermionOperator terms T_i from Cell 1.

    tol:
        numerical compression tolerance.

    store_commutators:
        False is recommended for large molecules.
        True is useful for H2 debugging, but can be memory-heavy.

    Returns
    -------
    G:
        networkx.Graph

    stats_df:
        pandas.DataFrame with timing and skip counts
    """
    t_start = time.perf_counter()

    G = nx.Graph()
    stats = Counter()

    metadata = [operator_metadata(T) for T in hermitian_terms]

    # Add vertices.
    for i, T in enumerate(hermitian_terms):
        G.add_node(
            i,
            label=f"T_{i}",
            operator=T,
            operator_string=operator_to_string(T),
            number_of_monomials=len(T.terms),
            modes=sorted(metadata[i]["modes"]),
            is_diagonal=metadata[i]["is_diagonal"],
            is_even=metadata[i]["is_even"],
        )

    n = len(hermitian_terms)

    # Pairwise graph construction.
    for i in range(n):
        A = hermitian_terms[i]
        meta_A = metadata[i]

        for j in range(i + 1, n):
            B = hermitian_terms[j]
            meta_B = metadata[j]

            stats["total_pairs"] += 1

            # 1. Fast guaranteed-commuting rules.
            definitely_commutes, reason = operator_pair_definitely_commutes(
                A, B, meta_A, meta_B
            )

            if definitely_commutes:
                stats["pairs_skipped_by_index_rules"] += 1
                stats[f"skip_{reason}"] += 1
                continue

            # 2. Exact symbolic fallback.
            stats["pairs_sent_to_exact_symbolic"] += 1

            Cij = exact_symbolic_fermionic_commutator(A, B, tol=tol)

            if len(Cij.terms) != 0:
                stats["noncommuting_edges"] += 1

                edge_data = {
                    "method": "exact_symbolic_fallback",
                    "meaning": f"[T_{i}, T_{j}] != 0",
                }

                if store_commutators:
                    edge_data["commutator"] = Cij
                    edge_data["commutator_string"] = operator_to_string(Cij)
                else:
                    edge_data["commutator_string"] = (
                        "(not stored; rerun with store_commutators=True)"
                    )

                G.add_edge(i, j, **edge_data)

            else:
                stats["exact_symbolic_found_commuting"] += 1

    elapsed = time.perf_counter() - t_start

    stats["vertices"] = n
    stats["edges"] = G.number_of_edges()
    stats["commuting_pairs"] = stats["total_pairs"] - G.number_of_edges()
    stats["elapsed_seconds"] = elapsed

    stats_df = pd.DataFrame([dict(stats)])

    return G, stats_df


# ------------------------------------------------------------
# Run alpha graph builder
# ------------------------------------------------------------

# For H2 debugging, you can set store_commutators=True.
# For larger molecules, keep this False.
G_alpha, stats_df = build_fermionic_noncommutation_graph_alpha(
    hermitian_terms,
    tol=1e-12,
    store_commutators=False,
)

print("=== Fermionic noncommutation graph alpha summary ===")
display(stats_df)

print("Number of vertices / fermionic terms:", G_alpha.number_of_nodes())
print("Number of noncommuting pairs / edges:", G_alpha.number_of_edges())
print("Is graph bipartite?", nx.is_bipartite(G_alpha))


# ------------------------------------------------------------
# Vertex table
# ------------------------------------------------------------

vertex_rows = []

for i, data in G_alpha.nodes(data=True):
    vertex_rows.append(
        {
            "vertex": f"T_{i}",
            "degree": G_alpha.degree[i],
            "commutes_with_all": G_alpha.degree[i] == 0,
            "number_of_monomials": data["number_of_monomials"],
            "modes": data["modes"],
            "is_diagonal": data["is_diagonal"],
            "fermionic_term": data["operator_string"],
        }
    )

vertex_df_alpha = pd.DataFrame(vertex_rows)

print("\n=== Alpha vertices: fermionic terms ===")
display(vertex_df_alpha)


# ------------------------------------------------------------
# Edge table
# ------------------------------------------------------------

edge_rows = []

for i, j, data in G_alpha.edges(data=True):
    edge_rows.append(
        {
            "source": f"T_{i}",
            "target": f"T_{j}",
            "meaning": data["meaning"],
            "method": data["method"],
            "commutator": data["commutator_string"],
        }
    )

edge_df_alpha = pd.DataFrame(edge_rows)

print("\n=== Alpha edges: noncommuting pairs ===")
display(edge_df_alpha)

# The commutation graph is too large for this.

# # ------------------------------------------------------------
# # Draw graph
# # ------------------------------------------------------------

# plt.figure(figsize=(12, 8))

# pos = nx.kamada_kawai_layout(G_alpha)

# node_labels = {
#     i: f"T_{i}"
#     for i in G_alpha.nodes()
# }

# node_sizes = [
#     1000 + 250 * G_alpha.degree[i]
#     for i in G_alpha.nodes()
# ]

# nx.draw_networkx_nodes(G_alpha, pos, node_size=node_sizes)
# nx.draw_networkx_edges(G_alpha, pos, width=1.5)
# nx.draw_networkx_labels(
#     G_alpha,
#     pos,
#     labels=node_labels,
#     font_size=11,
#     font_weight="bold",
# )

# plt.title("Fermionic Noncommutation Graph Alpha")
# plt.axis("off")
# plt.show()

=== Fermionic noncommutation graph alpha summary ===

,total_pairs,pairs_skipped_by_index_rules,skip_identity,pairs_sent_to_exact_symbolic,noncommuting_edges,skip_disjoint_even_support,skip_diagonal_diagonal,skip_all_monomial_pairs_diagonal_support_preserved,exact_symbolic_found_commuting,vertices,edges,commuting_pairs,elapsed_seconds
0,215496,95568,656,119928,107184,91984,1920,1008,12744,657,107184,108312,6.479637

Number of vertices / fermionic terms: 657
Number of noncommuting pairs / edges: 107184
Is graph bipartite? False

=== Alpha vertices: fermionic terms ===

,vertex,degree,commutes_with_all,number_of_monomials,modes,is_diagonal,fermionic_term
0,T_0,0,True,1,[],True,-76.41243108 I
1,T_1,126,False,1,[0],True,-6.45260511 a_0^dagger a_0
2,T_2,250,False,2,"[0, 8]",False,-0.43156158 a_0^dagger a_8 + -0.43156158 a_8^dagger a_0
3,T_3,126,False,1,[1],True,-6.45260511 a_1^dagger a_1
4,T_4,250,False,2,"[1, 9]",False,-0.43156158 a_1^dagger a_9 + -0.43156158 a_9^dagger a_1
...,...,...,...,...,...,...,...
652,T_652,380,False,2,"[12, 13, 14, 15]",False,+0.04723612 a_14^dagger a_13^dagger a_15 a_12 + +0.04723612 a_15^dagger a_12^dagger a_14 a_13
653,T_653,211,False,1,"[12, 15]",True,-0.62168539 a_15^dagger a_12^dagger a_15 a_12
654,T_654,211,False,1,"[13, 14]",True,-0.62168539 a_14^dagger a_13^dagger a_14 a_13
655,T_655,197,False,1,"[13, 15]",True,-0.57444927 a_15^dagger a_13^dagger a_15 a_13
656,T_656,225,False,1,"[14, 15]",True,-0.76034873 a_15^dagger a_14^dagger a_15 a_14

=== Alpha edges: noncommuting pairs ===

,source,target,meaning,method,commutator
0,T_1,T_2,"[T_1, T_2] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
1,T_1,T_22,"[T_1, T_22] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
2,T_1,T_23,"[T_1, T_23] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
3,T_1,T_24,"[T_1, T_24] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
4,T_1,T_25,"[T_1, T_25] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
...,...,...,...,...,...
107179,T_648,T_652,"[T_648, T_652] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
107180,T_649,T_650,"[T_649, T_650] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
107181,T_650,T_656,"[T_650, T_656] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
107182,T_652,T_653,"[T_652, T_653] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)
107183,T_652,T_654,"[T_652, T_654] != 0",exact_symbolic_fallback,(not stored; rerun with store_commutators=True)

In [4]:
print("Same edge set?")
print(set(G.edges()) == set(G_alpha.edges()))

Same edge set?
True

In [5]:
# Cell 3: Color graph, build commuting blocks, map JW/BK, verify commutation

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from itertools import combinations
from openfermion.ops import FermionOperator
from openfermion.transforms import normal_ordered, jordan_wigner, bravyi_kitaev

pd.set_option("display.max_colwidth", None)


# ------------------------------------------------------------
# 1. Color the noncommutation graph
# ------------------------------------------------------------
# Since edges mean noncommutation, each color class is a commuting group.

coloring = nx.coloring.greedy_color(G, strategy="largest_first")

color_groups = {}

for node, color in coloring.items():
    color_groups.setdefault(color, []).append(node)

for color in color_groups:
    color_groups[color] = sorted(color_groups[color])

color_names = [
    "red",
    "blue",
    "green",
    "orange",
    "purple",
    "brown",
    "pink",
    "gray",
]

color_name = {
    color: color_names[color] if color < len(color_names) else f"color_{color}"
    for color in color_groups
}

num_grouped_terms = sum(len(nodes) for nodes in color_groups.values())

print("Number of fermionic terms / vertices:", G.number_of_nodes())
print("Number of colors / commuting groups:", len(color_groups))
print("Number of grouped terms:", num_grouped_terms)

assert num_grouped_terms == G.number_of_nodes()


# ------------------------------------------------------------
# 2. Verify each color group is mutually commuting
# ------------------------------------------------------------

def verify_commuting_group(nodes, tol=1e-12):
    for i, j in combinations(nodes, 2):
        A = G.nodes[i]["operator"]
        B = G.nodes[j]["operator"]

        if not commute(A, B, tol=tol):
            return False

    return True


group_summary_rows = []

for color, nodes in sorted(color_groups.items()):
    group_summary_rows.append(
        {
            "color_id": color,
            "color_name": color_name[color],
            "number_of_terms": len(nodes),
            "vertices": [f"T_{i}" for i in nodes],
            "verified_mutually_commuting": verify_commuting_group(nodes),
        }
    )

group_summary_df = pd.DataFrame(group_summary_rows)

print("\n=== Commuting groups from graph coloring ===")
display(group_summary_df)


# ------------------------------------------------------------
# 3. Build Hamiltonian pieces by color
# ------------------------------------------------------------

H_by_color = {}

for color, nodes in sorted(color_groups.items()):
    H_color = FermionOperator.zero()

    for node in nodes:
        H_color += G.nodes[node]["operator"]

    H_color = normal_ordered(H_color)
    H_color.compress(abs_tol=1e-12)

    H_by_color[color] = H_color


color_block_rows = []

for color, nodes in sorted(color_groups.items()):
    for local_index, node in enumerate(nodes, start=1):
        color_block_rows.append(
            {
                "color_block": f"H_{color_name[color]}",
                "local_term_name": f"{color_name[color][0].upper()}_{local_index}",
                "vertex": f"T_{node}",
                "fermionic_term": G.nodes[node]["operator_string"],
            }
        )

color_block_df = pd.DataFrame(color_block_rows)

print("\n=== Which T_i belongs to which color block ===")
display(color_block_df)


print("\n=== Hamiltonian split by commuting color groups ===")

for color, H_color in H_by_color.items():
    nodes = color_groups[color]

    print("\n" + "=" * 80)
    print(f"H_{color_name[color]} consists of:")
    print(" + ".join([f"T_{node}" for node in nodes]))

    print(f"\nSummed operator H_{color_name[color]} =")
    print(H_color)


# ------------------------------------------------------------
# 4. Trotter ordering induced by color groups
# ------------------------------------------------------------

trotter_order = []

for color, nodes in sorted(color_groups.items()):
    for node in nodes:
        trotter_order.append(node)

print("\n=== Trotter order by commuting color groups ===")
print([f"T_{i}" for i in trotter_order])


# ------------------------------------------------------------
# 5. Helper functions for JW/BK output
# ------------------------------------------------------------

def sort_qubit_key(term):
    return (len(term), term)


def format_qubit_term(term):
    if term == ():
        return "I"

    return " ".join([f"{pauli}{qubit}" for qubit, pauli in term])


def qubit_coeff_to_str(c, digits=8):
    c = complex(c)
    if abs(c.imag) < 1e-12:
        return f"{c.real:+.{digits}f}"
    return f"{c.real:+.{digits}f}{c.imag:+.{digits}f}j"


def qubit_operator_to_string(op, digits=8):
    pieces = []

    for term, coeff in sorted(op.terms.items(), key=lambda item: sort_qubit_key(item[0])):
        pieces.append(f"{qubit_coeff_to_str(coeff, digits)} {format_qubit_term(term)}")

    if len(pieces) == 0:
        return "0"

    return " + ".join(pieces)


def apply_bk(op, n_qubits):
    try:
        return bravyi_kitaev(op, n_qubits=n_qubits)
    except TypeError:
        return bravyi_kitaev(op, n_qubits)


def qubit_commutator(A, B, tol=1e-12):
    C = A * B - B * A
    C.compress(abs_tol=tol)
    return C


def qubit_commute(A, B, tol=1e-12):
    C = qubit_commutator(A, B, tol=tol)
    return len(C.terms) == 0


n_qubits = molecule.n_qubits

print("\nNumber of qubits / spin orbitals:", n_qubits)


# ------------------------------------------------------------
# 6. Map each fermionic vertex T_i to JW(T_i) and BK(T_i)
# ------------------------------------------------------------

mapped_rows = []

for node in sorted(G.nodes()):
    T_i = G.nodes[node]["operator"]

    JW_T_i = jordan_wigner(T_i)
    JW_T_i.compress(abs_tol=1e-12)

    BK_T_i = apply_bk(T_i, n_qubits=n_qubits)
    BK_T_i.compress(abs_tol=1e-12)

    G.nodes[node]["JW_operator"] = JW_T_i
    G.nodes[node]["BK_operator"] = BK_T_i
    G.nodes[node]["JW_operator_string"] = qubit_operator_to_string(JW_T_i)
    G.nodes[node]["BK_operator_string"] = qubit_operator_to_string(BK_T_i)

    node_color = coloring[node]
    node_color_name = color_name[node_color]

    mapped_rows.append(
        {
            "color": node_color_name,
            "vertex": f"T_{node}",
            "fermionic_term": G.nodes[node]["operator_string"],
            "number_of_JW_Pauli_strings": len(JW_T_i.terms),
            "JW_transform": qubit_operator_to_string(JW_T_i),
            "number_of_BK_Pauli_strings": len(BK_T_i.terms),
            "BK_transform": qubit_operator_to_string(BK_T_i),
        }
    )

mapped_terms_df = pd.DataFrame(mapped_rows)

print("\n=== Fermionic terms mapped to JW and BK ===")
display(mapped_terms_df)


# ------------------------------------------------------------
# 7. Map each color block H_color to JW and BK
# ------------------------------------------------------------

JW_by_color = {}
BK_by_color = {}

block_rows = []

for color, H_color in sorted(H_by_color.items()):
    JW_color = jordan_wigner(H_color)
    JW_color.compress(abs_tol=1e-12)

    BK_color = apply_bk(H_color, n_qubits=n_qubits)
    BK_color.compress(abs_tol=1e-12)

    JW_by_color[color] = JW_color
    BK_by_color[color] = BK_color

    block_rows.append(
        {
            "color_block": f"H_{color_name[color]}",
            "fermionic_vertices": " + ".join([f"T_{node}" for node in color_groups[color]]),
            "number_of_fermionic_terms": len(color_groups[color]),
            "number_of_JW_Pauli_strings": len(JW_color.terms),
            "JW_block": qubit_operator_to_string(JW_color),
            "number_of_BK_Pauli_strings": len(BK_color.terms),
            "BK_block": qubit_operator_to_string(BK_color),
        }
    )

block_map_df = pd.DataFrame(block_rows)

print("\n=== Color blocks mapped to JW and BK ===")
display(block_map_df)


# ------------------------------------------------------------
# 8. Verify same-color terms commute after JW and BK
# ------------------------------------------------------------

verification_rows = []

for color, nodes in sorted(color_groups.items()):
    for i, j in combinations(nodes, 2):
        Ti = G.nodes[i]["operator"]
        Tj = G.nodes[j]["operator"]

        JW_Ti = G.nodes[i]["JW_operator"]
        JW_Tj = G.nodes[j]["JW_operator"]

        BK_Ti = G.nodes[i]["BK_operator"]
        BK_Tj = G.nodes[j]["BK_operator"]

        verification_rows.append(
            {
                "color_group": color_name[color],
                "pair": f"T_{i}, T_{j}",
                "fermionic_commute": commute(Ti, Tj),
                "JW_commute": qubit_commute(JW_Ti, JW_Tj),
                "BK_commute": qubit_commute(BK_Ti, BK_Tj),
            }
        )

verification_df = pd.DataFrame(verification_rows)

print("\n=== Verify commuting groups after JW/BK mapping ===")
display(verification_df)

Number of fermionic terms / vertices: 657
Number of colors / commuting groups: 53
Number of grouped terms: 657

=== Commuting groups from graph coloring ===

,color_id,color_name,number_of_terms,vertices,verified_mutually_commuting
0,0,red,13,"[T_0, T_28, T_94, T_95, T_231, T_294, T_362, T_440, T_448, T_449, T_507, T_637, T_640]",True
1,1,blue,12,"[T_25, T_62, T_63, T_202, T_289, T_309, T_311, T_390, T_618, T_622, T_650, T_652]",True
2,2,green,12,"[T_26, T_79, T_81, T_218, T_288, T_298, T_299, T_380, T_619, T_625, T_638, T_643]",True
3,3,orange,12,"[T_29, T_110, T_112, T_247, T_292, T_350, T_353, T_428, T_441, T_458, T_554, T_583]",True
4,4,purple,12,"[T_30, T_127, T_130, T_263, T_291, T_339, T_341, T_418, T_446, T_495, T_549, T_558]",True
5,5,brown,12,"[T_58, T_68, T_98, T_207, T_216, T_223, T_348, T_366, T_426, T_435, T_514, T_557]",True
6,6,pink,12,"[T_77, T_86, T_99, T_190, T_198, T_222, T_360, T_367, T_415, T_434, T_456, T_596]",True
7,7,gray,12,"[T_102, T_107, T_119, T_227, T_255, T_262, T_306, T_363, T_387, T_432, T_546, T_582]",True
8,8,color_8,12,"[T_103, T_126, T_137, T_226, T_238, T_244, T_318, T_364, T_376, T_431, T_493, T_616]",True
9,9,color_9,12,"[T_23, T_36, T_41, T_181, T_462, T_496, T_511, T_540, T_553, T_574, T_576, T_608]",True
10,10,color_10,12,"[T_24, T_42, T_145, T_184, T_304, T_322, T_342, T_463, T_497, T_528, T_552, T_575]",True
11,11,color_11,12,"[T_31, T_39, T_149, T_282, T_374, T_406, T_409, T_468, T_512, T_541, T_551, T_568]",True
12,12,color_12,12,"[T_32, T_146, T_150, T_283, T_290, T_321, T_325, T_405, T_452, T_472, T_503, T_517]",True
13,13,color_13,12,"[T_40, T_49, T_96, T_192, T_235, T_280, T_467, T_505, T_530, T_537, T_592, T_609]",True
14,14,color_14,12,"[T_50, T_97, T_144, T_171, T_221, T_281, T_323, T_407, T_453, T_485, T_504, T_529]",True
15,15,color_15,14,"[T_33, T_69, T_115, T_185, T_191, T_234, T_464, T_527, T_563, T_573, T_585, T_593, T_610, T_627]",True
16,16,color_16,14,"[T_70, T_116, T_143, T_170, T_178, T_220, T_454, T_480, T_486, T_524, T_562, T_584, T_607, T_635]",True
17,17,color_17,12,"[T_37, T_71, T_133, T_182, T_193, T_251, T_550, T_566, T_567, T_603, T_620, T_628]",True
18,18,color_18,16,"[T_72, T_134, T_142, T_194, T_252, T_279, T_316, T_319, T_343, T_385, T_403, T_410, T_479, T_536, T_564, T_601]",True
19,19,color_19,12,"[T_38, T_87, T_117, T_183, T_208, T_236, T_461, T_487, T_494, T_510, T_531, T_547]",True
20,20,color_20,8,"[T_88, T_118, T_209, T_237, T_305, T_354, T_375, T_420]",True
21,21,color_21,12,"[T_89, T_135, T_210, T_253, T_460, T_473, T_492, T_509, T_518, T_545, T_621, T_631]",True
22,22,color_22,12,"[T_90, T_136, T_147, T_211, T_254, T_284, T_302, T_326, T_338, T_372, T_392, T_417]",True
23,23,color_23,12,"[T_104, T_156, T_228, T_271, T_447, T_477, T_488, T_506, T_522, T_532, T_639, T_646]",True
24,24,color_24,15,"[T_3, T_7, T_11, T_17, T_105, T_157, T_205, T_256, T_317, T_320, T_355, T_381, T_424, T_442, T_469]",True
25,25,color_25,23,"[T_1, T_5, T_9, T_12, T_15, T_18, T_57, T_84, T_106, T_138, T_229, T_272, T_295, T_312, T_337, T_358, T_386, T_404, T_421, T_450, T_489, T_598, T_641]",True
26,26,color_26,13,"[T_45, T_64, T_109, T_195, T_243, T_267, T_336, T_365, T_377, T_548, T_578, T_605, T_649]",True
27,27,color_27,7,"[T_73, T_152, T_166, T_186, T_246, T_402, T_433]",True
28,28,color_28,12,"[T_46, T_65, T_125, T_167, T_187, T_261, T_560, T_569, T_581, T_590, T_597, T_615]",True
29,29,color_29,12,"[T_47, T_82, T_108, T_168, T_203, T_245, T_457, T_491, T_499, T_515, T_535, T_543]",True
30,30,color_30,16,"[T_48, T_83, T_124, T_169, T_204, T_260, T_307, T_388, T_455, T_478, T_498, T_513, T_523, T_542, T_642, T_648]",True
31,31,color_31,14,"[T_51, T_113, T_172, T_197, T_232, T_416, T_561, T_577, T_580, T_591, T_604, T_614, T_624, T_633]",True
32,32,color_32,10,"[T_52, T_76, T_114, T_173, T_215, T_233, T_445, T_482, T_484, T_539]",True
33,33,color_33,12,"[T_53, T_59, T_131, T_174, T_199, T_249, T_556, T_572, T_586, T_595, T_600, T_611]",True
34,34,color_34,30,"[T_10, T_13, T_14, T_16, T_19, T_20, T_54, T_75, T_132, T_175, T_214, T_250, T_349, T_427, T_439, T_459, T_474, T_500, T_508, T_519, T_544, T_617, T_623, T_629, T_630, T_634, T_636, T_644, T_647, T_656]",True
35,35,color_35,10,"[T_56, T_93, T_151, T_177, T_230, T_266, T_361, T_438, T_443, T_470]",True
36,36,color_36,10,"[T_74, T_153, T_196, T_268, T_314, T_328, T_383, T_394, T_555, T_594]",True
37,37,color_37,8,"[T_91, T_154, T_212, T_269, T_303, T_327, T_373, T_393]",True
38,38,color_38,12,"[T_92, T_128, T_155, T_213, T_264, T_270, T_297, T_332, T_344, T_379, T_398, T_411]",True
39,39,color_39,12,"[T_61, T_122, T_158, T_201, T_241, T_273, T_315, T_329, T_351, T_384, T_395, T_429]",True
40,40,color_40,8,"[T_123, T_159, T_242, T_274, T_334, T_356, T_400, T_422]",True
41,41,color_41,10,"[T_140, T_160, T_258, T_275, T_333, T_345, T_399, T_412, T_651, T_655]",True
42,42,color_42,13,"[T_80, T_141, T_161, T_219, T_259, T_276, T_286, T_300, T_330, T_346, T_370, T_396, T_413]",True
43,43,color_43,13,"[T_21, T_66, T_120, T_162, T_188, T_239, T_277, T_310, T_335, T_357, T_391, T_401, T_423]",True
44,44,color_44,6,"[T_43, T_164, T_579, T_587, T_606, T_612]",True
45,45,color_45,26,"[T_2, T_6, T_22, T_44, T_78, T_85, T_101, T_121, T_129, T_163, T_176, T_287, T_308, T_313, T_331, T_347, T_352, T_369, T_444, T_483, T_559, T_570, T_588, T_632, T_645, T_653]",True
46,46,color_46,24,"[T_4, T_8, T_27, T_55, T_165, T_200, T_206, T_225, T_257, T_265, T_278, T_293, T_378, T_382, T_397, T_425, T_430, T_437, T_451, T_471, T_501, T_533, T_626, T_654]",True
47,47,color_47,10,"[T_60, T_139, T_189, T_217, T_296, T_359, T_371, T_389, T_502, T_516]",True
48,48,color_48,12,"[T_67, T_111, T_240, T_248, T_301, T_340, T_414, T_419, T_466, T_475, T_481, T_490]",True
49,49,color_49,10,"[T_34, T_100, T_179, T_224, T_324, T_408, T_476, T_520, T_534, T_571]",True
50,50,color_50,13,"[T_35, T_148, T_180, T_285, T_368, T_436, T_465, T_521, T_525, T_565, T_599, T_602, T_613]",True
51,51,color_51,2,"[T_526, T_538]",True
52,52,color_52,1,[T_589],True

=== Which T_i belongs to which color block ===

,color_block,local_term_name,vertex,fermionic_term
0,H_red,R_1,T_0,-76.41243108 I
1,H_red,R_2,T_28,-0.05152201 a_1^dagger a_0^dagger a_9 a_8 + -0.05152201 a_9^dagger a_8^dagger a_1 a_0
2,H_red,R_3,T_94,-0.11156468 a_8^dagger a_0^dagger a_14 a_2 + -0.11156468 a_14^dagger a_2^dagger a_8 a_0
3,H_red,R_4,T_95,+0.05152201 a_8^dagger a_1^dagger a_9 a_0 + +0.05152201 a_9^dagger a_0^dagger a_8 a_1
4,H_red,R_5,T_231,-0.11156468 a_9^dagger a_1^dagger a_15 a_3 + -0.11156468 a_15^dagger a_3^dagger a_9 a_1
...,...,...,...,...
652,H_color_50,C_12,T_602,-0.03478850 a_11^dagger a_7^dagger a_13 a_7 + -0.03478850 a_13^dagger a_7^dagger a_11 a_7
653,H_color_50,C_13,T_613,-0.62030379 a_14^dagger a_7^dagger a_14 a_7
654,H_color_51,C_1,T_526,+0.03478850 a_11^dagger a_5^dagger a_11 a_7 + +0.03478850 a_11^dagger a_7^dagger a_11 a_5
655,H_color_51,C_2,T_538,-0.03478850 a_13^dagger a_5^dagger a_13 a_7 + -0.03478850 a_13^dagger a_7^dagger a_13 a_5
656,H_color_52,C_1,T_589,-0.51791667 a_8^dagger a_7^dagger a_8 a_7

=== Hamiltonian split by commuting color groups ===

================================================================================
H_red consists of:
T_0 + T_28 + T_94 + T_95 + T_231 + T_294 + T_362 + T_440 + T_448 + T_449 + T_507 + T_637 + T_640

Summed operator H_red =
-76.41243108300478 [] +
-0.05152200694044894 [1^ 0^ 9 8] +
-0.04785324996201084 [3^ 2^ 15 14] +
-0.02401588474180662 [5^ 4^ 7 6] +
0.13055493144496294 [6^ 4^ 12 10] +
0.02401588474180662 [6^ 5^ 7 4] +
0.02401588474180662 [7^ 4^ 6 5] +
0.13055493144496294 [7^ 5^ 13 11] +
-0.02401588474180662 [7^ 6^ 5 4] +
-0.1115646752961843 [8^ 0^ 14 2] +
0.05152200694044894 [8^ 1^ 9 0] +
0.05152200694044894 [9^ 0^ 8 1] +
-0.1115646752961843 [9^ 1^ 15 3] +
-0.05152200694044894 [9^ 8^ 1 0] +
-0.02508112016622244 [11^ 10^ 13 12] +
0.13055493144496294 [12^ 10^ 6 4] +
0.02508112016622244 [12^ 11^ 13 10] +
0.02508112016622244 [13^ 10^ 12 11] +
0.13055493144496294 [13^ 11^ 7 5] +
-0.02508112016622244 [13^ 12^ 11 10] +
-0.1115646752961843 [14^ 2^ 8 0] +
0.04785324996201084 [14^ 3^ 15 2] +
0.04785324996201084 [15^ 2^ 14 3] +
-0.1115646752961843 [15^ 3^ 9 1] +
-0.04785324996201084 [15^ 14^ 3 2]

================================================================================
H_blue consists of:
T_25 + T_62 + T_63 + T_202 + T_289 + T_309 + T_311 + T_390 + T_618 + T_622 + T_650 + T_652

Summed operator H_blue =
-0.10510610517640354 [1^ 0^ 5 4] +
-0.05080949375455379 [3^ 2^ 7 6] +
0.06506915527936745 [4^ 0^ 14 12] +
0.10510610517640354 [4^ 1^ 5 0] +
0.10510610517640354 [5^ 0^ 4 1] +
0.06506915527936745 [5^ 1^ 15 13] +
-0.10510610517640354 [5^ 4^ 1 0] +
0.11456891282515055 [6^ 2^ 10 8] +
0.05080949375455379 [6^ 3^ 7 2] +
0.05080949375455379 [7^ 2^ 6 3] +
0.11456891282515055 [7^ 3^ 11 9] +
-0.05080949375455379 [7^ 6^ 3 2] +
-0.0382262516203235 [9^ 8^ 11 10] +
0.11456891282515058 [10^ 8^ 6 2] +
0.0382262516203235 [10^ 9^ 11 8] +
0.0382262516203235 [11^ 8^ 10 9] +
0.11456891282515058 [11^ 9^ 7 3] +
-0.0382262516203235 [11^ 10^ 9 8] +
-0.047236124428525414 [13^ 12^ 15 14] +
0.06506915527936745 [14^ 12^ 4 0] +
0.047236124428525414 [14^ 13^ 15 12] +
0.047236124428525414 [15^ 12^ 14 13] +
0.06506915527936745 [15^ 13^ 5 1] +
-0.047236124428525414 [15^ 14^ 13 12]

================================================================================
H_green consists of:
T_26 + T_79 + T_81 + T_218 + T_288 + T_298 + T_299 + T_380 + T_619 + T_625 + T_638 + T_643

Summed operator H_green =
-0.10510610517640348 [1^ 0^ 7 6] +
-0.05080949375455382 [3^ 2^ 5 4] +
0.11456891282515058 [4^ 2^ 12 8] +
0.05080949375455382 [4^ 3^ 5 2] +
0.05080949375455382 [5^ 2^ 4 3] +
0.11456891282515058 [5^ 3^ 13 9] +
-0.05080949375455382 [5^ 4^ 3 2] +
0.06506915527936742 [6^ 0^ 14 10] +
0.10510610517640348 [6^ 1^ 7 0] +
0.10510610517640348 [7^ 0^ 6 1] +
0.06506915527936742 [7^ 1^ 15 11] +
-0.10510610517640348 [7^ 6^ 1 0] +
-0.03822625162032347 [9^ 8^ 13 12] +
-0.04723612442852542 [11^ 10^ 15 14] +
0.11456891282515058 [12^ 8^ 4 2] +
0.03822625162032347 [12^ 9^ 13 8] +
0.03822625162032347 [13^ 8^ 12 9] +
0.11456891282515058 [13^ 9^ 5 3] +
-0.03822625162032347 [13^ 12^ 9 8] +
0.06506915527936742 [14^ 10^ 6 0] +
0.04723612442852542 [14^ 11^ 15 10] +
0.04723612442852542 [15^ 10^ 14 11] +
0.06506915527936742 [15^ 11^ 7 1] +
-0.04723612442852542 [15^ 14^ 11 10]

================================================================================
H_orange consists of:
T_29 + T_110 + T_112 + T_247 + T_292 + T_350 + T_353 + T_428 + T_441 + T_458 + T_554 + T_583

Summed operator H_orange =
-0.04418890184108795 [1^ 0^ 11 10] +
-0.08236679300225275 [3^ 2^ 13 12] +
-0.028068387899039274 [5^ 4^ 9 8] +
-0.03536732805262955 [7^ 6^ 15 14] +
-0.11296437401540485 [8^ 4^ 12 2] +
0.028068387899039274 [8^ 5^ 9 4] +
0.028068387899039274 [9^ 4^ 8 5] +
-0.11296437401540485 [9^ 5^ 13 3] +
-0.028068387899039274 [9^ 8^ 5 4] +
0.038610509814851326 [10^ 0^ 14 6] +
0.04418890184108795 [10^ 1^ 11 0] +
0.04418890184108795 [11^ 0^ 10 1] +
0.038610509814851326 [11^ 1^ 15 7] +
-0.04418890184108795 [11^ 10^ 1 0] +
-0.11296437401540485 [12^ 2^ 8 4] +
0.08236679300225275 [12^ 3^ 13 2] +
0.08236679300225275 [13^ 2^ 12 3] +
-0.11296437401540485 [13^ 3^ 9 5] +
-0.08236679300225275 [13^ 12^ 3 2] +
0.038610509814851326 [14^ 6^ 10 0] +
0.03536732805262955 [14^ 7^ 15 6] +
0.03536732805262955 [15^ 6^ 14 7] +
0.038610509814851326 [15^ 7^ 11 1] +
-0.03536732805262955 [15^ 14^ 7 6]

================================================================================
H_purple consists of:
T_30 + T_127 + T_130 + T_263 + T_291 + T_339 + T_341 + T_418 + T_446 + T_495 + T_549 + T_558

Summed operator H_purple =
-0.04418890184108793 [1^ 0^ 13 12] +
-0.08236679300225276 [3^ 2^ 11 10] +
-0.03536732805262958 [5^ 4^ 15 14] +
-0.02806838789903926 [7^ 6^ 9 8] +
-0.11296437401540484 [8^ 6^ 10 2] +
0.02806838789903926 [8^ 7^ 9 6] +
0.02806838789903926 [9^ 6^ 8 7] +
-0.11296437401540484 [9^ 7^ 11 3] +
-0.02806838789903926 [9^ 8^ 7 6] +
-0.11296437401540484 [10^ 2^ 8 6] +
0.08236679300225276 [10^ 3^ 11 2] +
0.08236679300225276 [11^ 2^ 10 3] +
-0.11296437401540484 [11^ 3^ 9 7] +
-0.08236679300225276 [11^ 10^ 3 2] +
0.038610509814851326 [12^ 0^ 14 4] +
0.04418890184108793 [12^ 1^ 13 0] +
0.04418890184108793 [13^ 0^ 12 1] +
0.038610509814851326 [13^ 1^ 15 5] +
-0.04418890184108793 [13^ 12^ 1 0] +
0.038610509814851326 [14^ 4^ 12 0] +
0.03536732805262958 [14^ 5^ 15 4] +
0.03536732805262958 [15^ 4^ 14 5] +
0.038610509814851326 [15^ 5^ 13 1] +
-0.03536732805262958 [15^ 14^ 5 4]

================================================================================
H_brown consists of:
T_58 + T_68 + T_98 + T_207 + T_216 + T_223 + T_348 + T_366 + T_426 + T_435 + T_514 + T_557

Summed operator H_brown =
-0.01589784753914661 [4^ 0^ 10 2] +
0.013880633434630217 [5^ 0^ 9 4] +
0.013880633434630217 [5^ 4^ 9 0] +
0.01388063343463021 [6^ 1^ 8 7] +
0.015897847539146623 [7^ 1^ 13 3] +
-0.01388063343463021 [7^ 6^ 8 1] +
-0.01388063343463021 [8^ 1^ 7 6] +
0.028607827087888355 [8^ 6^ 14 12] +
0.01388063343463021 [8^ 7^ 6 1] +
0.013880633434630217 [9^ 0^ 5 4] +
0.013880633434630217 [9^ 4^ 5 0] +
-0.02860782708788833 [9^ 5^ 15 11] +
-0.01589784753914661 [10^ 2^ 4 0] +
-0.036108730531062935 [11^ 2^ 15 10] +
-0.036108730531062935 [11^ 10^ 15 2] +
-0.03610873053106292 [12^ 3^ 14 13] +
0.015897847539146626 [13^ 3^ 7 1] +
0.03610873053106292 [13^ 12^ 14 3] +
0.03610873053106292 [14^ 3^ 13 12] +
0.028607827087888355 [14^ 12^ 8 6] +
-0.03610873053106292 [14^ 13^ 12 3] +
-0.036108730531062935 [15^ 2^ 11 10] +
-0.036108730531062935 [15^ 10^ 11 2] +
-0.02860782708788833 [15^ 11^ 9 5]

================================================================================
H_pink consists of:
T_77 + T_86 + T_99 + T_190 + T_198 + T_222 + T_360 + T_367 + T_415 + T_434 + T_456 + T_596

Summed operator H_pink =
0.013880633434630217 [4^ 1^ 8 5] +
-0.01589784753914661 [5^ 1^ 11 3] +
-0.013880633434630217 [5^ 4^ 8 1] +
0.015897847539146623 [6^ 0^ 12 2] +
0.01388063343463021 [7^ 0^ 9 6] +
0.01388063343463021 [7^ 6^ 9 0] +
-0.013880633434630217 [8^ 1^ 5 4] +
-0.02860782708788833 [8^ 4^ 14 10] +
0.013880633434630217 [8^ 5^ 4 1] +
0.01388063343463021 [9^ 0^ 7 6] +
0.01388063343463021 [9^ 6^ 7 0] +
0.028607827087888355 [9^ 7^ 15 13] +
-0.036108730531062935 [10^ 3^ 14 11] +
-0.01589784753914661 [11^ 3^ 5 1] +
0.036108730531062935 [11^ 10^ 14 3] +
0.015897847539146626 [12^ 2^ 6 0] +
-0.03610873053106292 [13^ 2^ 15 12] +
-0.03610873053106292 [13^ 12^ 15 2] +
0.036108730531062935 [14^ 3^ 11 10] +
-0.02860782708788833 [14^ 10^ 8 4] +
-0.036108730531062935 [14^ 11^ 10 3] +
-0.03610873053106292 [15^ 2^ 13 12] +
-0.03610873053106292 [15^ 12^ 13 2] +
0.028607827087888355 [15^ 13^ 9 7]

================================================================================
H_gray consists of:
T_102 + T_107 + T_119 + T_227 + T_255 + T_262 + T_306 + T_363 + T_387 + T_432 + T_546 + T_582

Summed operator H_gray =
-0.006624210313074922 [4^ 2^ 10 0] +
-0.02385389678171298 [5^ 2^ 15 4] +
-0.02385389678171298 [5^ 4^ 15 2] +
-0.023853896781712965 [6^ 3^ 14 7] +
0.006624210313074934 [7^ 3^ 13 1] +
0.023853896781712965 [7^ 6^ 14 3] +
-0.025006850068928034 [8^ 1^ 13 12] +
0.025006850068928048 [9^ 0^ 11 10] +
-0.006624210313074924 [10^ 0^ 4 2] +
-0.025006850068928048 [10^ 9^ 11 0] +
-0.025006850068928048 [11^ 0^ 10 9] +
0.027167628873757177 [11^ 9^ 15 5] +
0.025006850068928048 [11^ 10^ 9 0] +
-0.025006850068928034 [12^ 1^ 13 8] +
-0.027167628873757198 [12^ 8^ 14 6] +
0.006624210313074936 [13^ 1^ 7 3] +
-0.025006850068928034 [13^ 8^ 12 1] +
-0.025006850068928034 [13^ 12^ 8 1] +
0.023853896781712965 [14^ 3^ 7 6] +
-0.027167628873757198 [14^ 6^ 12 8] +
-0.023853896781712965 [14^ 7^ 6 3] +
-0.02385389678171298 [15^ 2^ 5 4] +
-0.02385389678171298 [15^ 4^ 5 2] +
0.027167628873757177 [15^ 5^ 11 9]

================================================================================
H_color_8 consists of:
T_103 + T_126 + T_137 + T_226 + T_238 + T_244 + T_318 + T_364 + T_376 + T_431 + T_493 + T_616

Summed operator H_color_8 =
-0.02385389678171298 [4^ 3^ 14 5] +
-0.006624210313074922 [5^ 3^ 11 1] +
0.02385389678171298 [5^ 4^ 14 3] +
0.006624210313074934 [6^ 2^ 12 0] +
-0.023853896781712965 [7^ 2^ 15 6] +
-0.023853896781712965 [7^ 6^ 15 2] +
-0.025006850068928048 [8^ 1^ 11 10] +
0.025006850068928034 [9^ 0^ 13 12] +
-0.025006850068928048 [10^ 1^ 11 8] +
0.027167628873757177 [10^ 8^ 14 4] +
-0.006624210313074924 [11^ 1^ 5 3] +
-0.025006850068928048 [11^ 8^ 10 1] +
-0.025006850068928048 [11^ 10^ 8 1] +
0.006624210313074936 [12^ 0^ 6 2] +
-0.025006850068928034 [12^ 9^ 13 0] +
-0.025006850068928034 [13^ 0^ 12 9] +
-0.027167628873757198 [13^ 9^ 15 7] +
0.025006850068928034 [13^ 12^ 9 0] +
0.02385389678171298 [14^ 3^ 5 4] +
0.027167628873757177 [14^ 4^ 10 8] +
-0.02385389678171298 [14^ 5^ 4 3] +
-0.023853896781712965 [15^ 2^ 7 6] +
-0.023853896781712965 [15^ 6^ 7 2] +
-0.027167628873757198 [15^ 7^ 13 9]

================================================================================
H_color_9 consists of:
T_23 + T_36 + T_41 + T_181 + T_462 + T_496 + T_511 + T_540 + T_553 + T_574 + T_576 + T_608

Summed operator H_color_9 =
-0.05620697656185599 [1^ 0^ 3 2] +
-0.009273637226071687 [2^ 0^ 10 4] +
0.05620697656185599 [2^ 1^ 3 0] +
0.05620697656185599 [3^ 0^ 2 1] +
-0.009273637226071687 [3^ 1^ 11 5] +
-0.05620697656185599 [3^ 2^ 1 0] +
-0.03382179136523368 [7^ 6^ 13 12] +
-0.027277038113972522 [8^ 5^ 14 11] +
-0.027277038113972522 [9^ 4^ 15 10] +
-0.009273637226071687 [10^ 4^ 2 0] +
0.027277038113972522 [10^ 9^ 15 4] +
-0.009273637226071687 [11^ 5^ 3 1] +
0.027277038113972522 [11^ 8^ 14 5] +
0.001440198214131154 [12^ 6^ 14 8] +
0.03382179136523368 [12^ 7^ 13 6] +
0.03382179136523368 [13^ 6^ 12 7] +
0.001440198214131154 [13^ 7^ 15 9] +
-0.03382179136523368 [13^ 12^ 7 6] +
0.027277038113972522 [14^ 5^ 11 8] +
0.001440198214131154 [14^ 8^ 12 6] +
-0.027277038113972522 [14^ 11^ 8 5] +
0.027277038113972522 [15^ 4^ 10 9] +
0.001440198214131154 [15^ 9^ 13 7] +
-0.027277038113972522 [15^ 10^ 9 4]

================================================================================
H_color_10 consists of:
T_24 + T_42 + T_145 + T_184 + T_304 + T_322 + T_342 + T_463 + T_497 + T_528 + T_552 + T_575

Summed operator H_color_10 =
0.05911257020782717 [1^ 0^ 14 3] +
0.05911257020782717 [3^ 0^ 14 1] +
0.009273637226071692 [3^ 1^ 13 7] +
0.046737898606760746 [5^ 2^ 11 8] +
0.047763690338698775 [7^ 6^ 13 10] +
0.0016045388097457383 [8^ 2^ 10 6] +
-0.046737898606760746 [8^ 5^ 11 2] +
-0.08775094827276778 [9^ 4^ 15 12] +
0.0016045388097457383 [10^ 6^ 8 2] +
-0.047763690338698775 [10^ 7^ 13 6] +
-0.046737898606760746 [11^ 2^ 8 5] +
-0.0014401982141311529 [11^ 5^ 15 9] +
0.046737898606760746 [11^ 8^ 5 2] +
-0.02645864546451612 [12^ 4^ 14 0] +
0.08775094827276778 [12^ 9^ 15 4] +
-0.047763690338698775 [13^ 6^ 10 7] +
0.00927363722607169 [13^ 7^ 3 1] +
0.047763690338698775 [13^ 10^ 7 6] +
-0.02645864546451612 [14^ 0^ 12 4] +
0.05911257020782717 [14^ 1^ 3 0] +
0.05911257020782717 [14^ 3^ 1 0] +
0.08775094827276778 [15^ 4^ 12 9] +
-0.0014401982141311529 [15^ 9^ 11 5] +
-0.08775094827276778 [15^ 12^ 9 4]

================================================================================
H_color_11 consists of:
T_31 + T_39 + T_149 + T_282 + T_374 + T_406 + T_409 + T_468 + T_512 + T_541 + T_551 + T_568

Summed operator H_color_11 =
-0.05911257020782717 [1^ 0^ 15 2] +
0.009273637226071692 [2^ 0^ 12 6] +
0.05911257020782717 [2^ 1^ 15 0] +
0.046737898606760746 [4^ 3^ 10 9] +
-0.047763690338698775 [7^ 6^ 12 11] +
-0.08775094827276778 [8^ 5^ 14 13] +
0.0016045388097457383 [9^ 3^ 11 7] +
-0.046737898606760746 [9^ 4^ 10 3] +
-0.046737898606760746 [10^ 3^ 9 4] +
-0.0014401982141311529 [10^ 4^ 14 8] +
0.046737898606760746 [10^ 9^ 4 3] +
-0.047763690338698775 [11^ 6^ 12 7] +
0.0016045388097457383 [11^ 7^ 9 3] +
0.00927363722607169 [12^ 6^ 2 0] +
-0.047763690338698775 [12^ 7^ 11 6] +
-0.047763690338698775 [12^ 11^ 7 6] +
-0.02645864546451612 [13^ 5^ 15 1] +
0.08775094827276778 [13^ 8^ 14 5] +
0.08775094827276778 [14^ 5^ 13 8] +
-0.0014401982141311529 [14^ 8^ 10 4] +
-0.08775094827276778 [14^ 13^ 8 5] +
0.05911257020782717 [15^ 0^ 2 1] +
-0.02645864546451612 [15^ 1^ 13 5] +
-0.05911257020782717 [15^ 2^ 1 0]

================================================================================
H_color_12 consists of:
T_32 + T_146 + T_150 + T_283 + T_290 + T_321 + T_325 + T_405 + T_452 + T_472 + T_503 + T_517

Summed operator H_color_12 =
-0.1066654988912812 [1^ 0^ 15 14] +
-0.22380686513530634 [3^ 2^ 9 8] +
0.13468241118218222 [6^ 5^ 13 10] +
0.13468241118218222 [7^ 4^ 12 11] +
0.0016045388097457453 [8^ 2^ 12 4] +
0.22380686513530634 [8^ 3^ 9 2] +
0.22380686513530634 [9^ 2^ 8 3] +
0.0016045388097457453 [9^ 3^ 13 5] +
-0.22380686513530634 [9^ 8^ 3 2] +
0.13468241118218222 [10^ 5^ 13 6] +
-0.026458645464516095 [10^ 6^ 14 0] +
0.13468241118218222 [11^ 4^ 12 7] +
-0.026458645464516095 [11^ 7^ 15 1] +
0.0016045388097457453 [12^ 4^ 8 2] +
0.13468241118218222 [12^ 7^ 11 4] +
0.13468241118218222 [12^ 11^ 7 4] +
0.0016045388097457453 [13^ 5^ 9 3] +
0.13468241118218222 [13^ 6^ 10 5] +
0.13468241118218222 [13^ 10^ 6 5] +
-0.026458645464516095 [14^ 0^ 10 6] +
0.1066654988912812 [14^ 1^ 15 0] +
0.1066654988912812 [15^ 0^ 14 1] +
-0.026458645464516095 [15^ 1^ 11 7] +
-0.1066654988912812 [15^ 14^ 1 0]

================================================================================
H_color_13 consists of:
T_40 + T_49 + T_96 + T_192 + T_235 + T_280 + T_467 + T_505 + T_530 + T_537 + T_592 + T_609

Summed operator H_color_13 =
-0.08659892439340204 [2^ 0^ 14 8] +
0.09289720158874734 [3^ 0^ 9 2] +
0.09289720158874734 [3^ 2^ 9 0] +
0.030329929331201006 [4^ 1^ 15 10] +
-0.04776369033869881 [6^ 5^ 13 12] +
-0.08775094827276778 [8^ 7^ 14 11] +
0.09289720158874734 [9^ 0^ 3 2] +
0.09289720158874734 [9^ 2^ 3 0] +
-0.02496575090278226 [9^ 3^ 15 1] +
0.030329929331201006 [10^ 1^ 15 4] +
0.11582829262353062 [10^ 4^ 12 6] +
-0.01472663882143231 [11^ 7^ 13 5] +
0.08775094827276778 [11^ 8^ 14 7] +
-0.04776369033869881 [12^ 5^ 13 6] +
0.11582829262353062 [12^ 6^ 10 4] +
-0.01472663882143231 [13^ 5^ 11 7] +
-0.04776369033869881 [13^ 6^ 12 5] +
-0.04776369033869881 [13^ 12^ 6 5] +
0.08775094827276778 [14^ 7^ 11 8] +
-0.08659892439340205 [14^ 8^ 2 0] +
-0.08775094827276778 [14^ 11^ 8 7] +
-0.024965750902782257 [15^ 1^ 9 3] +
0.030329929331201006 [15^ 4^ 10 1] +
0.030329929331201006 [15^ 10^ 4 1]

================================================================================
H_color_14 consists of:
T_50 + T_97 + T_144 + T_171 + T_221 + T_281 + T_323 + T_407 + T_453 + T_485 + T_504 + T_529

Summed operator H_color_14 =
-0.05702753634832372 [2^ 1^ 15 8] +
-0.05702753634832372 [3^ 0^ 14 9] +
-0.0041274797372193054 [6^ 5^ 12 11] +
-0.0041274797372193054 [7^ 4^ 13 10] +
-0.05702753634832372 [8^ 1^ 15 2] +
-0.0004987645960558285 [8^ 2^ 12 6] +
-0.05702753634832372 [9^ 0^ 14 3] +
-0.0004987645960558285 [9^ 3^ 13 7] +
-0.008224566172621805 [10^ 4^ 14 0] +
0.0041274797372193054 [10^ 7^ 13 4] +
-0.008224566172621805 [11^ 5^ 15 1] +
0.0041274797372193054 [11^ 6^ 12 5] +
0.0041274797372193054 [12^ 5^ 11 6] +
-0.0004987645960558285 [12^ 6^ 8 2] +
-0.0041274797372193054 [12^ 11^ 6 5] +
0.0041274797372193054 [13^ 4^ 10 7] +
-0.0004987645960558285 [13^ 7^ 9 3] +
-0.0041274797372193054 [13^ 10^ 7 4] +
-0.008224566172621808 [14^ 0^ 10 4] +
-0.05702753634832372 [14^ 3^ 9 0] +
-0.05702753634832372 [14^ 9^ 3 0] +
-0.008224566172621808 [15^ 1^ 11 5] +
-0.05702753634832372 [15^ 2^ 8 1] +
-0.05702753634832372 [15^ 8^ 2 1]

================================================================================
H_color_15 consists of:
T_33 + T_69 + T_115 + T_185 + T_191 + T_234 + T_464 + T_527 + T_563 + T_573 + T_585 + T_593 + T_610 + T_627

Summed operator H_color_15 =
-0.45593364533748104 [2^ 0^ 2 0] +
-0.08659892439340204 [3^ 1^ 15 9] +
-0.02861822829171308 [4^ 1^ 10 3] +
-0.02861822829171308 [4^ 3^ 10 1] +
-0.02861822829171308 [5^ 0^ 11 2] +
-0.02861822829171308 [5^ 2^ 11 0] +
0.02727703811397254 [8^ 7^ 14 13] +
0.02727703811397254 [9^ 6^ 15 12] +
-0.02861822829171308 [10^ 1^ 4 3] +
-0.02861822829171308 [10^ 3^ 4 1] +
-0.5117731798973485 [10^ 4^ 10 4] +
-0.02861822829171308 [11^ 0^ 5 2] +
-0.02861822829171308 [11^ 2^ 5 0] +
0.11582829262353062 [11^ 5^ 13 7] +
-0.511773179897348 [12^ 6^ 12 6] +
-0.02727703811397254 [12^ 9^ 15 6] +
0.11582829262353062 [13^ 7^ 11 5] +
-0.02727703811397254 [13^ 8^ 14 7] +
-0.02727703811397254 [14^ 7^ 13 8] +
-0.5026840985390725 [14^ 8^ 14 8] +
0.02727703811397254 [14^ 13^ 8 7] +
-0.02727703811397254 [15^ 6^ 12 9] +
-0.08659892439340205 [15^ 9^ 3 1] +
0.02727703811397254 [15^ 12^ 9 6]

================================================================================
H_color_16 consists of:
T_70 + T_116 + T_143 + T_170 + T_178 + T_220 + T_454 + T_480 + T_486 + T_524 + T_562 + T_584 + T_607 + T_635

Summed operator H_color_16 =
0.09289720158874734 [2^ 1^ 8 3] +
-0.45593364533748104 [3^ 1^ 3 1] +
-0.09289720158874734 [3^ 2^ 8 1] +
0.030329929331201006 [5^ 0^ 14 11] +
0.04776369033869881 [7^ 4^ 13 12] +
-0.09289720158874734 [8^ 1^ 3 2] +
-0.02496575090278226 [8^ 2^ 14 0] +
0.09289720158874734 [8^ 3^ 2 1] +
-0.08775094827276778 [9^ 6^ 15 10] +
-0.01472663882143231 [10^ 6^ 12 4] +
0.08775094827276778 [10^ 9^ 15 6] +
0.030329929331201006 [11^ 0^ 14 5] +
-0.5117731798973485 [11^ 5^ 11 5] +
-0.01472663882143231 [12^ 4^ 10 6] +
-0.04776369033869881 [12^ 7^ 13 4] +
-0.04776369033869881 [13^ 4^ 12 7] +
-0.511773179897348 [13^ 7^ 13 7] +
0.04776369033869881 [13^ 12^ 7 4] +
-0.024965750902782257 [14^ 0^ 8 2] +
0.030329929331201006 [14^ 5^ 11 0] +
0.030329929331201006 [14^ 11^ 5 0] +
0.08775094827276778 [15^ 6^ 10 9] +
-0.5026840985390725 [15^ 9^ 15 9] +
-0.08775094827276778 [15^ 10^ 9 6]

================================================================================
H_color_17 consists of:
T_37 + T_71 + T_133 + T_182 + T_193 + T_251 + T_550 + T_566 + T_567 + T_603 + T_620 + T_628

Summed operator H_color_17 =
-0.029833534606111826 [2^ 0^ 12 4] +
-0.029833534606111826 [3^ 1^ 13 5] +
-0.0920655923121648 [4^ 1^ 12 3] +
-0.0920655923121648 [4^ 3^ 12 1] +
-0.0920655923121648 [5^ 0^ 13 2] +
-0.0920655923121648 [5^ 2^ 13 0] +
-0.17263168228463566 [7^ 6^ 11 10] +
-0.09160067945380962 [9^ 8^ 15 14] +
-0.004633155493741763 [10^ 6^ 14 8] +
0.17263168228463566 [10^ 7^ 11 6] +
0.17263168228463566 [11^ 6^ 10 7] +
-0.004633155493741763 [11^ 7^ 15 9] +
-0.17263168228463566 [11^ 10^ 7 6] +
-0.0920655923121648 [12^ 1^ 4 3] +
-0.0920655923121648 [12^ 3^ 4 1] +
-0.029833534606111826 [12^ 4^ 2 0] +
-0.0920655923121648 [13^ 0^ 5 2] +
-0.0920655923121648 [13^ 2^ 5 0] +
-0.029833534606111826 [13^ 5^ 3 1] +
-0.004633155493741763 [14^ 8^ 10 6] +
0.09160067945380962 [14^ 9^ 15 8] +
0.09160067945380962 [15^ 8^ 14 9] +
-0.004633155493741763 [15^ 9^ 11 7] +
-0.09160067945380962 [15^ 14^ 9 8]

================================================================================
H_color_18 consists of:

,color,vertex,fermionic_term,number_of_JW_Pauli_strings,JW_transform,number_of_BK_Pauli_strings,BK_transform
0,red,T_0,-76.41243108 I,1,-76.41243108 I,1,-76.41243108 I
1,color_25,T_1,-6.45260511 a_0^dagger a_0,2,-3.22630256 I + +3.22630256 Z0,2,-3.22630256 I + +3.22630256 Z0
2,color_45,T_2,-0.43156158 a_0^dagger a_8 + -0.43156158 a_8^dagger a_0,2,-0.21578079 X0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 X8 + -0.21578079 Y0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Y8,2,-0.21578079 X0 X1 X3 Y7 Y8 X9 X11 + +0.21578079 Y0 X1 X3 Y7 X8 X9 X11
3,color_24,T_3,-6.45260511 a_1^dagger a_1,2,-3.22630256 I + +3.22630256 Z1,2,-3.22630256 I + +3.22630256 Z0 Z1
4,color_46,T_4,-0.43156158 a_1^dagger a_9 + -0.43156158 a_9^dagger a_1,2,-0.21578079 X1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 X9 + -0.21578079 Y1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Y9,2,-0.21578079 Z0 X1 X3 Y7 Y9 X11 + +0.21578079 Y1 X3 Y7 Z8 X9 X11
...,...,...,...,...,...,...,...
652,blue,T_652,+0.04723612 a_14^dagger a_13^dagger a_15 a_12 + +0.04723612 a_15^dagger a_12^dagger a_14 a_13,8,-0.00590452 X12 X13 X14 X15 + -0.00590452 X12 X13 Y14 Y15 + -0.00590452 X12 Y13 X14 Y15 + +0.00590452 X12 Y13 Y14 X15 + +0.00590452 Y12 X13 X14 Y15 + -0.00590452 Y12 X13 Y14 X15 + -0.00590452 Y12 Y13 X14 X15 + -0.00590452 Y12 Y13 Y14 Y15,8,-0.00590452 X12 X14 + -0.00590452 Y12 Y14 + +0.00590452 X12 Z13 X14 + +0.00590452 Y12 Z13 Y14 + -0.00590452 Z7 Z11 X12 X14 Z15 + -0.00590452 Z7 Z11 Y12 Y14 Z15 + +0.00590452 Z7 Z11 X12 Z13 X14 Z15 + +0.00590452 Z7 Z11 Y12 Z13 Y14 Z15
653,color_45,T_653,-0.62168539 a_15^dagger a_12^dagger a_15 a_12,4,+0.15542135 I + -0.15542135 Z12 + -0.15542135 Z15 + +0.15542135 Z12 Z15,4,+0.15542135 I + -0.15542135 Z12 + -0.15542135 Z7 Z11 Z13 Z14 Z15 + +0.15542135 Z7 Z11 Z12 Z13 Z14 Z15
654,color_46,T_654,-0.62168539 a_14^dagger a_13^dagger a_14 a_13,4,+0.15542135 I + -0.15542135 Z13 + -0.15542135 Z14 + +0.15542135 Z13 Z14,4,+0.15542135 I + -0.15542135 Z14 + -0.15542135 Z12 Z13 + +0.15542135 Z12 Z13 Z14
655,color_41,T_655,-0.57444927 a_15^dagger a_13^dagger a_15 a_13,4,+0.14361232 I + -0.14361232 Z13 + -0.14361232 Z15 + +0.14361232 Z13 Z15,4,+0.14361232 I + -0.14361232 Z12 Z13 + +0.14361232 Z7 Z11 Z12 Z14 Z15 + -0.14361232 Z7 Z11 Z13 Z14 Z15
656,color_34,T_656,-0.76034873 a_15^dagger a_14^dagger a_15 a_14,4,+0.19008718 I + -0.19008718 Z14 + -0.19008718 Z15 + +0.19008718 Z14 Z15,4,+0.19008718 I + -0.19008718 Z14 + +0.19008718 Z7 Z11 Z13 Z15 + -0.19008718 Z7 Z11 Z13 Z14 Z15

=== Color blocks mapped to JW and BK ===

,color_block,fermionic_vertices,number_of_fermionic_terms,number_of_JW_Pauli_strings,JW_block,number_of_BK_Pauli_strings,BK_block
0,H_red,T_0 + T_28 + T_94 + T_95 + T_231 + T_294 + T_362 + T_440 + T_448 + T_449 + T_507 + T_637 + T_640,13,49,-76.41243108 I + -0.01288050 X0 X1 Y8 Y9 + +0.01288050 X0 Y1 Y8 X9 + +0.01288050 Y0 X1 X8 Y9 + -0.01288050 Y0 Y1 X8 X9 + -0.01196331 X2 X3 Y14 Y15 + +0.01196331 X2 Y3 Y14 X15 + +0.01196331 Y2 X3 X14 Y15 + -0.01196331 Y2 Y3 X14 X15 + -0.00600397 X4 X5 Y6 Y7 + +0.00600397 X4 Y5 Y6 X7 + +0.00600397 Y4 X5 X6 Y7 + -0.00600397 Y4 Y5 X6 X7 + -0.00627028 X10 X11 Y12 Y13 + +0.00627028 X10 Y11 Y12 X13 + +0.00627028 Y10 X11 X12 Y13 + -0.00627028 Y10 Y11 X12 X13 + -0.01631937 X4 Z5 X6 X10 Z11 X12 + +0.01631937 X4 Z5 X6 Y10 Z11 Y12 + -0.01631937 X4 Z5 Y6 X10 Z11 Y12 + -0.01631937 X4 Z5 Y6 Y10 Z11 X12 + -0.01631937 Y4 Z5 X6 X10 Z11 Y12 + -0.01631937 Y4 Z5 X6 Y10 Z11 X12 + +0.01631937 Y4 Z5 Y6 X10 Z11 X12 + -0.01631937 Y4 Z5 Y6 Y10 Z11 Y12 + -0.01631937 X5 Z6 X7 X11 Z12 X13 + +0.01631937 X5 Z6 X7 Y11 Z12 Y13 + -0.01631937 X5 Z6 Y7 X11 Z12 Y13 + -0.01631937 X5 Z6 Y7 Y11 Z12 X13 + -0.01631937 Y5 Z6 X7 X11 Z12 Y13 + -0.01631937 Y5 Z6 X7 Y11 Z12 X13 + +0.01631937 Y5 Z6 Y7 X11 Z12 X13 + -0.01631937 Y5 Z6 Y7 Y11 Z12 Y13 + +0.01394558 X0 Z1 X2 X8 Z9 Z10 Z11 Z12 Z13 X14 + +0.01394558 X0 Z1 X2 Y8 Z9 Z10 Z11 Z12 Z13 Y14 + -0.01394558 X0 Z1 Y2 X8 Z9 Z10 Z11 Z12 Z13 Y14 + +0.01394558 X0 Z1 Y2 Y8 Z9 Z10 Z11 Z12 Z13 X14 + +0.01394558 Y0 Z1 X2 X8 Z9 Z10 Z11 Z12 Z13 Y14 + -0.01394558 Y0 Z1 X2 Y8 Z9 Z10 Z11 Z12 Z13 X14 + +0.01394558 Y0 Z1 Y2 X8 Z9 Z10 Z11 Z12 Z13 X14 + +0.01394558 Y0 Z1 Y2 Y8 Z9 Z10 Z11 Z12 Z13 Y14 + +0.01394558 X1 Z2 X3 X9 Z10 Z11 Z12 Z13 Z14 X15 + +0.01394558 X1 Z2 X3 Y9 Z10 Z11 Z12 Z13 Z14 Y15 + -0.01394558 X1 Z2 Y3 X9 Z10 Z11 Z12 Z13 Z14 Y15 + +0.01394558 X1 Z2 Y3 Y9 Z10 Z11 Z12 Z13 Z14 X15 + +0.01394558 Y1 Z2 X3 X9 Z10 Z11 Z12 Z13 Z14 Y15 + -0.01394558 Y1 Z2 X3 Y9 Z10 Z11 Z12 Z13 Z14 X15 + +0.01394558 Y1 Z2 Y3 X9 Z10 Z11 Z12 Z13 Z14 X15 + +0.01394558 Y1 Z2 Y3 Y9 Z10 Z11 Z12 Z13 Z14 Y15,49,-76.41243108 I + +0.01288050 X0 Z1 X8 + +0.01288050 X0 X8 Z9 + +0.01288050 Y0 Z1 Y8 + +0.01288050 Y0 Y8 Z9 + +0.00600397 X4 Z5 X6 + +0.00600397 Y4 Z5 Y6 + +0.00627028 X10 X12 Z13 + +0.00627028 Y10 Y12 Z13 + +0.01196331 Z1 X2 Z3 X14 + +0.01196331 Z1 Y2 Z3 Y14 + +0.00627028 Z9 X10 Z11 X12 + +0.00627028 Z9 Y10 Z11 Y12 + +0.00600397 Z3 X4 Z5 X6 Z7 + +0.00600397 Z3 Y4 Z5 Y6 Z7 + -0.01631937 Z3 Y5 Z7 X11 Y13 + -0.01631937 Z4 Y5 Z6 X11 Y13 + -0.01631937 X5 Z6 X11 Z12 X13 + -0.01394558 X1 Z2 Y9 Y11 Z13 Z14 + -0.01394558 Y1 Z3 Z7 Y9 X11 Z15 + +0.01196331 X2 Z7 Z11 Z13 X14 Z15 + +0.01196331 Y2 Z7 Z11 Z13 Y14 Z15 + +0.01631937 X5 Z6 Z9 Z10 Y11 Y13 + +0.01394558 Z0 X1 Z3 Y9 Y11 Z13 Z14 + +0.01394558 Z0 Y1 Z2 Z7 Y9 X11 Z15 + -0.01394558 X1 Z2 Z7 Z8 X9 X11 Z15 + +0.01394558 Y1 Z3 Z8 X9 Y11 Z13 Z14 + -0.01631937 Z3 Z4 X5 Z7 X11 Z12 X13 + -0.01394558 X0 Y1 X2 X8 X9 Y11 Z13 X14 + -0.01394558 X0 Y1 X2 Y8 X9 Y11 Z13 Y14 + +0.01394558 X0 Y1 Y2 X8 X9 Y11 Z13 Y14 + -0.01394558 X0 Y1 Y2 Y8 X9 Y11 Z13 X14 + -0.01394558 Y0 Y1 X2 X8 X9 Y11 Z13 Y14 + +0.01394558 Y0 Y1 X2 Y8 X9 Y11 Z13 X14 + -0.01394558 Y0 Y1 Y2 X8 X9 Y11 Z13 X14 + -0.01394558 Y0 Y1 Y2 Y8 X9 Y11 Z13 Y14 + +0.01394558 Z0 X1 Z3 Z7 Z8 X9 X11 Z15 + -0.01394558 Z0 Y1 Z2 Z8 X9 Y11 Z13 Z14 + +0.01631937 Z3 Z4 X5 Z7 Z9 Z10 Y11 Y13 + -0.01631937 Z3 Y5 Z7 Z9 Z10 Y11 Z12 X13 + -0.01631937 X4 Y5 X6 Z9 X10 Y11 X12 X13 + +0.01631937 X4 Y5 X6 Z9 Y10 Y11 Y12 X13 + -0.01631937 X4 Y5 Y6 Z9 X10 Y11 Y12 X13 + -0.01631937 X4 Y5 Y6 Z9 Y10 Y11 X12 X13 + -0.01631937 Y4 Y5 X6 Z9 X10 Y11 Y12 X13 + -0.01631937 Y4 Y5 X6 Z9 Y10 Y11 X12 X13 + +0.01631937 Y4 Y5 Y6 Z9 X10 Y11 X12 X13 + -0.01631937 Y4 Y5 Y6 Z9 Y10 Y11 Y12 X13 + -0.01631937 Z4 Y5 Z6 Z9 Z10 Y11 Z12 X13
1,H_blue,T_25 + T_62 + T_63 + T_202 + T_289 + T_309 + T_311 + T_390 + T_618 + T_622 + T_650 + T_652,12,48,-0.02627653 X0 X1 Y4 Y5 + +0.02627653 X0 Y1 Y4 X5 + +0.02627653 Y0 X1 X4 Y5 + -0.02627653 Y0 Y1 X4 X5 + -0.01270237 X2 X3 Y6 Y7 + +0.01270237 X2 Y3 Y6 X7 + +0.01270237 Y2 X3 X6 Y7 + -0.01270237 Y2 Y3 X6 X7 + -0.00955656 X8 X9 Y10 Y11 + +0.00955656 X8 Y9 Y10 X11 + +0.00955656 Y8 X9 X10 Y11 + -0.00955656 Y8 Y9 X10 X11 + -0.01180903 X12 X13 Y14 Y15 + +0.01180903 X12 Y13 Y14 X15 + +0.01180903 Y12 X13 X14 Y15 + -0.01180903 Y12 Y13 X14 X15 + -0.00813364 X0 Z1 Z2 Z3 X4 X12 Z13 X14 + +0.00813364 X0 Z1 Z2 Z3 X4 Y12 Z13 Y14 + -0.00813364 X0 Z1 Z2 Z3 Y4 X12 Z13 Y14 + -0.00813364 X0 Z1 Z2 Z3 Y4 Y12 Z13 X14 + -0.00813364 Y0 Z1 Z2 Z3 X4 X12 Z13 Y14 + -0.00813364 Y0 Z1 Z2 Z3 X4 Y12 Z13 X14 + +0.00813364 Y0 Z1 Z2 Z3 Y4 X12 Z13 X14 + -0.00813364 Y0 Z1 Z2 Z3 Y4 Y12 Z13 Y14 + -0.00813364 X1 Z2 Z3 Z4 X5 X13 Z14 X15 + +0.00813364 X1 Z2 Z3 Z4 X5 Y13 Z14 Y15 + -0.00813364 X1 Z2 Z3 Z4 Y5 X13 Z14 Y15 + -0.00813364 X1 Z2 Z3 Z4 Y5 Y13 Z14 X15 + -0.00813364 Y1 Z2 Z3 Z4 X5 X13 Z14 Y15 + -0.00813364 Y1 Z2 Z3 Z4 X5 Y13 Z14 X15 + +0.00813364 Y1 Z2 Z3 Z4 Y5 X13 Z14 X15 + -0.00813364 Y1 Z2 Z3 Z4 Y5 Y13 Z14 Y15 + -0.01432111 X2 Z3 Z4 Z5 X6 X8 Z9 X10 + +0.01432111 X2 Z3 Z4 Z5 X6 Y8 Z9 Y10 + -0.01432111 X2 Z3 Z4 Z5 Y6 X8 Z9 Y10 + -0.01432111 X2 Z3 Z4 Z5 Y6 Y8 Z9 X10 + -0.01432111 Y2 Z3 Z4 Z5 X6 X8 Z9 Y10 + -0.01432111 Y2 Z3 Z4 Z5 X6 Y8 Z9 X10 + +0.01432111 Y2 Z3 Z4 Z5 Y6 X8 Z9 X10 + -0.01432111 Y2 Z3 Z4 Z5 Y6 Y8 Z9 Y10 + -0.01432111 X3 Z4 Z5 Z6 X7 X9 Z10 X11 + +0.01432111 X3 Z4 Z5 Z6 X7 Y9 Z10 Y11 + -0.01432111 X3 Z4 Z5 Z6 Y7 X9 Z10 Y11 + -0.01432111 X3 Z4 Z5 Z6 Y7 Y9 Z10 X11 + -0.01432111 Y3 Z4 Z5 Z6 X7 X9 Z10 Y11 + -0.01432111 Y3 Z4 Z5 Z6 X7 Y9 Z10 X11 + +0.01432111 Y3 Z4 Z5 Z6 Y7 X9 Z10 X11 + -0.01432111 Y3 Z4 Z5 Z6 Y7 Y9 Z10 Y11,48,+0.02627653 X0 Z1 X4 + +0.02627653 X0 X4 Z5 + +0.02627653 Y0 Z1 Y4 + +0.02627653 Y0 Y4 Z5 + +0.00955656 X8 Z9 X10 + +0.00955656 Y8 Z9 Y10 + +0.01180903 X12 Z13 X14 + +0.01180903 Y12 Z13 Y14 + +0.01270237 Z1 X2 Z3 X6 + +0.01270237 Z1 Y2 Z3 Y6 + -0.01432111 Y3 Z7 Y9 Z11 + +0.00955656 X8 Z9 X10 Z11 + +0.00955656 Y8 Z9 Y10 Z11 + +0.01270237 X2 Z3 Z5 X6 Z7 + +0.01270237 Y2 Z3 Z5 Y6 Z7 + -0.01432111 X3 Z5 Z6 X9 Z10 + -0.01432111 Y3 Z7 Z8 Y9 Z10 + +0.00813364 Z0 X1 Y3 Y5 X13 Z14 + +0.00813364 Y1 Y3 Z4 X5 X13 Z14 + +0.00813364 Y1 Y3 Y5 Z12 Y13 Z14 + -0.01432111 Z1 Z2 X3 Z7 X9 Z10 + -0.01432111 X3 Z5 Z6 Z8 X9 Z11 + +0.01180903 Z7 Z11 X12 Z13 X14 Z15 + +0.01180903 Z7 Z11 Y12 Z13 Y14 Z15 + +0.00813364 Y1 Y3 Y5 Z7 Z11 Y13 Z15 + -0.01432111 Z1 Z2 X3 Z7 Z8 X9 Z11 + -0.01432111 Z1 Z2 Y3 Z5 Z6 Y9 Z11 + -0.00813364 X0 X1 Y3 X4 X5 X12 Y13 X14 + +0.00813364 X0 X1 Y3 X4 X5 Y12 Y13 Y14 + -0.00813364 X0 X1 Y3 Y4 X5 X12 Y13 Y14 + -0.00813364 X0 X1 Y3 Y4 X5 Y12 Y13 X14 + -0.00813364 Y0 X1 Y3 X4 X5 X12 Y13 Y14 + -0.00813364 Y0 X1 Y3 X4 X5 Y12 Y13 X14 + +0.00813364 Y0 X1 Y3 Y4 X5 X12 Y13 X14 + -0.00813364 Y0 X1 Y3 Y4 X5 Y12 Y13 Y14 + -0.00813364 Z0 X1 Y3 Z4 X5 Z12 Y13 Z14 + -0.01432111 Z1 X2 Y3 Z5 X6 X8 Y9 X10 + +0.01432111 Z1 X2 Y3 Z5 X6 Y8 Y9 Y10 + -0.01432111 Z1 X2 Y3 Z5 Y6 X8 Y9 Y10 + -0.01432111 Z1 X2 Y3 Z5 Y6 Y8 Y9 X10 + -0.01432111 Z1 Y2 Y3 Z5 X6 X8 Y9 Y10 + -0.01432111 Z1 Y2 Y3 Z5 X6 Y8 Y9 X10 + +0.01432111 Z1 Y2 Y3 Z5 Y6 X8 Y9 X10 + -0.01432111 Z1 Y2 Y3 Z5 Y6 Y8 Y9 Y10 + -0.01432111 Z1 Z2 Y3 Z5 Z6 Z8 Y9 Z10 + -0.00813364 Z0 X1 Y3 Z4 X5 Z7 Z11 Y13 Z15 + +0.00813364 Z0 X1 Y3 Y5 Z7 Z11 Z12 X13 Z15 + +0.00813364 Y1 Y3 Z4 X5 Z7 Z11 Z12 X13 Z15
2,H_green,T_26 + T_79 + T_81 + T_218 + T_288 + T_298 + T_299 + T_380 + T_619 + T_625 + T_638 + T_643,12,48,-0.02627653 X0 X1 Y6 Y7 + +0.02627653 X0 Y1 Y6 X7 + +0.02627653 Y0 X1 X6 Y7 + -0.02627653 Y0 Y1 X6 X7 + -0.01270237 X2 X3 Y4 Y5 + +0.01270237 X2 Y3 Y4 X5 + +0.01270237 Y2 X3 X4 Y5 + -0.01270237 Y2 Y3 X4 X5 + -0.00955656 X8 X9 Y12 Y13 + +0.00955656 X8 Y9 Y12 X13 + +0.00955656 Y8 X9 X12 Y13 + -0.00955656 Y8 Y9 X12 X13 + -0.01180903 X10 X11 Y14 Y15 + +0.01180903 X10 Y11 Y14 X15 + +0.01180903 Y10 X11 X14 Y15 + -0.01180903 Y10 Y11 X14 X15 + -0.01432111 X2 Z3 X4 X8 Z9 Z10 Z11 X12 + +0.01432111 X2 Z3 X4 Y8 Z9 Z10 Z11 Y12 + -0.01432111 X2 Z3 Y4 X8 Z9 Z10 Z11 Y12 + -0.01432111 X2 Z3 Y4 Y8 Z9 Z10 Z11 X12 + -0.01432111 Y2 Z3 X4 X8 Z9 Z10 Z11 Y12 + -0.01432111 Y2 Z3 X4 Y8 Z9 Z10 Z11 X12 + +0.01432111 Y2 Z3 Y4 X8 Z9 Z10 Z11 X12 + -0.01432111 Y2 Z3 Y4 Y8 Z9 Z10 Z11 Y12 + -0.01432111 X3 Z4 X5 X9 Z10 Z11 Z12 X13 + +0.01432111 X3 Z4 X5 Y9 Z10 Z11 Z12 Y13 + -0.01432111 X3 Z4 Y5 X9 Z10 Z11 Z12 Y13 + -0.01432111 X3 Z4 Y5 Y9 Z10 Z11 Z12 X13 + -0.01432111 Y3 Z4 X5 X9 Z10 Z11 Z12 Y13 + -0.01432111 Y3 Z4 X5 Y9 Z10 Z11 Z12 X13 + +0.01432111 Y3 Z4 Y5 X9 Z10 Z11 Z12 X13 + -0.01432111 Y3 Z4 Y5 Y9 Z10 Z11 Z12 Y13 + -0.00813364 X0 Z1 Z2 Z3 Z4 Z5 X6 X10 Z11 Z12 Z13 X14 + +0.00813364 X0 Z1 Z2 Z3 Z4 Z5 X6 Y10 Z11 Z12 Z13 Y14 + -0.00813364 X0 Z1 Z2 Z3 Z4 Z5 Y6 X10 Z11 Z12 Z13 Y14 + -0.00813364 X0 Z1 Z2 Z3 Z4 Z5 Y6 Y10 Z11 Z12 Z13 X14 + -0.00813364 Y0 Z1 Z2 Z3 Z4 Z5 X6 X10 Z11 Z12 Z13 Y14 + -0.00813364 Y0 Z1 Z2 Z3 Z4 Z5 X6 Y10 Z11 Z12 Z13 X14 + +0.00813364 Y0 Z1 Z2 Z3 Z4 Z5 Y6 X10 Z11 Z12 Z13 X14 + -0.00813364 Y0 Z1 Z2 Z3 Z4 Z5 Y6 Y10 Z11 Z12 Z13 Y14 + -0.00813364 X1 Z2 Z3 Z4 Z5 Z6 X7 X11 Z12 Z13 Z14 X15 + +0.00813364 X1 Z2 Z3 Z4 Z5 Z6 X7 Y11 Z12 Z13 Z14 Y15 + -0.00813364 X1 Z2 Z3 Z4 Z5 Z6 Y7 X11 Z12 Z13 Z14 Y15 + -0.00813364 X1 Z2 Z3 Z4 Z5 Z6 Y7 Y11 Z12 Z13 Z14 X15 + -0.00813364 Y1 Z2 Z3 Z4 Z5 Z6 X7 X11 Z12 Z13 Z14 Y15 + -0.00813364 Y1 Z2 Z3 Z4 Z5 Z6 X7 Y11 Z12 Z13 Z14 X15 + +0.00813364 Y1 Z2 Z3 Z4 Z5 Z6 Y7 X11 Z12 Z13 Z14 X15 + -0.00813364 Y1 Z2 Z3 Z4 Z5 Z6 Y7 Y11 Z12 Z13 Z14 Y15,48,+0.02627653 X0 Z1 X6 + +0.02627653 Y0 Z1 Y6 + +0.01270237 X2 X4 Z5 + +0.01270237 Y2 Y4 Z5 + +0.00955656 X8 Z9 X12 + +0.00955656 X8 X12 Z13 + +0.00955656 Y8 Z9 Y12 + +0.00955656 Y8 Y12 Z13 + -0.00813364 Y1 X3 Y11 Z15 + +0.01270237 Z1 X2 Z3 X4 + +0.01270237 Z1 Y2 Z3 Y4 + +0.01180903 Z9 X10 Z11 X14 + +0.01180903 Z9 Y10 Z11 Y14 + +0.02627653 X0 Z3 Z5 X6 Z7 + +0.02627653 Y0 Z3 Z5 Y6 Z7 + +0.01432111 X3 Y5 Y9 Y11 Y13 + +0.01180903 Z7 X10 Z11 Z13 X14 Z15 + +0.01180903 Z7 Y10 Z11 Z13 Y14 Z15 + -0.00813364 Z0 X1 X3 Z7 X11 Z13 Z14 + -0.00813364 Z0 X1 X3 Z9 Z10 X11 Z15 + +0.00813364 Y1 Y3 Z5 Z6 X11 Z13 Z14 + +0.01432111 X3 Z4 X5 Z8 X9 Y11 Y13 + +0.01432111 X3 Z4 X5 Y9 Y11 Z12 X13 + -0.01432111 X3 Y5 Z8 X9 Y11 Z12 X13 + -0.00813364 Z0 X1 Y3 Z5 Z6 Z7 Y11 Z15 + -0.00813364 Y1 X3 Z7 Z9 Z10 Y11 Z13 Z14 + +0.01432111 Z1 Z2 Y3 Z4 X5 Y9 Y11 Y13 + -0.01432111 Z1 Z2 Y3 Y5 Z8 X9 Y11 Y13 + -0.01432111 Z1 Z2 Y3 Y5 Y9 Y11 Z12 X13 + +0.00813364 Y1 Y3 Z5 Z6 Z7 Z9 Z10 X11 Z15 + -0.00813364 X0 X1 Y3 Z5 X6 Z9 X10 Y11 Z13 X14 + +0.00813364 X0 X1 Y3 Z5 X6 Z9 Y10 Y11 Z13 Y14 + -0.00813364 X0 X1 Y3 Z5 Y6 Z9 X10 Y11 Z13 Y14 + -0.00813364 X0 X1 Y3 Z5 Y6 Z9 Y10 Y11 Z13 X14 + -0.00813364 Y0 X1 Y3 Z5 X6 Z9 X10 Y11 Z13 Y14 + -0.00813364 Y0 X1 Y3 Z5 X6 Z9 Y10 Y11 Z13 X14 + +0.00813364 Y0 X1 Y3 Z5 Y6 Z9 X10 Y11 Z13 X14 + -0.00813364 Y0 X1 Y3 Z5 Y6 Z9 Y10 Y11 Z13 Y14 + -0.00813364 Z0 X1 Y3 Z5 Z6 Z9 Z10 Y11 Z13 Z14 + -0.01432111 Z1 X2 Y3 X4 X5 X8 X9 Y11 X12 X13 + +0.01432111 Z1 X2 Y3 X4 X5 Y8 X9 Y11 Y12 X13 + -0.01432111 Z1 X2 Y3 Y4 X5 X8 X9 Y11 Y12 X13 + -0.01432111 Z1 X2 Y3 Y4 X5 Y8 X9 Y11 X12 X13 + -0.01432111 Z1 Y2 Y3 X4 X5 X8 X9 Y11 Y12 X13 + -0.01432111 Z1 Y2 Y3 X4 X5 Y8 X9 Y11 X12 X13 + +0.01432111 Z1 Y2 Y3 Y4 X5 X8 X9 Y11 X12 X13 + -0.01432111 Z1 Y2 Y3 Y4 X5 Y8 X9 Y11 Y12 X13 + -0.01432111 Z1 Z2 Y3 Z4 X5 Z8 X9 Y11 Z12 X13
3,H_orange,T_29 + T_110 + T_112 + T_247 + T_292 + T_350 + T_353 + T_428 + T_441 + T_458 + T_554 + T_583,12,48,-0.01104723 X0 X1 Y10 Y11 + +0.01104723 X0 Y1 Y10 X11 + +0.01104723 Y0 X1 X10 Y11 + -0.01104723 Y0 Y1 X10 X11 + -0.02059170 X2 X3 Y12 Y13 + +0.02059170 X2 Y3 Y12 X13 + +0.02059170 Y2 X3 X12 Y13 + -0.02059170 Y2 Y3 X12 X13 + -0.00701710 X4 X5 Y8 Y9 + +0.00701710 X4 Y5 Y8 X9 + +0.00701710 Y4 X5 X8 Y9 + -0.00701710 Y4 Y5 X8 X9 + -0.00884183 X6 X7 Y14 Y15 + +0.00884183 X6 Y7 Y14 X15 + +0.00884183 Y6 X7 X14 Y15 + -0.00884183 Y6 Y7 X14 X15 + +0.01412055 X2 Z3 X4 X8 Z9 Z10 Z11 X12 + +0.01412055 X2 Z3 X4 Y8 Z9 Z10 Z11 Y12 + +0.01412055 X2 Z3 Y4 X8 Z9 Z10 Z11 Y12 + -0.01412055 X2 Z3 Y4 Y8 Z9 Z10 Z11 X12 + -0.01412055 Y2 Z3 X4 X8 Z9 Z10 Z11 Y12 + +0.01412055 Y2 Z3 X4 Y8 Z9 Z10 Z11 X12 + +0.01412055 Y2 Z3 Y4 X8 Z9 Z10 Z11 X12 + +0.01412055 Y2 Z3 Y4 Y8 Z9 Z10 Z11 Y12 + +0.01412055 X3 Z4 X5 X9 Z10 Z11 Z12 X13 + +0.01412055 X3 Z4 X5 Y9 Z10 Z11 Z12 Y13 + +0.01412055 X3 Z4 Y5 X9 Z10 Z11 Z12 Y13 + -0.01412055 X3 Z4 Y5 Y9 Z10 Z11 Z12 X13 + -0.01412055 Y3 Z4 X5 X9 Z10 Z11 Z12 Y13 + +0.01412055 Y3 Z4 X5 Y9 Z10 Z11 Z12 X13 + +0.01412055 Y3 Z4 Y5 X9 Z10 Z11 Z12 X13 + +0.01412055 Y3 Z4 Y5 Y9 Z10 Z11 Z12 Y13 + -0.00482631 X0 Z1 Z2 Z3 Z4 Z5 X6 X10 Z11 Z12 Z13 X14 + -0.00482631 X0 Z1 Z2 Z3 Z4 Z5 X6 Y10 Z11 Z12 Z13 Y14 + +0.00482631 X0 Z1 Z2 Z3 Z4 Z5 Y6 X10 Z11 Z12 Z13 Y14 + -0.00482631 X0 Z1 Z2 Z3 Z4 Z5 Y6 Y10 Z11 Z12 Z13 X14 + -0.00482631 Y0 Z1 Z2 Z3 Z4 Z5 X6 X10 Z11 Z12 Z13 Y14 + +0.00482631 Y0 Z1 Z2 Z3 Z4 Z5 X6 Y10 Z11 Z12 Z13 X14 + -0.00482631 Y0 Z1 Z2 Z3 Z4 Z5 Y6 X10 Z11 Z12 Z13 X14 + -0.00482631 Y0 Z1 Z2 Z3 Z4 Z5 Y6 Y10 Z11 Z12 Z13 Y14 + -0.00482631 X1 Z2 Z3 Z4 Z5 Z6 X7 X11 Z12 Z13 Z14 X15 + -0.00482631 X1 Z2 Z3 Z4 Z5 Z6 X7 Y11 Z12 Z13 Z14 Y15 + +0.00482631 X1 Z2 Z3 Z4 Z5 Z6 Y7 X11 Z12 Z13 Z14 Y15 + -0.00482631 X1 Z2 Z3 Z4 Z5 Z6 Y7 Y11 Z12 Z13 Z14 X15 + -0.00482631 Y1 Z2 Z3 Z4 Z5 Z6 X7 X11 Z12 Z13 Z14 Y15 + +0.00482631 Y1 Z2 Z3 Z4 Z5 Z6 X7 Y11 Z12 Z13 Z14 X15 + -0.00482631 Y1 Z2 Z3 Z4 Z5 Z6 Y7 X11 Z12 Z13 Z14 X15 + -0.00482631 Y1 Z2 Z3 Z4 Z5 Z6 Y7 Y11 Z12 Z13 Z14 Y15,48,+0.01104723 X0 Z1 X10 + +0.01104723 Y0 Z1 Y10 + +0.02059170 X2 X12 Z13 + +0.02059170 Y2 Y12 Z13 + +0.00701710 X4 Z5 X8 + +0.00701710 X4 X8 Z9 + +0.00701710 Y4 Z5 Y8 + +0.00701710 Y4 Y8 Z9 + +0.01104723 X0 Z9 X10 Z11 + +0.01104723 Y0 Z9 Y10 Z11 + +0.00482631 Y1 X3 Y11 Z15 + +0.02059170 Z1 X2 Z3 X12 + +0.02059170 Z1 Y2 Z3 Y12 + -0.01412055 X3 Y5 Y9 Y11 Y13 + +0.00884183 Z3 Z5 X6 Z7 X14 + +0.00884183 Z3 Z5 Y6 Z7 Y14 + +0.00884183 X6 Z7 Z11 Z13 X14 Z15 + +0.00884183 Y6 Z7 Z11 Z13 Y14 Z15 + +0.00482631 Z0 X1 X3 Z7 X11 Z13 Z14 + -0.00482631 Z0 X1 X3 Z9 Z10 X11 Z15 + +0.00482631 Y1 Y3 Z5 Z6 X11 Z13 Z14 + +0.01412055 X3 Z4 X5 Z8 X9 Y11 Y13 + -0.01412055 X3 Z4 X5 Y9 Y11 Z12 X13 + -0.01412055 X3 Y5 Z8 X9 Y11 Z12 X13 + -0.00482631 Z0 X1 Y3 Z5 Z6 Z7 Y11 Z15 + -0.00482631 Y1 X3 Z7 Z9 Z10 Y11 Z13 Z14 + +0.01412055 Z1 Z2 Y3 Z4 X5 Y9 Y11 Y13 + +0.01412055 Z1 Z2 Y3 Y5 Z8 X9 Y11 Y13 + -0.01412055 Z1 Z2 Y3 Y5 Y9 Y11 Z12 X13 + -0.00482631 Y1 Y3 Z5 Z6 Z7 Z9 Z10 X11 Z15 + +0.00482631 X0 X1 Y3 Z5 X6 Z9 X10 Y11 Z13 X14 + +0.00482631 X0 X1 Y3 Z5 X6 Z9 Y10 Y11 Z13 Y14 + -0.00482631 X0 X1 Y3 Z5 Y6 Z9 X10 Y11 Z13 Y14 + +0.00482631 X0 X1 Y3 Z5 Y6 Z9 Y10 Y11 Z13 X14 + +0.00482631 Y0 X1 Y3 Z5 X6 Z9 X10 Y11 Z13 Y14 + -0.00482631 Y0 X1 Y3 Z5 X6 Z9 Y10 Y11 Z13 X14 + +0.00482631 Y0 X1 Y3 Z5 Y6 Z9 X10 Y11 Z13 X14 + +0.00482631 Y0 X1 Y3 Z5 Y6 Z9 Y10 Y11 Z13 Y14 + +0.00482631 Z0 X1 Y3 Z5 Z6 Z9 Z10 Y11 Z13 Z14 + +0.01412055 Z1 X2 Y3 X4 X5 X8 X9 Y11 X12 X13 + +0.01412055 Z1 X2 Y3 X4 X5 Y8 X9 Y11 Y12 X13 + +0.01412055 Z1 X2 Y3 Y4 X5 X8 X9 Y11 Y12 X13 + -0.01412055 Z1 X2 Y3 Y4 X5 Y8 X9 Y11 X12 X13 + -0.01412055 Z1 Y2 Y3 X4 X5 X8 X9 Y11 Y12 X13 + +0.01412055 Z1 Y2 Y3 X4 X5 Y8 X9 Y11 X12 X13 + +0.01412055 Z1 Y2 Y3 Y4 X5 X8 X9 Y11 X12 X13 + +0.01412055 Z1 Y2 Y3 Y4 X5 Y8 X9 Y11 Y12 X13 + +0.01412055 Z1 Z2 Y3 Z4 X5 Z8 X9 Y11 Z12 X13
4,H_purple,T_30 + T_127 + T_130 + T_263 + T_291 + T_339 + T_341 + T_418 + T_446 + T_495 + T_549 + T_558,12,48,-0.01104723 X0 X1 Y12 Y13 + +0.01104723 X0 Y1 Y12 X13 + +0.01104723 Y0 X1 X12 Y13 + -0.01104723 Y0 Y1 X12 X13 + -0.02059170 X2 X3 Y10 Y11 + +0.02059170 X2 Y3 Y10 X11 + +0.02059170 Y2 X3 X10 Y11 + -0.02059170 Y2 Y3 X10 X11 + -0.00884183 X4 X5 Y14 Y15 + +0.00884183 X4 Y5 Y14 X15 + +0.00884183 Y4 X5 X14 Y15 + -0.00884183 Y4 Y5 X14 X15 + -0.00701710 X6 X7 Y8 Y9 + +0.00701710 X6 Y7 Y8 X9 + +0.00701710 Y6 X7 X8 Y9 + -0.00701710 Y6 Y7 X8 X9 + -0.00482631 X0 Z1 Z2 Z3 X4 X12 Z13 X14 + -0.00482631 X0 Z1 Z2 Z3 X4 Y12 Z13 Y14 + +0.00482631 X0 Z1 Z2 Z3 Y4 X12 Z13 Y14 + -0.00482631 X0 Z1 Z2 Z3 Y4 Y12 Z13 X14 + -0.00482631 Y0 Z1 Z2 Z3 X4 X12 Z13 Y14 + +0.00482631 Y0 Z1 Z2 Z3 X4 Y12 Z13 X14 + -0.00482631 Y0 Z1 Z2 Z3 Y4 X12 Z13 X14 + -0.00482631 Y0 Z1 Z2 Z3 Y4 Y12 Z13 Y14 + -0.00482631 X1 Z2 Z3 Z4 X5 X13 Z14 X15 + -0.00482631 X1 Z2 Z3 Z4 X5 Y13 Z14 Y15 + +0.00482631 X1 Z2 Z3 Z4 Y5 X13 Z14 Y15 + -0.00482631 X1 Z2 Z3 Z4 Y5 Y13 Z14 X15 + -0.00482631 Y1 Z2 Z3 Z4 X5 X13 Z14 Y15 + +0.00482631 Y1 Z2 Z3 Z4 X5 Y13 Z14 X15 + -0.00482631 Y1 Z2 Z3 Z4 Y5 X13 Z14 X15 + -0.00482631 Y1 Z2 Z3 Z4 Y5 Y13 Z14 Y15 + +0.01412055 X2 Z3 Z4 Z5 X6 X8 Z9 X10 + +0.01412055 X2 Z3 Z4 Z5 X6 Y8 Z9 Y10 + +0.01412055 X2 Z3 Z4 Z5 Y6 X8 Z9 Y10 + -0.01412055 X2 Z3 Z4 Z5 Y6 Y8 Z9 X10 + -0.01412055 Y2 Z3 Z4 Z5 X6 X8 Z9 Y10 + +0.01412055 Y2 Z3 Z4 Z5 X6 Y8 Z9 X10 + +0.01412055 Y2 Z3 Z4 Z5 Y6 X8 Z9 X10 + +0.01412055 Y2 Z3 Z4 Z5 Y6 Y8 Z9 Y10 + +0.01412055 X3 Z4 Z5 Z6 X7 X9 Z10 X11 + +0.01412055 X3 Z4 Z5 Z6 X7 Y9 Z10 Y11 + +0.01412055 X3 Z4 Z5 Z6 Y7 X9 Z10 Y11 + -0.01412055 X3 Z4 Z5 Z6 Y7 Y9 Z10 X11 + -0.01412055 Y3 Z4 Z5 Z6 X7 X9 Z10 Y11 + +0.01412055 Y3 Z4 Z5 Z6 X7 Y9 Z10 X11 + +0.01412055 Y3 Z4 Z5 Z6 Y7 X9 Z10 X11 + +0.01412055 Y3 Z4 Z5 Z6 Y7 Y9 Z10 Y11,48,+0.01104723 X0 Z1 X12 + +0.01104723 X0 X12 Z13 + +0.01104723 Y0 Z1 Y12 + +0.01104723 Y0 Y12 Z13 + +0.00884183 X4 Z5 X14 + +0.00884183 Y4 Z5 Y14 + +0.00701710 X6 X8 Z9 + +0.00701710 Y6 Y8 Z9 + +0.02059170 Z1 X2 Z3 X10 + +0.02059170 Z1 Y2 Z3 Y10 + +0.02059170 X2 Z9 X10 Z11 + +0.02059170 Y2 Z9 Y10 Z11 + +0.01412055 Y3 Z7 Y9 Z11 + +0.01412055 X3 Z5 Z6 X9 Z10 + -0.01412055 Y3 Z7 Z8 Y9 Z10 + +0.00701710 Z3 Z5 X6 Z7 X8 + +0.00701710 Z3 Z5 Y6 Z7 Y8 + -0.00482631 Z0 X1 Y3 Y5 X13 Z14 + +0.00482631 Y1 Y3 Z4 X5 X13 Z14 + +0.00482631 Y1 Y3 Y5 Z12 Y13 Z14 + -0.01412055 Z1 Z2 X3 Z7 X9 Z10 + -0.01412055 X3 Z5 Z6 Z8 X9 Z11 + +0.00884183 X4 Z7 Z11 Z13 X14 Z15 + +0.00884183 Y4 Z7 Z11 Z13 Y14 Z15 + -0.00482631 Y1 Y3 Y5 Z7 Z11 Y13 Z15 + +0.01412055 Z1 Z2 X3 Z7 Z8 X9 Z11 + -0.01412055 Z1 Z2 Y3 Z5 Z6 Y9 Z11 + +0.00482631 X0 X1 Y3 X4 X5 X12 Y13 X14 + +0.00482631 X0 X1 Y3 X4 X5 Y12 Y13 Y14 + -0.00482631 X0 X1 Y3 Y4 X5 X12 Y13 Y14 + +0.00482631 X0 X1 Y3 Y4 X5 Y12 Y13 X14 + +0.00482631 Y0 X1 Y3 X4 X5 X12 Y13 Y14 + -0.00482631 Y0 X1 Y3 X4 X5 Y12 Y13 X14 + +0.00482631 Y0 X1 Y3 Y4 X5 X12 Y13 X14 + +0.00482631 Y0 X1 Y3 Y4 X5 Y12 Y13 Y14 + +0.00482631 Z0 X1 Y3 Z4 X5 Z12 Y13 Z14 + +0.01412055 Z1 X2 Y3 Z5 X6 X8 Y9 X10 + +0.01412055 Z1 X2 Y3 Z5 X6 Y8 Y9 Y10 + +0.01412055 Z1 X2 Y3 Z5 Y6 X8 Y9 Y10 + -0.01412055 Z1 X2 Y3 Z5 Y6 Y8 Y9 X10 + -0.01412055 Z1 Y2 Y3 Z5 X6 X8 Y9 Y10 + +0.01412055 Z1 Y2 Y3 Z5 X6 Y8 Y9 X10 + +0.01412055 Z1 Y2 Y3 Z5 Y6 X8 Y9 X10 + +0.01412055 Z1 Y2 Y3 Z5 Y6 Y8 Y9 Y10 + +0.01412055 Z1 Z2 Y3 Z5 Z6 Z8 Y9 Z10 + -0.00482631 Z0 X1 Y3 Z4 X5 Z7 Z11 Y13 Z15 + +0.00482631 Z0 X1 Y3 Y5 Z7 Z11 Z12 X13 Z15 + -0.00482631 Y1 Y3 Z4 X5 Z7 Z11 Z12 X13 Z15

=== Verify commuting groups after JW/BK mapping ===

     color_group          pair  fermionic_commute  JW_commute  BK_commute
0            red     T_0, T_28               True        True        True
1            red     T_0, T_94               True        True        True
2            red     T_0, T_95               True        True        True
3            red    T_0, T_231               True        True        True
4            red    T_0, T_294               True        True        True
...          ...           ...                ...         ...         ...
4333    color_50  T_565, T_613               True        True        True
4334    color_50  T_599, T_602               True        True        True
4335    color_50  T_599, T_613               True        True        True
4336    color_50  T_602, T_613               True        True        True
4337    color_51  T_526, T_538               True        True        True

[4338 rows x 5 columns]

In [6]:
# Find duplicated JW Pauli strings across fermionic terms T_i

from collections import defaultdict
import pandas as pd

pauli_usage = defaultdict(list)

for node in sorted(G.nodes()):
    JW_T = G.nodes[node]["JW_operator"]

    for pauli_key, coeff in JW_T.terms.items():
        pauli_string = format_qubit_term(pauli_key)

        pauli_usage[pauli_string].append(
            {
                "vertex": f"T_{node}",
                "coefficient": coeff,
                "fermionic_term": G.nodes[node]["operator_string"],
            }
        )

duplicate_rows = []

for pauli_string, appearances in pauli_usage.items():
    if len(appearances) > 1:
        duplicate_rows.append(
            {
                "JW_Pauli_string": pauli_string,
                "number_of_appearances": len(appearances),
                "appears_in_vertices": [x["vertex"] for x in appearances],
                "coefficients": [x["coefficient"] for x in appearances],
            }
        )

duplicate_jw_df = pd.DataFrame(duplicate_rows)
duplicate_jw_df = duplicate_jw_df.sort_values(
    "number_of_appearances",
    ascending=False
).reset_index(drop=True)

print("Total JW Pauli-string appearances:", sum(len(G.nodes[node]["JW_operator"].terms) for node in G.nodes()))
print("Number of unique JW Pauli strings:", len(pauli_usage))
print("Number of duplicated JW Pauli strings:", len(duplicate_jw_df))

display(duplicate_jw_df)

Total JW Pauli-string appearances: 4361
Number of unique JW Pauli strings: 1929
Number of duplicated JW Pauli strings: 1665

,JW_Pauli_string,number_of_appearances,appears_in_vertices,coefficients
0,I,137,"[T_0, T_1, T_3, T_5, T_7, T_9, T_10, T_11, T_12, T_13, T_14, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_33, T_43, T_57, T_66, T_75, T_84, T_93, T_100, T_106, T_120, T_124, T_138, T_142, T_162, T_164, T_178, T_188, T_197, T_205, T_214, T_224, T_230, T_239, T_243, T_256, T_260, T_277, T_279, T_286, T_295, T_300, T_307, T_312, T_319, T_330, T_337, T_346, T_349, T_358, T_361, T_368, T_370, T_377, T_381, T_388, T_396, T_403, T_413, T_416, T_424, T_427, T_436, T_438, T_439, T_447, T_450, T_455, T_459, T_464, T_474, T_479, T_489, T_492, T_500, T_501, T_506, T_508, T_513, T_519, T_524, T_533, T_536, T_544, T_545, T_548, T_555, T_559, T_564, T_570, T_573, T_578, T_580, ...]","[-76.41243108300478, -3.2263025563149195, -3.2263025563149195, -2.5330181470267243, -2.5330181470267243, -2.6626134366646674, -2.6626134366646674, -2.6626134366646657, -2.6626134366646657, -2.532305229532999, -2.532305229532999, -2.475983217761466, -2.475983217761466, -2.4759832177614656, -2.4759832177614656, -2.3996691935208325, -2.3996691935208325, 0.18700182520310787, 0.11398341133437026, 0.12803515547483427, 0.12813774000415315, 0.15441426629825403, 0.12813774000415304, 0.15441426629825394, 0.12277831667770017, 0.1356588184128124, 0.13805542016704353, 0.1491026456273155, 0.1380554201670435, 0.14910264562731548, 0.15449646387462293, 0.18116283859744323, 0.12803515547483427, 0.11398341133437026, 0.15441426629825403, 0.12813774000415315, 0.15441426629825394, 0.12813774000415304, 0.1356588184128124, 0.12277831667770017, 0.1491026456273155, 0.13805542016704353, 0.14910264562731548, 0.1380554201670435, 0.18116283859744323, 0.15449646387462293, 0.1363994271196187, 0.1148330984053242, 0.12753547184396263, 0.11483309840532413, 0.12753547184396258, 0.08338122258429083, 0.13933293886811743, 0.11342752264772253, 0.13401922089828572, 0.11342752264772249, 0.13401922089828566, 0.1279608402251692, 0.13992415271567188, 0.12753547184396263, 0.1148330984053242, 0.12753547184396258, 0.11483309840532413, 0.13933293886811743, 0.08338122258429083, 0.13401922089828572, 0.11342752264772253, 0.13401922089828566, 0.11342752264772249, 0.13992415271567188, 0.1279608402251692, 0.14709020314234053, 0.12907828958598547, 0.1350822607714371, 0.12246207154396146, 0.1294791685187213, 0.12794329497433712, 0.1363987428156455, 0.10266788152381243, 0.14582580209497134, 0.14623411472701525, 0.15507594674017267, 0.1350822607714371, 0.12907828958598547, 0.1294791685187213, 0.12246207154396146, 0.1363987428156455, 0.12794329497433712, 0.14582580209497134, 0.10266788152381243, 0.15507594674017267, 0.14623411472701525, 0.14709020314234034, 0.12246207154396141, 0.1294791685187212, 0.1026678815238124, 0.1458258020949713, 0.127943294974337, 0.13639874281564546, 0.14623411472701517, ...]"
1,Z4,16,"[T_9, T_57, T_188, T_295, T_370, T_439, T_447, T_450, T_455, T_459, T_464, T_474, T_479, T_489, T_492, T_500]","[2.6626134366646674, -0.12813774000415315, -0.15441426629825403, -0.1148330984053242, -0.12753547184396263, -0.14709020314234053, -0.12907828958598547, -0.1350822607714371, -0.12246207154396146, -0.1294791685187213, -0.12794329497433712, -0.1363987428156455, -0.10266788152381243, -0.14582580209497134, -0.14623411472701525, -0.15507594674017267]"
2,Z15,16,"[T_20, T_162, T_279, T_368, T_438, T_500, T_545, T_588, T_614, T_629, T_635, T_644, T_648, T_653, T_655, T_656]","[2.3996691935208325, -0.18116283859744323, -0.15449646387462293, -0.13992415271567188, -0.1279608402251692, -0.15507594674017267, -0.14623411472701525, -0.15507594674017255, -0.14623411472701517, -0.14857119449822054, -0.12567102463476812, -0.15542134861027598, -0.14361231750314465, -0.15542134861027587, -0.14361231750314454, -0.1900871826077792]"
3,Z14,16,"[T_19, T_142, T_277, T_361, T_436, T_492, T_544, T_580, T_613, T_627, T_634, T_642, T_647, T_651, T_654, T_656]","[2.3996691935208325, -0.15449646387462293, -0.18116283859744323, -0.1279608402251692, -0.13992415271567188, -0.14623411472701525, -0.15507594674017267, -0.14623411472701517, -0.15507594674017255, -0.12567102463476812, -0.14857119449822054, -0.14361231750314465, -0.15542134861027598, -0.14361231750314454, -0.15542134861027587, -0.1900871826077792]"
4,Z13,16,"[T_18, T_138, T_260, T_358, T_427, T_489, T_536, T_578, T_607, T_626, T_633, T_641, T_646, T_649, T_654, T_655]","[2.4759832177614656, -0.14910264562731548, -0.1380554201670435, -0.13401922089828566, -0.11342752264772249, -0.14582580209497134, -0.10266788152381243, -0.13639874281564546, -0.127943294974337, -0.1351903204242456, -0.12563375751916475, -0.1387172902325226, -0.132447010190967, -0.1512578503156338, -0.15542134861027587, -0.14361231750314454]"
...,...,...,...,...
1660,Y1 Z2 Z3 Z4 Y5 X10 Z11 Z12 Z13 X14,2,"[T_241, T_273]","[0.0022910004730661475, 0.0022910004730661475]"
1661,X1 Z2 Z3 Z4 X5 Y10 Z11 Z12 Z13 Y14,2,"[T_241, T_273]","[0.0022910004730661475, 0.0022910004730661475]"
1662,X1 Z2 Z3 Z4 Y5 Y10 Z11 Z12 Z13 X14,2,"[T_241, T_273]","[0.0022910004730661475, -0.0022910004730661475]"
1663,Y1 Z2 Z3 Z4 Y5 Y10 Z11 Z12 Z13 Y14,2,"[T_241, T_273]","[0.0022910004730661475, 0.0022910004730661475]"
1664,X12 Y13 X14 Y15,2,"[T_650, T_652]","[0.005904515553565677, -0.005904515553565677]"

In [7]:
# Compute Pauli-duplication ratio for JW and BK

from collections import defaultdict
import pandas as pd

from openfermion.ops import FermionOperator
from openfermion.transforms import jordan_wigner, bravyi_kitaev, normal_ordered


def pauli_support(qubit_op, tol=1e-12, include_identity=True):
    """
    Return the set of Pauli strings with nonzero coefficients.
    """
    qubit_op.compress(abs_tol=tol)

    support = set()

    for pauli_key, coeff in qubit_op.terms.items():
        if abs(coeff) <= tol:
            continue

        if not include_identity and pauli_key == ():
            continue

        support.add(pauli_key)

    return support


def map_fermion_to_qubit(op, mapping="JW", n_qubits=None):
    """
    Map a FermionOperator to a QubitOperator using JW or BK.
    """
    mapping = mapping.upper()

    if mapping == "JW":
        qop = jordan_wigner(op)

    elif mapping == "BK":
        if n_qubits is None:
            raise ValueError("n_qubits is required for BK.")

        try:
            qop = bravyi_kitaev(op, n_qubits=n_qubits)
        except TypeError:
            qop = bravyi_kitaev(op, n_qubits)

    else:
        raise ValueError("mapping must be 'JW' or 'BK'.")

    qop.compress(abs_tol=1e-12)
    return qop


def pauli_duplication_ratio(
    fermionic_terms,
    mapping="JW",
    n_qubits=None,
    include_identity=True,
    tol=1e-12,
):
    """
    Compute

        sum_alpha #mapping(H_alpha) / #mapping(H)

    where H = sum_alpha H_alpha.

    Also returns a duplicate-use table.
    """

    H_full = FermionOperator.zero()

    numerator = 0
    union_support = set()
    pauli_usage = defaultdict(list)

    for alpha, H_alpha in enumerate(fermionic_terms):
        H_full += H_alpha

        Q_alpha = map_fermion_to_qubit(
            H_alpha,
            mapping=mapping,
            n_qubits=n_qubits,
        )

        support_alpha = pauli_support(
            Q_alpha,
            tol=tol,
            include_identity=include_identity,
        )

        numerator += len(support_alpha)
        union_support |= support_alpha

        for pauli_key, coeff in Q_alpha.terms.items():
            if abs(coeff) <= tol:
                continue

            if not include_identity and pauli_key == ():
                continue

            pauli_usage[pauli_key].append(
                {
                    "vertex": f"T_{alpha}",
                    "coefficient": coeff,
                }
            )

    H_full = normal_ordered(H_full)
    H_full.compress(abs_tol=tol)

    Q_full = map_fermion_to_qubit(
        H_full,
        mapping=mapping,
        n_qubits=n_qubits,
    )

    full_support = pauli_support(
        Q_full,
        tol=tol,
        include_identity=include_identity,
    )

    denominator = len(full_support)

    duplication_ratio = numerator / denominator
    union_ratio = numerator / len(union_support)

    summary_df = pd.DataFrame(
        [
            {
                "mapping": mapping.upper(),
                "include_identity": include_identity,
                "sum_alpha_number_of_Pauli_strings": numerator,
                "number_of_unique_Pauli_strings_before_cancellation": len(union_support),
                "number_of_Pauli_strings_in_full_H": denominator,
                "duplication_ratio": duplication_ratio,
                "raw_reuse_ratio_before_cancellation": union_ratio,
            }
        ]
    )

    duplicate_rows = []

    for pauli_key, appearances in pauli_usage.items():
        if len(appearances) <= 1:
            continue

        combined_coeff = Q_full.terms.get(pauli_key, 0.0)

        duplicate_rows.append(
            {
                "Pauli_string": format_qubit_term(pauli_key),
                "number_of_appearances": len(appearances),
                "appears_in_vertices": [x["vertex"] for x in appearances],
                "individual_coefficients": [complex(x["coefficient"]) for x in appearances],
                "combined_coefficient_in_full_H": complex(combined_coeff),
                "survives_in_full_H": abs(combined_coeff) > tol,
            }
        )

    duplicate_df = pd.DataFrame(duplicate_rows)

    if len(duplicate_df) > 0:
        duplicate_df = duplicate_df.sort_values(
            "number_of_appearances",
            ascending=False,
        ).reset_index(drop=True)

    return summary_df, duplicate_df


# ------------------------------------------------------------
# Run for JW
# ------------------------------------------------------------

n_qubits = molecule.n_qubits

jw_summary_df, jw_duplicate_df = pauli_duplication_ratio(
    hermitian_terms,
    mapping="JW",
    n_qubits=n_qubits,
    include_identity=True,
)

print("=== JW Pauli-duplication ratio ===")
display(jw_summary_df)

print("\n=== Duplicated JW Pauli strings ===")
display(jw_duplicate_df)


# ------------------------------------------------------------
# Optional: run for BK too
# ------------------------------------------------------------

bk_summary_df, bk_duplicate_df = pauli_duplication_ratio(
    hermitian_terms,
    mapping="BK",
    n_qubits=n_qubits,
    include_identity=True,
)

print("=== BK Pauli-duplication ratio ===")
display(bk_summary_df)

print("\n=== Duplicated BK Pauli strings ===")
display(bk_duplicate_df)

=== JW Pauli-duplication ratio ===

,mapping,include_identity,sum_alpha_number_of_Pauli_strings,number_of_unique_Pauli_strings_before_cancellation,number_of_Pauli_strings_in_full_H,duplication_ratio,raw_reuse_ratio_before_cancellation
0,JW,True,4361,1929,1177,3.705183,2.260757

=== Duplicated JW Pauli strings ===

,Pauli_string,number_of_appearances,appears_in_vertices,individual_coefficients,combined_coefficient_in_full_H,survives_in_full_H
0,I,137,"[T_0, T_1, T_3, T_5, T_7, T_9, T_10, T_11, T_12, T_13, T_14, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_33, T_43, T_57, T_66, T_75, T_84, T_93, T_100, T_106, T_120, T_124, T_138, T_142, T_162, T_164, T_178, T_188, T_197, T_205, T_214, T_224, T_230, T_239, T_243, T_256, T_260, T_277, T_279, T_286, T_295, T_300, T_307, T_312, T_319, T_330, T_337, T_346, T_349, T_358, T_361, T_368, T_370, T_377, T_381, T_388, T_396, T_403, T_413, T_416, T_424, T_427, T_436, T_438, T_439, T_447, T_450, T_455, T_459, T_464, T_474, T_479, T_489, T_492, T_500, T_501, T_506, T_508, T_513, T_519, T_524, T_533, T_536, T_544, T_545, T_548, T_555, T_559, T_564, T_570, T_573, T_578, T_580, ...]","[(-76.41243108300478+0j), (-3.2263025563149195+0j), (-3.2263025563149195+0j), (-2.5330181470267243+0j), (-2.5330181470267243+0j), (-2.6626134366646674+0j), (-2.6626134366646674+0j), (-2.6626134366646657+0j), (-2.6626134366646657+0j), (-2.532305229532999+0j), (-2.532305229532999+0j), (-2.475983217761466+0j), (-2.475983217761466+0j), (-2.4759832177614656+0j), (-2.4759832177614656+0j), (-2.3996691935208325+0j), (-2.3996691935208325+0j), (0.18700182520310787+0j), (0.11398341133437026+0j), (0.12803515547483427+0j), (0.12813774000415315+0j), (0.15441426629825403+0j), (0.12813774000415304+0j), (0.15441426629825394+0j), (0.12277831667770017+0j), (0.1356588184128124+0j), (0.13805542016704353+0j), (0.1491026456273155+0j), (0.1380554201670435+0j), (0.14910264562731548+0j), (0.15449646387462293+0j), (0.18116283859744323+0j), (0.12803515547483427+0j), (0.11398341133437026+0j), (0.15441426629825403+0j), (0.12813774000415315+0j), (0.15441426629825394+0j), (0.12813774000415304+0j), (0.1356588184128124+0j), (0.12277831667770017+0j), (0.1491026456273155+0j), (0.13805542016704353+0j), (0.14910264562731548+0j), (0.1380554201670435+0j), (0.18116283859744323+0j), (0.15449646387462293+0j), (0.1363994271196187+0j), (0.1148330984053242+0j), (0.12753547184396263+0j), (0.11483309840532413+0j), (0.12753547184396258+0j), (0.08338122258429083+0j), (0.13933293886811743+0j), (0.11342752264772253+0j), (0.13401922089828572+0j), (0.11342752264772249+0j), (0.13401922089828566+0j), (0.1279608402251692+0j), (0.13992415271567188+0j), (0.12753547184396263+0j), (0.1148330984053242+0j), (0.12753547184396258+0j), (0.11483309840532413+0j), (0.13933293886811743+0j), (0.08338122258429083+0j), (0.13401922089828572+0j), (0.11342752264772253+0j), (0.13401922089828566+0j), (0.11342752264772249+0j), (0.13992415271567188+0j), (0.1279608402251692+0j), (0.14709020314234053+0j), (0.12907828958598547+0j), (0.1350822607714371+0j), (0.12246207154396146+0j), (0.1294791685187213+0j), (0.12794329497433712+0j), (0.1363987428156455+0j), (0.10266788152381243+0j), (0.14582580209497134+0j), (0.14623411472701525+0j), (0.15507594674017267+0j), (0.1350822607714371+0j), (0.12907828958598547+0j), (0.1294791685187213+0j), (0.12246207154396146+0j), (0.1363987428156455+0j), (0.12794329497433712+0j), (0.14582580209497134+0j), (0.10266788152381243+0j), (0.15507594674017267+0j), (0.14623411472701525+0j), (0.14709020314234034+0j), (0.12246207154396141+0j), (0.1294791685187212+0j), (0.1026678815238124+0j), (0.1458258020949713+0j), (0.127943294974337+0j), (0.13639874281564546+0j), (0.14623411472701517+0j), ...]",-102.078503+ 0.000000j,True
1,Z4,16,"[T_9, T_57, T_188, T_295, T_370, T_439, T_447, T_450, T_455, T_459, T_464, T_474, T_479, T_489, T_492, T_500]","[(2.6626134366646674+0j), (-0.12813774000415315+0j), (-0.15441426629825403+0j), (-0.1148330984053242+0j), (-0.12753547184396263+0j), (-0.14709020314234053+0j), (-0.12907828958598547+0j), (-0.1350822607714371+0j), (-0.12246207154396146+0j), (-0.1294791685187213+0j), (-0.12794329497433712+0j), (-0.1363987428156455+0j), (-0.10266788152381243+0j), (-0.14582580209497134+0j), (-0.14623411472701525+0j), (-0.15507594674017267+0j)]",0.660355+ 0.000000j,True
2,Z15,16,"[T_20, T_162, T_279, T_368, T_438, T_500, T_545, T_588, T_614, T_629, T_635, T_644, T_648, T_653, T_655, T_656]","[(2.3996691935208325+0j), (-0.18116283859744323+0j), (-0.15449646387462293+0j), (-0.13992415271567188+0j), (-0.1279608402251692+0j), (-0.15507594674017267+0j), (-0.14623411472701525+0j), (-0.15507594674017255+0j), (-0.14623411472701517+0j), (-0.14857119449822054+0j), (-0.12567102463476812+0j), (-0.15542134861027598+0j), (-0.14361231750314465+0j), (-0.15542134861027587+0j), (-0.14361231750314454+0j), (-0.1900871826077792+0j)]",0.131108+ 0.000000j,True
3,Z14,16,"[T_19, T_142, T_277, T_361, T_436, T_492, T_544, T_580, T_613, T_627, T_634, T_642, T_647, T_651, T_654, T_656]","[(2.3996691935208325+0j), (-0.15449646387462293+0j), (-0.18116283859744323+0j), (-0.1279608402251692+0j), (-0.13992415271567188+0j), (-0.14623411472701525+0j), (-0.15507594674017267+0j), (-0.14623411472701517+0j), (-0.15507594674017255+0j), (-0.12567102463476812+0j), (-0.14857119449822054+0j), (-0.14361231750314465+0j), (-0.15542134861027598+0j), (-0.14361231750314454+0j), (-0.15542134861027587+0j), (-0.1900871826077792+0j)]",0.131108+ 0.000000j,True
4,Z13,16,"[T_18, T_138, T_260, T_358, T_427, T_489, T_536, T_578, T_607, T_626, T_633, T_641, T_646, T_649, T_654, T_655]","[(2.4759832177614656+0j), (-0.14910264562731548+0j), (-0.1380554201670435+0j), (-0.13401922089828566+0j), (-0.11342752264772249+0j), (-0.14582580209497134+0j), (-0.10266788152381243+0j), (-0.13639874281564546+0j), (-0.127943294974337+0j), (-0.1351903204242456+0j), (-0.12563375751916475+0j), (-0.1387172902325226+0j), (-0.132447010190967+0j), (-0.1512578503156338+0j), (-0.15542134861027587+0j), (-0.14361231750314454+0j)]",0.446263+ 0.000000j,True
...,...,...,...,...,...,...
1660,Y1 Z2 Z3 Z4 Y5 X10 Z11 Z12 Z13 X14,2,"[T_241, T_273]","[(0.0022910004730661475+0j), (0.0022910004730661475+0j)]",0.004582+ 0.000000j,True
1661,X1 Z2 Z3 Z4 X5 Y10 Z11 Z12 Z13 Y14,2,"[T_241, T_273]","[(0.0022910004730661475+0j), (0.0022910004730661475+0j)]",0.004582+ 0.000000j,True
1662,X1 Z2 Z3 Z4 Y5 Y10 Z11 Z12 Z13 X14,2,"[T_241, T_273]","[(0.0022910004730661475+0j), (-0.0022910004730661475+0j)]",0.000000+ 0.000000j,False
1663,Y1 Z2 Z3 Z4 Y5 Y10 Z11 Z12 Z13 Y14,2,"[T_241, T_273]","[(0.0022910004730661475+0j), (0.0022910004730661475+0j)]",0.004582+ 0.000000j,True
1664,X12 Y13 X14 Y15,2,"[T_650, T_652]","[(0.005904515553565677+0j), (-0.005904515553565677+0j)]",0.000000+ 0.000000j,False

=== BK Pauli-duplication ratio ===

,mapping,include_identity,sum_alpha_number_of_Pauli_strings,number_of_unique_Pauli_strings_before_cancellation,number_of_Pauli_strings_in_full_H,duplication_ratio,raw_reuse_ratio_before_cancellation
0,BK,True,4361,1929,1177,3.705183,2.260757

=== Duplicated BK Pauli strings ===

,Pauli_string,number_of_appearances,appears_in_vertices,individual_coefficients,combined_coefficient_in_full_H,survives_in_full_H
0,I,137,"[T_0, T_1, T_3, T_5, T_7, T_9, T_10, T_11, T_12, T_13, T_14, T_15, T_16, T_17, T_18, T_19, T_20, T_21, T_33, T_43, T_57, T_66, T_75, T_84, T_93, T_100, T_106, T_120, T_124, T_138, T_142, T_162, T_164, T_178, T_188, T_197, T_205, T_214, T_224, T_230, T_239, T_243, T_256, T_260, T_277, T_279, T_286, T_295, T_300, T_307, T_312, T_319, T_330, T_337, T_346, T_349, T_358, T_361, T_368, T_370, T_377, T_381, T_388, T_396, T_403, T_413, T_416, T_424, T_427, T_436, T_438, T_439, T_447, T_450, T_455, T_459, T_464, T_474, T_479, T_489, T_492, T_500, T_501, T_506, T_508, T_513, T_519, T_524, T_533, T_536, T_544, T_545, T_548, T_555, T_559, T_564, T_570, T_573, T_578, T_580, ...]","[(-76.41243108300478+0j), (-3.2263025563149195+0j), (-3.2263025563149195+0j), (-2.5330181470267243+0j), (-2.5330181470267243+0j), (-2.6626134366646674+0j), (-2.6626134366646674+0j), (-2.6626134366646657+0j), (-2.6626134366646657+0j), (-2.532305229532999+0j), (-2.532305229532999+0j), (-2.475983217761466+0j), (-2.475983217761466+0j), (-2.4759832177614656+0j), (-2.4759832177614656+0j), (-2.3996691935208325+0j), (-2.3996691935208325+0j), (0.18700182520310787+0j), (0.11398341133437026+0j), (0.12803515547483427+0j), (0.12813774000415315+0j), (0.15441426629825403+0j), (0.12813774000415304+0j), (0.15441426629825394+0j), (0.12277831667770017+0j), (0.1356588184128124+0j), (0.13805542016704353+0j), (0.1491026456273155+0j), (0.1380554201670435+0j), (0.14910264562731548+0j), (0.15449646387462293+0j), (0.18116283859744323+0j), (0.12803515547483427+0j), (0.11398341133437026+0j), (0.15441426629825403+0j), (0.12813774000415315+0j), (0.15441426629825394+0j), (0.12813774000415304+0j), (0.1356588184128124+0j), (0.12277831667770017+0j), (0.1491026456273155+0j), (0.13805542016704353+0j), (0.14910264562731548+0j), (0.1380554201670435+0j), (0.18116283859744323+0j), (0.15449646387462293+0j), (0.1363994271196187+0j), (0.1148330984053242+0j), (0.12753547184396263+0j), (0.11483309840532413+0j), (0.12753547184396258+0j), (0.08338122258429083+0j), (0.13933293886811743+0j), (0.11342752264772253+0j), (0.13401922089828572+0j), (0.11342752264772249+0j), (0.13401922089828566+0j), (0.1279608402251692+0j), (0.13992415271567188+0j), (0.12753547184396263+0j), (0.1148330984053242+0j), (0.12753547184396258+0j), (0.11483309840532413+0j), (0.13933293886811743+0j), (0.08338122258429083+0j), (0.13401922089828572+0j), (0.11342752264772253+0j), (0.13401922089828566+0j), (0.11342752264772249+0j), (0.13992415271567188+0j), (0.1279608402251692+0j), (0.14709020314234053+0j), (0.12907828958598547+0j), (0.1350822607714371+0j), (0.12246207154396146+0j), (0.1294791685187213+0j), (0.12794329497433712+0j), (0.1363987428156455+0j), (0.10266788152381243+0j), (0.14582580209497134+0j), (0.14623411472701525+0j), (0.15507594674017267+0j), (0.1350822607714371+0j), (0.12907828958598547+0j), (0.1294791685187213+0j), (0.12246207154396146+0j), (0.1363987428156455+0j), (0.12794329497433712+0j), (0.14582580209497134+0j), (0.10266788152381243+0j), (0.15507594674017267+0j), (0.14623411472701525+0j), (0.14709020314234034+0j), (0.12246207154396141+0j), (0.1294791685187212+0j), (0.1026678815238124+0j), (0.1458258020949713+0j), (0.127943294974337+0j), (0.13639874281564546+0j), (0.14623411472701517+0j), ...]",-102.078503+ 0.000000j,True
1,Z4,16,"[T_9, T_57, T_188, T_295, T_370, T_439, T_447, T_450, T_455, T_459, T_464, T_474, T_479, T_489, T_492, T_500]","[(2.6626134366646674+0j), (-0.12813774000415315+0j), (-0.15441426629825403+0j), (-0.1148330984053242+0j), (-0.12753547184396263+0j), (-0.14709020314234053+0j), (-0.12907828958598547+0j), (-0.1350822607714371+0j), (-0.12246207154396146+0j), (-0.1294791685187213+0j), (-0.12794329497433712+0j), (-0.1363987428156455+0j), (-0.10266788152381243+0j), (-0.14582580209497134+0j), (-0.14623411472701525+0j), (-0.15507594674017267+0j)]",0.660355+ 0.000000j,True
2,Z7 Z11 Z13 Z14 Z15,16,"[T_20, T_162, T_279, T_368, T_438, T_500, T_545, T_588, T_614, T_629, T_635, T_644, T_648, T_653, T_655, T_656]","[(2.3996691935208325+0j), (-0.18116283859744323+0j), (-0.15449646387462293+0j), (-0.13992415271567188+0j), (-0.1279608402251692+0j), (-0.15507594674017267+0j), (-0.14623411472701525+0j), (-0.15507594674017255+0j), (-0.14623411472701517+0j), (-0.14857119449822054+0j), (-0.12567102463476812+0j), (-0.15542134861027598+0j), (-0.14361231750314465+0j), (-0.15542134861027587+0j), (-0.14361231750314454+0j), (-0.1900871826077792+0j)]",0.131108+ 0.000000j,True
3,Z14,16,"[T_19, T_142, T_277, T_361, T_436, T_492, T_544, T_580, T_613, T_627, T_634, T_642, T_647, T_651, T_654, T_656]","[(2.3996691935208325+0j), (-0.15449646387462293+0j), (-0.18116283859744323+0j), (-0.1279608402251692+0j), (-0.13992415271567188+0j), (-0.14623411472701525+0j), (-0.15507594674017267+0j), (-0.14623411472701517+0j), (-0.15507594674017255+0j), (-0.12567102463476812+0j), (-0.14857119449822054+0j), (-0.14361231750314465+0j), (-0.15542134861027598+0j), (-0.14361231750314454+0j), (-0.15542134861027587+0j), (-0.1900871826077792+0j)]",0.131108+ 0.000000j,True
4,Z12 Z13,16,"[T_18, T_138, T_260, T_358, T_427, T_489, T_536, T_578, T_607, T_626, T_633, T_641, T_646, T_649, T_654, T_655]","[(2.4759832177614656+0j), (-0.14910264562731548+0j), (-0.1380554201670435+0j), (-0.13401922089828566+0j), (-0.11342752264772249+0j), (-0.14582580209497134+0j), (-0.10266788152381243+0j), (-0.13639874281564546+0j), (-0.127943294974337+0j), (-0.1351903204242456+0j), (-0.12563375751916475+0j), (-0.1387172902325226+0j), (-0.132447010190967+0j), (-0.1512578503156338+0j), (-0.15542134861027587+0j), (-0.14361231750314454+0j)]",0.446263+ 0.000000j,True
...,...,...,...,...,...,...
1660,Z0 X1 Y3 Y5 Z9 Y10 Y11 Z13 X14,2,"[T_241, T_273]","[(-0.0022910004730661475+0j), (-0.0022910004730661475+0j)]",-0.004582+ 0.000000j,True
1661,Y1 Y3 Z4 X5 Z9 X10 Y11 Z13 Y14,2,"[T_241, T_273]","[(-0.0022910004730661475+0j), (-0.0022910004730661475+0j)]",-0.004582+ 0.000000j,True
1662,Y1 Y3 Y5 Z9 X10 Y11 Z13 X14,2,"[T_241, T_273]","[(-0.0022910004730661475+0j), (0.0022910004730661475+0j)]",0.000000+ 0.000000j,False
1663,Z0 X1 Y3 Y5 Z9 X10 Y11 Z13 Y14,2,"[T_241, T_273]","[(0.0022910004730661475+0j), (0.0022910004730661475+0j)]",0.004582+ 0.000000j,True
1664,Z7 Z11 Y12 Y14 Z15,2,"[T_650, T_652]","[(0.005904515553565677+0j), (-0.005904515553565677+0j)]",0.000000+ 0.000000j,False